### ISSUE TITLE
0.1.0 Endgame

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-test#10]
# Build
- [x] 11/30 - Instrument production AI key - @testforstephen 
([Jenkins RC build job](https://vscjavaci.cloudapp.net/job/vscode-java-test.vsix-withSign/))
- [x] 11/30 - Bump version to 0.1.0 - @testforstephen 
(PR #16)
- [x] 11/30 - Add change log for 0.1.0 #15 - @yaohaizh 
- [x] 11/30 - Signed RC Bits - @testforstephen 
([#2](https://vscjavaci.cloudapp.net/job/vscode-java-test.vsix-withSign/2/Azure/processDownloadRequest/java-test/extension/signedartifacts/2/vscode-java-test-0.1.0.vsix)) 
([#3](https://vscjavaci.cloudapp.net/job/vscode-java-test.vsix-withSign/3/Azure/)) that fixed blocking bug, please use this one for final verification.

# Test
- [x] 11/30 - Run test plan [vscjavaci/java-test-ci/#1](https://github.com/vscjavaci/java-test-ci/issues/1) - @bsaby @sallyur 
- [x] 11/30 - Java 9 support on Mac - @testforstephen 
- [x] 11/30 - Java 9 support on Linux/Ubuntu - @yaohaizh 
- [x] 11/30 - Validate production BI data - @ansyral @JialinXin 

# Release
- [x] 11/30 - Add 0.1.0 tag for vscode-java-test - @testforstephen 
- [x] 11/30 - Release to marketplace - @testforstephen 
https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by yaohaizh** [comment]
# Java9/Ubuntu

- VSCode Insider
- Ubuntu 1.18.0
- Follow test plan, it will take 2~3 times to successfully to load test cases.

**Comment by testforstephen** [comment]
# Java 9 on Mac

1. Install RC#2, and open `color-checker` project from test plan, VSCode pop up a message box saying "Couldn't find Java home...". See bug #17 
2. Install RC#3 again, verify that bug #17 is fixed.
3. Continue to debug test case from `color-checker` project, found several bugs: #20 #21 #22

**Comment by akaroml** [comment]
#20 is fixed by #26

**Comment by songkaiape** [comment]
Following the steps from here: https://github.com/vscjavaci/java-test-ci/issues/1

1. Configurations

Platform | Win10 x64 | Mac |
-- | -- | -- 
Configurations | VSCode 1.18.1 x64 JDK8 x64| VSCode 1.18.1  JDK8  

2. Duration show issue:#25
   Add Ignore issue:#27

3. Test result details:


Test case | Win10 x64 | Mac Sierra 10.12.4 | issue
-- | -- | -- | --
Configurations | VSCode   1.18.1 x64   JDK1.8.0_151 x64 | VSCode 1.18.1   JDK1.8.0_144 |  
Owner | Barney | Sally |  
Clean install | Pass | Pass |  
Uninstall | Pass | Pass |  
Update | Pass | Pass |  
eclipse junit test   project | Pass | Pass | #25 #27
maven junit test   project | Pass | Pass | #25 #27
spring boot   project | Pass | Pass | #25 #27
test Ignore attribute | Pass | Pass | #25 #27
TODO application | Pass | Pass | #25 #27

**Comment by testforstephen** [comment]
Issue #20 is fixed by PR #26.
Issue #21 is fixed by PR #31.
Issue #22 is fixed by PR #28, #30, #33.
