### ISSUE TITLE
Allow launch configuration for tests

### ISSUE THREAD

**Issue by falco467** [Microsoft/vscode-java-test#100]
It would be great if one could add command-line arguments to the testrunner.

I work with a code-base which needs a custom property set for running local tests
(VM Argument: -Dconfig="local_test") - but I cannot find a way to pass this argument to the Testrunner Plugin...

**Comment by ansyral** [comment]
other requests to configure test location: #94 #104

**Comment by ansyral** [comment]
delivered in 0.5.0
