### ISSUE TITLE
Feature request: Ability to "Show test report" via keyboard shortcut and CMD + P

### ISSUE THREAD

**Issue by rootulp** [microsoft/vscode-java-test#1002]
## Suggestion

I would like the ability to open the **Java Test Report** window via keyboard shortcut or via the CMD + P menu

## Examples

<img width="195" alt="Screen Shot 2020-05-23 at 6 21 30 PM" src="https://user-images.githubusercontent.com/3699047/82741655-855af100-9d22-11ea-8408-63067306bb4c.png">
<img width="746" alt="Screen Shot 2020-05-23 at 6 21 42 PM" src="https://user-images.githubusercontent.com/3699047/82741656-868c1e00-9d22-11ea-883c-d623ede2753d.png">

**Comment by rootulp** [comment]
@akaroml thanks! Is it possible for vs-code-java-test to provide this functionality out of the box? Other extensions populate commands in the CMD + P menu that are core to their functionality:

<img width="742" alt="Screen Shot 2020-05-28 at 3 15 00 PM" src="https://user-images.githubusercontent.com/3699047/83183573-02f17900-a0f6-11ea-93f5-0594ab2ea440.png">

**Comment by jdneo** [comment]
@rootulp Thank you for the feedback.

Sure thing we can expose this command. The thing we need to do is to cache the test items in last run then we can get the test items from the cache when the command is triggered.

_The current implementation is store the test items in last run in the status bar item, which is not accessible from outside._
