### ISSUE TITLE
'compileTestJava' gradle task seems to be ignored.

### ISSUE THREAD

**Issue by gyuwon** [microsoft/vscode-java-test#1009]
I have a simple gradle file.

```groovy
plugins {
    id 'java-library'
}

repositories {
    jcenter()
}

dependencies {
    testImplementation 'junit:junit:4.12'
}

compileTestJava {
    options.compilerArgs << '-parameters'
}
```

When I run `gradlew build` manually '-parameters' flag works correctly. But not for Java Test Runner. Can I get some help with this problem?

**Comment by jdneo** [comment]
@gyuwon Could you please try to add `-parameters` into the vmargs of the [test configuration](https://github.com/microsoft/vscode-java-test/wiki/Run-with-Configuration#tldr)?

**Comment by gyuwon** [comment]
@jdneo Unfortunately that does not work because the option `-parameter` is for `javac` not `java`.

```text
Unrecognized option: -parameters
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by jdneo** [comment]
Would you mind to share the settings file to us? (located in .settings/org.eclipse.buildship.core.prefs).

**Comment by gyuwon** [comment]
Here it is

```text
arguments=
auto.sync=false
build.scans.enabled=false
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=
eclipse.preferences.version=1
gradle.user.home=
java.home=C\:/Users/gyuwon/AppData/Local/Programs/AdoptOpenJDK
jvm.arguments=
offline.mode=false
override.workspace.settings=true
show.console.view=true
show.executions.view=true
```

**Comment by jdneo** [comment]
@gyuwon Not sure the root cause of this issue so far. But at least it seems not a Test Runner's bug since the Test Runner is not responsible for building/compiling. 

I guess it's an issue related with buildship or jdt.ls.

**Comment by gyuwon** [comment]
@jdneo Oh it's not a good news for me. 😢 I'll try to find any clue with buildship or jdt.ls things you said. Thank you.

**Comment by gyuwon** [comment]
I found this issue and it helped me to solve the problem.

https://github.com/redhat-developer/vscode-java/issues/666

**Comment by jdneo** [comment]
Good to know we have a workaround here. Thanks @gyuwon
