### ISSUE TITLE
Passing test is shown as failed when using a runner that renames test methods

### ISSUE THREAD

**Issue by Artur-** [microsoft/vscode-java-test#1013]
To reproduce you need a test runner that renames the method
```
public class RenamingRunner extends BlockJUnit4ClassRunner {
    public RenamingRunner(Class<?> klass) throws InitializationError {
        super(klass);
    }
    @Override
    protected List<FrameworkMethod> computeTestMethods() {
        List<FrameworkMethod> methods = super.computeTestMethods();
        return methods.stream().map(method -> new RenamedFrameworkMethod(method.getMethod()))
                .collect(Collectors.toList());
    }
}
```
```
   public class RenamedFrameworkMethod extends FrameworkMethod {
        public RenamedFrameworkMethod(Method method) {
            super(method);
        }
        @Override
        public String getName() {
            return "renamed-" + super.getName();
        }
    }
```
and a test class
```
package org.vaadin.artur;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(RenamingRunner.class)
public class FooTest {

    @Test
    public void simpleTest() {
        Assert.assertTrue(false);
    }

}
```

Then to see the problem you
1. Run the test, it should fail and does fail
2. change `false` to `true` in the assertion
3. Run the test again, it passes but is shown as failure with the failure from the last run

**Comment by jdneo** [comment]
@Artur- Thanks for reporting.

This issue was actually duplicated with #1008 and fixed by #1011. So I'm closing it right now.

We will release this fix very soon. If the problem still occurs after the release, please feel free to let us know.

Thanks.

**Comment by Artur-** [comment]
Thanks, you have re-introduced this in the new test runner.

https://user-images.githubusercontent.com/260340/133435225-1536632f-cd83-47cd-9c9e-9ebe5ac3ddc2.mov

**Comment by jdneo** [comment]
Should be a different bug from the video. I created a new issue https://github.com/microsoft/vscode-java-test/issues/1304 to track.
