### ISSUE TITLE
Eclipse JDT error when trying to run tests

### ISSUE THREAD

**Issue by veredcon** [microsoft/vscode-java-test#1017]
Hi I get:

Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.

I have installed https://github.com/microsoft/vscode-java-test/releases/tag/0.22.1 vscode extension in theia based IDE (0.22.3 currently does not work).

Running test pops up this error:
![image](https://user-images.githubusercontent.com/9718939/84649295-f26f3a00-af0e-11ea-80c3-3e7eb8cc0405.png)

This is Java Maven spring boot based application and in VScode windows enviorment the same project runs successfully.
The project: git clone https://github.com/SAP-samples/cloud-cap-samples-java.git

This is the log I get in the Java log file:

!ENTRY org.eclipse.jdt.ls.core 4 0 2020-06-15 11:10:40.070
!MESSAGE Error in calling delegate command handler
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveLaunchArgument(JUnitLaunchUtils.java:69)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:48)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:443)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$39(JDTLanguageServer.java:875)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by jdneo** [comment]
Hmm, I'm not sure what's the differences between VS Code and Eclipse Theia. Is that because some capabilities of VS Code are not supported in Theia?

**Comment by veredcon** [comment]
After giving it more thought, might it be related to the Java we are using in theia? 
Maybe trying to install Java JDK in later version than 8 would solve this issue?

**Comment by jdneo** [comment]
Hmm, I'm not sure of that. JDK 8 should be ok. I'm also using JDK 8 before.

**Comment by veredcon** [comment]
Thanks. As far as I know in our environment we are installing JRE and not JDK so maybe this might be the root cause
