### ISSUE TITLE
Test passes even if one of parameterized tests fail.

### ISSUE THREAD

**Issue by ndac-todoroki** [microsoft/vscode-java-test#1018]
maybe related: #954 

Consider this test code:
```java
@ParameterizedTest
@CsvSource({"1,1", "1,2", "2,2"})
void twoValuesAreTheSame(final int a, final int b) {
    assertThat(a).isEqualTo(b);
}
```
This should not pass, since the second example fails.
The output for this is:

![image](https://user-images.githubusercontent.com/11530165/85172558-4d58b680-b2ac-11ea-963d-c3238f6e7d37.png)

The results shown on the bottom bar shows the same too.

**Comment by ndac-todoroki** [comment]
Removing the `"2,2"` element from the source CSV made the test fail, so the root problem is almost the same with #954. I think vscode-java-test keeps only the last result.

**Comment by jdneo** [comment]
I cannot repro on my side. Does it stable occur?
<img width="1124" alt="Screen Shot 2020-06-28 at 10 16 50 AM" src="https://user-images.githubusercontent.com/6193897/85935943-94881c80-b928-11ea-97d4-3f2e112769f8.png">

**Comment by jdneo** [comment]
I can repro it now. Sorry not sure why it's not reproduced at first

**Comment by jdneo** [comment]
Provided a workaround in #1027: show failed in the test status.

To total resolve the problem #954 is needed to fix.
