### ISSUE TITLE
some problems in Chinese

### ISSUE THREAD

**Issue by whmmm** [Microsoft/vscode-java-test#103]
![image](https://user-images.githubusercontent.com/22763406/35264353-655b2d44-0057-11e8-9266-3bbd6f2ef293.png)
There has some question in Chinese display...How can i fix this？

**Comment by ansyral** [comment]
Same to #37. Does adding the environment variable “JAVA_TOOLS_OPTIONS="-Dfile.encoding=utf-8" work?

**Comment by jdneo** [comment]
Closing since it's inactive for a long time. Please feel free to reopen it if the problem still occurred
