### ISSUE TITLE
Definition of current working directory is missing

### ISSUE THREAD

**Issue by treeno** [Microsoft/vscode-java-test#104]
Lets say we would like to read a file in a test using a relative path. In that case I would expect that the path could be expressed relative to the current Folder that is opend by vs Code. But the current working Directory is the Installation directory of vs Code. Is there a way to change that? If not, would you like to add a configration for that?

**Comment by ansyral** [comment]
@treeno, currently unfortunately no, but we plan to add configuration support later

**Comment by ansyral** [comment]
let's use #100 to track this
