### ISSUE TITLE
Support Gradle test delegation

### ISSUE THREAD

**Issue by hrsto** [microsoft/vscode-java-test#1045]
Inside `src/test/resources` there is an `arquillian.xml` file that has to be expanded by gradle at `processTestResources` task. When a test is run from within vs code, this doesn't happen and the resource file is used as is. This triggers an error from Junit that basically says that some property is invalid (because it's expanded, i.e. junit see it as `${somePropToExpand}`).

Same thing occurs when arquillian.xml is auto generated by a plugin - a gradle plugin can auto create it and put it directly in the buildDir/resources/test dir. When a test is run from within vs code, basically the file is invisible to vs code.

Both of these problems can be corrected by having a:

```groovy
sourceSets {
    test {
        resources {
            srcDirs += "$buildDir/resources/test"
        }
    }
}
```
But that by itself creates a new set of problems for the build.

**Comment by jdneo** [comment]
The project classpath is resolved by buildship (if it's a Gradle project). To help us better understand the problem, would you mind to share a sample project for this issue to us?

**Comment by hrsto** [comment]
Attaching the most minimal i could produce.

There's only one test class - `ArquillianInitTest`.

First do a `gradle clean test`. It should complete successfully.

This initial normal build is set to auto generate `arquillian.xml` at built time, thus: `/tmp/sample/src/test/resources/__arquillian.xml` is prefixed with `__` to ignore it. Such a build doesn't work when executed from __vscode__, because vscode code thinks this file doesn't exist. But it can be found in `$buildDir/resources/test`.

Now remove the `__` prefix from `/tmp/sample/src/test/resources/__arquillian.xml` to force gradle to explicitly use it. Make sure you manually set the `wlpHome` (in my case, project ran from `/tmp`). The following is observed:

1) when you do `gradle clean test` it should complete successfully.
2) when run from __vscode__, it will error out because of the properties the need to be expanded. For ex., this is the error i get: `java.lang.NumberFormatException: For input string: "${SERVER_PORT}"`
3) if you run `gradle processTestResources`, you can confirm the property expansion works - the files in `$buildDir/resources/test` have the proper values.
3) `src/test/resources/arquillian.xml` and `src/test/resources/persistence.xml` have commented out lines - toggle those so that you directly set the values. When run from __vscode__ it will complete successfully.

[sample.tar.gz](https://github.com/microsoft/vscode-java-test/files/5071365/sample.tar.gz)

**Comment by jdneo** [comment]
Here are some findings:

I can repro this issue and I also tried the project in Eclipse and IntelliJ.

In Eclipse, same error when running the test, but it can successfully run if I use the `Delegate to Gradle` feature.

In IntelliJ, since it will delegate to Gradle by default, so the test runs successfully.

Seems that we need to support `Delegate to Gradle` at VS Code side.

**Comment by egvimo** [comment]
I have the same problem. A "Delegate to Gradle" Feature would be great!

**Comment by ytreister** [comment]
Any update on this?

**Comment by prbpedro** [comment]
I have the same problem. A "Delegate to Gradle" Feature would be great!

**Comment by uk-taniyama** [comment]
I tried to call "gardle test"  with vscode-gradle but could only get as far as the call.

```
import * as util from "util";
import * as vscode from "vscode";
import { ExtensionApi as GradleApi, RunTaskOpts, Output } from "vscode-gradle";

function runGradleTest(context: IRunTestContext) {
    const extension = vscode.extensions.getExtension("vscjava.vscode-gradle");
    if (extension == null) {
        return null;
    }

    const gradleApi = extension!.exports as GradleApi;
    const testMethods: TestItem[] = [];
    const visitTestItem = (testItem: TestItem) => {
        if(testItem.id.indexOf('#') > 0 ){
            testMethods.push(testItem);
        } else {
            testItem.children.forEach(visitTestItem)
        }
    }
    context.testItems.forEach(visitTestItem);

    return new Promise(async (resolve, reject) => {
        while(testMethods.length) {
            const testMethod = testMethods.shift();
            if(testMethod==null){
                continue;
            }

            const taskId = testMethod.id;
            const runTaskOpts: RunTaskOpts = {
                projectFolder: context.workspaceFolder.uri.fsPath,
                taskName: "test",
                args: [
                    "--tasks",
                    taskId.replace(/.+@/, '').replace('#', '.'),
                ],
                showOutputColors: false,
                onOutput: (output: Output): void => {
                    const message = new util.TextDecoder("utf-8").decode(
                        output.getOutputBytes_asU8()
                    );
                    console.log(output.getOutputType(), message);
                },
            };
            await gradleApi.runTask(runTaskOpts);
        }
        resolve(null);
    });
}
```

**Comment by violetexistence** [comment]
Yes, please!

**Comment by jdneo** [comment]
Update: I'm implementing gradle test delegation recently and it will come very soon

**Comment by jdneo** [comment]
The Gradle Test Delegation (both run and debug) has supported now.

To use this feature, you need to install the latest [Test Runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) and [Gradle for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) extension.

To delegate the tests to Gradle, you can set the default testing profile in Testing explorer:
![image](https://github.com/user-attachments/assets/f3e982e0-0340-461c-b6c4-c8c7fe9352f5)
![image](https://github.com/user-attachments/assets/e1a2693c-e6d7-425a-b7d5-6adf878f4ce3)

If you do not want to change the default testing profile, you can trigger an one-time execution via:
![image](https://github.com/user-attachments/assets/1c3f7478-b100-40cf-98c2-6f0357050209)
![image](https://github.com/user-attachments/assets/55fa017c-adb3-4c5a-bc81-55db63834773)

**Comment by piotr-rachwalik** [comment]
@jdneo I don't see Delegate Test to Gradle option in my VS Code:
![Screenshot 2024-09-13 at 17 36 30](https://github.com/user-attachments/assets/af211f65-13d0-46da-912e-cdeb87260e8e)
![Screenshot 2024-09-13 at 17 38 08](https://github.com/user-attachments/assets/91514953-f81f-4418-a703-22d1919f7da3)
![Screenshot 2024-09-13 at 17 37 01](https://github.com/user-attachments/assets/9f563d17-7c89-4a36-a495-c5797cc47ccf)

![Screenshot 2024-09-13 at 17 39 07](https://github.com/user-attachments/assets/0234fc02-4145-4750-9b38-d3b6028b8a47)
![Screenshot 2024-09-13 at 17 39 40](https://github.com/user-attachments/assets/eb61a76a-1b1d-40cc-9d38-273324622b5e)

Any hints how to enable that feature?

**Comment by wenytang-ms** [comment]
consider upgrade to latest preview of vscode gradle with this issue `3.17.2026042802`

<img width="1126" height="276" alt="Image" src="https://github.com/user-attachments/assets/edc2cb12-ce11-4065-a924-fc7c3a063dfd" />
