### ISSUE TITLE
No Code Lens while working on remote directory

### ISSUE THREAD

**Issue by smrutisourav** [microsoft/vscode-java-test#1049]
Hello,

While working on remote directory, code lens does not work for unit tests or testng tests.

![image](https://user-images.githubusercontent.com/32691151/90978608-adf0c200-e581-11ea-930f-03c6dd725668.png)

It works perfectly while working on local directory.

![image](https://user-images.githubusercontent.com/32691151/90978690-353e3580-e582-11ea-8cb1-43a9cd82d3c4.png)

**Comment by jdneo** [comment]
Tried on Remote - WSL. Cannot repro.

![image](https://user-images.githubusercontent.com/6193897/90995354-49b81780-e5ee-11ea-9ac4-9586ebc85fdd.png)


What's your vs code version on your remote machine?

**Comment by smrutisourav** [comment]
VS Code version is 1.48.1. It's a system setup.

Please consider trying on remote shared folders.

**Comment by jdneo** [comment]
What's your JDK version in remote

**Comment by smrutisourav** [comment]
System Info: Parallels 14 Windows 10 VM running on MAC. Vscode running on windows VM, data is stored in mac accessed through SMB (I guess) protocol.

JDK version 14 on windows VM.

**Comment by jdneo** [comment]
Sorry I'm kind of lost here. Did you use the `Remote` extension here? how should I understand `working on remote directory`?
