### ISSUE TITLE
Test runner widgets not appearing in some environments

### ISSUE THREAD

**Issue by dsyer** [Microsoft/vscode-java-test#105]
I sometimes (e.g. on one of my laptops) don't see any test runner features, despite the fact that the language server is running and all the normal java features are working. I'm pretty sure it used to work. And I can't see any errors in the UI. Maybe there are some logs I can mine for more detail?

See discussion here for more detail: https://github.com/redhat-developer/vscode-java/issues/427.

**Comment by ansyral** [comment]
@dsyer, currently we don't expose test logs. we would support this next release.

**Comment by ansyral** [comment]
@dsyer, you can now open test log by invoking command "Java: Log"

**Comment by jdneo** [comment]
Closing this issue since it's inactive for a long time.
