### ISSUE TITLE
Unable to detect a test in simple environment

### ISSUE THREAD

**Issue by sridharanprasanna** [microsoft/vscode-java-test#1050]
I have tried the classpath workaround mentioned in forums.

When i try to refresh from the test explorer, i get an error:

"nodelegatecommandhandler for vscode.java.test.search.items" 

![image](https://user-images.githubusercontent.com/13363348/91185290-e0e2a500-e6aa-11ea-8610-8f98cd3c3fdc.png)

![image](https://user-images.githubusercontent.com/13363348/91185336-f061ee00-e6aa-11ea-9cba-02f58d56fabc.png)

**Comment by jdneo** [comment]
Does your JDK version < 11?

If yes, see: https://github.com/microsoft/vscode-java-test/issues/1048#issuecomment-676318039

**Comment by sridharanprasanna** [comment]
> Does your JDK version < 11?
> 
> If yes, see: [#1048 (comment)](https://github.com/microsoft/vscode-java-test/issues/1048#issuecomment-676318039)

Thank you. It cleared my misconception too. I required JDK1.8 for building project. Got confused with the VSCode environment.
JDK11 worked.
