### ISSUE TITLE
Error: Could not find or load main class when i used gradle to build java project

### ISSUE THREAD

**Issue by renzhonglu11** [microsoft/vscode-java-test#1058]
Error: Could not find or load main class rz.Test
Caused by: java.lang.ClassNotFoundException: rz.Test

my build.gradle:
plugins {
    id 'java-library'
}

repositories {

    jcenter()
}

dependencies {
    api 'org.apache.commons:commons-math3:3.6.1'

    
    implementation 'com.google.guava:guava:29.0-jre'

    
    testImplementation 'junit:junit:4.13'
}

**Comment by jdneo** [comment]
Would you mind to share a sample project for this issue?

// cc @testforstephen

**Comment by renzhonglu11** [comment]
thans for the reply. i have solved this problem. but now the java workshop created by Vscode gets the same proble :(
![b23b6d879a3797fb379fa7268fdafaf](https://user-images.githubusercontent.com/57646892/92302288-53853780-ef6b-11ea-8144-1ea3b3f4ecf4.png)
![081999b3b249ea8a36296955b084c32](https://user-images.githubusercontent.com/57646892/92302289-56802800-ef6b-11ea-90a3-c0e2d6233e43.png)

launch.json:
        {
            "type": "java",
            "name": "CodeLens (Launch) - Test",
            "request": "launch",
            "mainClass": "java.Test",
            "projectName": "java01_bfa072e7"
        },

**Comment by renzhonglu11** [comment]
by the way .class file is created by Code Runner. it can sucessfully compile and run the code

**Comment by renzhonglu11** [comment]
i think taht i have found the problem.when i delete junit-platform-console-standalone-1.6.0 (1).jar from Referenced Libraries in Java project management. it works perfectlly. but i cannot use unit test when i do that.
how can i fix the problem?

**Comment by jdneo** [comment]
You can share your project in a zip file to us if you don't mind.

The information provided is not enough to find out what's the gap here.

If you don't want to share the project, below are some suspicious points I found:

- Try to update your extensions to the latest version if they aren't.
- rename your jar from `junit-platform-console-standalone-1.6.0 (1).jar` to `junit-platform-console-standalone-1.6.0.jar` to avoid space in the command.
- Delete the `Test.class` file and your `launch.json`.
- relaunch your program from the Code Lens:
![image](https://user-images.githubusercontent.com/6193897/92342187-a2110e00-f0f2-11ea-86c6-34ea5f7521a7.png)

**Comment by renzhonglu11** [comment]
[Demo.zip](https://github.com/microsoft/vscode-java-test/files/5183216/Demo.zip)

**Comment by jdneo** [comment]
I can run the main class locally by just open the folder demo and click the code lens. 
![demo](https://user-images.githubusercontent.com/6193897/92435130-2ab3ab00-f1d4-11ea-93d2-a20acb5f3056.gif)

**Comment by renzhonglu11** [comment]
![image](https://user-images.githubusercontent.com/57646892/92459151-9b53cb00-f1c6-11ea-8862-6d3c53a50ee8.png)

**Comment by renzhonglu11** [comment]
the first one fails when i add .jar file in reference libraries.
the second works perfectlly when i delete this file

**Comment by jdneo** [comment]
Sorry but I still cannot repro this issue: 
![image](https://user-images.githubusercontent.com/6193897/93735306-1a0d2700-fc0f-11ea-85dd-6c4d12c8b48c.png)
