### ISSUE TITLE
No Code Lens in my mac

### ISSUE THREAD

**Issue by MicePilot** [microsoft/vscode-java-test#1059]
I am a new Java  developer. After creating a maven project, I cannot see Code Lens. Did I do something wrong? My java version is 1.8 and vscode version 1.49. This is my project file.

[test.zip](https://github.com/microsoft/vscode-java-test/files/5212122/test.zip)

**Comment by MicePilot** [comment]
I think I solved this problem, I lowered the plugin version to 0.24.0 and everything worked..

**Comment by jdneo** [comment]
@MicePilot The new version of the extension requires JDK 11. To make sure you can keep getting the improvement in the future. I strongly recommend to install the latest version of extension with JDK 11. If you meet any problem, please let me know.
