### ISSUE TITLE
Insufficient logging when error occurs 

### ISSUE THREAD

**Issue by CarlPer** [microsoft/vscode-java-test#1067]
Steps to reproduce:

Run a test with any mockito argument matcher as a argument in a test suit with multiple tests.
```
  @Test
  public void test() {
    class.method(Mockito.any());
  }
```
Some test might pass but the others will fail configuration with no more information given.

**Comment by jdneo** [comment]
@CarlPer Could you provide a sample project for this issue?

**Comment by CarlPer** [comment]
Method to test:

```
public void method(String  text) {
  if (text == null) {
     throw new Exception("Failed validation");
   }
 }
```

```
@Test
public  void test() {
  method(Mockito.anyString());
}
```
This will fail the test, but in eclipse it provides more information about why it fails

**Comment by jdneo** [comment]
Sorry I cannot get the point. The focal method is check if the input string is null or not. And the test method is passing `anyString()` to the focal method, so it should not fail.

Could you explain more about this? Or would you mind to share a sample project for this issue?
