### ISSUE TITLE
Add support group tests with their source root

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode-java-test#1068]
Add support to group tests with their source root, I have some projects with two test source roots, one for unit and other for integration. So I would like to see them separated in the Test Explorer.

**Comment by jdneo** [comment]
Something similar with #464

**Comment by jdneo** [comment]
Hi @gayanper,

Sorry for such a long time to revisit this issue. Could you provide some screenshot about your project structure? And another question: Is the latest new Test Runner extension meets your requirement?

**Comment by jdneo** [comment]
@gayanper Please let us know if you have more information, thanks!
