### ISSUE TITLE
Add support for shortenCommandLine for Test executor as well

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode-java-test#1069]
When running multiple tests or running a package some time for some large project the path too long error is shown. This can be avoided with the shortenCommandLine support which is there in Java Debug Plugin.

**Comment by jdneo** [comment]
Actually the Test Runner will delegate the execution to the Java Debugger extension. And the `shortenCommandLine` by default is `auto`, which means the Java Debugger extension will determine if the command line needs to shorten according to the launch infomation.

@gayanper Would you mind to share the launch configuration for your tests? I just want to check why the `auto` is not working here.

#### How to check the launch configuration for your tests
1. set `java.test.log.level` to verbose
![image](https://user-images.githubusercontent.com/6193897/97394911-bc12e400-191e-11eb-8e6f-224517a98762.png)

2. Open the output channel of Test Runner
![image](https://user-images.githubusercontent.com/6193897/97394954-d482fe80-191e-11eb-97ac-27ab55b6cde8.png)

3. Run your test and you will see the launch configuration at the beginning of the output
![image](https://user-images.githubusercontent.com/6193897/97395013-f7151780-191e-11eb-8212-90cd053b99bd.png)

> If the configuration contains any private characters, you can simply replace them with other characters but keep the same length.

**Comment by jdneo** [comment]
@gayanper Please need me know if you want to share more information
