### ISSUE TITLE
Support for JUnit 5 parameterized tests

### ISSUE THREAD

**Issue by dsyer** [Microsoft/vscode-java-test#107]
This actually runs:

```
@RunWith(Parameterized.class)
public class ParamTests {

    @Parameters
	public static List<Object[]> parameters() {
        return Arrays.asList(new Object[] {"foo"}, new Object[] {"bar"});
    }

   public ParamTests(String value) {}

   @Test
   public void test() {
       Assert.assertTrue(true);
   }
}
```

But the status is "?" and the report says that no tests were run, with no failures.

Logs:

```
"location":"java:test://com.example.demo.ParamTests"}}>
@@<{"name":"testSuiteStarted", "attributes":{"name":"com.example.demo.ParamTests", "location":"java:test://com.example.demo.ParamTests"}}>
@@<{"name":"testStarted", "attributes":{"name":"test[0]", "location":"java:test://com.example.demo.ParamTests.test[0]"}}>
@@<{"name":"testFinished", "attributes":{"name":"test[0]", "duration":"1"}}>
@@<{"name":"testStarted", "attributes":{"name":"test[1]", "location":"java:test://com.example.demo.ParamTests.test[1]"}}>
@@<{"name":"testFinished", "attributes":{"name":"test[1]", "duration":"0"}}>
@@<{"name":"testSuiteFinished", "attributes":{"name":"com.example.demo.ParamTests"}}>
Total tests run: 2, Failures: 0, Skips: 0
```

**Comment by ansyral** [comment]
@dsyer The feature for parameterized tests is postponed as we need to redesign how to show the status of a composite test which is actually a test collection.

**Comment by SSimcox** [comment]
Is there any headway on this? This is actually the last thing keeping Netbeans installed on my computer right now.

**Comment by ansyral** [comment]
@SSimcox thanks for the feedback, we'll take it in consideration!

**Comment by shawmanz32na** [comment]
The JUnit 5 parameterized tests should also be supported, e.g.
```
class ParamTests {
    static Stream<String> parameters() {
        return Stream.of("foo, "bar");
    }

    @ParameterizedTest
    @MethodSource("parameters")
    void test() {
        Assert.assertTrue(true);
    }
}
```

**Comment by Anatoly03** [comment]
<img width="93" alt="Screenshot 2023-04-19 at 17 59 35" src="https://user-images.githubusercontent.com/44678124/233133265-b05a2fe6-be07-4076-a6dc-92d9fc175e69.png">

I experience the issue although it was considered completed? Downloaded the latest java extensions for VSC today

**Comment by jdneo** [comment]
![image](https://user-images.githubusercontent.com/6193897/233237451-01854ab5-897f-4b84-86b4-cb59ce9a7b55.png)

@Anatoly03 Please file an issue with repro steps if it's not working.
