### ISSUE TITLE
link to string diff in test report if assertEquals of string fails

### ISSUE THREAD

**Issue by drummer3333** [microsoft/vscode-java-test#1070]
if assertEquals or similar fails the output of the test is somthing like:
```
org.junit.ComparisonFailure: expected:<1[
expected
]> but was:<1[
value
]>
```
A few of our tests export format a structure as a structured String and test this equal to a predefined String. So any diffence in structure can be seen in the Testresults. 
I'm comming from Eclipse and there you get a nice diff view for such Failed Tests which makes it ease to see the failures.

Please add a link in the Test View so `expected` and `value` can be open in the standrard VSCode Diff View.

**Comment by jdneo** [comment]
Hi @drummer3333, do you mean something like the SCM diff view?

**Comment by drummer3333** [comment]
Yes, like that.

**Comment by maroony** [comment]
I really miss this feature, too! In the meantime I'm using the extension "Partial Diff" and Copy&Paste the result and than do the diff.

**Comment by jdneo** [comment]
VS Code now is designing a new set of testing API, and having the capability to show this diff view. See the point 3 in this comment: https://github.com/microsoft/vscode/issues/107467#issuecomment-800044323

So far, from my understanding, different assertion libs have their own format to show expected-actual message. Then I need to parse them according to the format and filling the related fields.

**Comment by jdneo** [comment]
Finally it comes in 0.31.0 with the integration of the new VS Code testing API!

![image](https://user-images.githubusercontent.com/6193897/128447492-91c2138f-1cb8-4c39-9e08-f81259bba6c9.png)

**Comment by ocallesp** [comment]
@jdneo can you point me to the new api  (documentation) that shows the diff ?

**Comment by jdneo** [comment]
If you are looking for the vscode extension api for testing, you can find it here: https://github.com/microsoft/vscode/blob/d8af24e15daeb1ad5bd0ee4858852e60ea545c66/src/vscode-dts/vscode.d.ts#L18193
