### ISSUE TITLE
Cannot see System.out.println used in tests

### ISSUE THREAD

**Issue by paulosandinof** [microsoft/vscode-java-test#1072]
I'm using the extension but I'm unable to see the output of System.out.println on my console. I saw in some websites that it was supposed to appear on the Java Test Runner Output window, but here this window is always empty.
Example of code:
```
    @Test
    public void calculaImpostoTest() {
        System.out.println("TESTE");
        double resultado = CalculoImpostoRenda.calculaImposto(entrada);
        assertEquals(esperado, resultado, 0.01);
    }
```
And a can't see the output when running the test from the option Run Test on the editor.

I'm using JDK 11 and version 0.24.2 of the extension.

I'm sorry if I'm doing something wrong, but I couldn't find anywhere on the internet how to solve this. Thanks in advance.

**Comment by jdneo** [comment]
@paulosandinof Has the problem get resolved?

**Comment by paulosandinof** [comment]
Yes. I actually found where the program was outputting. I didn't found an option to delete the issue so I closed. Sorry about that.

**Comment by jdneo** [comment]
Good to know problems are solved. Thanks!
