### ISSUE TITLE
How to highlight and enable shortcut to go error code place

### ISSUE THREAD

**Issue by AnhPV670** [microsoft/vscode-java-test#1090]
I am considering to use vscode. When running a Junit test script, if it has an error then a Java Test report. But it's really hard to know where is the error line?
![image](https://user-images.githubusercontent.com/68980608/98005234-64dfa880-1e23-11eb-89ff-267490235703.png)

Do we have anyway to show it like this?
![image](https://user-images.githubusercontent.com/68980608/98005479-a708ea00-1e23-11eb-99f9-2e9f8622d3cf.png)

**Comment by jdneo** [comment]
Duplicated with #384.

And we already have a PR for that #1089. This feature will available in the next version which is very soon
