### ISSUE TITLE
Don't show the test icon in the sidebar unless I am actually working in a Java project or tests are found

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-java-test#1091]
If I am working in a Hugo project so I shouldn't be seeing the icon:

![image](https://user-images.githubusercontent.com/11936772/98187050-a9c41780-1ed5-11eb-954b-f2b5b31e261a.png)

**Comment by jdneo** [comment]
Thanks @tristan957. I'm closing this one because it's duplicated with #793
