### ISSUE TITLE
Feature Req: Support filtering tests by JUnit 5 tags

### ISSUE THREAD

**Issue by Skynet0** [microsoft/vscode-java-test#1092]
https://junit.org/junit5/docs/current/user-guide/#running-tests-tag-expressions

A lot of our existing tests are identified by tags, in addition to being in different files. As far as I'm aware, there's no way to run all tests in a workspace that match a tag expression. I would like to be able to create and run test configurations that filter tests based on tags.

**Comment by jdneo** [comment]
This can probably be done once the upstream proposed API for tags: https://github.com/microsoft/vscode/issues/129456

**Comment by jdneo** [comment]
To support this feature, follow tasks need to be done:

#### Recognize `@Tag("foo")`

When constructing a JUnit 5's test item, we can get its tag value via JDT's API, something like: `method.getAnnotation("Tag").getMemberValuePairs()[0].getValue()`

#### Recognize `@Tags({@Tag("foo"), @Tag("bar")})`
Similar with the `@Tag` annotation, but now the value we get are multiple `@Tag` instances, so just recursively dealing with the annotations should work.

#### Be able to run JUnit 5's tests with tag filtering
The tag filtering options should be exposed from the test configuration, so users can persist the filtering settings.

**Comment by jdneo** [comment]
To enable the tags filter, you need to add following sections into your `java.test.configuration`:

```
"testKind": "junit",
"filters": {
    "tags": [
        "foo",    // ---> include tag 'foo'
        "!bar"    // ---> exclude tag 'bar'
    ]
}
```
