### ISSUE TITLE
Unable To Run Java Test Runner

### ISSUE THREAD

**Issue by UHaooooo** [Microsoft/vscode-java-test#110]
![image](https://user-images.githubusercontent.com/29447608/35851877-3ec27bde-0b64-11e8-9af0-c04337248e3a.png)

There's no symbol beside the "Run Test".
And there's error showing 
"Exception occers while parsing params. Details: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined"

**Comment by ansyral** [comment]
@UHaooooo how did you trigger the test? clicking on "Run Test" codelens?

**Comment by UHaooooo** [comment]
@ansyral Ya. Btw those test do appear in test navigator

**Comment by ansyral** [comment]
@UHaooooo I couldn't repro this case. We've added a command "Java:log" to open test log in recent release, Could you repro this locally and share your logs here?

**Comment by jdneo** [comment]
Closing this since it's inactive for a long time. @UHaooooo Please feel free to reopen it if this problem still occurs
