### ISSUE TITLE
Add modulePath field in java.test.config

### ISSUE THREAD

**Issue by Empressia** [microsoft/vscode-java-test#1101]
## 環境
* VSCode 1.51.1
* Windows 10 Pro

『build/module/』に依存関係にあるモジュールを配置しています。  

## 問題

テスト用に、以下のように設定していますが、  
settings.json
```json
{
	"java.test.config": [
		{
			"name": "t",
			"vmArgs": ["--module-path", "bin/main/;build/module/"],
		}
	],
	"java.test.defaultConfig": "t"
}
```

テストを実行すると、以下のようなメッセージが出て、失敗してしまいます。  
> Error occurred during initialization of boot layer
> java.lang.module.FindException: Module _RequiredModule_ not found, required by _MyModule_

## その他

なお、テストではない、通常の起動設定では、以下のように設定していて、正常に動作しています。  
launch.json
```json
		{
			"type": "java",
			"name": "Debug (Launch) - Current File",
			"request": "launch",
			"mainClass": "${file}",
			"modulePaths": [
				"bin/main/",
				"build/module/"
			]
		},
```

いろいろ試していると、vmArgs自体は、テスト実行時に、反映されているようなので、  
"--module-path"が後続のオプションで上書きされているのかわかりませんが、無効化されているように見えます。  

指定の仕方に問題があるのでしょうか……。

**Comment by jdneo** [comment]
@Empressia Would you mind to share a sample project for this issue?

**Comment by Empressia** [comment]
@jdneo 簡単なのを作ってみました。これでどうでしょうか。
https://github.com/Empressia/VSCodeJavaTest01

**Comment by jdneo** [comment]
Closed and tracked by #1199. A rough idea is to fully honor the launch configuration of Debugger for Java thus the user can set modulepaths separately in the setting.

**Comment by jdneo** [comment]
@Empressia Will it work for you if Debugger expose a setting to specify modulePaths in the workspace setting?

And another question, in your case, will you need to configure multiple different modulePaths when running towards different cases?

**Comment by Empressia** [comment]
回答になるかわかりませんが、デバッガーはmodulePathを生成していると考えています。  
Gradleから正しく検出されてmodulePathが構成されるのが理想です。  

検出しないのであれば、差分を追加設定する必要があります。  
現在は、vmArgsにmodule-pathを設定すると、両方が有効になるのではなく、片方だけが有効になってしまいます。  
よって、ユーザーが指定したものと、検出したものを、同時に設定する機能が少なくとも必要だと考えます。  

-----

I don't know if it will be an answer, but I think the debugger is generating a modulePath.  
The ideal is to be detected from Gradle. And it's set on --module-path.  

If you don't want to detect it from gradle correctly, you're going to need to set additional differences.  
Currently, if I set module-path to vmArgs, only one of them will be enabled instead of both.  
Therefore, I think that I need at least the function of setting what the user specified and what is detected at the same time.

**Comment by Empressia** [comment]
短く回答します。

あなたが言うとおりの理由で、わたしは、モジュールパスを指定する必要があり、
わたしは、この設定を"java.test.config"で行うべきだと考えていました。
これが、デバッガーの設定なのか、テストランナーの設定なのかは、認識できていません。

----------

I will answer short.

For the reasons you say, I need to specify a module path,
I thought this should be done with "java.test.config".
I don't know if this is a debugger setting or a test runner setting.

**Comment by jdneo** [comment]
End game verification steps:

1. Download this project: https://github.com/Empressia/VSCodeJavaTest01
2. Update `java.test.config` in settings.json:
```
"java.test.config": [
		{
			"name": "t",
			"modulePaths": ["${workspaceFolder}/bin/main", "${workspaceFolder}/module/"],
		}
	],
```
3. Run `Test01Tests.java`
