### ISSUE TITLE
java.test.report.showAfterExecution is not available in the workspace settings

### ISSUE THREAD

**Issue by bennettdams** [microsoft/vscode-java-test#1104]
As I'm running a project inside a Docker container via VS Code's Remote Containers, I want to have a lot of settings in the workspace settings (instead of the user settings), so people who clone the repo don't have to configure it themselves.

The `java.test.report.showAfterExecution` is not available for workspace settings though:

![image](https://user-images.githubusercontent.com/29319414/99671366-3ba15800-2a72-11eb-9e0a-06a8004e8d86.png)

Is there a way to activate this setting for the workspace?

PS: This is the PR which added this setting presumably:  https://github.com/microsoft/vscode-java-test/pull/712

**Comment by jdneo** [comment]
That requires to change the [setting's scope](https://github.com/microsoft/vscode-java-test/blob/master/package.json#L264) from `application` to `window`.

This seems a valid request, let me think more about it and I'll update to you when I have more insight.

Thanks.

**Comment by jdneo** [comment]
@bennettdams I'm planning it to put it into the next release (0.27.0)

**Comment by bennettdams** [comment]
> @bennettdams I'm planning it to put it into the next release (0.27.0)

Great, thanks a lot!
