### ISSUE TITLE
The "java.test.config" setting is ignored

### ISSUE THREAD

**Issue by yacut** [microsoft/vscode-java-test#1108]
### Workspace settings:

```json
{
    "java.test.config": [
        {
            "name": "Unit Tests",
            "workingDirectory": "${workspaceFolder}",
            "args": [
                "--include-classname",
                ".*Test",
            ],
        },
        {
            "name": "Integration Tests",
            "workingDirectory": "${workspaceFolder}",
            "args": [
                "--include-classname",
                ".*IT",
            ],
        }
    ],
    "java.test.defaultConfig": "Unit Tests"
}
```

### Actual behaviour

The "Run all tests" command starts all tests including integration tests

### Expected behaviour

The "Run all tests" command starts only unit tests

**Comment by jdneo** [comment]
Thanks @yacut, we can only run test folders which are marked as test by the build tools (which are persisted in `.classpath`)

This issue is the same as https://github.com/microsoft/vscode-java-test/issues/464.
