### ISSUE TITLE
The case with @Test not in src/test will not be processed

### ISSUE THREAD

**Issue by oliver-csu** [microsoft/vscode-java-test#1109]
our module is a auto-test module, not the unit test for business code

so, the case is in src/main

in IntellJ idea, the case with @Test will be precessed

thanks

**Comment by jdneo** [comment]
Thanks @oliver-csu, it's duplicated with #464. Let's track it there.

**Comment by oliver-csu** [comment]
thank you again

**Comment by kmjuq** [comment]
> thank you again

What should i do ?please tell me.

**Comment by jdneo** [comment]
@kmjuq Is your project a Maven/Gradle one?
