### ISSUE TITLE
A feature request: Customize test sorting.

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-java-test#1114]
Customize sort type, such as sorting by position, sorting by name.

**Comment by jdneo** [comment]
@bonaluo is this for test report or the explorer?

**Comment by bonaluo** [comment]
The explorer

**Comment by jdneo** [comment]
Supported in 0.31.0 with the VS Code's latest testing API

![image](https://user-images.githubusercontent.com/6193897/128448539-0e7a6e7f-c4eb-4c89-9e0f-df522aff98cf.png)
