### ISSUE TITLE
It is not possible to start multiple junit tests or multiple Java applications under the same package, and the prompt is waiting...

### ISSUE THREAD

**Issue by netzhouxinghong** [microsoft/vscode-java-test#1115]
Issue Type: <b>Bug</b>

It is not possible to start multiple junit tests or multiple Java applications under the same package, and the prompt is waiting...

Extension version: 0.11.0
VS Code version: Code - Insiders 1.52.0-insider (6026ab576dc6a4fbb8e255241a364816f42464c5, 2020-11-23T05:56:29.761Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (4.85GB free)|
|Process Argv|--crash-reporter-id af141bd3-ad47-4a40-9a2e-daa571f22a8f|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by jdneo** [comment]
@netzhouxinghong I guess you are talking about running multiple test classes at the same time, right?

**Comment by netzhouxinghong** [comment]
Yes

**Comment by jdneo** [comment]
This is somehow similar to #780, let me link them first.

**Comment by netzhouxinghong** [comment]
Yes, it is this problem. Your analysis is right. This problem has been for a long time. It does not exist in Eclipse and idea and can execute multiple SpringBoot Junit test applications and Java test applications as expected
是的正是此问题 ，您分析的很对，此问题很长一段时间了，这个在Eclipse和idea中并不存在并且可以按照预期执行多个SpringBoot Junit测试应用和Java测试应用程序。

**Comment by jdneo** [comment]
Multi-selection and run is supported in 0.31.0
