### ISSUE TITLE
Please provide custom aria labels for status bar items.

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode-java-test#1126]
CC: @isidorn

As I am blind, I use VSCode with the help of a screen reader to execute my test cases. After running the tests, I access the status bar to check the test results.
The only information present in the status bar that is apparently related to the test results and which is presented to me by the screen reader is the following:
'x 0 check 3'

It seems to me that the extension could make use of aria labels with information about the results. Screen readers would pass this information on to users without any major problems.

Actually I am running code-insiders 1.53.0-insider in my arch linux box.

**Comment by jdneo** [comment]
@jvesouza Thank you for reporting this issue to us! I'm so glad that you are using our product to write Java code.

I've update the implementation and use Narrator (I'm on a Windows machine) to verify. Now the 'x 0 check 3' will read as 'test result: 0 failed, 3 passed'. Does it sounds good to you? If yes, I'll send the PR later.

**Comment by jvesouza** [comment]
wow!! Exactly what I would like to hear.
I need to test with orca, my screen reader.
Thank you very much.

**Comment by isidorn** [comment]
@jdneo thanks a lot for jumping on this.
Also let us know if something is missing on the VS Code side, though you should have all the API needed I believe.

My preference would be for the title to be more concise
"tests: 0 failed, 3 passed"
Or even better "0 failed, 3 passed tests"
Since the most important information should be at the start of the label so screen reader users can skip the repetative end "Tests"
Though @jvesouza would probably be better to give feedback regarding this

**Comment by jvesouza** [comment]
I agree with @isidorn, "0 failed, 3 passed tests".

**Comment by jdneo** [comment]
@isidorn I see. Thank you for the suggestion. I'll change to "0 failed, 3 passed tests" and raise the PR.

@jvesouza I planned this fix into the next release. But if you want to have a private build, please feel free to let me know.

**Comment by jvesouza** [comment]
A private build can be useful as I can check changes with orca and if I find any problems I can report in advance.
But if the next version is released quickly, the private build may not be necessary.

**Comment by jdneo** [comment]
@jvesouza Here it is: 
[vscode-java-test-0.27.0.vsix.zip](https://github.com/microsoft/vscode-java-test/files/5812004/vscode-java-test-0.27.0.vsix.zip)

**Comment by jvesouza** [comment]
Works perfectly, thanks.

**Comment by jdneo** [comment]
@jvesouza You are welcome. Happy coding!
