### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#113]
1. clone code from https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples
2. Run functionTests class: error occurs in toggle developer tools shown as below

![image](https://user-images.githubusercontent.com/22470312/36017526-09917266-0db3-11e8-8d86-8bfef1c17bfe.png)

**Comment by ansyral** [comment]
cannot repro locally. I'll update code to add the illegal json content into log. Let's run the tests again and see the logs.
