### ISSUE TITLE
Unit Test breakpoints don't light up when debugging

### ISSUE THREAD

**Issue by eak006** [microsoft/vscode-java-test#1138]
When I'm debugging a Java unit test (JUnit 5) with a set breakpoint(s), I can't tell when/where I've hit a breakpoint by looking directly at the code and waiting for a horizontal streak of yellow to appear.

I can, however, visit the `Call Stack` section in the Run/Debug side bar to see the `PAUSED ON BREAKPOINT` status message right next to the main thread. The only way I can progress the debug session for a unit test is by hovering over said status message and choosing the usual debug operations.

I can't necessarily identify *which* breakpoint has been hit. With that in mind, I'm not sure how I can step into a function if my editor doesn't display what line of code the debugger's paused at.

Has anyone encountered this issue before? Sorry for not providing info about my system settings. I'm currently using a different machine at the moment.

**Comment by jdneo** [comment]
@eak006 Is it possible to share more information about the issue? Or maybe a sample project? I can test it on my side to see if I can repro it.

**Comment by eak006** [comment]
Sorry for the long wait. I can't comment on the specifics of my local machine's settings, but I heard my co-workers had similar issues. We *think* it may be because we are still on Java 8 and *not* Java 11 since that's the version Red Hat's Language Support Java plugin prefers.

**Comment by jdneo** [comment]
@eak006 Java 11 is only required to activate the Java Language Support. You can still use Java 8 to build your project, by setting the following setting to let the Java Language Server know where are the JDK installations. It will pick the most match JDK according to your project configuration (pom/gradle)

```
"java.configuration.runtimes": [
  {
    "name": "JavaSE-1.8",
    "path": "/path/to/jdk-8",
  },
  {
    "name": "JavaSE-11",
    "path": "/path/to/jdk-11",
  }
]
```

Have you tried that?

**Comment by eak006** [comment]
Yes, those settings have been set. Fortunately, the unit tests run perfectly. I suppose if I ever need to debug them though, I can switch over to Eclipse.

**Comment by jdneo** [comment]
@eak006 Hmmm, sounds wired. I haven't met this situation before. I think a sample project is still needed to figure out what's the gap here.

**Comment by eak006** [comment]
I understand. You can close this thread until it becomes relevant again since I have found a backdoor solution in the meantime.

**Comment by jdneo** [comment]
Ok, but feel free to let us know when a sample project is available for this issue.

**Comment by eak006** [comment]
Update: My team shifted to Java 11 and everything is working fine.

On a slight tangent, I found that [this person](https://github.com/microsoft/vscode-java-debug/issues/656) had a similar issue to mine but their solution didn't work for me.

**Comment by eak006** [comment]
UPDATE: actual fix was that I deleted some lingering Java subprojects that my team no longer needed. It seems my working directory was out-of-date.
