### ISSUE TITLE
Couldn't see test explorer and code lens for maven project

### ISSUE THREAD

**Issue by vswamire** [microsoft/vscode-java-test#1139]
Hello,

Thanks for the pretty interesting feature.

I'm facing issues with the code lens and test explorer for the maven project. I've tried many ways changing .classpath, re-installing vscode, looking at the issues already been notified by other #470. Nothing seems to be working out. can you please help me out in setting up the IDE.

Thanks,
venkat.

**Comment by jdneo** [comment]
Would you mind to provide a sample project to us?

**Comment by vswamire** [comment]
Hello Sheng, thanks for reaching out. I didn't quite get what you mean by a sample project. 

I'm working on the junit tests maven project. The run|debug code lens are working when there's a main method in tests. but in our project we don't have a main method.

I think the java debugger or java test runner extensions are looking the project as java projects but it is actually a maven project.

Can you please help me out in resolving this issue.

Thanks,
venkat.

**Comment by jdneo** [comment]
You can share a sample project that is not working on your side. (You can simplify it to remove all the code that you don't want to share)

Then I can take a look at the project to see what's the gap.

**Comment by vswamire** [comment]
Hello, Ihttp://iatgitlab.mathworks.com/help_search/testintegration.git have shared the sample project with you. Please take a look and let me know.

https://drive.google.com/drive/folders/1VQC2rZrIwXVl7D3l4rwiZHPeFQafA0vt?usp=sharing

**Comment by jdneo** [comment]
Is the link correct? I cannot see any files in the link.
