### ISSUE TITLE
Unable to define a custom classpath for a Junit test

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode-java-test#1140]
Hi,
Some tests require custom classpath to run, when having a workspace with multiple projects (defined with .project and .classpath like in eclipse) and dependency inversion between some projects (plugin architecture).

Like in eclipse we need to define a launch configuration with a custom classpath made of path or project name.
We didn't found a way to do it in [Run with Configuration](https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration).

Using "-cp" in vmArgs or "CLASSPATH" env variable didn't work.

**Comment by jdneo** [comment]
Currently the when launch a test, we resolve the classpath and pass it to the Java Debugger. So the `-cp` is ignored.

This a valid request that the Test Runner should consider how to better integrate with the Java Debugger.

**Comment by jdneo** [comment]
Closed and tracked by #1199. A rough idea is to fully honor the launch configuration of `Debugger for Java` thus the user can set `classpaths` separately in the setting.

**Comment by jdneo** [comment]
@llgcode Will it work for you if Debugger expose a setting to specify classpaths in the workspace setting?

And another question, in your case, will you need to configure multiple different classpaths when running towards different cases?

**Comment by llgcode** [comment]
Hi Jdneo, sorry for the late.
A unique classpath for debugging could do the trick but a custom classpath for some specific junit are needed sometimes.
Thanks !

**Comment by jdneo** [comment]
End game verification steps:

1. Download https://github.com/jdneo/invisble-project?organization=jdneo&organization=jdneo
    This project missed a required jar to launch the junit 4 tests. But it's been added in the test configuration via classPaths.
2. Run `MyJunit4Test.java`

**Comment by llgcode** [comment]
Hi @jdneo,
thanks for this improvement, I guess it will really help us configuring our projects to launch test. Do you know if it's possible to define some sort of custom variable so we can reuse it in this classpath ?

**Comment by llgcode** [comment]
May be it needs to define. It could be a configuration variable in setting (like we could have in Eclipse) or an environment variable. Something that we could help factorise setting to not copy/paste every time we need to define the same classpath.
