### ISSUE TITLE
Non-java JUnit integration

### ISSUE THREAD

**Issue by azidar** [microsoft/vscode-java-test#1142]
We are interested in reusing your vscode UI interface, but have a non-java project with our own LSP. Is it possible to configure this plugin to integrate with a different LSP implementation? If so, any recommendations for where to start?

**Comment by jdneo** [comment]
If it's for testing purpose, will you consider the proposed new VS Code Testing API? https://github.com/microsoft/vscode/issues/107467

**Comment by azidar** [comment]
Ah thanks for the link! I'll check it out.
