### ISSUE TITLE
Remote developing: code lensing doesn't show up in my Junit test file 

### ISSUE THREAD

**Issue by lloydbond** [microsoft/vscode-java-test#1143]
The test runner doesn't show up either. Everything shows up just fine and works well locally. It's just when I attempt to develop out of a VPS using this extension pack [remote development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack). I have followed the FAQ steps for gradle just in case that would help. Ultimately, I'm just doing the Java track on [Element.io](https://element.io). It would be nice to be able to debug each test. 

I have Java 15 installed locally and remotely and gradle 6.8 local and remote as well. Not sure what I'm missing. Any help with this would be appreciated.

-Lloyd

**Comment by jdneo** [comment]
Would you mind to provide some detail steps for reproducing the issue? I would like to try it on my side.

**Comment by lloydbond** [comment]
Open VSCode
install the remote extension pack from Microsoft.

Connect to a remote VPS with ssh
install the extensions lombok, Gradle Tasks, Gradle Language Support, and the Java Extension Pack.
download a java solution with junit tests (example: https://github.com/exercism/java/tree/main/exercises/practice/acronym) to your VPS
Then open the java solution in current window.

If you open the same solution locally, you would get code lensing in the java test file and the Test Runner button would show up on the left extensions panel. If you download your java solution locally and open that in VSCode with the same extensions, you will get the Java Test Runner extension loaded and the code lensing in the Java test file will show up.

Let me know if you need more details.
-Lloyd

**Comment by jdneo** [comment]
What's the folder opened in your VS Code I opened  https://github.com/exercism/java/tree/main/exercises/practice/acronym and see this warning

![image](https://user-images.githubusercontent.com/6193897/110061442-90a77680-7da2-11eb-8f4c-4d0d991e93c4.png)
