### ISSUE TITLE
Step Filters with Java Test Runner?

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode-java-test#1152]
The default debugger of vscode provides [a configuration option](https://code.visualstudio.com/docs/java/java-debugging#_launch) to avoid stepping into certain packages(using wildcards). But I had a look at the configuration options for Java Test Runner [here](https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration), and it seems that it doesn't provide the same option. Is that really the case? Currently it's pretty annoying that I can't only step through my own project files.
Thanks in advance.

**Comment by jdneo** [comment]
Closed and track by #1199

**Comment by jdneo** [comment]
Also, you can also use the setting that the debugger exposed in the `settings.json`

For example, add following setting into settings.json

```
"java.debug.settings.stepping.skipClasses": ["$JDK"]
```

**Comment by aderchox** [comment]
The settings.json one works! Thanks.
