### ISSUE TITLE
how does this pluging determine java home?

### ISSUE THREAD

**Issue by shockdm** [microsoft/vscode-java-test#1154]
I am struggling to understand where Java Test plugin is getting JAVA_HOME value from. System wide JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`, however when trying to run tests via `Run Test` annotation - and executing the following code in the test itself:
```
System.out.println(System.getProperty("java.version"));
System.out.println(System.getProperty("java.home"));
```

I am seeing:
```
1.8.0_241
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
```

This JRE is not used or set anywhere that I know of...

This is on MacOS `11.2.1`

Deleting this JRE location - makes it automatically switch to another available JDK or JRE... So it seems that this is determined by the OS, but I wanted to understand if Java Test plugin has any logic with regards to determining JAVA_HOME.

The interesting thing is - running `/usr/libexec/java_home`, produces:
`/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`

But prior to deletion - the JVM defaulted to `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` still.

**Comment by jdneo** [comment]
The Test Runner extension itself does not detect JDK installations. The [Java Language Support](https://github.com/redhat-developer/vscode-java) is responsible for such task.

The Java Language Support needs JDK 11 to launch itself, but it does not mean it's also a requirement to build your project. I guess your project has some kind of setting in pom,xml/build.gradlet o specify the Java version to 1.8. The Java Language Support will pick the matchest JDK to build and launch your project.

`/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` this could be a pre-installed JDK on your machine I guess.

Does that answer your question?

**Comment by jdneo** [comment]
Close for inactive. If you have more questions, feel free to leave comments.
