### ISSUE TITLE
Detect the presence of Test Report (Test Explorer) for keyboard shortcut

### ISSUE THREAD

**Issue by kohane27** [microsoft/vscode-java-test#1156]
Hello there! Thanks for looking into this issue. I appreciate your time and help.

This is what I mean by "Test Report being present":

![presence](https://user-images.githubusercontent.com/57322459/110730713-e5903480-825b-11eb-9bf1-9f46ab1ac18c.png)

The Java Test Report in open in a tab (in the second Editor Group)

I'm trying to add a keybinding that would allow me to use the same keybinding to run both normal Java file and Java Test file:

Command: `code-runner.run` (it's from an extension)
Keybinding: `Ctrl+r`
When: `editorTextFocus`

Command: `java.test.editor.run`
Keybinding: `Ctrl+r`
When: `testExplorerVisible` (doesn't work)

![shortcut](https://user-images.githubusercontent.com/57322459/110730721-eb861580-825b-11eb-982c-eb1ebcf5fbe0.png)

But the `When` condition `testExplorerVisible` doesn't work. I also tried `TestExplorerVisible`.

Is there a way to detect the presence of Test Report?

Thank you!

**Comment by jdneo** [comment]
I think `testExplorerVisible` is a context registered by https://github.com/hbenl/vscode-test-explorer, which is not supported by this extension.

How about this workaround: `"resourceFilename =~ /.*Tests?.java$/"`

**Comment by kohane27** [comment]
Oh yes, I was randomly trying conditions like `testExplorerVisible`, probably inspired by that addon.

I'm happy to report that your workaround solution works flawlessly! Should've looked more closely into the vscode's innate condition supports.

Thanks again!

**Comment by jdneo** [comment]
Good to know it works. You can take a look at this post if you are interested: https://code.visualstudio.com/api/references/when-clause-contexts.
