### ISSUE TITLE
Failed to get workspace folder for the test items

### ISSUE THREAD

**Issue by fakeYanss** [microsoft/vscode-java-test#1158]
The error only occurred in this way:

1. set up a project, path: `/project`
2. make symbolic links, `ln -s /project /home/user/project`
3. vscode open new folder
    1. open `/project`, vscode-java-test run as well as always
    2. open `/project /home/user/project`, vscode-java-test cannot auto attach unit test function, and run specified funciton, will make error `Failed to get workspace folder for the test items`

**Comment by jdneo** [comment]
Duplicated with https://github.com/microsoft/vscode-java-test/issues/630
