### ISSUE TITLE
Junit4 Not Working when i used the new java project with no build tools

### ISSUE THREAD

**Issue by shaif-dorIT** [microsoft/vscode-java-test#1159]
I tried to run some unit test using Junit4.

I downloaded the jars as they said in the docs: [VScode Java unit testing](https://code.visualstudio.com/docs/java/java-testing#_getting-started-for-junit-4)

and added them to my project under lib directory.
![image](https://user-images.githubusercontent.com/53523883/111333387-4fa14300-867b-11eb-874f-f59165cff5bd.png)

they have been recognized by the java project manager:
![image](https://user-images.githubusercontent.com/53523883/111333505-6f386b80-867b-11eb-9121-588a550cd262.png)

but still i get this error then i try to run test:
```
java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:333)
Class.java:333
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadTestLoaderClass(RemoteTestRunner.java:381)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:371)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:366)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:310)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:225)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.Filter
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
BuiltinClassLoader.java:602
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
ClassLoaders.java:178
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
ClassLoader.java:521
	... 8 more
```

my VScode Version is the latest:
```
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

can someone help me with some direction what could made this error?

Thanks

**Comment by jdneo** [comment]
It should be ok. Can you try clean the workspace and restart?

![image](https://user-images.githubusercontent.com/6193897/111402725-b3bd1900-8706-11eb-9920-283a7a4b27a5.png)

If it's still not working after cleaning, could you share the project for us to diagnostic?

**Comment by shaif-dorIT** [comment]
Hi, Thanks but I tried it already I will try it again and will update the result back.

hoping for it to work :).

**Comment by shaif-dorIT** [comment]
Well It's still refusing to work.

how you want me to share the project with you?

currently it's private repository here on GitHub.

**Comment by jdneo** [comment]
You can make a copy and push to a new public repo in GitHub. Remember to remove all the private information.

**Comment by shaif-dorIT** [comment]
it's not really private it's just our college lessons mini-project we need to develop step by step through the semester.

This is the new public repo I created with the basic files: [MyRepo](https://github.com/shaif-dorIT/Java-Test-Runner-Not-Working).

you can test it I also uploaded which jars I used in the lib directory.

**Comment by jdneo** [comment]
Hmm, cannot repro

![image](https://user-images.githubusercontent.com/6193897/111743487-bd8c7b00-88c4-11eb-8627-a98aada2d258.png)

**Comment by jdneo** [comment]
Reinstall the extension maybe?

Remove the folder `$home/.vscode/extensions/vscjava.vscode-java-test-0.xx.x` entirely, and install it again?

**Comment by shaif-dorIT** [comment]
Summary:
I have tried uninstall deleting the file and reinstalling the extension.
Then I tried to install jdk-11 of openAdopt from the Configure Java Runtime menu in VSCode.

Sadly, both failed.

Then, I got an idea to check my path to the directory for any non alphanumeric characters.
Since my folder has Hebrew characters I moved it to by directly on my Desktop folder then it's started working.

Now, I can not say for sure if that was the problem or that i have 144 characters in my original path to the project.

**Comment by shaif-dorIT** [comment]
Should I Close this issue?

or you want to keep it open until the Hebrew characters in path is resolved?

**Comment by jdneo** [comment]
An example of a path with Hebrew characters?

(Let's just leave this open)

**Comment by shaif-dorIT** [comment]
Hello just checking where it's standing?

Should I close this issue?

Also, recently the Java test explorer not showing the tests, how does it find them?
does it's looking inside specific directory and can I change it?

Thanks for your help

**Comment by jdneo** [comment]
The extension will check the folders according to the project's source paths. What's your project structure now?

**Comment by shaif-dorIT** [comment]
![image](https://user-images.githubusercontent.com/53523883/116670893-f1b98800-a9a8-11eb-89bc-5759e3f53b6e.png)
This is the the folder structure and all my test sit under unittests

**Comment by jdneo** [comment]
Is it possible to share the project?
