### ISSUE TITLE
After removing the extension Icon is still visible

### ISSUE THREAD

**Issue by RockiRider** [microsoft/vscode-java-test#1160]
![image](https://user-images.githubusercontent.com/32150283/111371541-79656480-8691-11eb-9acd-70c16843ff2a.png)

Can I not uninstall this extension? I'm keeping the icon hidden for now, its just a bit annoying to have there especially when I am not using it

**Comment by jdneo** [comment]
Do you want to disable the extension when you are not working on a Java project?

**Comment by RockiRider** [comment]
Nope, I just wanted it completely uninstalled. When I uninstall it and reload VSCode, the icon in the side bar is still there for some reason. 

As shown in the screenshot above, the extension is not currently installed but somehow the Icon is still there?

**Comment by jdneo** [comment]
I guess it should be other extensions register their tree view in the test view. Please check if there is any other test related extensions installed on your side.
