### ISSUE TITLE
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing

### ISSUE THREAD

**Issue by zackaka** [microsoft/vscode-java-test#1161]
I am using vs code with java. I installed everything and running java classes fine. 
I tried using JUnit testing and below is the error message am getting I have no idea what's going on here. 

<img width="653" alt="Screen Shot 2021-03-21 at 2 29 22 AM" src="https://user-images.githubusercontent.com/81069442/111897331-561e1a80-89ed-11eb-9cc3-e69bb55395d0.png">

**Comment by jdneo** [comment]
@zackaka Is there any build tools in your project folder? Or it's just a simple folder with Java files in it.

Meanwhile, please check if https://search.maven.org/artifact/org.hamcrest/hamcrest-core/1.3/jar is on your classpath

**Comment by zackaka** [comment]
there is no build tools were used. Also, i have added hamcrest-core  and junit-4 into my class path.

**Comment by jdneo** [comment]
Any special character in your project path?
