### ISSUE TITLE
Adopt new Test APIs

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1162]
VS Code team is working on a new set of testing APIs. We plan to migrate to that API to provide better and more unified experience for testing scenarios.

**Comment by TimWebb** [comment]
@jdneo Is there any chance of leveraging the `TestMessage.location` field to include where the message should be bound in the source for assert failures and exceptions? It would appear from usage you already have this data from other visualizations the plugin does.

The other place `location` is set in `findTestLocation` also seems to set the general location of the test, whereas, I read the `TestMessage.location` field to be specific location inside the test method. Certainly I may be wrong on the interpretation of intended usage!  All that said, awesome to have these APIs stabilizing!

For context, working on an integration that leverages test results on the new Testing API.

**Comment by jdneo** [comment]
@TimWebb Do you mean set the location to the exact line where the case is failed (instead of appearing at the method definition)?

**Comment by TimWebb** [comment]
@jdneo Yes, that was my intent. 

More specifically, if an assert fails, have the TestMessage's location of the assert match the location in the method for the given assert. Similarly if something triggers an exception, we could have a TestMessage for the exception in potentially even a different file - such as extract from the exception stack the location in testMethod() that resulted in the failure.

**Comment by jdneo** [comment]
> More specifically, if an assert fails, have the TestMessage's location of the assert match the location in the method for the given assert. 

Currently we will put a diff view at the location of assertion failure (in most cases, since it's parsed via regexp)

![image](https://user-images.githubusercontent.com/6193897/128445447-01740e7f-6dc3-4690-bd20-94fa10252824.png)

But I agree put the stacktrace to where it happens is a good idea.

> Similarly if something triggers an exception, we could have a TestMessage for the exception in potentially even a different file - such as extract from the exception stack the location in testMethod() that resulted in the failure.

Not quite sure about this. My concern is how user can know which case generates this message if they located in different files.
