### ISSUE TITLE
Need to skip listing tests from specific folder

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode-java-test#1163]
The issue described in #464 seems to be exactly what I am looking for.

I want the Test Explorer to list only unit tests (src/test/java) and exclude all my integration tests (src/integration-test/java).

Is there such setting?

Thanks!

**Comment by jdneo** [comment]
There is a workaround to achieve this.

Open the `.classpath` file, find the entry `src/integration-test/java` and then remove `<attribute name="test" value="true"/>`

**Comment by tigerinus** [comment]
> There is a workaround to achieve this.
> 
> Open the `.classpath` file, find the entry `src/integration-test/java` and then remove `<attribute name="test" value="true"/>`

I am afraid this workaround does not persist. For a complicated project, occasionally we need to delete .classpath file to resolve some weird class missing issue. It'd be nice to have something that persists.

**Comment by jdneo** [comment]
Close this and track the issue at #464 

Thanks for reporting this to us. Your voice will definitely help us prioritize the tasks.
