### ISSUE TITLE
'Cannot find implementation' for mapstruct mappers

### ISSUE THREAD

**Issue by pumano** [microsoft/vscode-java-test#1171]
I prepare repo: https://github.com/pumano/vscode-mapstruct-tests
just check via `gradle clean test` and then try to run via vscode.

You got `java.lang.ExceptionInInitializerError` which Caused by: `java.lang.ClassNotFoundException: Cannot find implementation for com.example.vscode.mapstructdemo.mappers.ExampleMapper`

looks like path to `generated` code not included to tests.

Also I link this issue with issue in redhat repo: https://github.com/redhat-developer/vscode-java/issues/1660

**Comment by jdneo** [comment]
The annotation processing for Gradle projects were not supported when this issue is created. And that's why tests are failed.

But now it's supported upstream: https://github.com/eclipse/eclipse.jdt.ls/pull/2319.
