### ISSUE TITLE
High memory usage due to wrong cleanup java test processes

### ISSUE THREAD

**Issue by pumano** [microsoft/vscode-java-test#1174]
After multiple running unit tests (junit 5 / gradle / spring boot tests or just classes) on macOS catalina I got multiple zombie java processes caused by VSCode and that processes eat all my memory and then going to my swap memory and eat 16gb hard drive memory. Till 100mb available memory on my hard drive. All of that instances is my application under test. Also closing vscode not killing that processes because that processes are detached from vscode main process.

screenshot contains only few for example but yesterday I kill around 50-60 zombie processes
<img width="973" alt="Screenshot 2021-04-14 at 13 59 14" src="https://user-images.githubusercontent.com/17675259/114700005-a9a03180-9d29-11eb-83ff-62756957ca09.png">

**OS:** macos catalina 10.15.7
**vscode:** 1.55.2 (latest)
**extensions:** vscode-java, vscode-java-test

**Comment by jdneo** [comment]
What kind of project/test are you running with? Would you mind to share a sample project for this issue.

I tried with some simple cases on my mac - running a test class several times and then use `jps` to list the java process, no other java process observed except for the process running Java Language Server.

**Comment by pumano** [comment]
@jdneo I will prepare suitable repo with project soon.

**Comment by jdneo** [comment]
Today I used [spring-petclinic](https://github.com/spring-projects/spring-petclinic) and trigger `PetclinicIntegrationTests` for several times, then use `jps` to check running Java process. Still there is only a process running Java Language Server

**Comment by jdneo** [comment]
@pumano  If you have any more information, feel free to comment here.
