### ISSUE TITLE
Have unit tests update coverage files afterwards.

### ISSUE THREAD

**Issue by eak006** [microsoft/vscode-java-test#1187]
Is it possible to run a JUnit test(s) through the vscode-java-test plugin and have the coverage XML files updated immediately afterwards?

I'm using the [Coverage Gutters plugin](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) by ryanluker to read my coverage files and light up my source code with green/red if, respectively, a unit test has/hasn't executed the source line.

In my `build.gradle` file, I have the [jacocoTestCoverageVerification task](https://docs.gradle.org/current/dsl/org.gradle.testing.jacoco.tasks.JacocoCoverageVerification.html) defined, as well as the [jacocoTestReport task](https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_getting_started) to generate the coverage html and xml files. Can't share since it's proprietary.

I have this in my local workspace's `settings.json`:
```json
"java.test.config": {
  "name": "myConfiguration",
  "workingDirectory": "${workspaceFolder}",
  "args": ["jacocoTestReport"],
},
"java.test.defaultConfig": "myConfiguration",
```

Any help provided is greatly appreciated!

**Comment by eak006** [comment]
Just for clarification, the Coverage Gutters plugin reads in the coverage XML files from a specific directory. I want to know if *this* plugin can implicitly update that directory after running a unit test via the sidebar or the `Run Test`/`Debug Test` options shown directly above a unit test method.

**Comment by jdneo** [comment]
Code coverage will be a important story we will visit in the near future. (By adopting the VS Code new Testing APIs: https://github.com/microsoft/vscode/issues/107467#issuecomment-822849983)

**Comment by jdneo** [comment]
See: https://github.com/microsoft/vscode-java-test/issues/387#issuecomment-1862260272
