### ISSUE TITLE
Debug code lens errors out with Java 17

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-java-test#1191]
The "Run" code lens seems to work, but the "Debug" one just gets me an error dialog and an offer to open `launch.json` (not helpful).

**Comment by testforstephen** [comment]
this seems duplicated with https://github.com/microsoft/vscode-java-test/issues/1189.

The "Debugger for Java" extension published a hotfix release 0.33.1 for it, did you try it?

**Comment by dsyer** [comment]
I did not. But I can only see 0.31.0 in VSCode extensions marketplace view. Do I need to update or configure something?

**Comment by testforstephen** [comment]
Oh, you're using an older VS Code version, the latest debugger requires a minimum VS Code 1.55.0.

**Comment by dsyer** [comment]
That works. Thanks.
