### ISSUE TITLE
Getting java.lang.UnsupportedClassVersionError in debug console when trying to run or debug any test

### ISSUE THREAD

**Issue by jheidlage1222** [microsoft/vscode-java-test#1194]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10 Pro
- JDK version: 11
- Visual Studio Code version: 1.56.0
- Java extension version: v0.14.0
- Java Debugger extension version: 0.33.1

##### Steps To Reproduce
1. Go to any test file 
2. Click debug test
3. Observe debug console open

##### Current Result
Debugging fails, error is shown
![image](https://user-images.githubusercontent.com/23411611/117350769-f1bef980-ae7a-11eb-871b-b99dc7c934cc.png)

##### Expected Result
Test debugging session is launched and breakpoints are hit.

**Comment by jdneo** [comment]
Would you mind to share a sample project for this issue?
