### ISSUE TITLE
Run-with-Configuration missing support for preLaunchTask

### ISSUE THREAD

**Issue by sfrank-mc** [microsoft/vscode-java-test#1201]
According to https://github.com/microsoft/vscode-java-test/wiki/Run-with-Configuration we're supposed to transition to use the new `java.test.config` which replaces the older `launch.test.json`.

The new configuration doesn't support everything that launch configs do.
For example we would like to have a `preLaunchTask` which doesn't seem to work or be supported.

It would be much more helpful to use the existing vscode configuration schema with all it's benefits.

**Comment by cameronbraid** [comment]
Are there plans to support `preLaunchTask` ?

**Comment by jdneo** [comment]
The next release will happen around the end of Nov.

**Comment by jdneo** [comment]
End game verification steps:

1. Add a task label in `preLaunchTask` field in `java.test.config`
2. Launch the task and see if the the task been executed.
