### ISSUE TITLE
Allow `envFile` alternative to `env` in `java.test.config`

### ISSUE THREAD

**Issue by nerdkid93** [microsoft/vscode-java-test#1214]
The VS Code `launch.json` file allows specifying `envFile` in addition to `env`. However, there does not appear to be a similar mechanism when running tests via this extension. It would be super handy to be able to have 1 file specify the `env` rather than duplicate it in both `.env` and `.vscode/settings.json`.

**Comment by jdneo** [comment]
The next release will happen around the end of Nov.

**Comment by jdneo** [comment]
End game verification steps:

1. Add an .env file in project
2. Add `envFile` in `java.test.config`
3. Write a test case to verify the .env file is picked:
``` java
assertEquals("value", System.getenv("key"));
```
