### ISSUE TITLE
Java Test Report has context menu with non-functional entries

### ISSUE THREAD

**Issue by leogott** [microsoft/vscode-java-test#1222]
The Java Test Report has a context menu with Cut, Copy, Paste Entries that aren't functional

**Expected Behavior**
The CutCopyPaste Entries should only appear on selected tests and not on the panel itself

![grafik](https://user-images.githubusercontent.com/61663141/123551964-5fe5b580-d774-11eb-9b79-1fcade714896.png)

**Comment by jdneo** [comment]
Thank you for reporting.

Just FYI, in the near future we will migrate to the VS Code's new test APIs which means the test report view will be deprecated.

See: https://github.com/microsoft/vscode-java-test/issues/1162

**Comment by jdneo** [comment]
0.31.0 is released which removes the test report.
