### ISSUE TITLE
Java Test Report gives no indication of a test being a Parameterized Test

### ISSUE THREAD

**Issue by leogott** [microsoft/vscode-java-test#1223]
Java Test currently does not display individual executions of parameterized tests or the number of executions.

#667 is related, but this Issue here can probably solved more quickly?

With a class like 

```java
public class SimpleTest {
    @ParameterizedTest
    @ValueSource(strings={"apple", "banana"})
    void (String value) {
        assertTrue(true);
    }
}
```
I'd expect an output like:

1 testAnotherThing
2 testAnotherThing

or

testAnotherThing (2/2)

and not 
![grafik](https://user-images.githubusercontent.com/61663141/123552712-9a9d1d00-d777-11eb-9172-c3074cb7752f.png)

vscode 1.57.1
java-test 0.30.0
java adapt-openjdk 8
junit jupiter 5.7.0 via maven
system windows with WSL

**Comment by jdneo** [comment]
dup with #954
