### ISSUE TITLE
"Go to Test" triggers test explorer changes in new Test APIs

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-test#1225]
I just tried #1162 , and there is a strange UI behavior. When I click `Go to Test` menu in the test explorer, the test explorer will change, the test node will disappear and appear again.
![gototest](https://user-images.githubusercontent.com/45906942/123576097-e0ec8d80-d804-11eb-8709-032552f1196c.gif)

**Comment by jdneo** [comment]
Fixed in https://github.com/jdneo/vscode-java-test/commit/b4e95958f70222fd02bdf3d8b28e93b13764766f.

Please find the latest bit in #1162.

Close it for now.
