### ISSUE TITLE
Editing causes test explorer changes in new Test API

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-test#1226]
When editing java file with the new Test API, the test nodes in the test explorer sometimes change. IMO if there is any error in the test file, the whole test node `PetTypeFormatterTests` can keep and the child node like `testPrint` can be dismissed. 
![editing](https://user-images.githubusercontent.com/45906942/123583218-cf5db280-d811-11eb-8f1c-44e3389a21ba.gif)

**Comment by jdneo** [comment]
The root cause is the same as #1225
