### ISSUE TITLE
Refine the order of the top buttons in Test Explorer

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-test#1228]
![image](https://user-images.githubusercontent.com/14052197/123603269-4b64f400-d82c-11eb-858c-06bfddf5d9be.png)

Suggest to place the collapse button at the last.

**Comment by jdneo** [comment]
In the latest insider, `collapse all` has been moved into the overflow button.

![image](https://user-images.githubusercontent.com/6193897/125916544-b4dc6a2f-6798-4152-9ec5-eaca5e237768.png)
