### ISSUE TITLE
The top Cancel button doesn't work well

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-test#1229]
![image](https://user-images.githubusercontent.com/14052197/123603743-c3cbb500-d82c-11eb-8cb1-3e657c5aef1b.png)

- Click “Debug All Tests” button first
- Then click "Cancel Test Run" button. The test is not cancelled, need click again.

**Comment by jdneo** [comment]
Fixed in https://github.com/jdneo/vscode-java-test/commit/8928b7de4f32613d6f106b8d76aea09420ff904c
