### ISSUE TITLE
Display multiple progresses reporter when trigger "Run Test" on a test class

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-test#1230]
- Open spring-petclinic project.
- Go to Test Explorer, find ClinicServiceTests and execute "Run Test". It pops up two progresses.
![image](https://user-images.githubusercontent.com/14052197/123605518-80724600-d82e-11eb-8636-15b0b4899e91.png)

**Comment by jdneo** [comment]
The following code can be used to repro this issue:

```
let progressReporter = progressProvider?.createProgressReporter('Foo');
progressReporter?.report('Bar...');
progressReporter?.done();

progressReporter = progressProvider?.createProgressReporter('Foo');
progressReporter?.report('Bar...');
progressReporter?.done();

progressReporter = progressProvider?.createProgressReporter('Foo');
progressReporter?.report('Bar...');
progressReporter?.done();
```

**Comment by jdneo** [comment]
Fixed in https://github.com/jdneo/vscode-java-test/commit/d8352a427c05f0cf6d070ea277f2e56746d9be1a
