### ISSUE TITLE
Try not to open a new debug console every time

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-test#1231]
Tried playing with the new Test API for a while, and found that there are lots of consoles opened in the DEBUG CONSOLE view. I prefer not to create new console, but reuse consoles whenever possible.
![image](https://user-images.githubusercontent.com/14052197/123610288-08f2e580-d833-11eb-8458-7c53996292b0.png)

**Comment by jdneo** [comment]
fixed in https://github.com/jdneo/vscode-java-test/commit/28e00d9dfd7d1eb6a2a479d9042d0223a98a6a3f
