### ISSUE TITLE
improve the awareness of passing tests from Java Project Manager

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-test#1236]
When running or debugging a test from Java Project Manager, if there is no error exists the user should have a proper way to aware of the result. (by status bar, decorating item, etc.)

**Comment by jdneo** [comment]
See: https://github.com/microsoft/vscode/issues/153068

**Comment by jdneo** [comment]
This can be improved if we leverage the test result view by #1588
