### ISSUE TITLE
show test status on test explorer nodes

### ISSUE THREAD

**Issue by ansyral** [microsoft/vscode-java-test#126]
Currently we don't show test status on nodes of test explorer, so when user choose to run all tests from test explorer, if some tests failed, they can open test report to check the failed tests but it is hard for them to locate the file that contains the failed tests.

**Comment by thoni56** [comment]
This could be done by providing an adapter for the [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer).
