### ISSUE TITLE
Error message is not clear when run TestNG project

### ISSUE THREAD

**Issue by chenyuanmac** [microsoft/vscode-java-test#1260]
**Environment:**

OS: Linux
JDK: 11
Java Test Runner Extension: 0.31.0

**Repro steps:**

1. Download project:[http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip](http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip)
2. Open TestNG-Spring-Example project with VSCode
3. Click Run All Tests

**Result:**
Test cases cannot run
![image](https://user-images.githubusercontent.com/70991161/128156532-d71d4bff-e163-416a-b039-0b04b519b7f9.png)
Some error message show in test output.
![image](https://user-images.githubusercontent.com/70991161/128157058-765dc9d4-143e-4b60-9927-8e7c8eae1cd7.png)

**Comment by jdneo** [comment]
To verify this issue:

1. Open a TestNG project, i.e. http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip
2. `Run All` tests
3. Check if the failure root cause is printed into the debug console

**Comment by Eskibear** [comment]
verified that exceptions and callstack printed in debug console
