### ISSUE TITLE
Put the test message location to where it happens

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1266]
More specifically, if an assert fails, have the TestMessage's location of the assert match the location in the method for the given assert. Similarly if something triggers an exception, we could have a TestMessage for the exception in potentially even a different file - such as extract from the exception stack the location in testMethod() that resulted in the failure.

_Originally posted by @TimWebb in https://github.com/microsoft/vscode-java-test/issues/1162#issuecomment-893464998_

**Comment by TimWebb** [comment]
@jdneo Your last two points make good sense, focusing on the assertion stack placement in the data model.

**Comment by jdneo** [comment]
Verification steps:

1. Run a test case that will fail.
2. Check the test message displayed at where the error happens instead of the method declaration.
