### ISSUE TITLE
Performance regression for vscode.java.test.junit.argument between 0.30 and 0.31

### ISSUE THREAD

**Issue by mfussenegger** [microsoft/vscode-java-test#1273]
Running the `vscode.java.test.junit.argument` command takes around ~50seconds on my machine with vscode-java-test 0.31.
In 0.30 it only took a couple of milliseconds.

I suspect it depends on the project size. So a project to test would be [crate/crate](https://github.com/crate/crate). Within the `PlannerTest`. Full payload:

```
 {
  projectName = "server",
  testKind = 1,
  testLevel = 6,
  testNames = { "=server/src\\/test\\/java=/gradle_scope=/test=/=/gradle_used_by_scope=/test=/=/test=/true=/<io.crate.planner{PlannerTest.java[PlannerTest~testSetPlan" }
}
```

Based on a quick flamegraph, it looks as if it is re-parsing / re-analysing the project?

![image](https://user-images.githubusercontent.com/38700/128066929-82090505-03fa-4ca1-8337-589ecec73119.png)

This is how it looked before:

![image](https://user-images.githubusercontent.com/38700/128067320-a942ba9a-3166-4f18-abe3-1ad04021f20d.png)

**Comment by jdneo** [comment]
Thank you for reporting, I'll take a look sometime today.

**Comment by jdneo** [comment]
@mfussenegger, could you try this bit and let me know if the perf issue get resolved?

[vscode-java-test-0.31.1.vsix.zip](https://github.com/microsoft/vscode-java-test/files/6959022/vscode-java-test-0.31.1.vsix.zip)

And feel free to let me know if there is any other issues, thanks!

**Comment by mfussenegger** [comment]
> could you try this bit and let me know if the perf issue get resolved?

 yes it seems to fix the performance regression.

**Comment by mfussenegger** [comment]
Thanks for fixing this so quickly :+1:

**Comment by stefanrybacki** [comment]
Not sure this is related but I am stuck on "Run Tests: Resolving launch configuration...", After starting a JUnit test a couple of times, where the time this window is shown becomes longer and loger each time a start it until I wait forever. This worked on the old test runner (the one using the HTML report)

![image](https://user-images.githubusercontent.com/29799350/129171498-7a32ed4f-89f9-4d92-9d26-1ef95c900ac1.png)

**Comment by jdneo** [comment]
@stefanrybacki I guess so. Planning to make a hotfix release if more people are suffering from this.

**Comment by stefanrybacki** [comment]
@jdneo Yes I had to revert back to 0.30.1 as this is not usable as it is for me (though I like the new integration with the testing view etc.)

**Comment by stefanrybacki** [comment]
@jdneo can you reopen this issue?

**Comment by jdneo** [comment]
The issue has been fixed and I plan to make a hotfix release early next week. So I'm not gonna to reopen this one.

**Comment by jdneo** [comment]
@stefanrybacki 0.31.2 released

**Comment by mucham1992** [comment]
Hi 

this issue ![](https://user-images.githubusercontent.com/29799350/129171498-7a32ed4f-89f9-4d92-9d26-1ef95c900ac1.png)
is sill visible with 0.31.2 for TestNG project  with error:
PM Problems occurred when invoking code from plug-in: \"org.eclipse.jdt.ls.core\". null java.lang.NullPointerException at on the version 0.31.1. this problem didn't occurs

**Comment by jdneo** [comment]
@mucham1992 Please create a new issue with repro steps, thanks!

**Comment by mucham1992** [comment]
@jdneo 

Yes exactly my project is TestNg type and when i use previous version i don;t have this problem.

**Comment by jdneo** [comment]
@mucham1992 Thank you for reporting, tracking by https://github.com/microsoft/vscode-java-test/issues/1284

**Comment by stefanrybacki** [comment]
> @stefanrybacki 0.31.2 released

Thank you, works for me now
