### ISSUE TITLE
[Request] Offer an easy way to view the Message on failed tests from the Testing Pane

### ISSUE THREAD

**Issue by leogott** [microsoft/vscode-java-test#1280]
Currently when investigating the cause of a failing test, I have to switch back and forward between the Test Code and the Code Tested, because the Testing Pane only offers the per-test buttons to jump to the Test Code, or the one to jump to the bottom of the (plaintext and uncolored) Test Output.

If a tooltip in the test-pane displayed the error message on each failed test, that would help me a lot. And/or if a right-click option allowed me to jump to the start of the Test Output for the most recent execution of this test.

**Comment by jdneo** [comment]
The VS Code provides a item called `Peek error` in the context menu of the test decoration. But it's not available in the test explorer.

If it's also available in the text explorer, does that meet your requirement?

**Comment by leogott** [comment]
I think so? Specifically I'm looking for a way to view the test result without moving my editor-tab to the background.

My "Peek-Error" Code-Lens typically looks something like this:
![grafik](https://user-images.githubusercontent.com/61663141/130302401-6c2f7e29-fb73-45d7-8d9a-df813d041320.png)
which contains a lot of useful information, in a slightly unwieldy format.

When I hover over the failed assertion I get this tooltip
![grafik](https://user-images.githubusercontent.com/61663141/130303047-af9830e9-cb65-42ea-9347-6b2abaa4f23a.png)
which is pretty much what I'd like to have on hovering over the failed test in the sidebar.

**Comment by jdneo** [comment]
Ok I got your point, you would like to have a tooltip shows the text which is same as hovering over, right?

**Comment by jdneo** [comment]
Ok I got your point, you would like to have a tooltip shows the text which is same as hovering over, right?

**Comment by leogott** [comment]
> 
> 
> Ok I got your point, you would like to have a tooltip shows the text which is same as hovering over, right?

Yes, I would consider it a big improvement, if the failed test in the sidebar showed the same tooltip as the assertion that failed.

**Comment by jdneo** [comment]
This could be a UX change request to the VS Code. It's out of control from the extension side given the current API capability. I suggest that you can file an issue VS Code repo.

**Comment by jdneo** [comment]
Filed an issue upstream: https://github.com/microsoft/vscode/issues/153789.

**Comment by jdneo** [comment]
See: https://github.com/microsoft/vscode/issues/153789#issuecomment-1839320207
