### ISSUE TITLE
Cannot run TestNG tests from method level in 0.31.2

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1284]
Hi 

this issue is sill visible with 0.31.2 for TestNG project  with error:
PM Problems occurred when invoking code from plug-in: \"org.eclipse.jdt.ls.core\". null java.lang.NullPointerException at on the version 0.31.1. this problem didn't occurs

 ![](https://user-images.githubusercontent.com/29799350/129171498-7a32ed4f-89f9-4d92-9d26-1ef95c900ac1.png)

_Originally posted by @mucham1992 in https://github.com/microsoft/vscode-java-test/issues/1273#issuecomment-900132965_

**Comment by CarlPer** [comment]
I cannot run my tests at all, not sure if it is related.

![NPE](https://user-images.githubusercontent.com/36195670/129739602-705b9e57-da18-489e-aeab-1ff805a77bb1.PNG)

**Comment by jdneo** [comment]
@CarlPer Only for the method level as well?

**Comment by CarlPer** [comment]
@jdneo Yes it is only for method level

**Comment by jdneo** [comment]
Fixed and should be released in next version. Thanks
