### ISSUE TITLE
Individual Tests Hang on Run Test: Resolving launch configuration...

### ISSUE THREAD

**Issue by mrasmussen** [microsoft/vscode-java-test#1288]
**Environment:**

OS: Mac Big Sur
JDK: 11
JDK Project: 1.8
Java Test Runner Extension: 0.31.2

**Repro steps:**

- Run all tests in a class by clicking "Run Test" next to the class name in Test Explorer 
- All tests run and pass
- Click "Run Test" on any individual test within Test Explorer
- Message box in bottom right corner displays "Run Tests: Resolving launch configuration..." and test never runs

<img width="1306" alt="Run Test" src="https://user-images.githubusercontent.com/688757/130158934-e6eb251f-7b08-4118-bb2a-19c49f262781.png">

**Comment by jdneo** [comment]
I guess it's TestNG project right?

duplicated with #1284. If that's not the case please reopen this issue and let me know, thanks!

**Comment by mrasmussen** [comment]
Yes, thank you.  I searched for this problem in your issues tracker.  I guess I didn't use the correct keywords. :)
