### ISSUE TITLE
Cannot Run Single Test with TestNG v7.4.0

### ISSUE THREAD

**Issue by ferdyciputra** [microsoft/vscode-java-test#1293]
When I Click "Run Test" for single Test with TestNG v7.4.0, The Test not working well.

![image](https://user-images.githubusercontent.com/28496366/130387623-aa4d6ecf-d653-474f-a4c7-b705e39b58c7.png)

**Comment by jdneo** [comment]
Duplicated with #1284 

We'll release a fix this week.
