### ISSUE TITLE
Keep showing Run Tests: Resolving launch configuration... but nothing happens when using TestNG

### ISSUE THREAD

**Issue by molly-w** [microsoft/vscode-java-test#1294]
1. Download [TestNG-7.4.0.jar](https://mvnrepository.com/artifact/org.testng/testng/7.4.0) then add it to referenced libraries
2. Run simple test code from [TestNG docs](https://testng.org/doc/)
```
import org.testng.annotations.*;

public class TestNgTwoTests {

    @BeforeClass
    public void setUp() {
        // code that will be invoked when this test is instantiated
    }

    @Test(groups = { "fast" })
    public void aFastTest() {
        System.out.println("Fast test");
    }

    @Test(groups = { "slow" })
    public void aSlowTest() {
        System.out.println("Slow test");
    }
}
```
Clicking the triangle button to run test and notification pops up `Run Tests: Resolving launch configuration... `, it keeps resolving and nothing happens: 
![image](https://user-images.githubusercontent.com/63043224/130418729-9d6115ed-acb4-45f9-85ec-22dedc49a19d.png)

**Comment by jdneo** [comment]
Duplicated with #1284. We will release a fix soon
