### ISSUE TITLE
New test runner reports are really weird for parameterized tests

### ISSUE THREAD

**Issue by Artur-** [microsoft/vscode-java-test#1296]
Consider for instance this test where `method` is run twice and will once pass and once fail. 
```
@RunWith(Parameterized.class)
public class MyTest {

    @Parameters
    public static Integer[] data() {
        return new Integer[] { 1, 2 };
    }

    private Integer id;

    public MyTest(Integer id) {
        this.id = id;
    }

    @Test
    public void method() {
        Assert.assertEquals(Integer.valueOf(1), id);
    }
}
```

Running in VS Code gives me
![Screenshot 2021-08-27 at 15 53 26](https://user-images.githubusercontent.com/260340/131130247-e9dd3442-ac0a-40f9-9ad8-100dcbcd381f.png)

Changing the method to assert the value is 2 gives
![Screenshot 2021-08-27 at 15 53 52](https://user-images.githubusercontent.com/260340/131130296-5bc8cd2a-f4da-4ff3-b82e-c91ca8cad8d3.png)

At this point I no longer have any idea of what is going on. The is no indication anywhere about two tests being run as far as I can see.

If I add
```
    @Rule
    public TestName testName = new TestName();
```

and

```
        System.out.println("Name: " + testName.getMethodName());
```

I can see that the tests are actually named
```
Name: method[0]
Name: method[1]
```

but the popup only shows `method`

**Comment by jdneo** [comment]
Took a look at the code, it seems that the code here needs to be fixed: https://github.com/microsoft/vscode-java-test/blob/1bc3c5b9a478aff0c069160d71c1703f6e68a267/src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts#L198-L201

**Comment by jdneo** [comment]
To verify this issue (only used for tester):

1. Open the test project https://github.com/microsoft/vscode-java-test/tree/main/test/test-projects/junit
2. Run https://github.com/microsoft/vscode-java-test/blob/main/test/test-projects/junit/src/test/java/junit4/ParameterizedTest.java, or https://github.com/microsoft/vscode-java-test/blob/main/test/test-projects/junit/src/test/java/junit4/ParameterizedWithNameTest.java
3. Check if the test result can be show separately according to different parameters.

**Comment by Eskibear** [comment]
verified

**Comment by Artur-** [comment]
Does this also solve #1304 or is it a different problem?

**Comment by jdneo** [comment]
It's a different problem.
