### ISSUE TITLE
'findTestLocation' is not registered as a bundle command

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1300]

**Comment by jdneo** [comment]
To verify this issue:

1. Open the test project https://github.com/microsoft/vscode-java-test/tree/main/test/test-projects/junit
2. Run https://github.com/microsoft/vscode-java-test/blob/main/test/test-projects/junit/src/test/java/junit4/ParameterizedTest.java
3. See if the error message can show in the editor area

**Comment by Eskibear** [comment]
verified
