### ISSUE TITLE
Renaming the JUnit test causing the test status could not display correctly

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1304]
Thanks, you have re-introduced this in the new test runner.

https://user-images.githubusercontent.com/260340/133435225-1536632f-cd83-47cd-9c9e-9ebe5ac3ddc2.mov

_Originally posted by @Artur- in https://github.com/microsoft/vscode-java-test/issues/1013#issuecomment-919984226_

**Comment by Artur-** [comment]
Tested that this is still a problem with 0.32.0

**Comment by jdneo** [comment]
@Artur- Just tried with 0.35.2, now the status should be set correctly

https://user-images.githubusercontent.com/6193897/179654872-06c353cd-5d22-43ff-9f56-9393392d6c25.mp4

If you have more concerns/questions, please let me know.
