### ISSUE TITLE
Code lenses for tests not showing

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-java-test#1310]
I have seen similar issues (#470, #576, #797) but none of the resolutions seems to apply. The test view is there and it works, but the code lenses just aren't working. They are working for main methods (to run the app) but not for tests. There are no errors in the language server logs. There are errors in the developer tools console, but none of them looks helpful (e.g. timeouts and resource not found type errors, but async so no details).

**Comment by jdneo** [comment]
What's the version of your test runner? We recently adopted to the new testing APIs from VS Code, now to run a test, you can use the testing decoration at the left side of the editor:

![image](https://user-images.githubusercontent.com/6193897/134475367-0893a94f-72dd-438a-8c59-0a4e6dcd5fd1.png)

**Comment by dsyer** [comment]
Ah. So no code lenses any more. I have those margin markers now when I upgrade everything (extension is now v0.32.0). Amazing,
