### ISSUE TITLE
The property file in src/test/resources is not recognized and the test fails.

### ISSUE THREAD

**Issue by tsukasa89** [microsoft/vscode-java-test#1311]
## Environment:
- OS: Windows10
- VS Code: v1.60.2
- JDK: v11
- Java Test Runner Extension: v0.32.0

## Repro steps:
1. git clone : https://github.com/tsukasa89/test-runner-example
2. Open test-runner-example with VSCode

### VSCode Test run:
Click "Run All Tests"

Result:

The test "test resource properties value" failed.

### Gradle Test run:
```
.\gradlew clean test
```
Result:

All tests succeed.

**Comment by jdneo** [comment]
Took a quick look and found that in the resolved classpath, main folder comes previous of the test folder.

Needs to take a deep look to see what's happening.

**Comment by jdneo** [comment]
Root cause is that the upstream does not specially put the test output location before the main output location.

Same bug can be seen in Eclipse as well.

**Comment by tsukasa89** [comment]
I know about the eclipse issue.
However, in eclipse, JUnit succeeds by prioritizing src/test in the Java Build Path.
Is it possible to prioritize src/test when running the Java Test Runner in VS Code?

![image](https://user-images.githubusercontent.com/18757739/135599265-02176992-1eab-460e-8d9e-70c8594c4c64.png)

**Comment by jdneo** [comment]
Currently the order of the build path is not configurable in VS Code. But that's a good point how we can solve such kind of issues.

**Comment by tsukasa89** [comment]
Thank you. I hope this problem will be solved.

**Comment by FieteO** [comment]
> Root cause is that the upstream does not specially put the test output location before the main output location.
> 
> Same bug can be seen in Eclipse as well.
May I ask who the upstream is in this case? Is there already a ticket addressing this issue?

**Comment by jdneo** [comment]
@FieteO Since this is a Gradle project, so Buildship is used to resolve the classpaths
