### ISSUE TITLE
how does vscode-java-test find unit tests?

### ISSUE THREAD

**Issue by gsiawGH** [microsoft/vscode-java-test#1334]
Hello, 
im using vscode-java-test, and it automatically loads most of my Junit tests fine in the explorer, but i have two paths for all my tests, `<project>/src/test and <project>/src/integration`
and vscode-java-test only seem to load the tests in `<project>/src/test`.

 is there some setting that i can tweek to load the other path as well?

**Comment by jdneo** [comment]
Thanks for reporting. This is duplicated with https://github.com/microsoft/vscode-java-test/issues/464.
