### ISSUE TITLE
Could not run the tests through code lens if the method has parameters

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#134]
1. Clone Junit projects from https://github.com/junit-team/junit5-samples
2. Open the junit5 project, e.g. junit5-maven-consumer
3. Trigger test from FirstTest class level: test passed
4. Trigger test from FirstTest method level: test skipped

![image](https://user-images.githubusercontent.com/22470312/37075787-6c68ad22-220e-11e8-82bb-535dae150c1d.png)

LOG:
![image](https://user-images.githubusercontent.com/22470312/37075839-b24dec80-220e-11e8-9414-6fd18959f447.png)

**Comment by ansyral** [comment]
The test has a parameter with `TestInfo` injected, that is why runner failed to parse test name
