### ISSUE TITLE
Explore better Junit testing experience (brainstorm)

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-test#1344]
Theme: Testing

**Comment by jdneo** [comment]
When the workspace contains only an unmanaged folder project and no test framework is found on the project's classpath, then the user will see this button in the `Testing` explorer to enabling Java tests.

https://user-images.githubusercontent.com/6193897/150263963-131f2128-5de1-4cf8-92a3-288985741d82.mp4

**Comment by nickzhums** [comment]
Thanks! Another thought from me is to generate an empty test class for them, which will complete the e2e journey.
But Let's wait for some user feedback first

**Comment by jdneo** [comment]
@nickzhums Good idea! We can explorer further for sure.
