### ISSUE TITLE
[BUG] Java Test Runner Refresh Tests fails with error message "command 'python.refreshTests' not found"

### ISSUE THREAD

**Issue by deekshithanand** [microsoft/vscode-java-test#1348]
Environment:
OS: Mac
VS Code: 1.63.2
JDK: v11.0.12
Java Test Runner Extension: v0.33.0
Repro steps:
Open test runner.
Click on refresh test icon/Refresh from the 3 dot menu.

Result:
Tests are not refreshed and the following error is shown.
`command 'python.refreshTests' not found
`
Expected Result:
Test cases shoul be refreshed.

Additional comments:
I have disabled python extensions in my hava workspace. I have multiple java folders(projects) added to this workspace. I dont get why python.refreshTests shows up in a Java environment. 

Thanks!

**Comment by jdneo** [comment]
I'm confused here, the command `python.refreshTests` is not registered by this extension.

Could you provide detailed steps how I can repro this? Thanks.

**Comment by PterX** [comment]
same issue,when click here got this error
![image](https://user-images.githubusercontent.com/1871048/147346058-ffea7031-640d-4707-8276-0dfe5e849f61.png)

click ... and Refresh is ok

**Comment by jdneo** [comment]
Ok, I guess I know what's happening here.

Is it correct that you installed both `Java` and `Python` extension?

If that is true, the one in the navigation bar is contributed by `Python` extension. While the `Refresh` in `...` is contributed by `Java` extension. If in your workspace, the python extension is not activated, click the `refresh` in navigation bar will cause this error.

**Comment by jdneo** [comment]
See https://github.com/microsoft/vscode/issues/139737

**Comment by deekshithanand** [comment]
Sorry for the delayed response. Yes, I have both Java and python extensions installed. But I had python  disabled on the workspace. (Adding this if it helps) In my case, both the refresh Icon on GUI and refresh option from the list gave this error.
