### ISSUE TITLE
[Feature Request] TestNG XML Suite Support

### ISSUE THREAD

**Issue by yunusemreayhan** [microsoft/vscode-java-test#1356]
Normally testng allow us to create custom test combinations with [xml files](https://testng.org/doc/documentation-main.html#testng-xml). But it is not allowed to run in vscode I guess. Can we add this feature?

**Comment by jdneo** [comment]
Thank you for the feedback. it's duplicated with https://github.com/microsoft/vscode-java-test/issues/596
