### ISSUE TITLE
target.target contains out of date dependencies?

### ISSUE THREAD

**Issue by karlvr** [microsoft/vscode-java-test#1360]
I have been unable to develop this project in VS Code as the JDT dependencies could not be resolved. I have followed the steps in the CONTRIBUTING guide to no avail. I believe this is the same issue I encountered that was resolved in the `vscode-checkstyle` plugin https://github.com/jdneo/vscode-checkstyle/issues/287#issuecomment-758370217

I'm not sure what I'm doing in `target.target` files, but copying the file from your `vscode-checkstyle` plugin to this plugin appears to resolve the issue with resolving the JDT dependencies. If I was confident that was the correct solution I'd propose a PR, but I imagine the actual solution in `target.target` may be slightly more nuanced.

The [CONTRIBUTING guide in `vscode-checkstyle`](https://github.com/jdneo/vscode-checkstyle/blob/master/CONTRIBUTING.md) includes an instruction to try "Reload Target Platform" which is missing from the CONTRIBUTING guide in this project. Perhaps that would be a useful addition?

**Comment by jdneo** [comment]
It turns out that the some of the module's target definition has been changed. I'll raise a PR to fix this. Thanks for reporting.

**Comment by jdneo** [comment]
Should be working now.
