### ISSUE TITLE
Test Explorer doesn't recognize test classes with '$' in their names

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-test#1364]
![test classes](https://user-images.githubusercontent.com/14052197/150740120-2f92aff5-13c8-4991-8860-be963561f52c.png)

**Comment by jdneo** [comment]
The code here returns `null` when the type contains `$`:

https://github.com/microsoft/vscode-java-test/blob/41e71f6b10ede42198c4fbb411bbb084e1f672bb/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java#L274
