### ISSUE TITLE
[BUG] The Testing Explorer may not work quickly for the No Build tools project for 1st time

### ISSUE THREAD

**Issue by silenceJialuo** [microsoft/vscode-java-test#1373]
#  The Testing Explorer may not work quickly for the No Build tools project for 1st time

When user creates the test class with source action 'Generating Tests' for the JAVA projects of no build tools after Enabling Tests,
the Testing Explorer may not work in time to create the hierarchy level quickly, it may puzzle our users.

![image](https://user-images.githubusercontent.com/99467262/153554310-a481f3d9-e026-45ec-b367-0465fbfa713c.png)

![image](https://user-images.githubusercontent.com/99467262/153554749-3131e21b-2635-4290-9bb4-cadfca5b1a6c.png)

Expected Result:
The Testing Explorer could update timely with users' behavior to show the hierarchy of Testing classes

**Comment by jdneo** [comment]
Could not find a stable reproduce steps. Reload window could solve the problem when it happens

**Comment by jdneo** [comment]
Tried several times but could not repro with the newest VS Code (1.66.1).

I'll close this for now but feel free to leave comments if it appears again.
