### ISSUE TITLE
Test runner showing "Configure Python Tests" instead of Java

### ISSUE THREAD

**Issue by officialbishowb** [microsoft/vscode-java-test#1390]
I installed the "Test Runner Java" but it is showing "Configure Python Tests" which is very suprising. Any fix?
![grafik](https://user-images.githubusercontent.com/55999477/159901951-db8b4826-70f9-4c85-9487-96f317b2519f.png)

**Comment by jdneo** [comment]
The button you seen is contributed by Python extension not Java.

To see Java tests, please make sure you have imported Java projects into VS Code. (Directly open the folder where your project pom.xml/build.gradle locates)

**Comment by officialbishowb** [comment]
@jdneo I am working with plain Java project not Maven & co. So there is no pom.xml.. How can i do it in plain Java project?

**Comment by jdneo** [comment]
Could you see a thumb up icon at the bottom right status bar?

**Comment by officialbishowb** [comment]
@jdneo No the thumb icon is down
![grafik](https://user-images.githubusercontent.com/55999477/160107057-f85c0e46-8c9a-4d62-b8b2-11f104b0ce04.png)

**Comment by jdneo** [comment]
Then that means the project is not imported successfully. Check this and see if there is any errors: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs

**Comment by officialbishowb** [comment]
@jdneo Sorry for late reply but after I manually download junit-platform-console-standalone where I am not sure if it is correct, from [here ](https://search.maven.org/artifact/org.junit.platform/junit-platform-console-standalone/1.8.2/jar) it is working
![grafik](https://user-images.githubusercontent.com/55999477/160288586-33868f8a-e421-4e96-8e57-6736a625cf83.png)

**Comment by jdneo** [comment]
junit-platform-console-standalone is the required jar to run JUnit 5's tests.

I'm closing this issue for now since it seems that the problem has been solved. Free feel to leave comments if you have any questions.

**Comment by luhenr** [comment]
> 

got it, many thanks! :)

**Comment by john-aws** [comment]
Note: it seems to be important that the Java source files are located under `src/package...` otherwise VS Code and the Testing extension don't consider this to be a Java project and continue to offer the 'Configure Python Tests' option only.
