### ISSUE TITLE
Test Report page not showing for testng report

### ISSUE THREAD

**Issue by sathiyabaskar** [microsoft/vscode-java-test#1395]
Test Report page not showing for testng report

**Comment by jdneo** [comment]
Could you provide more details and repro steps?

**Comment by sathiyabaskar** [comment]
![Screenshot from 2022-04-06 10-27-46](https://user-images.githubusercontent.com/62695438/161899392-ba9d9c29-b22b-42d2-9204-6a7b56134ffd.png)


i want like this...  above pic

but  i got like this...  how to view the passed failed cases as above pic

https://user-images.githubusercontent.com/62695438/161899492-ba101795-b7ae-40cc-9e9d-1cbe0f5aac45.mp4

**Comment by sathiyabaskar** [comment]
i'm new to java-projects in vs-code..   do i need any extensions for that..

**Comment by jdneo** [comment]
The first picture you referenced is an out-of-date screenshot. The UX has been changed a lot from that.

Take a look at this: https://code.visualstudio.com/docs/java/java-testing#_features

**Comment by jdneo** [comment]
Closing this issue for now. But feel free to leave comments if you have any questions.

**Comment by sathiyabaskar** [comment]
i mean..   can i view the test params from data-provider  in
test-reports...     testng report from eclipse was attached...

sorry my english is not good..

**Comment by jdneo** [comment]
The test report page has been removed. Are you using an old extension?

**Comment by sathiyabaskar** [comment]
Yes, it is.

**Comment by jdneo** [comment]
I remember that test params was not supported.
