### ISSUE TITLE
[Question] Relationship with debug protocol or other protocol?

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/vscode-java-test#14]
Are the test messages (commands, results) conform to any existing protocol that could be reused in other tools? Is this an extension of the debug-server protocol with additional message to report test progress and results?

**Comment by ansyral** [comment]
@mickaelistria we don't extend the debug protocol. The extension works with [java debugger](https://github.com/Microsoft/vscode-java-debug) to debug the tests.

**Comment by mickaelistria** [comment]
Ok, thanks.
The question was more how does the test runtime (application under test) notifies the IDE (VSCode) about test results? Do you use plain JUnit notifications/reports between the test runtime and VSCode, or is there something mre generic in between?

**Comment by ansyral** [comment]
@mickaelistria we customized `org.junit.runner.JUnitCore` and `org.junit.runner.notification.RunListener` to get test results. Right now it is not that generic, but later as we plan to support more test framework such as JUnit5, TestNG, we might consider to make it more generic.

**Comment by mickaelistria** [comment]
Ok. I have the impression that those test result notification (mimicking JUnit notifications) could be directly included in the debug protocol, so they would get somehow generic and could support any languages/test framework/IDE.
