### ISSUE TITLE
Support JUnit Nested tests 

### ISSUE THREAD

**Issue by LuoDL** [Microsoft/vscode-java-test#140]
Here is the screenshot.

<img width="1206" alt="2018-03-19 21 32 34" src="https://user-images.githubusercontent.com/6195232/37598400-13fec1ae-2bbd-11e8-9ba6-85f577316971.png">

The information in the "Test Output" window is:

> @@<{"name":"testReporterAttached"}>
@@<{"name":"rootName", "attributes":{"name":"Default Suite"}}>
@@<{"name":"suiteTreeStarted", "attributes":{"name":"tetris.Step1_FallingBlocksTest", "location":"java:test://tetris.Step1_FallingBlocksTest"}}>
@@<{"name":"suiteTreeStarted", "attributes":{"name":"tetris.Step1_FallingBlocksTest$A_new_board", "location":"java:test://tetris.Step1_FallingBlocksTest$A_new_board"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"is_empty", "location":"java:test://tetris.Step1_FallingBlocksTest$A_new_board.is_empty"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"has_no_falling_blocks", "location":"java:test://tetris.Step1_FallingBlocksTest$A_new_board.has_no_falling_blocks"}}>
@@<{"name":"suiteTreeEnded", "attributes":{"name":"tetris.Step1_FallingBlocksTest$A_new_board", "location":"java:test://tetris.Step1_FallingBlocksTest$A_new_board"}}>
@@<{"name":"suiteTreeStarted", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_is_dropped", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"at_most_one_block_may_be_falling_at_a_time", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.at_most_one_block_may_be_falling_at_a_time"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"the_block_is_falling", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.the_block_is_falling"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"it_moves_down_one_row_per_tick", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.it_moves_down_one_row_per_tick"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"it_starts_from_the_top_middle", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.it_starts_from_the_top_middle"}}>
@@<{"name":"suiteTreeEnded", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_is_dropped", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped"}}>
@@<{"name":"suiteTreeStarted", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"it_stops_when_it_hits_the_bottom", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom.it_stops_when_it_hits_the_bottom"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"it_is_still_falling_on_the_last_row", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom.it_is_still_falling_on_the_last_row"}}>
@@<{"name":"suiteTreeEnded", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom"}}>
@@<{"name":"suiteTreeEnded", "attributes":{"name":"tetris.Step1_FallingBlocksTest", "location":"java:test://tetris.Step1_FallingBlocksTest"}}>
@@<{"name":"testSuiteStarted", "attributes":{"name":"tetris.Step1_FallingBlocksTest$A_new_board", "location":"java:test://tetris.Step1_FallingBlocksTest$A_new_board"}}>
@@<{"name":"testStarted", "attributes":{"name":"is_empty", "location":"java:test://tetris.Step1_FallingBlocksTest$A_new_board.is_empty"}}>
@@<{"name":"testFinished", "attributes":{"name":"is_empty", "duration":"3"}}>
@@<{"name":"testStarted", "attributes":{"name":"has_no_falling_blocks", "location":"java:test://tetris.Step1_FallingBlocksTest$A_new_board.has_no_falling_blocks"}}>
@@<{"name":"testFinished", "attributes":{"name":"has_no_falling_blocks", "duration":"0"}}>
@@<{"name":"testSuiteFinished", "attributes":{"name":"tetris.Step1_FallingBlocksTest$A_new_board"}}>
@@<{"name":"testSuiteStarted", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_is_dropped", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped"}}>
@@<{"name":"testStarted", "attributes":{"name":"at_most_one_block_may_be_falling_at_a_time", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.at_most_one_block_may_be_falling_at_a_time"}}>
@@<{"name":"testFinished", "attributes":{"name":"at_most_one_block_may_be_falling_at_a_time", "duration":"11"}}>
@@<{"name":"testStarted", "attributes":{"name":"the_block_is_falling", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.the_block_is_falling"}}>
@@<{"name":"testFinished", "attributes":{"name":"the_block_is_falling", "duration":"2"}}>
@@<{"name":"testStarted", "attributes":{"name":"it_moves_down_one_row_per_tick", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.it_moves_down_one_row_per_tick"}}>
@@<{"name":"testFinished", "attributes":{"name":"it_moves_down_one_row_per_tick", "duration":"4"}}>
@@<{"name":"testStarted", "attributes":{"name":"it_starts_from_the_top_middle", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_is_dropped.it_starts_from_the_top_middle"}}>
@@<{"name":"testFinished", "attributes":{"name":"it_starts_from_the_top_middle", "duration":"1"}}>
@@<{"name":"testSuiteFinished", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_is_dropped"}}>
@@<{"name":"testSuiteStarted", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom"}}>
@@<{"name":"testStarted", "attributes":{"name":"it_stops_when_it_hits_the_bottom", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom.it_stops_when_it_hits_the_bottom"}}>
@@<{"name":"testFailed", "attributes":{"name":"it_stops_when_it_hits_the_bottom", "message":"expected:<...\n...\n.[X].\n> but was:<...\n...\n.[.].\n>", "details":"org.junit.ComparisonFailure: expected:<...\n...\n.[X].\n> but was:<...\n...\n.[.].\n>\n\tat org.junit.Assert.assertEquals(Assert.java:115)\n\tat org.junit.Assert.assertEquals(Assert.java:144)\n\tat tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom.it_stops_when_it_hits_the_bottom(Step1_FallingBlocksTest.java:103)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat net.orfjackal.nestedjunit.NestedJUnit$1.evaluate(NestedJUnit.java:73)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat com.microsoft.java.test.runner.JUnit4TestReference.run(JUnit4TestReference.java:51)\n\tat com.microsoft.java.test.runner.CustomizedJUnitCoreRunner.run(CustomizedJUnitCoreRunner.java:46)\n\tat com.microsoft.java.test.runner.JUnitLauncher.main(JUnitLauncher.java:21)\n", "duration":"3"}}>
@@<{"name":"testFinished", "attributes":{"name":"it_stops_when_it_hits_the_bottom", "duration":"5"}}>
@@<{"name":"testStarted", "attributes":{"name":"it_is_still_falling_on_the_last_row", "location":"java:test://tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom.it_is_still_falling_on_the_last_row"}}>
@@<{"name":"testFinished", "attributes":{"name":"it_is_still_falling_on_the_last_row", "duration":"0"}}>
@@<{"name":"testSuiteFinished", "attributes":{"name":"tetris.Step1_FallingBlocksTest$When_a_block_reaches_the_bottom"}}>
Total tests run: 8, Failures: 1, Skips: 0

Hope this will be helpful for you!

**Comment by ansyral** [comment]
@LuoDL are the tests parameterized? or could you help share the log? You can open the log using command"Java: open log"

**Comment by LuoDL** [comment]
The code is come from [tdd-tetris-tutorial](https://github.com/orfjackal/tdd-tetris-tutorial).
Maybe you want to try it yourself.

**Comment by ansyral** [comment]
@LuoDL thanks for the detailed info. Nested tests are not handled well, will fix it.

**Comment by jdneo** [comment]
Resolved in #633.

One limitation is that users need to get the report by clicking the status in the status bar. Tracking issue: #640
