### ISSUE TITLE
The logback configuration file is invalid

### ISSUE THREAD

**Issue by Keene-Chen** [microsoft/vscode-java-test#1404]
## problem description
First of all I'm not sure if this question should be submitted under issue under this plugin.

When I was developing Java applications on Linux using a remote plug-in for VsCode, I found that the logback configuration file didn't work.

I thought it was an environmental problem, but the problem still existed after I reconfigured the JDK. Then I checked my configuration file, and logback was not output to the file, only output to the console, but it was the default configuration file information.
![image](https://user-images.githubusercontent.com/46097224/162706676-22e67093-acd6-46ec-8a2d-c2a99bb48bf6.png)

I then reproduced my project on IntelliJ IDEA and found that the configuration file could be output normally without problems.
![image](https://user-images.githubusercontent.com/46097224/162706238-1504ad52-9343-4fe7-8c91-4d00faea3bbf.png)

I found that the VsCode Maven plugin does not generate logback .xml in the target directory, I wonder if this is the reason? My subsequent manual addition of the configuration file also fails.
Finally I tried to debug using the terminal command `-Dlogging.config` and the situation has not changed.
![image](https://user-images.githubusercontent.com/46097224/162705036-b29e4707-9be8-4b60-9d9c-c870e52836cb.png)

I hope to be helped, thanks!

## Project source code
[mvn_logback](https://github.com/Keene-Chen/mvn_logback)

## Compile environment
JDK: java-17-openjdk.x86_64

maven artifact: logback-classic 1.2.11

## System environment
OS: Rocky Linux release 8.5 (Green Obsidian)

VsCode Version: 1.66.1

VsCode plug-in Version: 
- Extension Pack for Java 0.22.3 (Pre-release)
- Language Support for Java(TM) by Red Hat  v1.4.0 
- Debugger for Java  v0.40.0 
- Test Runner for Java  v0.34.2 
- Maven for Java  v0.35.1 
- Project Manager for Java  v0.19.0

**Comment by jdneo** [comment]
The behavior you want is, when launching your project, the `logback.xml` is expected to be generated in the output folder? Am I right？

**Comment by Keene-Chen** [comment]
> The behavior you want is, when launching your project, the `logback.xml` is expected to be generated in the output folder? Am I right?
> 
> You can provide repro steps to help us understand to problem

No, I want the custom logback profile to take effect instead of using the default profile because it can't output logs to a file
Since it can be implemented in IDEA, I am sure it is not the problem with my configuration file

**Comment by Keene-Chen** [comment]
I found the problem because of my path problem

**Comment by jdneo** [comment]
How to repro the problem? Simply run the sample project?
