### ISSUE TITLE
Stop raising an error when re-running all invocations of a JUnit5 test method

### ISSUE THREAD

**Issue by fladdimir** [microsoft/vscode-java-test#1416]
https://github.com/microsoft/vscode-java-test/pull/1412#pullrequestreview-949352726
Re-running invocations is currently limited to selecting a single invocation, since it works via restricting the parent-method to a single parameter-set.
So when selecting multiple invocations of the same method for a re-run, an error is thrown:

![rerun_all_invocations_before_not_supported](https://user-images.githubusercontent.com/53265832/165363310-5ea46079-1bed-401e-b2c5-4e52d21ecc71.gif)

However, when selecting all invocations, the complete parent method could be re-run without any problem.

**Comment by jdneo** [comment]
To verifier:

1. Prepare a JUnit 5 parameterized test method: [sample](https://github.com/junit-team/junit5-samples/blob/c474e4143775e2f31e23c308638638e24f6b760d/junit5-jupiter-starter-maven/src/test/java/com/example/project/CalculatorTests.java#L29-L40). and run it.
2. In Test explorer, select all the children of `add(int, int, int)`
3. Click Run/Debug Test, 
4. Verify that the tests can be run
