### ISSUE TITLE
different behavior in vsc testing and gradle testing

### ISSUE THREAD

**Issue by yiyitech** [microsoft/vscode-java-test#1423]
Hi,

I have a spring boot project which uses jackson for serialization and deserialization. The model has a property of type Instant, which requires java time module. I believe this is automatically configured in spring boot web starter so the code is striaghtforward:

```java
var mapper = new ObjectMapper();
```

All my tests are passed using vsc testing extension, however, some failed when running gradle test during jenkins job. I have to change the above line to:

```java
var mapper = new ObjectMapper().registerModule(new JavaTimeModule());
```

I can understand that in unit test context does not provide sufficient constructs therefore registering the module manually is a must, however these tests are expected to fail in vsc testing as well. Is this a known bug?

Nice plugin, keep up the nice work!

Samuel

**Comment by jdneo** [comment]
What's the result if running the test via the Gradle command line? Or in other IDEs like Eclipse/IDEA?

And it would be helpful if a sample project can be provided for this issue.

**Comment by jdneo** [comment]
Closing due to inactive for 2 weeks.

But you can still provide more information here when it's possible.
