### ISSUE TITLE
Activating extension 'vscjava.vscode-java-test' failed: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Avirup-301294** [microsoft/vscode-java-test#1426]
I'm using an online vscode editor (code-server) and getting this issue while working with Gradle based projects. But I am not getting the above issue always. 
So it's difficult for me to reproduce the bug certainly. But as I am working for days, I observe a pattern that if I open any .java files before the Java Projects loads it gives that error.
I mean to say, as soon as I open folder a java project and get into src/ folder and open a .java file and the Java projects is still loading and after it completes it gives the pop up (Activating extension 'vscjava.vscode-java-test' failed: Cannot read properties of undefined (reading 'name')). But if I wait till Java projects load it won't give me that error.

Will you confirm if there is some timing issue involved in this case? 

![image](https://user-images.githubusercontent.com/45994215/170661003-e42742f1-bbff-45d0-8376-fac30d854eb8.png)

**Comment by jdneo** [comment]
I'm not familiar with code server, but it's most likely that some apis are not supported in code server. Could you confirm that this issue can be repro in VS Code itself as well?

**Comment by jdneo** [comment]
Closing since it's inactive for a long time. You can still add comments here if you have more information about this issue.
