### ISSUE TITLE
Test execution working directory points toward vscode installation folder

### ISSUE THREAD

**Issue by Romalouz** [Microsoft/vscode-java-test#143]
Hello,

The working directory of the test execution points towards VS Code installation folder when starting a test from the Run Test & Debug Test controls.

Here is a simple test that expose the issue:

```java
public class AppTest {
   
   @Test
   public void testPrintMessage() {	
      System.out.println("Will print user.dir:");
      System.out.println(" - " + System.getProperty("user.dir"));    
   }
}
```

Running this test with `mvn test` outputs:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running test.issue.userdir.AppTest
Will print user.dir:
 - C:\Dev\Dev_tests\VSCode_Ext_Issue\userdir
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.075 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

Whereas starting it with the Run Test control or `Java: Run Test` command gives:
```
@@<{"name":"testReporterAttached"}>
@@<{"name":"rootName", "attributes":{"name":"Default Suite"}}>
@@<{"name":"suiteTreeStarted", "attributes":{"name":"test.issue.userdir.AppTest", "location":"java:test://test.issue.userdir.AppTest"}}>
@@<{"name":"suiteTreeNode", "attributes":{"name":"testPrintMessage", "location":"java:test://test.issue.userdir.AppTest.testPrintMessage"}}>
@@<{"name":"suiteTreeEnded", "attributes":{"name":"test.issue.userdir.AppTest", "location":"java:test://test.issue.userdir.AppTest"}}>
@@<{"name":"testSuiteStarted", "attributes":{"name":"test.issue.userdir.AppTest", "location":"java:test://test.issue.userdir.AppTest"}}>
@@<{"name":"testStarted", "attributes":{"name":"testPrintMessage", "location":"java:test://test.issue.userdir.AppTest.testPrintMessage"}}>
Will print user.dir:
 - C:\Program Files\Microsoft VS Code
@@<{"name":"testFinished", "attributes":{"name":"testPrintMessage", "duration":"5"}}>
@@<{"name":"testSuiteFinished", "attributes":{"name":"test.issue.userdir.AppTest"}}>
Total tests run: 1, Failures: 0, Skips: 0
```

Would it be possible to define the user.dir property when a test is triggered from the UI control? 
Attached is a sample project to reproduce the issue.
[userdir-issue.zip](https://github.com/Microsoft/vscode-java-test/files/1831873/userdir-issue.zip)

**Comment by ansyral** [comment]
@Romalouz we'll support test configuration later and you can configure properties from UI

**Comment by Romalouz** [comment]
@ansyral Can you explain how I can configure the properties from UI?
Thanks in advance.

**Comment by ansyral** [comment]
@Romalouz  sorry it hasn't been supported yet, we'll work on it later.

**Comment by ansyral** [comment]
@Romalouz could you try the latest version of the extension? By default the working directory would be current workspace folder, and you could configure it by command `Java: Edit Test Configuration`

**Comment by Romalouz** [comment]
@ansyral Just tested it and it work nicely.
Thanks for your support.

**Comment by wortner** [comment]
Is it really working? I am unable to change the user.dir. There seems to be no such comand to set it. Can you please advise how to change the directory from VS Code instalation folder to project home.

**Comment by jdneo** [comment]
@wortner You can find a file named `launch.test.json` in `.vscode` folder.

**Comment by wortner** [comment]
@jdneo With the configuration it works. But I need to always select "Run with configuration". And in the "Lens" or how is the name for in code menu, I have red that the extension no more supports "Run with configuration". Anyway why is it not set by default to the project home? #458 seems related.

**Comment by jdneo** [comment]
For now, you can set the default field in the launch.test.json with the default configuration name you want to run with.
