### ISSUE TITLE
Can't run test due to multiple bindings

### ISSUE THREAD

**Issue by ytreister** [microsoft/vscode-java-test#1436]
This is similar to issue #131.

I am using gradle to build my application.  I have the following exclusion in my `build.gradle` file:
```
configurations.testImplementation {
   exclude module: 'slf4j-jboss-logmanager'// This is to resolve multiple bindings error
}
```
to prevent a multiple bindings error: `SLF4J: Class path contains multiple SLF4J bindings.`  due to my use of `testImplementation 'org.simplify4u:slf4j-mock:2.2.0'` in my dependencies.  The problem is one of the other dependencies includes: `slf4j-jboss-logmanager`.  All of my test successfully run and pass when I run `gradlew build`, however when I try and debug a test in VS Code, it fails with this error: `SLF4J: Class path contains multiple SLF4J bindings.`

Is there some way to fix this?

**Comment by jdneo** [comment]
Let's track the issue in https://github.com/microsoft/vscode-java-test/issues/1045.

Thank you for reporting this.

**Comment by jdneo** [comment]
The Gradle Test Delegation (both run and debug) has supported now.

To use this feature, you need to install the latest [Test Runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) and [Gradle for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) extension.

To delegate the tests to Gradle, you can set the default testing profile in Testing explorer:
![image](https://github.com/user-attachments/assets/f3e982e0-0340-461c-b6c4-c8c7fe9352f5)
![image](https://github.com/user-attachments/assets/e1a2693c-e6d7-425a-b7d5-6adf878f4ce3)

If you do not want to change the default testing profile, you can trigger an one-time execution via:
![image](https://github.com/user-attachments/assets/1c3f7478-b100-40cf-98c2-6f0357050209)
![image](https://github.com/user-attachments/assets/55fa017c-adb3-4c5a-bc81-55db63834773)
