### ISSUE TITLE
Update vscode-test to @vscode/test-electron

### ISSUE THREAD

**Issue by DatGuyJonathan** [microsoft/vscode-java-test#1439]
I'm running into this error during `npm run test`: 

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

Seems related to https://github.com/microsoft/vscode-test/issues/153. Should this repo update to `"@vscode/test-electron": "^2.1.4"`?

**Comment by jdneo** [comment]
Yes, we need to update the test dependency to the new one.

But regarding to this issue, I think it's not caused by the npm module, I can run `npm run test` locally, and we use that in our CI: https://github.com/microsoft/vscode-java-test/blob/main/.github/workflows/build.yml#L83.

**Comment by DatGuyJonathan** [comment]
@jdneo, the linked issue on vscode-test says he's on M1 chip, and so am I. I wonder if only people on M1 will run into this issue, and it's fixed in the later version of that npm mpdule.

**Comment by DatGuyJonathan** [comment]
Thanks @jdneo, July sounds good, it's not a blocking issue for me.
