### ISSUE TITLE
java.io.FileNotFoundException because target-Folder not available 

### ISSUE THREAD

**Issue by braetkuegeli** [Microsoft/vscode-java-test#144]
In my Junit-Tests I'm creating a file in the target-Folder, which works with Maven and Eclipse. But with Java Test Runner I'm getting a java.io.FileNotFoundException.

```
@Test
public void test() throws IOException {
    try (final FileOutputStream out = new FileOutputStream("target/file.txt")) {
        out.write("A string".getBytes());
    }
}
```
In the launch configuration I can add the target folder to the source path to make it work. But I don't know how to configure it for the Java: Run Test

```
{ "type": "java",
    "name": "Debug (Launch)",
    "request": "launch",
    "cwd": "${workspaceFolder}",
    "console": "internalConsole",
    "stopOnEntry": false,
    "mainClass": "org.junit.runner.JUnitCore",
    "args": "MyUnitTest",
    "sourcePaths": [
        "${workspaceFolder}/src/test/java",
        "${workspaceFolder}/target"
    ]
}

```

**Comment by ansyral** [comment]
@braetkuegeli we haven't supported test configuration yet, will work on it soon!

**Comment by braetkuegeli** [comment]
@ansyral I expect the same behaviour regardless if I use Eclipse, Maven, VS Code with Maven for Java or VS Code with Java Test Runner Extension.

**Comment by ansyral** [comment]
@braetkuegeli make sense, the default working directory could be changed to current workspace folder if other IDEs all follow this way

**Comment by ansyral** [comment]
@braetkuegeli could you try the latest version of the extension? It should work now

**Comment by braetkuegeli** [comment]
It works now as excpeted!

Thank you @ansyral
