### ISSUE TITLE
Codicon clutter in test explorer

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1453]
See the old and new comparison in https://github.com/microsoft/vscode-java-test/pull/1449

I'm used to seeing red and green in a list of over 200 tests and orange and violet disturb that quick scan.

Parameterized tests have been left out of the icon. (not that I want them, but just pointing out inconsistency)

Could you use the greyscale versions of these codicons ?

**Comment by jdneo** [comment]
The icons are just added by a simple string. So, I'm afraid that there is no way to make it grey.

Maybe add a setting to control whether to show the codicon or not.

Meanwhile, I would like to see more feedback from users.

**Comment by z-aki** [comment]
> Meanwhile, I would like to see more feedback from users.

sounds good

**Comment by matter-it-does** [comment]
just me maybe.. 
I got used to it
