### ISSUE TITLE
Executing tests gives me "Failed to get workspace folder from test item"

### ISSUE THREAD

**Issue by halloleo** [microsoft/vscode-java-test#1463]
I have created a small Java example project with a test in a package. VS code recognizes the project and the test perfectly (e.g. I was able to use the _Source Actions..._ --> _Generate Tests..._ command to create the test file).

However when I execute the test I get the following error balloon:

""Failed to get workspace folder from test item: $(symbol-class) ClassInPackageTest."

Any idea how to fix this?

***

PS: Happy to share the complete project (e.g. as an archive), but don't know where's the best spot to share it.

**Comment by jdneo** [comment]
Yes, sharing a sample project could help me understand the problem. Using an archive works for me. :)

**Comment by halloleo** [comment]
Ok, here some screenshots to start with. First the project in the **Explorer panel**:

![Explorer view](https://i.imgur.com/S2CMNRS.png)

Then in the **Testing panel**:

![Testing view](https://i.imgur.com/nClt9sl.png)

And finally the **full window** with the error balloons:

![Full window](https://i.imgur.com/m7PtCyF.png)

Hope this help!

**Comment by halloleo** [comment]
And the full content of the `settings.json`:

```
{
    "java.project.sourcePaths": ["src"],
    "java.project.outputPath": "bin",
    "java.project.referencedLibraries": [
        "lib/**/*.jar"
    ]
}
```

***

ps: I have now I idea how I can upload a zip file here to the issue area of GitHub - that's why I sent the screenshots.

**Comment by jdneo** [comment]
The last screenshot looks similar with this issue: https://github.com/microsoft/vscode-java-test/issues/1394

Will it help if you trigger `Java: Clean Java Language Server Workspace` and restart VS Code?

**Comment by halloleo** [comment]
Thanks, @jdneo, for looking at this!

I just tried Cleaning the JLS Workspace, but I get the same error.

Is there a way to provide the workspace location manually?

**Comment by jdneo** [comment]
> ps: I have now I idea how I can upload a zip file here to the issue area of GitHub - that's why I sent the screenshots.

You can just simply drag the zip file into the comment input box, should work.

**Comment by halloleo** [comment]
> You can just simply drag the zip file into the comment input box, should work.

Cool! So here the zip of the demo project: [packaged-tester.zip](https://github.com/microsoft/vscode-java-test/files/9232676/packaged-tester.zip)

**Comment by jdneo** [comment]
Hmm, the project works well on my Windows machine:
![image](https://user-images.githubusercontent.com/6193897/182134255-3541438b-1adc-4a82-a5d1-769f4570332e.png)

Are you working on a symlink folder in Linux?

**Comment by halloleo** [comment]
> Are you working on a symlink folder in Linux?

I definitely work on Linux (RHEL 7 and RHEL 8). As for the symlink: That _might_ be the case. I'll check tomorrow when I'm back at the machine.

Does this mean when I open the project via its direct path (no symlink part in the path), then it should work?

**Comment by halloleo** [comment]
> Does this mean when I open the project via its direct path (no symlink part in the path), then it should work? _(Always nice to quote myself. :wink:)_

Yes, it DOES work when I open the project through its direct path (no symlink part in the path). All tests work. -Thanks for pointing out the possible issues, @jdneo!

IMHO this is a bug. Symlinked project directories _should_ work, I think.

**Comment by jdneo** [comment]
Unfortunately, this issue is out of the control of the test runner extension. According to the [discussion](https://github.com/microsoft/vscode/issues/74104#issuecomment-562050914), it's related with Electron framework.

I'm closing this issue since we have an issue: https://github.com/microsoft/vscode-java-test/issues/630 to track this actually. I'm sorry that so far, I cannot provide any more help on this

**Comment by halloleo** [comment]
Makes all sense.

> I'm sorry that so far, I cannot provide any more help on this.

Well, for me, using direct, canonicalised links is good enough. 😄
