### ISSUE TITLE
parameterized tests: sorting should be natural instead of alphabetical

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1465]
Make 15  parameterized test cases

https://en.wikipedia.org/wiki/Natural_sort_order

<img width="33" alt="image" src="https://user-images.githubusercontent.com/76812421/182598337-c11a6858-696a-43c5-bc76-24c62bd609cf.png">

**Comment by jdneo** [comment]
Related code is:

https://github.com/microsoft/vscode-java-test/blob/794227efdfe574e4d290db636df7cbd1c57b0786/src/controller/utils.ts#L162-L164
