### ISSUE TITLE
Test Explorer not working with DisplayName and DisplayNameGenerators

### ISSUE THREAD

**Issue by brunotacca** [microsoft/vscode-java-test#1466]
I think my VSCode is not configured correctly or another extension is messing with this one. \
I searched for similar issues and all seem to be resolved, like #1448 and #667 \
I also couldn't find any configuration guide that solves the problem.

![image](https://user-images.githubusercontent.com/6067887/182623414-8832aded-23a3-4382-9a97-d39d324ccf79.png)

And I have nothing configured in its settings:

![image](https://user-images.githubusercontent.com/6067887/182624507-a8a2c59e-0271-4497-917f-0bb8fcd97497.png)

Thank you all in advance.

I am using Test Runner for Java v0.36.2022080202

![image](https://user-images.githubusercontent.com/6067887/182624383-ba872b2e-0bb4-4576-bcc2-d24dd1dba5bd.png)

VSCode:
```
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:14:10.636Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-41-generic
```

This is my `settings.json` when opened from the verifier project (`junit5-jupiter-starter-maven`)

<details><summary>settings.json</summary>

```json
{
    "dart.flutterSdkPath": ".fvm/flutter_sdk",
    // Remove .fvm files from search
    "search.exclude": {
        "**/.fvm": true
    },
    // Remove from file watching
    "files.watcherExclude": {
        "**/.fvm": true
    },
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },    
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },    
    "dart.openDevTools": "flutter",
    "git.autofetch": true,
    "editor.wordWrapColumn": 80,
    "dart.lineLength": 80,
    "dart.debugExternalLibraries": true,
    "dart.debugSdkLibraries": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"/home/tacca/.vscode/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar\"",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "redhat.telemetry.enabled": false,
    "eslint.alwaysShowStatus": true,
    "eslint.nodePath": "",
    "git.enableSmartCommit": true,
    "java.project.importOnFirstTimeStartup": "automatic",
    "java.jdt.ls.java.home": "/usr/java/openjdk/jdk-17",
    "maven.executable.path": "/usr/bin/mvn",
    "java.configuration.runtimes": [
    
        {
            "name": "JavaSE-17",
            "path": "/usr/java/openjdk/jdk-17"
        }
    ],
    "workbench.iconTheme": "vscode-icons",
    "[scss]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "svg.preview.mode": "svg",
    "gitlens.gitCommands.skipConfirmations": [
        "fetch:command",
        "switch:command"
    ],
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "editor.unicodeHighlight.nonBasicASCII": false,
    "prettier.singleQuote": true,
    "editor.inlineSuggest.enabled": true,
    "prettier.trailingComma": "none",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "go.executable.path": "/usr/local/go",
    "[html]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "angular.trace.server": "verbose",
    "angular.log": "verbose",
    "java.test.config": {
      "telemetry.enableTelemetry": false
    },
    "editor.unicodeHighlight.allowedCharacters": {},
    "editor.renderControlCharacters": false,
    "editor.renderWhitespace": "all",
    "vsicons.dontShowNewVersionMessage": true,
    "auto-close-tag.activationOnLanguage": [
      "xml",
      "markdown",
      "HTML (EEx)",
      "HTML (Eex)",
    ],
}
```

</details>

**Comment by jdneo** [comment]
Currently the display name is displayed as the description part in the explorer:

![image](https://user-images.githubusercontent.com/6193897/182745725-e98cd4b1-658d-4d3f-98ae-714455c5dbff.png)

**Comment by brunotacca** [comment]
> If you are asking about the place of the display name. Currently the it's displayed as the description part in the explorer:
> 
> ![image](https://user-images.githubusercontent.com/6193897/182745725-e98cd4b1-658d-4d3f-98ae-714455c5dbff.png)

Ah, now I see it, I totally missed it. 

After running the example on issue #667 I get the same result compared to your comment (https://github.com/microsoft/vscode-java-test/issues/667#issuecomment-893242589)

![image](https://user-images.githubusercontent.com/6067887/182827502-2cd4aca3-152e-4db4-bf4d-bcd121f86326.png)

It would be nice if there was a setting to completely hide the method/class name if a DisplayName is present. \
The list view is kinda confusing also, it seems a little buggy because it doesn't show the display name as the description, but `@ParameterizedTest` are displayed nicely.

![image](https://user-images.githubusercontent.com/6067887/182828238-7a248c9b-b67a-40d1-9ca5-ad4b52979218.png)

This is solved for me, I will leave it up to you in case you want to follow up on another aspect.

Thank you @jdneo

**Comment by jdneo** [comment]
Thank you @brunotacca for sharing your thoughts. The reason why current implementation put the display name as the description part is that: the display name can only be resolved at the runtime. So, we have to show the method declaration name at first before the test case runs.

But I agree that the description part is not 'eye-catching' enough and might bring some confusion here.

We will keep an eye on it and if more users complain about it, we will consider improving the UI here. :)

**Comment by brunotacca** [comment]
I see, makes sense @jdneo.

Also, just as a matter of curiosity, do you happen to know where (or how) I could generate a test output like this?

![image](https://user-images.githubusercontent.com/6067887/182998305-2394a3d8-f5e2-45b2-b8df-da5d34411c48.png) \
[Source: Baeldung](https://www.baeldung.com/junit-custom-display-name-generator)

Thank you.

**Comment by jdneo** [comment]
Sorry have no idea 🤔

**Comment by PaulDMooney** [comment]
@brunotacca IntelliJ produces a nice output like that.
