### ISSUE TITLE
JUnit 5 from Eclipse Project not working

### ISSUE THREAD

**Issue by Snowald** [microsoft/vscode-java-test#1467]
If you try to run JUnit 5 test in a project which was created in Eclipse the do not work and you get the following two issues:

Invalid classpath container: 'JUnit 5' in project 'JUnitTester'
The project cannot be built until build path errors are resolved

I have attached an example project as well as a screenshot from said example. 
[JUnitTester.zip](https://github.com/microsoft/vscode-java-test/files/9284132/JUnitTester.zip)
![Screenshot from 2022-08-08 20-19-30](https://user-images.githubusercontent.com/104894252/183486488-bc13c35e-7f3d-483c-9a72-3bcbe87e89d7.png)
![Screenshot from 2022-08-08 20-23-17](https://user-images.githubusercontent.com/104894252/183486997-7a6f10b6-96fc-4ef9-b9f3-c3f9c51c39cd.png)

If there is anything else needed just let me know.

The VSCode About popup:
Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:48.541Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-43-generic

**Comment by jdneo** [comment]
The JUnit 5 classpath container is not supported yet, please refer to this link as a workaround: https://stackoverflow.com/a/73243569/13068918

**Comment by Snowald** [comment]
Thank you
