### ISSUE TITLE
Test history: access test run history of a test that is passing now

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1468]
run an obviously failing test, `assertEquals(1,2)`
then fix it and run it again , `assertEquals(1,1)`

Now how do I get to the error _message expected 1, was 2_ ? It only shows up when a test fails. but often past runs have some info that I need again.

**Comment by jdneo** [comment]
You can run the command `Test: Peek Output`

And then in the peek view, you can see the run history
![image](https://user-images.githubusercontent.com/6193897/183588203-de9c0dcd-ba08-48b4-ba7b-3157dac92190.png)

**Comment by matter-it-does** [comment]
thanks
