### ISSUE TITLE
Support JUnit5 parallel execution

### ISSUE THREAD

**Issue by mseele** [microsoft/vscode-java-test#1472]
We write more and more test to be able to run in [parallel](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution). This works, but vscode sometimes does display the wrong result-status icon in front of the tests.
After a (parallel) test run, there should be a green checkbox (or red cross) next to the test name in the test view. However vscode does get confused by the parallel test run and shows only a few result icons and lot's of "not-run" icons next to the (ran) tests. Please see my attached screenshot for further details.

And feel free to reach out for more details or something I can help with this issue.

![Bildschirmfoto 2022-08-19 um 11 32 01](https://user-images.githubusercontent.com/15141672/185590256-0f35b215-0497-4425-9b5e-1e66b99ad2bc.png)

**Comment by mseele** [comment]
It's even worse! Running the tests in parallel do hide failures:

![Bildschirmfoto 2022-08-19 um 12 54 04](https://user-images.githubusercontent.com/15141672/185603830-df687a03-d882-4269-9d33-b4eb931635b9.png)

**Comment by jdneo** [comment]
Thank you for the feedback. Parallel execution is not supported right now.

**Comment by mseele** [comment]
Thank you for the clarification. Is there a timeline to implement this feature or anything I can help with?

**Comment by jdneo** [comment]
Sorry no definite timeline yet. But contributions are welcome.

I think the problem happens at https://github.com/microsoft/vscode-java-test/blob/794227efdfe574e4d290db636df7cbd1c57b0786/src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts#L63

The current logic assumes that each time only one test item is treated, which is wrong.

**Comment by fladdimir** [comment]
@mseele its been some time since there was activity on this issue, so I assumed you did not have time to work on it for now. please feel free to have a look at the created PR, suggest improvements, and see whether this also fits your use-case.
