### ISSUE TITLE
Test case(s) crash VSCode

### ISSUE THREAD

**Issue by jvdevlab** [microsoft/vscode-java-test#1486]
When running test cases I get 
![image](https://user-images.githubusercontent.com/83979897/189493149-4a8fec2c-d609-49ab-bd05-b0422af83022.png)
and then
![image](https://user-images.githubusercontent.com/83979897/189490404-8381141c-8c46-426f-a2f8-95fd713ce401.png)

What works?
- Brand new project works fine. 
- Using Maven to run the same test works fine. 

What didn't help?
- I tried to narrow down the issue by removing all optional things from my project (.vscode folder, etc) except a single test.
- I've tried different Java, junit, and maven versions.
- I've tried "Java: Clean Java Language Server Workspace" numerous times
- I've created brand new project, verified sample test works, then copy paste files from my project and the issue reappeared.
- Tried to switch "Extension Pack for Java", "Extension Pack for Java" and "Test Runner for Java" to different older version and pre-release versions. 
- Disable all plugins except "Extension Pack for Java"
- Removed AppData\Roaming\Code\User\settings.json

Versions:

VSCode 

Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No

Plugins

Test Runner for Java v0.37.1
Language Support for Java(TM) by Red Hat v1.10.0
Extension Pack for Java v0.25.1

Java version: 16.0.2, vendor: Eclipse Foundation, runtime: jdk-16.0.2.7-hotspot
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

Here is the test cases that I run. https://github.com/jvdevlab/java-test/
Can you please run them and see if you get the same issue?

Please tell me where I can see other useful information such as log for Test Runner for Java to further troubleshoot the issue.

Thanks,

**Comment by jdneo** [comment]
I can repro your issue. Will investigate what happened.

**Comment by jdneo** [comment]
Okay, looks like there is come name conflicting happening.

Our test controller's id is named `java`, and the project is named `java` as well. I'll report to VS Code team to see if this can be fixed from the API level.

For now, as a workaround, you can rename your project, sth like:

```xml
...
<name>java-test</name>
<artifactId>java-test</artifactId>
<groupId>com.jvdevlab.app</groupId>
...
```

**Comment by jdneo** [comment]
upstream discussion: https://github.com/microsoft/vscode/issues/160671

**Comment by jvdevlab** [comment]
@jdneo thank you for the solution and a quick turnaround. It works!

**Comment by jdneo** [comment]
It's fixed upstream, so I'm closing this now.
