### ISSUE TITLE
No delegateCommandHandler for vscode.java.test.get.testpath

### ISSUE THREAD

**Issue by musiKk** [microsoft/vscode-java-test#1487]
My JUnit 5 tests are not discovered anymore. I have

* cleaned the Java workspace multiple times
* reinstalled the extension

Extension version: 0.37.1
**Reverting to 0.36.0 immediately fixes the issue.**

Java version:
```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
```

I do not even have a Java 8 installed on my system.

Developer console shows these errors:
```
[[object Object]]No delegateCommandHandler for vscode.java.test.get.testpath
mainThreadExtensionService.ts:80 Error: No delegateCommandHandler for vscode.java.test.get.testpath
	at vscode-file://vscode-app/Users/whahn/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1034658
	at vscode-file://vscode-app/Users/whahn/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1034952
	at Immediate.<anonymous> (vscode-file://vscode-app/Users/whahn/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1035317)
	at process.processImmediate (node:internal/timers:466:21)
```

Let me know if I can provide more details.

**Comment by jdneo** [comment]
What's the version of your `vscode.java` extension?

**Comment by musiKk** [comment]
That would be 1.0.0.

**Comment by jdneo** [comment]
Please update it to latest `1.10.0` and try again.

**Comment by musiKk** [comment]
Sorry, are you talking about the built-in `vscode.java` which can only be updated with VSCode itself? Or the "Language Support for Java(TM) by Red Hat" (`redhat.java`) as installed by Microsoft's "Extension Pack for Java"? Because that one is indeed at 1.10.0.

**Comment by jdneo** [comment]
It's `Language Support for Java(TM) by Red Hat` I'm talking about, the version list above looks fine.

Does that mean, with `redhat.java@1.10.0` + `vscjava.vscode-java-test@0.37.1`, it's stably reproducible that when you open a Java project, the `No delegateCommandHandler` error appear?

**Comment by musiKk** [comment]
I don't know what to say. I tested the current version again and now it works.

As said, previously I tried uninstalling and installing again; reloading and cleaning the Java language server workspace all the time. It was consistently not discovering any test and printing the errors as provided above. But now all seems resolved.

If you want to know something else, I can provide it but apart from that, I guess this issue can be closed.

**Comment by jdneo** [comment]
Can you share the server logs if it still exists? (Trigger the command: `Java: Open Java Language Server Log File`, it might be deleted when clean the workspace cache)

**Comment by musiKk** [comment]
Unfortunately the logs got indeed deleted as you said. I only have the last couple of minutes and there is nothing suspicious in there.

**Comment by jdneo** [comment]
Thank you.

I'm closing this issue now. But when you encounter it again, please leave comments here.
