### ISSUE TITLE
The test runner does not find tests from the super class

### ISSUE THREAD

**Issue by nicolas-vancea** [microsoft/vscode-java-test#1492]
When having testng tests in a super class, the vs code test runner does not find them for the current class (the one extending the super class), only for the super class, but maven founds them. I haven't tried this behaviour with junit. Also, when having an abstract class with tests in it, those tests appear in the test finder, but they shouldn't as those can not run for that abstract class, they will run for the class that extends the abstract class.

**Comment by jdneo** [comment]
Thanks for reporting, inherited tests for TestNG have some problems now.

Related with #435, #718
