### ISSUE TITLE
运行test后, vscode加alt跳转文件失效

### ISSUE THREAD

**Issue by izilongwan** [microsoft/vscode-java-test#1496]
vscode 1.66
test 0.34
运行test后, alt跳转文件失效

**Comment by jdneo** [comment]
Could you share your server logs? See: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

如果可以，请分享一下你的server日志。

**Comment by izilongwan** [comment]
![image](https://user-images.githubusercontent.com/48234072/197160052-4f1c98ba-ef11-4ec6-81fc-db5e754e9048.png)

**Comment by izilongwan** [comment]
不运行test就可以, 运行了之后就失效了

**Comment by jdneo** [comment]
Is there anything strange in the server log? Trigger `Java: Open Java Language Server log file`
