### ISSUE TITLE
0.5.0 EndGame

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode-java-test#150]
# Build
- [x]  3/29 - Bump version to 0.5.0  - @ansyral 
- [x]  3/29 - Add change log for 0.5.0 - @ansyral
- [ ]  3/29 - Signed RC Bits - @ansyral

# Test
- [x]  3/29 - Run test plan #49 - @bsaby
- [x]  3/29 - Test configuration - @ansyral

# Release
- [x]  4/3 - Add 0.5.0 tag for vscode-java-test - @ansyral
- [x]  4/3 - Release to marketplace - @ansyral 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by bsaby** [comment]
# Run test plan

1. Configuration：

Win10 x64 | Mac
-- | --
VSCode1.20.1 Jdk1:1.8.0_161 | VSCode:1.20.1 JDK:1.8.0_144

2. Open bugs: 
 #152 #153  #154 #155 #156
3. Test result:

Test case | Win10 | Mac
-- | -- | --
Clean   install | Pass | Pass
Update | Pass | Pass
Uninstall | Pass | Pass
Test   explorer | Pass | Pass
Test   explorer of Multi-root | Pass | Pass
Test   report | Pass | Pass
Test   status bar | Pass | Pass
Trigger   tests from test explorer | Pass | Pass
Open   test log command | Pass | Pass
Configure   test report position | Pass | Pass
Junit5   test | #156 | #156
Test   configuration | #152 #153 #154 #155 | #152 #153 #154 #155

**Comment by ansyral** [comment]
fixed #152 #153 #154 #155
