### ISSUE TITLE
Test extension icon not visible in the side pane

### ISSUE THREAD

**Issue by ArbeenaAzeeb1** [microsoft/vscode-java-test#1501]
Even after installing the 'Test runner' extension, I'm not able to see the testing icon 
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/92846742/198991151-92bdd7e5-02c4-486d-ab92-a30e48b09104.png">

**Comment by jdneo** [comment]
have you opened a Java project in VS Code? You should be able to see it after a project is imported and extensions are activated.

**Comment by vejei** [comment]
Same issue for me. My project is an android project, and I test with a java project which created by IDEA, it worked. Maybe it doesn't worked for Android project.
