### ISSUE TITLE
Build problems with generated-sources.

### ISSUE THREAD

**Issue by timvahlbrock** [microsoft/vscode-java-test#1502]
We are running a JUnit Test suite which tests automatically generated code. We can run the tests using maven with `mvn clean test` without any problems, but get 'Build failed, do you want to continue?' from this extension. The extension reports problems that imports from the generated sources cannot be resolved. If we click 'Proceed', the tests are run without any problems. We included the maven build helper plugin to compile the generated sources. We are using the default configuration of this extension. Adding `mvn clean compile` or `mvn clean test-compile` as `preLaunchTask` didn't help either.

**Comment by jdneo** [comment]
You mean, though the extensions report compilation errors, but the tests can still be executed successfully, and the result is as expected?

**Comment by timvahlbrock** [comment]
Okay i just rechecked. If 'Proceed' is clicked, the tests are run from the last `mvn clean test` run.

**Comment by timvahlbrock** [comment]
So the compilation actually fails and the tests can only be run if the target directory hasn't been cleared from the last manual run.

**Comment by timvahlbrock** [comment]
The repo we are talking about is: https://github.com/timvahlbrock/miniJavaParser

**Comment by jdneo** [comment]
> If 'Proceed' is clicked, the tests are run from the last mvn clean test run.

Looks like it's running from `mvn clean test` because you set it as a preLaunch Task?

**Comment by timvahlbrock** [comment]
> > If 'Proceed' is clicked, the tests are run from the last mvn clean test run.
> 
> Looks like it's running from `mvn clean test` because you set it as a preLaunch Task?

That's what I mean. Proceeding will result in the last successful compilation result being executed. But the issue is that the build shouldn't fail in the first place.

**Comment by jdneo** [comment]
Hmm, so we have two problems here.

1. The Java language server does not pick the generated source which causes the compilation errors (the pop up dialog you have seen)

2. If there are build errors, we should stop test execution and let user know what happened.

**Comment by timvahlbrock** [comment]
Is this possibly related to https://github.com/microsoft/vscode-java-debug/issues/1214?

**Comment by timvahlbrock** [comment]
Okay, after taking another look at https://github.com/microsoft/vscode-java-debug/i, i think that this repo is the wrong location for this issue. The compilation error is caused by https://github.com/microsoft/vscode-java-debug/.
