### ISSUE TITLE
Everything is Japanese #164386

### ISSUE THREAD

**Issue by Aravindray** [microsoft/vscode-java-test#1504]
Type: <b>Bug</b>

@TylerLeonhardt this is the extension that cause those issues. [I think so]

Extension version: 0.37.1
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.19GB free)|
|Process Argv|--crash-reporter-id c945fef1-5917-4641-9104-106a397e2beb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
vscutilityc:30590830
3biah626:30602489
3d0df643:30602300
dbltrim-noruby:30603953

```

</details>

**Comment by jdneo** [comment]
Sorry I didn't get it. This extension does not provide any feature related with the Markdown preview. Please provide detailed steps for how to reproduce the issue, thanks.

**Comment by jdneo** [comment]
I can assure you that the markdown editing feature in the [screenshot you provided](https://github.com/Aravindray/Arduino/blob/d806fd7af848e1ba4dbe1b142138edac6cda60c8/README.md) is not contributed by this extension.
