### ISSUE TITLE
Get error when run a @DataJdbcTest using VScode

### ISSUE THREAD

**Issue by zarinfam** [microsoft/vscode-java-test#1518]
I wrote a very simple test for a `Repository` method that is implemented by `Spring Data JDBC` and used `@Query` with a parameter:
```
	@Modifying
	@Transactional
	@Query("delete from Item where itemType = :itemType")
	void deleteByItemType(String itemType);
```
In the test, when I call the `deleteByItemType` method, I get this error:
```
java.lang.IllegalStateException: For queries with named parameters you need to provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.
 at org.springframework.data.jdbc.repository.query.StringBasedJdbcQuery.lambda$convertAndAddParameter$1([StringBasedJdbcQuery.java:163])
```
I can run this test using vsode gradle plugin, gradle wrapper and IntelliJ successfully.

**Comment by jdneo** [comment]
Could you try to generate a global preference setting according to https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences

And then add this compiler setting: `org.eclipse.jdt.core.compiler.codegen.methodParameters=generate`.

**Comment by zarinfam** [comment]
Thanks for your workaround, It worked for me. But my question is, why you don't put this simple setting by default?

**Comment by jdneo** [comment]
Thank you for the suggestion. It's worth consideration. I'll file an issue at the Language Server(where compilation happens) side.

**Comment by jdneo** [comment]
Let's discuss in the upstream issue and I'm closing this one.
