### ISSUE TITLE
Test Runner compile java by java.jdt.ls.java.home not by maven or java.configuration.runtimes

### ISSUE THREAD

**Issue by JackDrogon** [microsoft/vscode-java-test#1527]
my config:
```json
"java.configuration.runtimes": [
	{
		"name": "JavaSE-1.8",
		"path": "/home/linuxbrew/.linuxbrew/opt/openjdk@8/libexec"
	},
	{
		"name": "JavaSE-11",
		"path": "/home/linuxbrew/.linuxbrew/opt/openjdk@11/libexec",
		"default": true
	},

],
"java.jdt.ls.java.home": "/home/linuxbrew/.linuxbrew/opt/openjdk@17/libexec",
```
Test Runner used openjdk@17 to compile, not by openjdk@11.

I didn't find any jdk config in vscode-java-test source code.

              The debugger will use the same the runtime as the language server recognized. This is nothing much the debugger can do here. Please open an issue at https://github.com/redhat-developer/vscode-java/issues

_Originally posted by @testforstephen in https://github.com/microsoft/vscode-java-debug/issues/879#issuecomment-707455946_

**Comment by jdneo** [comment]
Test runner is not responsible for compiling the project, it just resolves the launch configuration and let debugger to launch it.

The issue should be filed at https://github.com/redhat-developer/vscode-java.

Anyway, I tried to specify `java.jdt.ls.java.home` locally but cannot reproduce your problem.

Can you provide some reproduce steps?

**Comment by JackDrogon** [comment]
> Test runner is not responsible for compiling the project, it just resolves the launch configuration and let debugger to launch it.
> 
> The issue should be filed at https://github.com/redhat-developer/vscode-java.
> 
> Anyway, I tried to specify `java.jdt.ls.java.home` locally but cannot reproduce your problem.
> 
> Can you provide some reproduce steps?

I used above config.
![image](https://user-images.githubusercontent.com/3295714/217752200-b6c49de2-023b-4199-a085-7671ff99e3d6.png)
I ran test in the Testing sidebar. After I clicked the run button, VSCode compile the source.
![image](https://user-images.githubusercontent.com/3295714/217752503-eb10e855-ea56-4ed5-af73-1138e5368e42.png)
It used openjdk@17 not openjdk@11.
![image](https://user-images.githubusercontent.com/3295714/217752567-956b9e75-cd85-48aa-b401-6e917d9539e7.png)

**Comment by jdneo** [comment]
> for more info, Maven can recognized openjdk@11, it used openjdk@11 to compile the whole project.

It's because Maven extension directly delegate it to a Maven command executed in terminal.

Do you mean that the target version of compiled class filed by the extension is not 55?

**Comment by JackDrogon** [comment]
> > for more info, Maven can recognized openjdk@11, it used openjdk@11 to compile the whole project.
> 
> It's because Maven extension directly delegate it to a Maven command executed in terminal.
> 
> Do you mean that the version of compiled class filed by the extension is not 55? You can check it by `javap -verbose X.class`

emm，this is a good suggestion, I will check it. which is the folder of java lsp compile cache.

**Comment by jdneo** [comment]
If your project is a Maven project, it's in target folder.

**Comment by JackDrogon** [comment]
I didn't find any class file in target folder. Can vscode java lsp output more verbose log?

I checked class info major version, 52 is mean jdk8, it is the version in maven.

``` bash
#: javap -verbose ./java-udf/target/test-classes/org/apache/doris/udf/UdfExecutorTest.class | rg major
major version: 52
```
The project is doris-fe, https://github.com/apache/doris/tree/master/fe. You can try to compile it by debug.
https://doris.apache.org/zh-CN/community/developer-guide/fe-vscode-dev/ is the vscode dev guide.

**Comment by jdneo** [comment]
> I checked class info major version, 52 is mean jdk8, it is the version in maven.

If the class file you checked is not generated via running maven command in the terminal. Then that shows that the language server works as expected.

the screenshot you shared at the beginning is the JDK used to launch the java language server.

**Comment by JackDrogon** [comment]
> is not generated via running maven command in the terminal. Then that shows that the language server works as expected.

Yes，but I didn't know why lsp can't compile the project correctly, but maven can do

**Comment by jdneo** [comment]
> I didn't know why lsp can't compile the project correctly

Any more details?

**Comment by JackDrogon** [comment]
no more details. I can't find anything usefully in lsp log. idea do that right.

**Comment by JackDrogon** [comment]
is there any verbose log of lsp

**Comment by jdneo** [comment]
All the details about troubleshooting can be found here: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting.

To be honest, Sorry that I still cannot understand the problem you've encountered so I cannot provide more help to you now.

It was suspected that wrong JDK is used to compile the class file, but your check via javap shows that the version information is correct.

Then what's the problem makes you feel that 'incorrect'?

Does the extension return wrong result for the tests compared to Maven command line?

Or does the language server wrongly report some compiling errors that actually does not exist?
