### ISSUE TITLE
Tests not found along with Run/Debug options

### ISSUE THREAD

**Issue by Wolverine1122** [microsoft/vscode-java-test#1529]
I am in a gradle project. My `build.gradle` specifies:
`testImplementation 'org.junit.jupiter:junit-jupiter:5.9.0'`

My test files are located in `test/java` not `main/java`

My tests have `@Test` annotation

When I try to run, it says tests not found inside text file. There is also a popup that says `i` is not a function although there is no such thing. 

![image](https://user-images.githubusercontent.com/74157130/218481858-07aadcf4-d0bf-4455-a7ac-64055ec93079.png)

**Comment by FuzzyBoots** [comment]
For what it is worth, I saw the same error earlier today. Unfortunately, it's on a work project, so I don't know how much I can share.

**Comment by jdneo** [comment]
@fluke Could you describe about the project? Like what's the:
- build tool
- testing framework & version
- extensions version
- test annotation being used

And will the problem still appear if you `Refresh` the tests?
