### ISSUE TITLE
Failed to load ApplicationContext for MergedContextConfiguration

### ISSUE THREAD

**Issue by anibalsanchez** [microsoft/vscode-java-test#1530]
Hi,

I'm running tests on a simple Maven/Spring project.

If I run the tests with maven, they are Ok. 

If I click on the individual tests, they are Ok.

But, if I click on **Run Tests**, a test fails with the error: **java.lang.IllegalStateException: Failed to load ApplicationContext for MergedContextConfiguration** ...

What is the difference? Can anything be configured to solve the **Run Tests** case?

**Comment by jdneo** [comment]
Could you share a sample project?

**Comment by anibalsanchez** [comment]
Sure, pls, give me a day to clean it up a little bit.

**Comment by anibalsanchez** [comment]
Looking into the exception details, there are other reported causes:

```
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springApplicationAdminRegistrar' defined in class path resource [org/springframework/boot/autoconfigure/admin/SpringApplicationAdminJmxAutoConfiguration.class]: org.springframework.boot:type=Admin,name=SpringApplication
....
Caused by: javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Admin,name=SpringApplication
...
```

This previous issue and workaround solved the issue: https://github.com/microsoft/vscode-java-test/issues/1420#issuecomment-1132829069

Case closed.

Best Regards

**Comment by jdneo** [comment]
@anibalsanchez This surprises me if the issue is caused by Spring Boot Tools extension, cuz the issue should be fixed several months ago: https://github.com/microsoft/vscode-java-test/issues/1435#issuecomment-1259584327

What's the version of your extension?

**Comment by anibalsanchez** [comment]
I'm using the latest versions available. JDK17

```sh
hbenl.vscode-test-explorer@2.21.1
ms-vscode.test-adapter-converter@0.1.6
redhat.java@1.14.0
redhat.vscode-commons@0.0.6
sohibe.java-generate-setters-getters@7.4.0
SonarSource.sonarlint-vscode@3.14.0
VisualStudioExptTeam.intellicode-api-usage-examples@0.2.7
VisualStudioExptTeam.vscodeintellicode@1.2.30
vmware.vscode-boot-dev-pack@0.2.1
vmware.vscode-spring-boot@1.44.0
vscjava.vscode-java-debug@0.48.0
vscjava.vscode-java-dependency@0.21.1
vscjava.vscode-java-pack@0.25.7
vscjava.vscode-java-test@0.37.1
vscjava.vscode-lombok@1.1.0
vscjava.vscode-maven@0.40.4
vscjava.vscode-spring-boot-dashboard@0.10.1
vscjava.vscode-spring-initializr@0.11.2
```

**Comment by jdneo** [comment]
Is it possible to provide a sample project? Thanks.

**Comment by jdneo** [comment]
Hi @kanidjar, Is it possible to provide a sample project? I hope to check if there is any regression happens at the spring boot extension.
