### ISSUE TITLE
Regression: test detection broken, test status broken

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1531]
Maybe there's a simple repro but this will do.

test is duplicated, one of them doesn't have action buttons. After run, status is not updated.

Pre release version: v0.37.2023021404

suspect https://github.com/microsoft/vscode-java-test/issues/1517 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/76812421/219308435-dede1ab5-fa65-418e-be17-59e834450e32.png">

```
package com.blah;

import java.util.stream.Stream;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;

@ExtendWith(VertxExtension.class)
public class foo {
    @Nested
    @TestInstance(TestInstance.Lifecycle.PER_CLASS)
    class Bar{ Stream<Arguments> data() {
        return Stream.of(
                Arguments.of("foo", "bar"),
                Arguments.of("baz", "qux")
        );
    }
    
    @ParameterizedTest
    @MethodSource("data")
    public void test(String a, String b, VertxTestContext testContext) {
        System.out.println("Hello World");
        testContext.completeNow();
    }
    }
}
```

**Comment by jdneo** [comment]
I made a similar sample but not reproduce this.

![image](https://user-images.githubusercontent.com/6193897/219312056-d9164eb3-299a-48ad-92f0-abbe7ef10b2c.png)

Could you share a sample maybe?

**Comment by jdneo** [comment]
It's caused here: https://github.com/microsoft/vscode-java-test/blob/main/src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts#L229

Should use global match instead `.replace(/\\,/g, ',')`

After change the replace pattern, looks like it's working now.
![image](https://user-images.githubusercontent.com/6193897/219316930-0d544f6b-1709-4c60-9aae-af55796609d2.png)

@matter-it-does Thank you for reporting this. I'll prepare a PR to fix this issue.

**Comment by jdneo** [comment]
@matter-it-does The fix is included in 0.37.2023021802

**Comment by matter-it-does** [comment]
Please reopen

v0.38.2023022502


<img width="1210" alt="image" src="https://user-images.githubusercontent.com/76812421/221555543-d2cf135d-4aaf-45b2-bd9d-de0334b85280.png">

```
package com.example.starter;


import io.vertx.core.Vertx;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;


@ExtendWith(VertxExtension.class)
public class TestMainVerticle {

  
  @Test
  void tesfoo(Vertx vertx, VertxTestContext testContext) throws InterruptedException {
    Thread.sleep(1000);
    testContext.completeNow();
  }

}

```

**Comment by matter-it-does** [comment]
https://user-images.githubusercontent.com/76812421/221555770-e712e966-b18a-4bb8-a3c6-3dc02e0e2897.mov

**Comment by jdneo** [comment]
Tracked here: https://github.com/microsoft/vscode-java-test/issues/1534
