### ISSUE TITLE
Version 0.38.+ don't work with testNG version 6.x.x

### ISSUE THREAD

**Issue by klauerm** [microsoft/vscode-java-test#1544]
Since I've upgraded the Test Runner for Java extension to version v0.38.1. Now I can't run my testng unit tests any longer. The error message is:

```sh
java.lang.NoSuchMethodError: 'java.lang.Class[] org.testng.ITestNGMethod.getParameterTypes()'
```

The method `ITestNGMethod.getParameterTypes()` is available in testng version 7+. We are using version 6.14.3. and currently have no plans from our build team to upgrade it.
In the release notes of the test runner, there is no hint that I need to upgrade my testng version.

How to fix this?

**Comment by jdneo** [comment]
Hi @klauerm,

That's a regression issue. We have fixed it in the pre-release version `v0.38.2023030203`.

![image](https://user-images.githubusercontent.com/6193897/223886786-6a88e54c-d675-414b-9ddd-47be79ca473b.png)

More details at: https://github.com/microsoft/vscode-java-test/issues/1540
