### ISSUE TITLE
Any Update about "Delegate to Gradle" for Java Test?

### ISSUE THREAD

**Issue by PYOSESEUNG** [microsoft/vscode-java-test#1547]
Recently, I read issues about "Delegate to Gradle" below. 
#1045  https://github.com/microsoft/vscode-java-debug/issues/1127

So, Is 'Delegate to Gradle' feature on developing?

There is still same problem.

Expected : 
For a Spring Boot project, if both src/main/resource and src/test/resource contain application.properties file,
**the test runner should pick the one in src/test/resource.**

Actual :
It seems that the test runner pick the one in src/main/resource.

**Comment by jdneo** [comment]
It's in our backlog now: https://github.com/microsoft/vscode-java-test/issues/1045. But no concrete date about when to support.

**Comment by jdneo** [comment]
The Gradle Test Delegation (both run and debug) has supported now.

To use this feature, you need to install the latest [Test Runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) and [Gradle for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) extension.

To delegate the tests to Gradle, you can set the default testing profile in Testing explorer:
![image](https://github.com/user-attachments/assets/f3e982e0-0340-461c-b6c4-c8c7fe9352f5)
![image](https://github.com/user-attachments/assets/e1a2693c-e6d7-425a-b7d5-6adf878f4ce3)

If you do not want to change the default testing profile, you can trigger an one-time execution via:
![image](https://github.com/user-attachments/assets/1c3f7478-b100-40cf-98c2-6f0357050209)
![image](https://github.com/user-attachments/assets/55fa017c-adb3-4c5a-bc81-55db63834773)
