### ISSUE TITLE
Tests when using pact are not executed

### ISSUE THREAD

**Issue by jeanbrazcosta** [microsoft/vscode-java-test#1548]
Type: <b>Bug</b>

When running the tests below, the results appear as 0 tests passed, 0 tests failed.

Below is an example of the class, all dependencies and imports are fine in my project as the same problem does not occur with intellij.
public class Test {
    import static java.nio.charset.Charset.defaultCharset;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyBoolean;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.web.server.LocalServerPort;
import org.springframework.core.io.ClassPathResource;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.util.StreamUtils;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import au.com.dius.pact.provider.junit.Provider;
import au.com.dius.pact.provider.junit.State;
import au.com.dius.pact.provider.junit.loader.PactBroker;
import au.com.dius.pact.provider.junit.loader.PactBrokerAuth;
import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;

@PactBroker(scheme = "http", host = "localhost:9282" (token = "${PACT_TOKEN}"))
@Provider("GetPricesV3Service")
@ExtendWith(SpringExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = PriceApiApplication.class)
@EnabledIfSystemProperty(named = "execute-contract-tests", matches = "true")

ObjectMapper objectMapper = new ObjectMapper();

    @LocalServerPort
    private int randomServerPort;

    @MockBean
    private PriceEntityV2Repository priceRepositoryV2;

    @BeforeEach
    public void setupTestTarget(final PactVerificationContext context) {

        context.setTarget(new HttpTestTarget("localhost", randomServerPort));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(final PactVerificationContext context) {

        context.verifyInteraction();
    }

    

@State("Invalid header")
    public void invalidHeader() {
        final List<String> priceResultList = new ArrayList<>();
        when(priceRepositoryV2.findPricesByTypes(any(List.class), anyString(), any()))
                .thenReturn(priceResultList);
    }
}

Extension version: 0.25.9
VS Code version: Code - Insiders 1.77.0-insider (a32f38f8ae718d9c3313238173eb5f0b268222db, 2023-03-14T21:49:24.725Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.20GB free)|
|Process Argv|--crash-reporter-id a45738e8-c9c4-445a-ad0d-5fa819e01fb6|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2294)|
|Memory (System)|3.77GB (2.18GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30659908
pythonb192:30661256
funwalk2:30682974
pythonms35:30671666

```

</details>

**Comment by jdneo** [comment]
Could you provide a sample project?

**Comment by jeanbrazcosta** [comment]
Sorry, I discovered the problem was missing dependencies in my project.
