### ISSUE TITLE
Support postDebugTask property

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-java-test#1557]
Provide support for **postLaunchTask** (like [postDebugTask](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) for launch configurations) property to launch a task at the end of testing.

This attribute should be set to the name of a task specified in [tasks.json](https://code.visualstudio.com/docs/editor/tasks) (in the workspace's .vscode folder).

_NOTE_: This would be the companion to [preLaunchTask](https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration#property-details).

**Comment by jdneo** [comment]
Makes sense since we have `postDebugTask` for launch configuration. Would you like to share what kind of task you hope to run after testing?

Another problem I'm thinking is about the naming. Maybe we should call it `postDebugTask` as well to avoid introducing 'ambiguousness'

**Comment by rubensa** [comment]
No problem with the naming but I don't know why the naming **preLaunchTask** (_launch_) and then **postDebugTask** (**debug**) in the [launch attributes](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes).

In my case, In a [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) configuration, for just one workspace folder, I'm running a [docker-compose up](https://code.visualstudio.com/docs/containers/reference#_compose-task-reference) (for **ignite** and **postgres** start) for tests that needs database access.  I'd like to automatically call a docker-compose down task to tear down the databases just after the tests for that workspace folder has ended.

_NOTE_:  It's also a pitty that I need to define the corresponding empty tasks in other workspaces for the extension complaining for non existing task on those workspaces (as the [java.test.config](https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration) referencing the **preLaunchTask** is defined at [devcontainer.json](https://containers.dev/implementors/json_reference/) level), but this is a different issue.

**Comment by jdneo** [comment]
> I don't know why the naming preLaunchTask (launch) and then postDebugTask (debug) in the [launch attributes](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes).

I'm confused as well.  😂

Thanks for the information.

**Comment by jdneo** [comment]
@rubensa, I just released a pre-release `0.38.2023051002` containing this feature. Should be available in a few hours.

**Comment by rubensa** [comment]
Thanks @jdneo 
I'll try it!

**Comment by rubensa** [comment]
@jdneo I tried it and works like a charm :+1:

**Comment by jdneo** [comment]
Good to know, thank you for the update! 😁

**Comment by rubensa** [comment]
Doing some more test I found some weird behavior...

For some settings looks like it works ok but for other it can't find the corresponding **postDebugTask**.

I have a `java.test.config` with a **postDebugTask** `Teardown test-local` and I get a `Could not find the task 'Teardown test-local'.`.  I double checked that the task label matches but the result is always the same.

I have other `java.test.config` with a **postDebugTask** `Teardown test-snowflake` that is working ok.

**Comment by jdneo** [comment]
Do you have a sample to reproduce the issue?

Is it caused by scope mismatch? (User/Workspace/Workspace Folder)

**Comment by rubensa** [comment]
@jdneo some more investigations...

I I change the order that the tasks are defined in **tasks.json** the one that was working is not working anymore an the one that was not working is working now :fearful:.

For now I'm using both **settings.json** and **tasks.json** defined at **.vscode** folder level in a VSCode workspace.

**Comment by rubensa** [comment]
This is the **settings.json** I'm using
```json
{
  "java.test.config": [
    {
      "name": "test-local",
      "vmArgs": [
        "-Dspring.profiles.active=test-local"
      ],
      "envFile": "${workspaceFolder:data-api}/.devcontainer/.env.local",
      "preLaunchTask": "Setup test-local",
      "postDebugTask": "Teardown test-local"
    },
    {
      "name": "test-snowflake",
      "vmArgs": [
        "-Dspring.profiles.active=test-snowflake"
      ],
      "envFile": "${workspaceFolder:data-api}/.devcontainer/.env.local",
      "preLaunchTask": "Setup test-snowflake",
      "postDebugTask": "Teardown test-snowflake"
    }
  ]
}
```

and this is the **tasks.json**

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Setup test-local",
      "type": "docker-compose",
      "dockerCompose": {
        "projectName": "data-api",
        "up": {
          "detached": true
        },
        "files": [
          "../.devcontainer/docker-compose-test.yml"
        ]
      }
    },
    {
      "label": "Teardown test-local",
      "type": "docker-compose",
      "dockerCompose": {
        "projectName": "data-api",
        "down": {},
        "files": [
          "../.devcontainer/docker-compose-test.yml"
        ]
      }
    },
    {
      "label": "Setup test-snowflake",
      "type": "docker-compose",
      "dockerCompose": {
        "projectName": "data-api",
        "up": {
          "detached": true,
          "services": [
            "ignite-db"
          ]
        },
        "files": [
          "../.devcontainer/docker-compose-test.yml"
        ]
      }
    },
    {
      "label": "Teardown test-snowflake",
      "type": "docker-compose",
      "dockerCompose": {
        "projectName": "data-api",
        "down": {},
        "files": [
          "../.devcontainer/docker-compose-test.yml"
        ]
      }
    }
  ]
}
```

**Comment by jdneo** [comment]
Have you defined `java.test.defaultConfig`?

**Comment by rubensa** [comment]
Nope, as, If I define that, I can't select which config should be used for the execution (see: https://github.com/microsoft/vscode-java-test/issues/1556).

**Comment by jdneo** [comment]
Hmm, what the extension does is simply put the configured `postDebugTask` to the launch configuration and pass it to the debugger. The implementation of `postDebugTask` support is very similar to `preLaunchTask`. Are the pre-launch tasks work for the two test configs?

**Comment by rubensa** [comment]
Yes, both pre-launch tasks are working.  The problem is only with post-debug tasks.

**Comment by jdneo** [comment]
Interesting. What if replacing the current post debug tasks to some very simple ones, like:

```
"tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello"
        },
        {
            "label": "echo2",
            "type": "shell",
            "command": "echo Hello2"
        }
    ]
```

**Comment by rubensa** [comment]
It works with that!!

I'm really confused now...  Looks like a bug in the `docker-compose` type of tasks??

**Comment by jdneo** [comment]
> Looks like a bug in the docker-compose type of tasks??

Maybe?? 🤔

**Comment by jdneo** [comment]
If you can reproduce it using normal launch configuration with `postDebugTask` set, maybe file a ticket to the Docker extension for help?

**Comment by rubensa** [comment]
I managed to guess that the problem only happens if the **docker-compose** task definitions are equal (only changes the **label**).

If I modify, for example, the **down** content (adding a **removeOrphans** option in one of them, but not in the other), both tasks are recognized without problem.

Again I'm very confused and surprised here...

Should this be some kind of "optimization" in the [vscode-docker](https://github.com/microsoft/vscode-docker) extension (as the same with type **shell** works) that is not working right? :confused:
