### ISSUE TITLE
How to set the folder in src/main/ as testing folder?

### ISSUE THREAD

**Issue by lruihan** [microsoft/vscode-java-test#1568]
We have java repo for e2e testing, the e2e test cases are in the src/main folder. Do we have anywhere to set for this? Seems that it checks src/test/ folder for tests by default.

**Comment by jdneo** [comment]
Currently the extensions find the test according to the test source paths configured in build tool configuration: https://github.com/microsoft/vscode-java-test/wiki/FAQ#i-cannot-see-the-codelens-in-my-test-code-why

There is a feature request to customize the test set location: https://github.com/microsoft/vscode-java-test/issues/464, but it's not supported right now.

**Comment by lruihan** [comment]
It works now by changing testSourceDirectory in pom.xml, I will close the issue. Thanks a lot for your help!
