### ISSUE TITLE
Java version used to start test runs

### ISSUE THREAD

**Issue by pablocarle** [microsoft/vscode-java-test#1570]
Hi, 
This is just a question, I couldn't find this information anywhere. 
Is it possible to customize the java version used to run the tests? 
It seems to be using always `java.jdt.ls.java.home` which has a java 17 minimum requirement. We develop on 8 still and there's some code that does not run on 17 yet.

**Comment by jdneo** [comment]
The extension now has embedded jre now (for most popular platforms), so you do not need to specify `java.jdt.ls.java.home`.

You can try remove the setting `java.jdt.ls.java.home` and `java.home`, then specify your own JDK installation path via the setting `java.configuration.runtimes`. Then everything should work.

**Comment by pablocarle** [comment]
Thanks for the answer @jdneo. my current configuration is to have `java.jdt.ls.java.home` and `java.configuration.runtimes` set. However, if I understand the answer right, it ignores the `java.configuration.runtimes` if `java.jdt.ls.java.home` is set. This is not what happens with the gradle extension for example.

**Comment by jdneo** [comment]
Looking at the section here: https://github.com/microsoft/vscode-gradle#compatibility-with-the-java-language-support-extension

Looks like it is not necessary to set `java.jdt.ls.java.home` to make Gradle extension work, you can use `java.import.gradle.java.home` instead.

**Comment by pablocarle** [comment]
Thank you
