### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hexin2021** [microsoft/vscode-java-test#1571]
- Issue Type: `Performance`
- Extension Name: `vscode-java-test`
- Extension Version: `0.38.2`
- OS Version: `Darwin arm64 22.4.0`
- VS Code version: `1.78.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/t1/jtd82l2x61344jsgt72pxcp00000gn/T/vscjava.vscode-java-test-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jdneo** [comment]
Please attach the profile file.
