### ISSUE TITLE
无法运行测试文件

### ISSUE THREAD

**Issue by izilongwan** [microsoft/vscode-java-test#1577]
Type: <b>Bug</b>

![image](https://github.com/microsoft/vscode-java-test/assets/48234072/e32b9993-b856-4707-8af4-3c4c31fed93a)
<img width="650" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/48234072/e9f975b9-5a50-4810-aa03-808623bb7cc5">

Extension version: 0.39.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 20.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 21, 20|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 27686d5b-a59e-48da-9b9f-61e3336d4b9e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
pythongtdpath:30739704
pythonnosm12tcf:30757130

```

</details>

**Comment by jdneo** [comment]
The project structure displayed in the Java Projects view shows that the test code is not on the project's classpath.

Have you set it correctly?

https://github.com/microsoft/vscode-java-test/wiki/FAQ

**Comment by jdneo** [comment]
If you can share a sample project, I can take a look.

**Comment by izilongwan** [comment]
> Language Support for Java(TM) by Red Hat v1.14.0 this plugin is bad
> 
> back to this verison is ok

![image](https://github.com/microsoft/vscode-java-test/assets/48234072/00e1b974-ad7c-4cd1-a921-e922b822367f)


When I back to this version, the test classpath is exist then every thing is ok.
Test Runner for Java  v0.39.0

**Comment by izilongwan** [comment]
> If you can share a sample project, I can take a look.

Use plugin Language Support for Java(TM) by Red Hat v1.19.0 then you will reproduction

**Comment by SongYuWong** [comment]
I seem to have the same problem, but switching to the corresponding plugin version does not solve it. I switched from the IDEA development tool, and the plugin runs normally when I switch to VSCode and build a similar directory structure. Here is the address of the project I switched to, please help me take a look https://github.com/SongYuWong/songyu-java.git @jdneo

**Comment by SongYuWong** [comment]
I seem to have the same issue. Upon careful investigation, I found that ultimately it was a Maven compiler plugin configuration skipping the test code that caused it. 
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <skip>true</skip>
                </configuration>
            </plugin>
