### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by joaquimpacheco21** [microsoft/vscode-java-test#1578]
Type: <b>Bug</b>

Not working, not detecting the Extension on tests

Extension version: 0.39.0
VS Code version: Code 1.79.1 (Universal) (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:16:49.215Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|21, 62, 74|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id ae0eb0a0-53d2-4aa8-8421-22a402107ae5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
pythongtdpathcf:30739705
e440d664:30763025
pythonnosm12tcf:30765602

```

</details>

**Comment by jdneo** [comment]
Please provide detailed reproduce steps, thanks!

**Comment by jdneo** [comment]
Are you talking about the Jupyter in Python?

Or the Java testing framework JUnit Jupiter?

This extension is about Java testing support.

**Comment by joaquimpacheco21** [comment]
Java testing support.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jdneo** [comment]
Please share a sample project if you don't mind.
