### ISSUE TITLE
VsCode tests are not clickable - does not show source code

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode-java-test#1587]
Ubuntu 20.04.04 LTS
VS Code 1.79.2

I have spring and java related + gradle plugins (just the basics)

We have the laboratory glass breaker icon, running the test some of them are failing some of them are not.

I would like every node to be clicckable, not only the failed test.

1) Not sure, why i have red dots on all Test class, if one of the test is failing inside the package. It's annoying fuzzing feature, not helpfull at all.
2) Why i can't click on the certain class node? Why i can't click on test method node, if it's passed?

Totally annoying and useless. Many times i need to go to the source code panel, and look up for that class, and click,
naturally double click, which i hate the most in visual studio code.

3) It would be better, if i want not to open new tab, just make shift  click etc. on the particular file node.
Double click, many times alien from Ubuntu, does not handle properly.
(even in Nautilus, not sure what is the new name of it)

4) the spring related plugins are slow, every time when you save, it's reparsing the whole project.
(because of speed, i have choosen over Intellij, but now the advantage is partly lost)
If i'm inside a file, i don't care how the spring context is being proceed, when i debug it's more crutial.
I just want a flawless editor in this case, deferring the parse, when i open the spring configuration would be better.

5) clicking on the logs (Test Results tab), it has been cut off, no scroll bar

**Comment by jdneo** [comment]
> Not sure, why i have red dots on all Test class.

Could you share some screenshots or videos to help me understand your problem? Thanks!

> Why i can't click on the certain class node? Why i can't click on test method node, if it's passed?
> It would be better, if i want not to open new tab, just make shift click etc

The behavior is determined by VS Code. This extension is just using the API to provide test items. But if you want to open a text method/class, you can single click on this shortcut
![image](https://github.com/microsoft/vscode-java-test/assets/6193897/6f580376-4dbc-4cc1-b630-096ea6c26e55)

> the spring related plugins are slow

Suggest to report problems to the related extension repo, for example: https://github.com/spring-projects/sts4/tree/main/vscode-extensions

> clicking on the logs (Test Results tab), it has been cut off, no scroll bar

The Result tab is now just used for logging purpose. We can definitely enhance it. Do you mean the horizontal scroll bar?

**Comment by fssrepository** [comment]
1) red dots are something spring context related, however the other classes are unrelated, shouldn't red dot the whole package. I'm not sure how the issues occur, but i have attached a screenshot, which kind of problem can cause it.
![image](https://github.com/microsoft/vscode-java-test/assets/45578746/d4dba7c4-5cb6-4d29-b68d-1391d2088a2e)

2) I have seen clickable trees at GitLens plugin, hence not sure, why it can't be done.
a) Not sure whether you can click separately on the arrow of the particular class,
but you can remove the icon from the test methods. If someone is clicking on the particular node, expects
that the file opens at that method. The icon is really unexpected, not intuitive.
b) I think you can wire up leaf node to trigger a file open. The third icon is superflous.

5) cut off, no scroll bar, however, if i select the long rows, and copy over to the text editor, i saw the content.
![image](https://github.com/microsoft/vscode-java-test/assets/45578746/e4637b2a-ff9c-4015-a198-83a53413f8a8)

**Comment by jdneo** [comment]
> red dots are something spring context related, however the other classes are unrelated, shouldn't red dot the whole package. I'm not sure how the issues occur, but i have attached a screenshot, which kind of problem can cause it.

Is this caused by wrong project configuration loaded? For example, the extension loadsthe  prod config instead of the one for test?

##### Regarding to point 2 ~ 4

To share more background, the testing tree view you've seen is different from the tree view of GitLens. In short, the testing UI is mostly controlled by VS Code. This extension is only responsible for providing test items. And VS Code will display them. So for point 2 ~ 4, I suggest to filing issues at VS Code repo. As an extension, nothing we can do here, sorry.
