### ISSUE TITLE
Missing release asset file

### ISSUE THREAD

**Issue by williamboman** [microsoft/vscode-java-test#1594]
Hello! This software is being distributed to Neovim users via https://github.com/mason-org/mason-registry by pulling the release assets. The latest 0.39.1 release seems to be missing the asset file and I'm wondering if this was intentional. If it is intentional I'd much appreciate any guidance for how to package this outside of VSCode.

##### Current Result

No asset file available for release 0.39.1.

##### Expected Result

An asset file to be present as with prior releases.

##### Additional Informations

**Comment by jdneo** [comment]
Hi @williamboman,

You can build by your own and it's very simple. You can refer to the GitHub Action yaml: https://github.com/microsoft/vscode-java-test/blob/main/.github/workflows/build.yml.

Feel free to let me know if you meet any problems.

**Comment by williamboman** [comment]
Alright, thanks! Do I understand things correctly that assets won't be provided via GitHub releases going forward?

**Comment by nickzhums** [comment]
Correct. Please use the provided steps to generate the assets, and feel free to let us know if you have any questions
