### ISSUE TITLE
If I have a Infinite cycle in the project, how can I stop this test?

### ISSUE THREAD

**Issue by AirBashX** [microsoft/vscode-java-test#1596]
How do I stop if there is a Infinite loop while junit is running?

**Comment by AirBashX** [comment]
None of Ctrl+F2 and Shift+F5 did not respond

**Comment by jdneo** [comment]
Have you tried this button?
![image](https://github.com/microsoft/vscode-java-test/assets/6193897/597971b8-61a8-45b7-9c1a-bb43d0088e3f)

**Comment by AirBashX** [comment]
I didn't find this page, where is it?
![vscode](https://github.com/microsoft/vscode-java-test/assets/40747740/403cb40e-0dce-4498-875c-7ec9c671d13f)


> 你试过这个按钮吗？ ![image](https://user-images.githubusercontent.com/6193897/260339639-597971b8-61a8-45b7-9c1a-bb43d0088e3f.png)

**Comment by jdneo** [comment]
It's here

![image](https://github.com/microsoft/vscode-java-test/assets/6193897/47ccf758-33f9-4638-b406-783e144d2c5c)


What's your VS Code version, and you test runner extension 's version?

**Comment by AirBashX** [comment]
vscode:1.81.1
runner:0.39.1
After testing, I found the problem.This is caused by a plug -in called [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner).When I stop this plug -in, the problem is solved

When I enable this plug -in, I will not be able to stop the infinite cycle, the CPU reaches 100 %, and VSCODE can hardly perform any operation until the software stops running.


> 它在这里
> 
> ![图像](https://user-images.githubusercontent.com/6193897/260346885-47ccf758-33f9-4638-b406-783e144d2c5c.png)
> 
> 您的 VS Code 版本是什么？您测试 runner extension 的版本是什么？

**Comment by jdneo** [comment]
I see. BTW, if you want to do some serious coding stuff using Java in VS Code, I recommend leveraging the extensions contained in the `Extension Pack for Java`.

**Comment by AirBashX** [comment]
> I see. BTW, if you want to do some serious coding stuff using Java in VS Code, I recommend leveraging the extensions contained in the `Extension Pack for Java`.

Thank you. Actually, I have been using the "Java Extension Pack" and only using "code runner" to compile JavaScript. I am testing Java and I'm not using this extension, but enabling it causes issues with "Test Runner for Java." I believe there might be compatibility problems between the two.
