### ISSUE TITLE
Testing view is not opened when running the test

### ISSUE THREAD

**Issue by anazar2001** [microsoft/vscode-java-test#1597]
<img width="1728" alt="Screenshot 2023-08-21 at 20 47 58" src="https://github.com/microsoft/vscode-java-test/assets/13858727/7d3cee45-0675-4e7f-9986-e78568f17b32">
Type: <b>Bug</b>

If Explorer view or any other tab is opened - run any java test. I would expect Testing view to be opened as it worked before. Instead the Test Results is getting in focus in the bottom of the screen. It has Test run panel which basically duplicates what is normally displayed in the Testing view.

Could you please take a look.

Thanks,
Andrei.

Extension version: 0.39.0
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 9, 8|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id ca77d4d7-a862-4b3b-a666-ca0626efb457|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by jdneo** [comment]
What's the value of your `testing.openTesting` setting?

**Comment by anazar2001** [comment]
openOnTestStart

**Comment by jdneo** [comment]
It's an upstream issue, see: https://github.com/microsoft/vscode/issues/191272

**Comment by jdneo** [comment]
Close since it's fixed from upstream. See: https://github.com/microsoft/vscode/pull/192237
