### ISSUE TITLE
Icon order mismatch in test explorer and output

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1598]
The icons of go to test, run and debug are in different order. It breaks habit.. 

test explorer
![image](https://github.com/microsoft/vscode-java-test/assets/76812421/25cbce47-4044-41b5-a9dc-8a3db204d2ac)

Test output pane
![image](https://github.com/microsoft/vscode-java-test/assets/76812421/61f035a8-94ec-4260-a5ac-a71a034de15f)

**Comment by jdneo** [comment]
Reported to upstream https://github.com/microsoft/vscode/issues/191182

**Comment by jdneo** [comment]
Fixed in upstream: https://github.com/microsoft/vscode/pull/192343
