### ISSUE TITLE
run issue

### ISSUE THREAD

**Issue by SOUMYAGURRALA** [microsoft/vscode-java-test#1599]
Type: <b>Feature Request</b>

i am unable to run my code

Extension version: 0.39.1
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by jdneo** [comment]
Please provide detailed reproduce steps
