### ISSUE TITLE
Provide Flag for default Test Configuration

### ISSUE THREAD

**Issue by falco467** [Microsoft/vscode-java-test#160]
Test Configuration works great!
But as far as I can tell a simple "Run Test" will run without any configuration.

If we could set one Configuration as default for a project, so it is used when I just press "Run Test" would be a nice time-saver.

**Comment by ansyral** [comment]
@falco467 simple "Run Test" would run with working directory pointing to current workspace folder, no other configurations except for this. Do you mean that you want to be able to configure a default configuration from your configuration file?

**Comment by falco467** [comment]
Yes! If one configuration could be set as default that would be a nice feature.

**Comment by ansyral** [comment]
@falco467 I would add a `default` section in the config, and you might need to fill it in to make "Run test" run with the specified default config.

**Comment by ansyral** [comment]
@psychelzh thanks for the suggestion, we would add some documentation later.
