### ISSUE TITLE
JDK mismatch from one used to compile and one used to run compiled tests 

### ISSUE THREAD

**Issue by Lassebq** [microsoft/vscode-java-test#1600]
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version number in .class file
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:268)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
```
Removing
```json
    {
      "name": "J2SE-1.5",
      "path": "/usr/lib/jvm/jdk1.5.0_22",
      "default": false
    },
```
from "java.configuration.runtimes" seems to fix the issue, however I still need this JRE/JDK to be accessible.
I'm running a junit test in a gradle project.
Gradle project has `sourceCompatibility` set to 1.5
I assume it uses Java 8 to compile and it doesn't properly set target version in `javac`, then tries to run it with java 5 and fails

**Comment by Lassebq** [comment]
Is there any temporary fix I can use? Such as setting preferred jdk for tests, or force jdk 5 to not be used

**Comment by jdneo** [comment]
Could you share a sample project for your issue?

**Comment by Lassebq** [comment]
It happens with tests which contain almost nothing
This is the project by the way: https://github.com/MCPHackers/LaunchWrapper
What I could find was that changing build.gradle to use 1.8 as target and source version version fixes it, assuming because java 8 is my default gradle jvm (it's set in "java.import.gradle.java.home" in settings.json)

**Comment by Lassebq** [comment]
```json
"java.configuration.runtimes": [
    {
      "name": "J2SE-1.5",
      "path": "/usr/lib/jvm/jdk1.5.0_22",
      "default": false
    },
    {
      "name": "JavaSE-1.8",
      "path": "/usr/lib/jvm/java-8-openjdk",
      "default": false
    },
    {
      "name": "JavaSE-17",
      "path": "/usr/lib/jvm/java-17-openjdk",
      "default": false
    },
    {
      "name": "JavaSE-20",
      "path": "/usr/lib/jvm/java-20-openjdk",
      "default": true
    }
  ]
  ```
  Also, here's a complete list of JVMs in my settings.json

**Comment by jdneo** [comment]
I see.

Looks like when you have

```
{
      "name": "J2SE-1.5",
      "path": "/usr/lib/jvm/jdk1.5.0_22",
      "default": false
    },
```

set, Java Language Server will pick that JDK to be your project jdk since that's a perfect match according to the `source/target compatibility` set in build.gradle.

But JUnit 5 needs at least java 1.8 as the runtime, so `UnsupportedClassVersionError` happens.

A work around could be:

1. Add `"java.import.generatesMetadataFilesAtProjectRoot": true` to your WORKSPACE level setting. Please do not change it in the USER level, because when the setting is enabled, it will generate metadata files in your project root.
2. Reload your vscode
3. After project is opened, you will see a .classpath file
4. Open `.classpath`
5. Change
```
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/J2SE-1.5/"/>
```

to 

```
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
```

**Comment by Lassebq** [comment]
Thank you, that solves it.
Also, note that I have JUnit 4.12 specified in build.gradle, not JUnit 5, and from what I know gradle would not include it if it wasn't compatible with target java version
