### ISSUE TITLE
Q: how to get test results output in integrated terminal or debug console ? 

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1601]
- The performance is not satisfactory for lots of text in the test results output.
- The link detection is also poor in test results pane.

Yet it's the only place to find stacktrace and assertion errors. I don't use test output peek view.

Is there a way to redirect the output in debug console or terminal?

 Expose lists of tests to be usable in inputs of task.json #1405  is still  desired for me.

Here's a test that shows perf issues.

```
import static org.junit.Assert.assertEquals;

import java.util.stream.IntStream;
import java.util.stream.Stream;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

public class BaarFTest {

    static Stream<Integer> filler() {
        return IntStream.range(0, 100).mapToObj(i -> i);
    }

    @ParameterizedTest
    @MethodSource("filler")
    void test(int a) {
        assertEquals(1, 2);
    }

}

```

**Comment by jdneo** [comment]
Could you give more detail about `The performance is not satisfactory for parameterized tests in the test results output.`?

**Comment by matter-it-does** [comment]
Scrolling it laggy with lots of output.

**Comment by jdneo** [comment]
> Scrolling is laggy with lots of output.

Could you give some more details? Like a video, your vscode version and details of your machine.

Looks like this issue should be handled by VS Code team, I can help you report this to them if those information is available.

**Comment by matter-it-does** [comment]
there you go.
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
OS: Darwin x64 20.5.0

Machine is macbook pro 16" intel 2.6 GHz 6-Core Intel Core i7 16 GB 2667 MHz DDR4


https://github.com/microsoft/vscode-java-test/assets/76812421/de44873b-ea58-474b-b03e-d03bb1dc27fa

**Comment by jdneo** [comment]
Tried your snippet on my windows and I did not observe lags.

https://github.com/microsoft/vscode-java-test/assets/6193897/e6a4a226-ecc6-4749-a7d1-ba3350260f55

**Comment by matter-it-does** [comment]
@jdneo yeah the performance is better in this release. 

Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.5.0

**Comment by jdneo** [comment]
Thank you for the update.
