### ISSUE TITLE
miss shortcut button of Test Runner for Java

### ISSUE THREAD

**Issue by meiliangdeng** [microsoft/vscode-java-test#1604]
> [provide a description of the issue]
> 
> ##### Environment
> * Operating System: Mac OS: 12.4
> * JDK version: "java.jdt.ls.java.home": jdk-17.0.3.1.jdk
> * Visual Studio Code version: 1.82.2
> * Java extension version: Language Support for Java(TM) by Red Hat
>   v1.23.2023091604 , Test Runner for Java v0.39.1
> 
> ##### Steps To Reproduce
> 1. open any java project(eg:maven Project)
> 2. coding any unit case
> 
> [Please attach a sample project reproducing the error] [Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
> 
> ##### Current Result
> don`t find The Test Runner for Java extension shortcuts button after coding any unit case <img alt="image" width="574" src="https://user-images.githubusercontent.com/7776627/268502483-b748feaf-0bd8-4ab5-9c72-43a0f32f2bd6.png">
> 
> ##### Expected Result
> show shortcuts button, following: <img alt="image" width="286" src="https://user-images.githubusercontent.com/7776627/268502539-aae6a8a8-9756-480f-b50e-39b5fac9de1b.png">
> 
> ##### Additional Informations
> The previous version of vscode or Java extension had this shortcut button, but it was not available in the Language Support for Java(TM) by Red Hat v1.23.2023091604 version

**Comment by jdneo** [comment]
Hi @meiliangdeng, some questions that need your help to confirm:

1. Will the shortcut appear if you close the file and re-open it?
2. Does the your project appear in the Java Projects View? (F1 > View: Focus on Java Projects View)

**Comment by meiliangdeng** [comment]
1. It has never appeared, even after re-open the file or restarting vscode
2. should be 'Explorer: Focus on Java Projects View', i have try to do, won't appear either,following:
<img width="1203" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/7776627/fc81ed6e-c737-4331-80ae-f15126cff864">

**Comment by jdneo** [comment]
Ok, is this project sharable? If you don't mind, please share it and I can open it on my side to see what happens.

**Comment by gustavosimon** [comment]
Hello @meiliangdeng and @jdneo! Hope you're well.

I had this same issue right now. The shortcut button didn't appear to me.

I solved this issue downgrading Language Support for Java(TM) by Red Hat to v1.22.1.

**Comment by meiliangdeng** [comment]
yes, for any java project, the release version is fine, but the pre-release version is not.

Language Support for Java(TM) by Red Hat
v1.23.2023091604、v1.23.2023091904 is not ok

**Comment by jdneo** [comment]
Thank you all, I can reproduce this issue with the provided information. Looking into it right now...

**Comment by jdneo** [comment]
[vscode-java-test-0.39.2023092012.vsix.zip](https://github.com/microsoft/vscode-java-test/files/12679118/vscode-java-test-0.39.2023092012.vsix.zip)
Please use this build as a workaround now if it blocks you. I'll schedule a release recently.

**Comment by jdneo** [comment]
Update:

Pre-release 0.39.2023092208 with the fix of this issue is published.

A stable release is planned in next week.
