### ISSUE TITLE
The working directory is not set to folder opened in VS Code when it's unmanaged folder

### ISSUE THREAD

**Issue by robaho** [microsoft/vscode-java-test#1606]
The 'test runner' correctly finds the tests in all of the subprojects, and shows them grouped by subproject.

The issue is that when run, the working directly is set to the top-level workspaceFolder, not the subject folder. When running the tests with gradle, the working directory is the top of the subproject.

I would try to create a test config, but I would need a test config for each project in order to set workingDirectory correctly - but then I would also need to somehow configure which test config to use for each subproject.

It seems that when subprojects are being used, something like:

{
   workingFolder = "${subprojectFolder}"
}

is necessary.

**Comment by jdneo** [comment]
I tried running a test case written like this:

```java
@Test
void test() {
    System.out.println(System.getProperty("user.dir"));
}
```

And it prints the directory of the sub-project, not the root project. Could you share a sample project and your VS Code Java settings?

**Comment by robaho** [comment]
Attaching a full project that demonstrates the problem.

Here are some screenshots as well:

With vscode test runner:

![image](https://github.com/microsoft/vscode-java-test/assets/4958833/b96c0e7c-52ca-4983-9d8e-ffca144560d3)

and running via the gradle runner:

![image](https://github.com/microsoft/vscode-java-test/assets/4958833/63d9195e-62b8-4c31-80e0-a7792634a5be)

and the project

[mytest.zip](https://github.com/microsoft/vscode-java-test/files/12673735/mytest.zip)

**Comment by jdneo** [comment]
What if you do this:

1. Close the workspace in VS Code
2. Remove all the .classpath, .project. .settings/ in your project folder, include the root folder and the subproject folder
3. Reopen the workspace

I tried on my Windows and the path is correct.
![image](https://github.com/microsoft/vscode-java-test/assets/6193897/77c41437-a9ae-44a7-8fe8-fb7e13053c0a)

**Comment by robaho** [comment]
So you’re saying this worked for you? This is a brand new project. How does deleting all of these files help - the grade plugin will recreate them.

**Comment by jdneo** [comment]
It's not necessarily caused by them, I was just guessing.

I did one more try on my Mac, this time I directly open the attached project without modifying anything, and the path is correct.

<img width="979" alt="Screenshot 2023-09-21 at 10 17 12" src="https://github.com/microsoft/vscode-java-test/assets/6193897/89ad70dc-c1c6-4178-99e6-11eb42306a45">

Could you share your vscode settings? Did you set `"workingDirectory": "${workspaceFolder}"` in `java.test.config`?

**Comment by robaho** [comment]
When I remove the workingDirectory from java.test.config it works as expected. If you look at this issue, that item in the workspace is added as part of he default https://github.com/microsoft/vscode-java-test/issues/797#issuecomment-550098908

It seems this should not be part of the default configuration.

**Comment by robaho** [comment]
The problem is if I remove that configuration, than non-Gradle projects have the wrong working directory. I can add it as a workspace setting, but it seems this should just work. Maybe allow the setting, but when it's a gradle project ignore it.

**Comment by jdneo** [comment]
> The problem is if I remove that configuration, then non-Gradle projects have the wrong working directory.

By default, the working directory should be the directory of the project. Could you give some more information about the projects that are not working on your side?

**Comment by robaho** [comment]
I think I’ve explained it. If you have that setting in there then it doesn’t work with gradle sub projects. If you remove it then non-gradle projects have the wrong directory.

**Comment by jdneo** [comment]
Sorry, I cannot reproduce it, below is a screenshot for a multi-module Maven project.

![image](https://github.com/microsoft/vscode-java-test/assets/6193897/0db6d4e4-e432-483e-8c8d-dab73c7e0beb)

I've left the global setting and workspace setting empty.

**Comment by robaho** [comment]
Do not use maven. It needs to be an “unmanaged  project”

**Comment by jdneo** [comment]
I see. I can repro this issue for an “unmanaged project”.

Root cause is that the real project location of the “unmanaged project” is located in a 'hidden' place - the extension workspace.

We could fix this issue by add some handling logic for the unmanaged project. To set the working directory to the folder opened in VS Code, since that is the project root from users' perspective.

**Comment by robaho** [comment]
That makes sense to me as a better default.

**Comment by jdneo** [comment]
This private build should fix the issue
[vscode-java-test-0.40.2023092608.vsix.zip](https://github.com/microsoft/vscode-java-test/files/12724872/vscode-java-test-0.40.2023092608.vsix.zip)

@robaho, it would be great if you can help check if it solves your problem.
