### ISSUE TITLE
JUnit5 DynamicContainer are not working

### ISSUE THREAD

**Issue by mapio** [microsoft/vscode-java-test#1617]
With this test

```
@TestFactory
public Stream<DynamicContainer> testContainers() {
  return Stream.of(dynamicContainer("Container", List.of(
    dynamicTest("Test", () -> {assertTrue(false);})
  )));
}
```

Gradle outputs the result, but VSCode runs the test and reports just an empty bullet, not picking the failure.

**Comment by jdneo** [comment]
Thank you for reporting this bug.

Though it's not related with #1603, but this reflects some 'bad' design/implementation when handling the invocation/dynamic tests.

Some refactoring is needed.

**Comment by jdneo** [comment]
Please use this private build to unblock yourself:
[vscode-java-test-0.40.2023092907.vsix.zip](https://github.com/microsoft/vscode-java-test/files/12762106/vscode-java-test-0.40.2023092907.vsix.zip)

The PR still needs more days (~ 1 week) to be merged due to the holiday here. If you find any issue using the private bit, please let me know.

**Comment by mapio** [comment]
I've tested it. It's true that now tests in a container are picked up. But test reports do not show any form of hierarchy.

According to [this post](https://medium.com/@BillyKorando/dynamic-testing-in-junit-5-a-practical-guide-a57e3ceaa240) for example it should go from ![flat](https://miro.medium.com/v2/resize:fit:800/format:webp/1*5qnrV0HkhtRkhcWBdvdTzA.png) to ![tree-like](https://miro.medium.com/v2/resize:fit:800/format:webp/1*bbq-bbxQACVIrHNywXbYmg.png).

**Comment by jdneo** [comment]
What did you see from your side?

![image](https://github.com/microsoft/vscode-java-test/assets/6193897/7907d9f2-b44e-43a7-b09f-0d575955c8c2)

**Comment by mapio** [comment]
I'm sorry but I can't reproduce the example of the Medium post.

With this code:

```
import static org.junit.jupiter.api.DynamicContainer.dynamicContainer;
import static org.junit.jupiter.api.DynamicTest.dynamicTest;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.junit.jupiter.api.DynamicContainer;
import org.junit.jupiter.api.TestFactory;

public class TestContainers {

	@TestFactory
	Collection<DynamicContainer> testContainer() {
    List<DynamicContainer> containers = new ArrayList<>();
    containers.add(
      dynamicContainer("First Container", List.of(
        dynamicTest("First test of first container", () -> {}),
        dynamicTest("Second test of first container", () -> {})
      ))
    );
    containers.add(
      dynamicContainer("Second Container", List.of(
        dynamicTest("First test of second container", () -> {}),
        dynamicTest("Second test of second container", () -> {})
      ))
    );
    return containers;
  }
}
```

I get 

```
TestContainers > testContainer() > First Container > TestContainers.First test of first container PASSED
TestContainers > testContainer() > First Container > TestContainers.Second test of first container PASSED
TestContainers > testContainer() > Second Container > TestContainers.First test of second container PASSED
TestContainers > testContainer() > Second Container > TestContainers.Second test of second container PASSED
```

as `gradle test`output, but this in the sidebar

![image](https://github.com/microsoft/vscode-java-test/assets/612826/f8629198-42ee-4108-bf5d-540f33a7b111)

So apparently the two containers are there, but are not viewable.

**Comment by mapio** [comment]
Ahah, my fault. I was looking at the "Testing result" panel, not at the testing sidebar. There the containers show up!

![image](https://github.com/microsoft/vscode-java-test/assets/612826/6401e97d-0ee6-495d-8860-e4b8eafd2809)

So now the question is: why the UI of the panel and sidebar are different?

**Comment by jdneo** [comment]
My understanding is that the Test Explorer (sidebar) is used to show all the tests in the workspace. While the Test Result (panel) is used to show the tests of each execution.

We have an issue about improve the Test Result content: https://github.com/microsoft/vscode-java-test/issues/1588

**Comment by mapio** [comment]
The explanation makes a lot of sense! Thank you for referring me to the other issue. You are very helpful, thank you for your time and work!
