### ISSUE TITLE
VS Code in the browser: Test Runner fails to run the first time, but runs fine the second time

### ISSUE THREAD

**Issue by firasm** [microsoft/vscode-java-test#1650]
Hello,

My colleagues and I are trying to use the "Test Runner for Java" extension in a workspace using VS Code in the browser (specifically the [code-server](https://github.com/coder/code-server) project). 

We are trying to troubleshoot a really strange issue that only shows up in the cloud, and not when trying to run things locally.

[Here is a very very simple Java project](https://github.com/firasm/reprex_java_tests) that when it's run in the browser, gives a `Class not found model.SampleTest` error.

<img width="1146" alt="Screenshot 2024-01-18 at 8 56 46 PM" src="https://github.com/microsoft/vscode-java-test/assets/2507459/68e11801-9c28-48e1-ae46-2aeb3f1833b8">

However, when you do nothing else except just run the test one more time, it works just fine:

<img width="1272" alt="Screenshot 2024-01-18 at 8 57 03 PM" src="https://github.com/microsoft/vscode-java-test/assets/2507459/ae65d0eb-7663-48ac-b929-f3a717337908">

This happens for **every** project that's run in the cloud this way, so we are nearly 100% sure that it's got something to do with being execute remotely. The stack trace seems useful, but it's not something that gives me any insight so I thought I'd post here to ask for help in troubleshooting!

```
Class not found model.ProjectInNeedTest
java.lang.ClassNotFoundException: model.ProjectInNeedTest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
BuiltinClassLoader.java:581
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
ClassLoaders.java:178
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
ClassLoader.java:527
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:766)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:490)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

I'll be cross-posting this in the code-server project to get some more eyes on it...

**Comment by jdneo** [comment]
What if you run it in GitHub Codespaces, will the same error happens for the first test execution?

**Comment by firasm** [comment]
I just tried it - and **no, I cannot** reproduce it in GitHub Codespaces, it runs fine the first time.

<img width="1071" alt="Screenshot 2024-01-18 at 11 32 57 PM" src="https://github.com/microsoft/vscode-java-test/assets/2507459/633e2bcd-eaf5-4b6d-9ea6-4bbc0c50d270">

I assume this means the issue is likely somewhere in `code-server` configuration?

**Comment by jdneo** [comment]
I'm not familiar with Code Server, seems like yes.

Maybe some filesystem issue that the .class file is not discovered? I dont know...

**Comment by firasm** [comment]
Fair enough - I'll close this for now and hope someone there can help. Thanks for the fast reply!
