### ISSUE TITLE
Could not connect to:  : 55899  java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by AYiXi** [microsoft/vscode-java-test#1653]
When first time I debug java test file, it's ok
<img width="2080" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/28703786/0768622b-2b67-4789-85a6-eeab6dc41331">

but when I restart the debugger
<img width="856" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/28703786/53358ccf-a685-4037-b3c3-4177be3c93a3">

 It always `Connection refused`
<img width="2080" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/28703786/f32a5345-5ba5-47c9-9eab-11291d7f850a">

**Comment by jdneo** [comment]
Thank you for reporting the error.

Duplicated with https://github.com/microsoft/vscode-java-test/issues/1561
