### ISSUE TITLE
Funky output in VS Code test output only

### ISSUE THREAD

**Issue by smil2k** [microsoft/vscode-java-test#1658]
Switching tabs while running turns the log into this funly one:
![funkyfonts](https://github.com/microsoft/vscode-java-test/assets/2590036/d9111452-ad65-4535-8551-c210e94d770e)

Sometimes only the capital letters of the stack is effected:
![image](https://github.com/microsoft/vscode-java-test/assets/2590036/1c251ddb-53a5-4bbb-b30a-a542087fe208)

It is not a font issue I suppose: 
![select](https://github.com/microsoft/vscode-java-test/assets/2590036/dd3b4e41-adad-4ad0-b610-29a5bc808d80)

If I take this selection to the clipboard:
![image](https://github.com/microsoft/vscode-java-test/assets/2590036/eb292484-6562-468e-a9f7-d53565b040bf)

```
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
The data seems to be right.

I did not see this problem in other panels, only the test output.

**Comment by jdneo** [comment]
Duplicated with https://github.com/microsoft/vscode-java-test/issues/1618

It's an upstream issue of VS Code: https://github.com/microsoft/vscode/issues/194156
