### ISSUE TITLE
Tests won't show up if java file is not opened and refreshing test runner makes vacode java extension crashed

### ISSUE THREAD

**Issue by v-yuyul** [microsoft/vscode-java-test#1660]
**Environment:**

- VS Code Version: Github Codespace
- Vscode java Version: 1.27.0
- Test runner version: 0.40.1
- JDK Type & Version: java 21
- OS Type & Version: windows

**Step to Reproduce:**
1. Clone [https://github.com/junit-team/junit5-samples](https://github.com/junit-team/junit5-samples/tree/master/junit5-migration-maven) to a folder of codespace, like /workspaces
2. Open junit5-samples/junit5-migration-maven project
3. Go to test runner explorer

**Expected Behavior:**
Can always show all tests in the project.

**Actual Behavior:**
1. If the java files are not opened, the tests in it won't show up.
2. Open a java file > Refresh test runner explorer 3-4 time, then vscode java extension will be crashed with the exception in the log files.
Note: This issue is unstable.

[server.txt](https://github.com/microsoft/vscode-java-test/files/14155521/server.txt)

[client.txt](https://github.com/microsoft/vscode-java-test/files/14123522/client.txt)
![image](https://github.com/microsoft/vscode-java-test/assets/31497677/ce8cccec-c971-480a-af98-da59abc18d91)

**Comment by jdneo** [comment]
Duplicated with https://github.com/microsoft/vscode-java-test/issues/1399
