### ISSUE TITLE
Peek view for failed JUnit test has two views randomly

### ISSUE THREAD

**Issue by Ao-Last** [microsoft/vscode-java-test#1661]
To reproduce,

1. Using JUnit to perform a test with assert statement. E.g. assertEquals(expected_string, actual_stirng)
2. If the test failed, the plugin would show a peek view for comparison between the expected and actual.
<img width="1301" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/63785048/a30b1eb7-be75-473a-8e93-72f0b95a3456">

4. If run the test again, the comparison view is broken.
<img width="1239" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/63785048/5196877c-92b0-45a2-866f-5ff8b42fd91a">

5. Close the popup peek view, and click the red error message nearby, the view is a perfect comparison view.

**Comment by jdneo** [comment]
Could you share a sample code for this issue?

**Comment by Ao-Last** [comment]
View1:
<img width="1098" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/63785048/a5049b2d-52c8-453c-a36a-8254daabc46a">

close the peek view and then click the red character could lead to view2.

View2:
<img width="1192" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/63785048/dcd2c0af-8c9c-4436-affa-9e0e60adbef4">

I found that with a long string that cannot be displayed in the screen would increase the probability triggering the bug.

Source code:
```java
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test_gradle;

public class App {
    public String getGreeting() {
        return "Hello World!jslkfajslkdfjaiosdjfalskdjfklajsdlkfjasiodfjasldkfj;lksdjvm,xchiugbhydafighdansk,vjhnioasdyifpujsldkfjnfcl;asdjfhiosja;fjasdikfjp9asiohjfncli;sdafi9opshalfl;asjdfkljasiopfjasolifjsdlkfcj;aiopdjflisdjfcklsdjnviogasyhgioasdjnlkhnsdaoiyhasiodjflksdjf9iajhasldfjnclksdjha9ioshjuflaidjflask";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
```

Test code:
```java
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test_gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("Wrong", classUnderTest.getGreeting());
    }
}
```

**Comment by jdneo** [comment]
Ok, I guess I got your point.

So, there are two different kinds of different peek views:
- The raw stacktrace view
- The diff view (when it's available)

You can switch between them in the test history

![image](https://github.com/microsoft/vscode-java-test/assets/6193897/6b1448ae-61e6-446b-a7f2-4067d28d7e22)

**Comment by Ao-Last** [comment]
Yes. One of the view will popup as the peek view. Is it undefined?

**Comment by jdneo** [comment]
On my machine it always shows the diff view. No random behavior is observed.

**Comment by Ao-Last** [comment]
Click the two "run" button near the method signature multiple times (maybe randomly), the random behavior happened. 
<img width="1358" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/63785048/79dcd7ec-4092-4be0-83cd-b0b220594731">
