### ISSUE TITLE
"Test Results" panel showing empty spaces between letters

### ISSUE THREAD

**Issue by fbarbari** [microsoft/vscode-java-test#1663]
When running a specific single test (like the following picture), the output in the "Test Results" panel is very weird.
![image](https://github.com/microsoft/vscode-java-test/assets/121092059/99bf44c5-6412-411f-90c0-dd4878013649)

![image](https://github.com/microsoft/vscode-java-test/assets/121092059/2fce575d-c2ce-451c-9eba-c7b0a6dff2b7)

**Comment by ReubenFrankel** [comment]
See #1618 and #1658

**Comment by jdneo** [comment]
duplicated with https://github.com/microsoft/vscode-java-test/issues/1618
