### ISSUE TITLE
Support test coverage for unmanaged folder projects

### ISSUE THREAD

**Issue by jeuzee** [microsoft/vscode-java-test#1671]
I installed VSCode Insiders and all necessary extensions, also I have latest JDK installed, but when I run Tests with coverage it goes through all the tests, but Test Coverage field is completely empty, why/how do I fix that?

**Comment by jdneo** [comment]
There are a couple of updates for the test coverage feature from VS Code. Do you still have this issue now?

If yes, would you mind sharing more information please?

**Comment by jeuzee** [comment]
> There are a couple of updates for the test coverage feature from VS Code. Do you still have this issue now?
> 
> If yes, would you mind sharing more information please? like some screenshots. gifs, sample project...

First of all, I updated VSCode Insiders to latest version:
![Screenshot_1](https://github.com/microsoft/vscode-java-test/assets/62665166/16010daa-5acc-4215-a1ae-dd697ad3d2d6)

I also have all extensions installed in pre-release version:
![Screenshot_2](https://github.com/microsoft/vscode-java-test/assets/62665166/e1da72dc-0bf5-4491-a6dd-e8fe8500f876)

And when I click "Run tests with coverage" I get no coverage:
![Screenshot_3](https://github.com/microsoft/vscode-java-test/assets/62665166/5edee005-8e8b-4052-ab27-a12ef0d9c1e1)

**Comment by jdneo** [comment]
Would you mind sharing a sample project for this issue?

**Comment by jeuzee** [comment]
> Would you mind sharing a sample project for this issue?

No, unfortunately I can't.

**Comment by jdneo** [comment]
Is there any errors in the server log? (Trigger `Java: Open Java Language Server log file`)

**Comment by jeuzee** [comment]
> Is there any errors in the server log? (Trigger `Java: Open Java Language Server log file`)

No, I can't find any error, maybe if you could specify what exactly error might be.

**Comment by jeuzee** [comment]
Actually, I can share another project:
[test.zip](https://github.com/microsoft/vscode-java-test/files/14635791/test.zip)

**Comment by jdneo** [comment]
I see.

Your project is an unmanaged Folder project (without build tool like Maven/Gradle/...), right?

It's not supported right now. But I'll check how we can support it.

Thanks for reporting the issue!

**Comment by jdneo** [comment]
@jeuzee

Made some progress. Would you mind try this vsix, should work now:

[vscode-java-test-0.40.2024031906.vsix.zip](https://github.com/microsoft/vscode-java-test/files/14646494/vscode-java-test-0.40.2024031906.vsix.zip)

**Comment by jeuzee** [comment]
> @jeuzee
> 
> Made some progress. Would you mind try this vsix, should work now:
> 
> [vscode-java-test-0.40.2024031906.vsix.zip](https://github.com/microsoft/vscode-java-test/files/14646494/vscode-java-test-0.40.2024031906.vsix.zip)

Umm, where do I suppose to put that file? And yeah, I am not using Maven/Gradle currently.

**Comment by jdneo** [comment]
You need to unzip it, and then manually install it:

![image](https://github.com/microsoft/vscode-java-test/assets/6193897/7cb328d4-e679-4e10-a5b2-f13a26a02c4e)

**Comment by jeuzee** [comment]
Yes, now its working, thank you!

**Comment by jdneo** [comment]
Fixed by https://github.com/microsoft/vscode-java-test/commit/a4a28c8615de7069ffa6d658b13ba71d1f11389f
