### ISSUE TITLE
Inline code coverage disappeared on latest pre-release

### ISSUE THREAD

**Issue by heruan** [microsoft/vscode-java-test#1674]
With the latest pre-release of Java Test (v0.40.2024030709) in Code Insiders (1.88.0-insider), I cannot see inline coverage in the editor. Until last week a I was able to toggle inline coverage in the editor hovering the cursor on the line numbers, but now that's gone. Has it moved elsewhere? I cannot find anything in command either.

![Screenshot 2024-03-18 at 12 28 12](https://github.com/microsoft/vscode-java-test/assets/851745/d4176d34-2674-4968-a9b7-d5b09f1273e2)

**Comment by jdneo** [comment]
What's your vscode insider version? You can copy it from the About page.

AFAIK, there is some API changes happen in VS Code side.

**Comment by heruan** [comment]
> What's your vscode insider version? You can copy it from the About page.
> 
> AFAIK, there is some API changes happen in VS Code side.

Version: 1.88.0-insider (Universal)
Commit: 9ccb0fa738a2f7a1c5328800c9fe18f4dd5b4f8a
Date: 2024-03-18T05:50:07.245Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.3.0

**Comment by jdneo** [comment]
Looks like it's a regression from VS Code. Because when I used the latest test runner extension on VS Code stable, it's working.

I filed a ticket at upstream: https://github.com/microsoft/vscode/issues/208055

**Comment by jdneo** [comment]
I've released a new pre-release version `0.40.2024032505` which should fix this issue.

Please note that `0.40.2024032505` can only be used in 1.88 insiders now, since there is an api breaking change.
