### ISSUE TITLE
Test Result not formatted well

### ISSUE THREAD

**Issue by robertonav20** [microsoft/vscode-java-test#1678]
Hi,
in the latest version of this `0.41.0` when run a test own log ins't formatted instead in the previous version `0.40.1` is correct and respect the stacktrace formatting.
Below the result of 2 version:

`0.41.0`  Bad formatting
![image](https://github.com/microsoft/vscode-java-test/assets/6991920/cbedcdbd-e84a-4c3c-b9ef-0a5db501674f)

`0.40.1` Correct formatting
![image](https://github.com/microsoft/vscode-java-test/assets/6991920/392ec47a-5389-4760-a09a-c5f7257e7ec2)

As you can see in the first image you must scroll right to see the entire output instead, in the second image the output is more java style format for stack trace

**Comment by robertonav20** [comment]
Hi,
i would raised up the same issue after the latest update of `v0.42.0`

![image](https://github.com/user-attachments/assets/5797193c-1692-4625-9aaf-a19cf1743c62)

As you can see the output of test is null
![image](https://github.com/user-attachments/assets/88c8b3a5-6ad7-4ad0-9bdf-4e5b89a210ee)

**Comment by jdneo** [comment]
@robertonav20 What's your vscode version?

I'm using vscode `1.92.0` and I can repro the same issue even using test runner `0.41.1`, which indicates that this might be a regression from vscode.

**Comment by robertonav20** [comment]
Hi @jdneo, yes I'm using the 1.92.0

**Comment by jdneo** [comment]
Filed upstream https://github.com/microsoft/vscode/issues/224575
