### ISSUE TITLE
I cannot see the test run button in the editor gutter, why

### ISSUE THREAD

**Issue by dongshen** [microsoft/vscode-java-test#1679]
i have try the guide related "I cannot see the test run button in the editor gutter, why", but still is not work.

**Comment by luatle090** [comment]
I have the same issue. I simply downgraded the version to 0.40.0 or 0.40.1, then restarted extension and it appeared again.

**Comment by GregoryLi360** [comment]
> i have try the guide related "I cannot see the test run button in the editor gutter, why", but still is not work.

Same.

> I have the same issue. I simply downgraded the version to 0.40.0 or 0.40.1, then restarted the extension and it appeared again.

Fixed it with this 💀

**Comment by jdneo** [comment]
Looks like it's same issue with #1681 

This issue could appear if using `redhat.java@1.30*`.

**Comment by jdneo** [comment]
For anyone encounters this issue, if you are using `redhat.java@1.30.*`, please install the pre-release version `0.41.2024042308`

A stable version `0.41.1` containing the fix will be released soon.
