### ISSUE TITLE
junit not support to scan test case in src/main/java folder

### ISSUE THREAD

**Issue by nowsdt** [microsoft/vscode-java-test#1682]
not support write test case in src/main/java folder, only support write case in /src/test/java, but idea,eclipse support.
sometimes ,we write test case in src/main/java just want to instead main method for quick test

**Comment by jdneo** [comment]
Basically, we scan the test cases according to the configuration in build.gradle/pom.xml.

See: https://github.com/microsoft/vscode-java-test/wiki/FAQ

In the future, if the capability of marking a source root as test root is supported, this issue can be resolved by marking `src/main/java` as test.
