### ISSUE TITLE
Run/Debug Tests and Run Tests with Coverage from java file don't work

### ISSUE THREAD

**Issue by v-yuyul** [microsoft/vscode-java-test#1687]
**Environment:**

- VS Code Version: 1.88.1
- Extension Version: test runner 0.41.1 + pack 0.26.0
- JDK Type & Version: 21
- OS Type & Version: linux

**Step to Reproduce:**
1. Clone and open https://github.com/junit-team/junit5-samples/tree/master/junit5-migration-maven
2. Right click the java file under `src/test/java/com/example/project` > `Run/Debug Tests` or `Run Tests with Coverage`

**Expected Behavior:**

**Actual Behavior:**
`Run/Debug Tests` and `Run Tests with Coverage` don't work while all tests works in test runner explorer.

![image](https://github.com/microsoft/vscode-java-test/assets/31497677/5a90a4d1-29c6-449c-9634-a23a3a97149f)

**Comment by jdneo** [comment]
Looks like an upstream issue: https://github.com/microsoft/vscode/issues/211338
