### ISSUE TITLE
debug testfile can not restart

### ISSUE THREAD

**Issue by AYiXi** [microsoft/vscode-java-test#1694]
### First click debug program run

<img width="897" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/28703786/128616e6-619b-49ad-a31e-9a5ce6dbed04">

### When I click restart
<img width="795" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/28703786/44feeb95-3d24-49ae-8e14-4872c5b72471">

### Nothing to run
<img width="757" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/28703786/268016c2-67fe-4681-8bf3-42951e7392bd">

### And wait for a minute
<img width="1612" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/28703786/3cca3c35-77b6-4f78-ae2b-8e958e5d538f">

**Comment by jdneo** [comment]
dup with #1561
