### ISSUE TITLE
Test Classpath containing conflicting classes with gradle

### ISSUE THREAD

**Issue by appleseedexm** [microsoft/vscode-java-test#1701]
## Background:
We migrated a multi-project Spring project to gradle. With maven everything worked. With gradle we noticed that vscode-java-test would fail on Spring integration tests due to conflicting beans, but the tests would run when executed with `./gradlew test`. 
I expected the classpath inconsistencies to be the reason for this, that vscode-java-test would load classes from a `test` folder even though we only have a dependency to the `testFixtures` of a project. I was able to confirm that with deleting the conflicting classes from the `test` folders. 

I reproduced this outside of Spring in a simple [gradle starter project](https://github.com/appleseedexm/gradle-classpath-vscode-java-test). If this project is tested with `./gradlew test`, the tests execute successfully, with vscode-java-test they will fail (`app/src/test/java/org/example/app/MessageUtilsTest.java`). The reason is that it will inject the `ConflictingClass.java` from `test` instead of `testFixtures`, or probably both, but with `test` being prioritised. 

## Reproduction steps:
1. Checkout [gradle starter project](https://github.com/appleseedexm/gradle-classpath-vscode-java-test).
2. run `./gradle test` - should be successful
3. run `app/src/test/java/org/example/app/MessageUtilsTest.java` with vscode-java-test

## Expected behaviour:
Test run through successfully

## Actual Behaviour:
Tests fail

## Environment
- Extension: `v0.41.1`
- VSCode: `1.90.0`
- OS: Arch Linux `6.9.6-arch1-1`
- Java: openjdk `17.0.11 2024-04-16 LTS`
- Gradle: `8.81

Same behaviour also happens in neovim with vscode-java-test `0.40.1`

Obviously fixing this would be amazing, but maybe there's a possible workaround with buildship to fix the classpath? This particular case is about `test` vs `testFixtures`, but I was so  far not able to rule out this behaviour between `main` and `test`. 

Edit:
I played around with it more and noticed that in vscode buildship occasionally reports `The type ConflictingClass is already defined`. We did not encounter this with classes in our Spring project.

**Comment by jdneo** [comment]
Thank you. It's just about the right time to ask about this.

I'm recently implementing test delegation to Gradle, which will solve your problem. The code is closed to be ready and I've verified that using the new way to run test, the issue is gone.

Stay intune: https://github.com/microsoft/build-server-for-gradle/issues/119

**Comment by jdneo** [comment]
dup: https://github.com/microsoft/vscode-java-test/issues/1045#issuecomment-676911725

**Comment by jdneo** [comment]
The Gradle Test Delegation (both run and debug) has supported now.

To use this feature, you need to install the latest [Test Runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) and [Gradle for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) extension.

To delegate the tests to Gradle, you can set the default testing profile in Testing explorer:
![image](https://github.com/user-attachments/assets/f3e982e0-0340-461c-b6c4-c8c7fe9352f5)
![image](https://github.com/user-attachments/assets/e1a2693c-e6d7-425a-b7d5-6adf878f4ce3)

If you do not want to change the default testing profile, you can trigger an one-time execution via:
![image](https://github.com/user-attachments/assets/1c3f7478-b100-40cf-98c2-6f0357050209)
![image](https://github.com/user-attachments/assets/55fa017c-adb3-4c5a-bc81-55db63834773)
