### ISSUE TITLE
Breakpoints in method under test no longer hit.

### ISSUE THREAD

**Issue by bworkmanMiso** [microsoft/vscode-java-test#1702]
I used to be able to do this. I'm not sure when it stopped, but other people on my team confirmed they also are experiencing the same behavior.

Steps:

- add breakpoint in JUnit test
- add breakpoint in method under test
- debug test
- test breakpoint hits, Continue (F5)
- results: test breakpoint hits, method under test breakpoint does not, test continues and succeeds as expected
or
- add breakpoint in JUnit test
- add breakpoint in method under test
- debug test
- test breakpoint hits, Step Into (F11) call to method under test that has a break point that should hit but doesn't
- results: I arrive at the method under test but see the following error when examining a method variable:
Failed to get variables. Reason: com.sun.jdi.InternalException: Got error code in reply:35

Environment:
Java17
SpringBoot 2.7.16
VS Code 1.90.2
Electron 29.4.0
Chromium 122.0.6261.156
Node.js 20.9.0
OS: Windows_NT x64 10.0.19045
Test Runner for Java v0.41.1

**Comment by jdneo** [comment]
@bworkmanMiso

Could you share a video or some screenshot for this issue?
