### ISSUE TITLE
Option to Clear Previous Test Runs in Output View

### ISSUE THREAD

**Issue by Biyakuga** [microsoft/vscode-java-test#1703]
Hello,

I am seeking a feature that allows for rerunning tests while ensuring the output view is cleared each time, so only the results of the latest test run are displayed. Currently, all previous test runs are shown in the output, which can be cluttered and confusing.

For example, as shown in the image below, the output view includes all past test runs. I would prefer an option to clear this history automatically before each run, displaying only the most recent test run results.

![image](https://github.com/microsoft/vscode-java-test/assets/67515021/5b305a48-d18e-4871-9ce7-6e2d69c32ebf)

**Comment by jdneo** [comment]
I believe this is something that out of the extension's control. So I filed an issue at upstream: https://github.com/microsoft/vscode/issues/219050.
