### ISSUE TITLE
View details not working

### ISSUE THREAD

**Issue by Azune** [Microsoft/vscode-java-test#172]
When you get the tests results and you have failed tests, on the output log you can see the failure cause.
On the test reporter, you can see the failed tests but whenever you want to see the failure cause and click on the failed test "View details", it doesn't show up.

I've removed the method path/name from the image below, so just to be clear, the names are showing fine but the failure details are not showing up.

![image](https://user-images.githubusercontent.com/4563975/39017408-71f1990e-43e0-11e8-8b93-8d57a2629077.png)

**Comment by ansyral** [comment]
@Azune  does the behavior occur on other tests or is it specific for this one? Could you help share the code to repro? Thanks.

**Comment by Azune** [comment]
It was doing this on all tests, I uninstalled the extension and reinstalled it and it solved the issue. If I get the issue again I try to get logs and code to reproduce the issue.

**Comment by ansyral** [comment]
@Azune I'm gonna close this one and feel free to open an issue if it reproduces again
