### ISSUE TITLE
Micronaut tests are skipped

### ISSUE THREAD

**Issue by ChrisVesters** [microsoft/vscode-java-test#1732]
1. Unzip the zip and try to run the default application test in VSCode.
2. See that they are skipped.

```
%TSTTREE2,com.example.DemoTest,true,1,false,1,DemoTest,,[engine:junit-jupiter]/[class:com.example.DemoTest]
%TSTTREE3,testItWorks(com.example.DemoTest),false,1,false,2,testItWorks(),,[engine:junit-jupiter]/[class:com.example.DemoTest]/[method:testItWorks()]
%TESTS  3,@Ignore: testItWorks(com.example.DemoTest)
%TESTE  3,@Ignore: testItWorks(com.example.DemoTest)
```

4. Comment out the line id("io.micronaut.test-resources") version "4.4.2" in build.gradle.
5. Run the tests again, and now they work.

[demo.zip](https://github.com/user-attachments/files/17023779/demo.zip)

**Comment by jdneo** [comment]
The attached project has compilation errors

![image](https://github.com/user-attachments/assets/b9bddbf0-801c-4ebe-99a3-6ea6a199bcdb)

Anyway, I comment out `RunCucumberTest.java` and `StepDefinitions.java`, and using gradle delegation feature, looks like it works as expected.

![image](https://github.com/user-attachments/assets/43a39639-f45b-4db1-8468-84a4e45b110f)

![image](https://github.com/user-attachments/assets/ded5472c-5acd-49a9-bbed-9148b2fce623)

**Comment by ChrisVesters** [comment]
I don't think you are looking at the right project.
The one I uploaded doesn't contain any Cucumber tests.

It only contains a single DemoTest file.

**Comment by jdneo** [comment]
Have you tried `Delegate Test to Gradle` mentioned above?

**Comment by ChrisVesters** [comment]
I don't seem to have the option to run it with a certain profile.

**Comment by jdneo** [comment]
> but it doesn't seem to do anything.

Could you explain more about what happened on your side?

**Comment by ChrisVesters** [comment]
As I say. I don't see any output.
Not in the test tab, not in the debug tab, nothing.
The test tab only shows this: ` *  The test run did not record any output. `

If i run it on the command line with gradle it does run the test successfully.
```
 ./gradlew test

BUILD SUCCESSFUL in 8s
```

**Comment by jdneo** [comment]
> Not in the test tab, not in the debug tab, nothing.

It's a limitation right now from upstream: https://github.com/microsoft/build-server-for-gradle/issues/119#issuecomment-2270972146

Can you see the green mark after running in the gutter?

**Comment by ChrisVesters** [comment]
I don't see the green mark.
I also don't seen an update about the tests in the testing panel.

<img width="1304" alt="Screenshot 2024-09-19 at 09 24 44" src="https://github.com/user-attachments/assets/29b8a990-bc35-4167-af7a-4c017721c90c">

**Comment by jdneo** [comment]
I cannot repro, here is what I've seen for this project.

https://github.com/user-attachments/assets/59797fea-d14a-4de1-a3e5-fc87e236903b

**Comment by ChrisVesters** [comment]
Interesting.
I just tried to disable all extensions except for Gradle and Java test runner, but I still have the same issue?
You think it could be related to the platorm/machine?

I am using Mac.

**Comment by jdneo** [comment]
> You think it could be related to the platorm/machine?

No I don't think so.

What are the enabled extensions and their versions on your side?

**Comment by ChrisVesters** [comment]
I am going to close this ticket for the following reasons:
1. I tried it with another project and I couldn't reproduce it, so something weird must have happened.
2. It only happens when you use the `test-resources` plugin from Micronaut. If you simply use the dependencies the runner works fine out of the box (no need to delegate to mvn)

Because of this, this doesn't feel like an important thing.
