### ISSUE TITLE
Error while running build-plugin

### ISSUE THREAD

**Issue by nathannguyen-nng** [microsoft/vscode-java-test#1733]
I'm trying to follow this guide https://github.com/mfussenegger/nvim-jdtls  and I'm stuck at vscode-java-test installation part.

running npm run build-plugin give me this error:

`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Test Runner for Java :: Parent 0.42.0 .............. SUCCESS [  0.027 s]
[INFO] Test Runner for Java :: Build Tools 1.0.0 .......... SUCCESS [  0.255 s]
[INFO] Test Runner for Java :: Plugin 0.42.0 .............. FAILURE [  0.327 s]
[INFO] Test Runner for Java :: Plugin Tests 0.42.0 ........ SKIPPED
[INFO] Test Runner for Java :: update site 0.42.0 ......... SKIPPED
[INFO] Test Runner for Java :: Target Platform 0.42.0 ..... SKIPPED
[INFO] Test Runner for Java :: Runner 0.42.0 .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.321 s
[INFO] Finished at: 2024-09-20T17:59:20-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to resolve target definition file:/Users/nathan/vscode-java-test/java-extension/com.microsoft.java.test.target/com.microsoft.java.test.tp.target: Failed to load p2 metadata repository from location https://download.eclipse.org/eclipse/updates/4.33-I-builds/I20240728-1800/: No repository found at https://download.eclipse.org/eclipse/updates/4.33-I-builds/I20240728-1800.
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
node:child_process:964
    throw err;
    ^

Error: Command failed: ./mvnw clean verify
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at Object.execSync (node:child_process:961:15)
    at Object.<anonymous> (/Users/nathan/vscode-java-test/scripts/buildJdtlsExt.js:31:4)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12004,
  stdout: null,
  stderr: null
}

Node.js v22.5.1`

**Comment by mkdirJava** [comment]
I am also facing the same issue, 
This repo is mentioned in the trail to setup NeoVim Debugging.
Would be nice to get the build working

**Comment by HyperAfnan** [comment]
Have you installed maven in your pc?

**Comment by mkdirJava** [comment]
I think I can answer that for both myself and @nathannguyen-nn, yes

Is there something special about the wrapper mvnw? 

I sense if we did not have maven installed the runner would not of got so far

**Comment by nathannguyen-nng** [comment]
> I think I can answer that for both myself and @nathannguyen-nn, yes.
> 
> Noticed its js calling maven commands. Is it using a mvnw wrapper or the host? Either way it's building two artifacts
> 
> I sense if we did not have maven installed the runner would not of got so far

Yes, I did have maven installed on my machine. Also, for anyone trying to setup Java debugging for NeoVim, you can just download "Test Runner for Java" extension via vscode and copy the already built jar files located in the extension folder. (Usually in ~/.vscode/extensions/vscjava.vscode-java-test-*/server)

**Comment by jdneo** [comment]
The target definition needs to be updated: https://github.com/microsoft/vscode-java-test/pull/1734
