### ISSUE TITLE
Debugging Tests fails: Unrecognized option: -Xnoagent

### ISSUE THREAD

**Issue by jochen-lise** [microsoft/vscode-java-test#1737]
I try to debug a specific test but it fails with the following message

```
OpenJDK 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
Unrecognized option: -Xnoagent
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Any ideas? Could this be related? https://github.com/microsoft/java-debug/issues/561

**Comment by jdneo** [comment]
Have you tried to use the latest pre-release version of java debugger?

**Comment by jochen-lise** [comment]
@jdneo  Hello, thank you very much! With version the Debugger v0.58.2024090204 (pre-release) everything works as expected! :)
