### ISSUE TITLE
Can't choose configuration when default is set

### ISSUE THREAD

**Issue by mlau-anet** [microsoft/vscode-java-test#1742]
Sometimes I want to append coverage, sometimes I do not.

If I specify the settings
```
    "java.test.config": [{
        "name": "don't append coverage",
        "coverage": {"appendResult": false}
    },
    {
        "name": "do append coverage",
    }
    ],
```
Then I can choose whether to append or not. But usually I do want to append, so I will set this as the default:
```
    "java.test.config": [{
        "name": "don't append coverage",
        "coverage": {"appendResult": false}
    },
    {
        "name": "do append coverage",
    }
    ],
    "java.test.defaultConfig": "do append coverage"
```
unfortunately, with these settings, I do not see an option run with the "don't append coverage" option. Is this possible, or do I have to change the defaultConfig setting every time I want to change the config I'm running with?

**Comment by jdneo** [comment]
Currently there might not be any perfect solution for your problem. You can remove the setting `java.test.defaultConfig`, then you can choose test config each time you launch the test.

Does this help with your problem?
