### ISSUE TITLE
Problem to get the root path of class when run a test

### ISSUE THREAD

**Issue by jiangdequan** [Microsoft/vscode-java-test#190]
When I use the extension to run a test, in some case I use the code below to get the root path
`Thread.currentThread().getContextClassLoader().getResource("").getFile()`

In vscode the result is: the/path/of/the/project/target/classes
In IDEA or Eclipse the result is: the/path/of/the/project/target/test-classes

Therefore, my previous unit tests could not be performed properly.
Could you help me out, many thanks!

**Comment by ansyral** [comment]
@jiangdequan might because in the calculated class path, `the/path/of/the/project/target/test-classes` is listed after `the/path/of/the/project/target/classes`. Do you also meet the problem when you try to access a resource ? or your code depends on the the value of `getResource("")`?

**Comment by jiangdequan** [comment]
@ansyral In the dir `the/path/of/the/project/target`, both test-classes and classes are there.

> Do you also meet the problem when you try to access a resource ? or your code depends on the the value of getResource("")?

Yes, I want to use the result to access a resource about test.

**Comment by jiangdequan** [comment]
Hi, @ansyral !
Is this problem related to this extension or vscode?

**Comment by ansyral** [comment]
@jiangdequan do you have same resources in both src and test folder? It seems no problem to access the resource file if it resides in test folder. Or could you help share a piece of code to repro it?

**Comment by ansyral** [comment]
@jiangdequan I think you can use `Thread.currentThread().getContextClassLoader().getResource("test.properties").getFile()` directly, does it work for you?

**Comment by jiangdequan** [comment]
It works fine.

My unit tests are working fine in other IDEs or maven.Modifying the code may be a good solution.

But, why are there different results with plugins and maven?

**Comment by ansyral** [comment]
the test runner doesn't use `maven test` to run the tests, the implementations might be different.

**Comment by jiangdequan** [comment]
Do you have a plan to make it the same as maven?

**Comment by jdneo** [comment]
Closing since it seems to have been resolve.
