### ISSUE TITLE
Restart is necessary after changing dependencies with Gradle

### ISSUE THREAD

**Issue by mouadino** [Microsoft/vscode-java-test#198]
**VS Code:** 1.23.1
**Java Test Runner:** 0.6.1

Each time I add a new dependency to `build.gradle`, tests fail in case they need the specific class (e.g. JDBC driver) while running `gradle test` from terminal works, and it seems (happens already 2 times) that it only works after I restart vs code.

**Comment by ansyral** [comment]
@mouadino , thanks for the report. Seems class path are not updated automatically when updating `build.gradle`. Will fix it.
