### ISSUE TITLE
Tests with Junit and Jmockit fail

### ISSUE THREAD

**Issue by andybarilla** [Microsoft/vscode-java-test#203]
When trying to run tests that use Jmockit and Junit the error below occurs. Is there a way to set the classpath for the unit tests?

`java.lang.IllegalStateException: JMockit wasn't properly initialized; check that jmockit.jar precedes junit.jar in the classpath (if using JUnit; if not, check the documentation)`

When run with mvn test and from Eclipse all of these tests run as expected.

**Comment by ansyral** [comment]
@ndbrlla  classpath is automatically set by the runner. Could you check your pom.xml, does dependency `jmockit` precede `junit`? Or could you share a code snippet to repro this issue? I cannot repro it right now.

**Comment by Magefo** [comment]
Hi, i have the same issue running tests with JMockit dependeny, mi project is configured with gradle and throws me the same error: 

`Caused by: java.lang.IllegalStateException: JMockit didn't get initialized; please check the -javaagent JVM initialization parameter was used`

My gradle dependency configuration is this:

`dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile 'org.mockito:mockito-core:2.23.0'
    testCompile group: 'org.jmockit', name: 'jmockit', version: '1.43'
}`

In my launch.test.json i added the path of the jmockit throught -javaagent and it didn't work:

`{
                "name": "bocc-empresas-approval",
                "projectName": "bocc-empresas-approval",
                "workingDirectory": "/Users/maguerrero/Documents/BOCC-Vehicular-project/bocc-empresas-backend/bocc-empresas-approval",
                "args": [],
                "vmargs": ["-javaagent:/Users/maguerrero/Documents/BOCC-Vehicular-project/bocc-empresas-backend/jmockit-1.43.jar"],
                "env": {},
                "preLaunchTask": ""
            }`

**Comment by jdneo** [comment]
@Magefo In the `launch.test.json`, did you also set the value of the `default` filed to `bocc-empresas-approval`?

**Comment by jdneo** [comment]
@andybarilla Is it possible for you to share a sample project which can repro this issue?

**Comment by dgileadi** [comment]
Just as a note, in case someone else finds this issue: I was able to get JMockit-based unit tests running successfully with the built-in unit test runner in vscode by adding the following to my workspace's .vscode/settings.json file:

```json
    "java.test.config": [
        {
            "name": "jmockitConfig",
            "vmArgs": [ "-javaagent:~/.m2/repository/org/jmockit/jmockit/1.49/jmockit-1.49.jar" ]
        }
    ],
    "java.test.defaultConfig": "jmockitConfig"
```

This is with the JMockit dependency in my pom.xml:

```xml
        <dependency>
            <groupId>org.jmockit</groupId>
            <artifactId>jmockit</artifactId>
            <version>1.49</version>
            <scope>test</scope>
        </dependency>
```
