### ISSUE TITLE
Disable auto-load/search of tests

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode-java-test#204]
I'm working with a huge codebase (SAP Hybris) with 10k+ tests. It takes like 15 minutes to load all tests.
Actually I don't want to index the Hybris tests, I just want to have my own tests visible.
So please provde a way to disable the index for certain files or paths.

Another way would be to not try to detect tests each time the workspac is opened. Why not persist the index somewhere?

**Comment by ansyral** [comment]
@mojo2012 thanks for reporting this. Yes, it could be a headache when you have a lot of tests in the workspace at first load. Persisting the index in local disk could be an option, but I 'm not sure whether it could be much faster to reload from disk. I'll do a test first. Thanks again.

**Comment by mojo2012** [comment]
Personally, I'd also be happy if I can just right click on a test method and click run (or use the command palette).
I don't need the panel with all the tests.

**Comment by jdneo** [comment]
@mojo2012, I'm closing this issue since it is somehow duplicated with #259. We are trying to rewrite the explorer to make it become lazy-loading.

Please feel free to let us know if you have any further problems.
