### ISSUE TITLE
Restart is necessary after changing dependencies with Maven

### ISSUE THREAD

**Issue by khe817** [Microsoft/vscode-java-test#205]
**VS Code**: 1.23.1
**Java Test Runner**: 0.6.1

Each time I add a new dependency to `pom.xml`, tests fail because they need some specific classes from the new dependency (throws error `NoClassDefFoundErrors`). Running `$ mvn test` from terminal works fine.

Test Runner only works again after I restart VSCode.

Possibly related issues: #198 , #138

**Comment by ansyral** [comment]
@khe817 thanks for reporting this, this should be the same issue with 198. Also you reminds me of issue 138, which I didn't recall before that it could be related to updating pom.xml. Thanks again.
