### ISSUE TITLE
Test results not refreshed after rerun

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-test#206]
https://www.linkedin.com/pulse/update-using-vs-code-java-scott-shipp/

According to this article, the test results were not refreshed after rerunning. Please help fix this.

**Comment by ansyral** [comment]
`TextDocumentContentProvider` interface has `onDidChange` event, which could be used to update the test result.

**Comment by akaroml** [comment]
Is there any progress?

**Comment by ansyral** [comment]
Current API cannot get access to the report window. I opened an issue to track. https://github.com/Microsoft/vscode/issues/51959

**Comment by ansyral** [comment]
The feature request for the API has been there for a while, so I used a walkaround to track text document open/close to get all uris to update.
