### ISSUE TITLE
Endgame 0.7.0

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode-java-test#214]
# Build
- [x]  6/21 - Bump version to 0.7.0  - @ansyral 
- [x]  6/21 - Add change log for 0.7.0 - @ansyral
- [x]  6/21 - Signed RC Bits - @ansyral

# Test
- [x]  6/21 - Run test plan #49  - @bsaby
- [x]  6/21 - verify bug #206 #205 #198  - @ansyral

# Release
- [x]  6/28 - Add 0.7.0 tag for vscode-java-test - @ansyral
- [x]  6/28 - Release to marketplace - @ansyral 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by bsaby** [comment]
### Run test plan 
1. Conguration

Win10 | Mac
-- | --
Vscode   1.24.1   Jdk   1.8.0_171 | Vscode   1.24.1   Jdk   1.8.0_161

2. No new bugs found
3. Test result

Test case | Win10 | Mac
-- | -- | --
Configurations | Vscode   1.24.1   Jdk   1.8.0_171 | Vscode   1.24.1   Jdk   1.8.0_161
Clean   install | Pass | Pass
Update | Pass | Pass
Uninstall | Pass | Pass
Test   explorer | Pass | Pass
Test   explorer of Multi-root | Pass | Pass
Test   report | #74 | #74
Multi   module project | Pass | #212
Test   status bar | Pass | Pass
Trigger   tests from test explorer | #213 | Pass
Open   test log command | Pass | Pass
Configure   test report position | Pass | Pass
Junit5   test | #134 | #134
Test   configuration | Pass | Pass
Cancel   a test run | Pass | Pass
Run   with default configuration | Pass | Pass
