### ISSUE TITLE
Environment Variables not passed to test

### ISSUE THREAD

**Issue by flakobatako** [Microsoft/vscode-java-test#222]
Edit: I downgraded to v 0.6.0 and worked like a charm. So definitely something messed up my projects in the new release:
![image](https://user-images.githubusercontent.com/28810524/41947887-db87060e-797f-11e8-893d-b9ba99a34b8d.png)

Prior to the latest extension update all my tests used to behave correctly, they would grab my user's environment variables (i'm on windows 7, 64 bits) whenever I explicitly wanted to (i.e. System.get("MYSQL_FFMA_JDBCURL"). 

After the extension update, I cannot get my user environment variables anymore (debug only, works normal), but when i want to run or debug a test, no matter how y call them, i'll always get a null.

I read in the changelog that now it supports configuring the env variables via the launch.test.json. 

I gave it a shot and configured my env in launch.test.json, like this:
... 
"env": {"a":"a"}, 
...

But after launchig it the problem is still there, my app can't grab any custom environment variable:
![image](https://user-images.githubusercontent.com/28810524/41946688-52c9594e-7979-11e8-9cb0-3d44c7fcb69a.png)

I tried everything from reinstalling the Extension pack, to restarting the machine.

I don't know if there's something i'm missing in my config, but i swear it worked without any problems yesterday.

Also, I noticed the Test Explorer disapeared.

Steps to reproduce: 
-Create new project with unit test (i use the maven extension).
-Add a user environment variable.
-Restart vscode.
-At any rate in the test call the env var like this System.getenv("VARIABLE_NAME")
-Try to debug the test, and step over until we can monitor the variable's value.
-It should be null.
-Configure the test adding the env variable.
-Try to debug the test, and step over until we can monitor the variable's value.
-It should be null.

These are the contents of my launch.test.json
-------------------------------------------------------------------------------------------------------------------
{
    "run": {
        "default": "",
        "items": [
            {
                "name": "app-ffma-setAppointment",
                "projectName": "app-ffma-setAppointment",
                "workingDirectory": "c:\\Git\\Work\\Java\\gdev-FieldServices\\Lambdas\\app-ffma-setAppointment",
                "args": [],
                "vmargs": [],
                "env": {
                    "a": "aaaa"
                },
                "preLaunchTask": ""
            }
        ]
    },
    "debug": {
        "default": "",
        "items": [
            {
                "name": "app-ffma-setAppointment",
                "projectName": "app-ffma-setAppointment",
                "workingDirectory": "c:\\Git\\Work\\Java\\gdev-FieldServices\\Lambdas\\app-ffma-setAppointment",
                "args": [],
                "vmargs": [],
                "env": {
                    "a": "aaaa"
                },
                "preLaunchTask": ""
            }
        ]
    }
}
-------------------------------------------------------------------------------------------------------------------
Thank you in advance.

**Comment by ansyral** [comment]
hi @flakobatako,
1. Test explorer has been moved to test view container.
![image](https://user-images.githubusercontent.com/1982828/41951316-d1da6560-79fc-11e8-8421-fb8d14f4d192.png)
2. I suppose you triggered the test directly from the codelens `Run Test`? Configuring env variables only works by triggering `Run Test with config`, which is only visible in the context menu of the test explorer(we kind of removed it from codelens as it make the codelens too long)
3. You mentioned you used to work, how did you set your env variables? Did you set it manually outside the test run or some way else?

**Comment by flakobatako** [comment]
Ok, good to know.

I'll try tomorrow to test it like you say, and yes i tried to run it via code lens.

As for 3, i use to setup my env variables directly in windows via setx command.

Thank you.

**Comment by ansyral** [comment]
@flakobatako I figured out that we have a bug that  kind of ignores the environment variables set by process, but before I fix it , you could try the `Run with config` command.
