### ISSUE TITLE
encoding in the test output window.

### ISSUE THREAD

**Issue by songxianpeng** [Microsoft/vscode-java-test#224]
I'm using Chinese and my file encoding is UTF-8,and my output when I use debug and maven test is correct. 
but when I use `Java:Show test output`: open the test output window. There's a garbled:

![image](https://user-images.githubusercontent.com/9303424/42075800-2d040f78-7ba5-11e8-8400-4c2fd762ae60.png)

I have tired to set  system environment variable “JAVA_TOOLS_OPTIONS", but it failed, is there any other solutions?

**Comment by ansyral** [comment]
@songxianpeng so `“JAVA_TOOLS_OPTIONS="-Dfile.encoding=utf-8"` does not work for you?
