### ISSUE TITLE
Sometimes Test Explorer would not show when I click on a Test Report

### ISSUE THREAD

**Issue by JanusWu** [Microsoft/vscode-java-test#235]
**To Reproduce**
	1. Open project junit5-migration-maven, select one java test file, the Test icon would show up
	2. Click on the Test  icon to open the Test Explorer, then run all test
	3. Open the Test Report, then swith the Test Explorer to File Explorer
	4. Select a folder in the File Explorer, the Test icon would disapper
	5. Click on the Test Report, the Test icon would not show up again

![image](https://user-images.githubusercontent.com/17060520/42370525-8a2a203a-813f-11e8-9066-7948e00d4d84.png)

**Comment by JanusWu** [comment]
A similar issue is that: 
The Test Explorer would also not show up when I select a test java file in the editor (and not select a java test file in the Explorer). I think it's not make sense.
![image](https://user-images.githubusercontent.com/17060520/42370795-48fbd5e4-8140-11e8-964e-f3c945802a4b.png)

**Comment by bsaby** [comment]
Now the explorer will always show in the activity bar after the extension has been activated see PR #291  . Close it.
