### ISSUE TITLE
Test explorer sometimes detect wrong tests when there have test functions with same name in different class

### ISSUE THREAD

**Issue by JanusWu** [Microsoft/vscode-java-test#236]
**To Reproduce**
1. Open project _junit5-samples_ in vscode
2. Open the Test Explorer, wait for the finish of test detecting
3. Open all java files one by one to let all tests show in the Test Explorer
4. There would have 3 _addsTwoNumbers_ test under class _CalculatorTetsts_
5. Check the file paths of three _addsTwoNumbers_ functions, you will see two of the functions have the same file path. (to get the file path, you can click on one of the function, move your mouse to hover over the opened java file title)

![image](https://user-images.githubusercontent.com/17060520/42371287-9692adfe-8141-11e8-99ba-5e9bb46ff0a0.png)

![image](https://user-images.githubusercontent.com/17060520/42371323-b3e98210-8141-11e8-8854-eff5481c33cd.png)

I checked all the _addsTwoNumbers_ functions (or CalculatorTests.java file) under _junit5-samples_ folder, and found one under project _junit5-jupiter-starter-gradle_, one under _junit5-jupiter-starter-ant_ and one under _junit5-jupiter-starter-maven_.
But in Test Explorer, one of the functions is under _junit5-jupiter-starter-gradle_, two of them are under  _junit5-jupiter-starter-maven_.

**Comment by ansyral** [comment]
@JanusWu thanks for the report, this is a known issue. Currently, runner uses fully qualified name of a test method as the unique identifier, which is not enough for the case above.

**Comment by ansyral** [comment]
root cause is same as #212

**Comment by bsaby** [comment]
Build: 338
The current behavior is that if there are some test files with the same name, the Test Explorer will only display one of the files. Other identical name files also have no code lens.

Test explorer:
![image](https://user-images.githubusercontent.com/22470312/48337238-5d0a2500-e69d-11e8-9bc1-1a97aaaf65b7.png)
Other identical name files: 
![image](https://user-images.githubusercontent.com/22470312/48337285-7f03a780-e69d-11e8-9226-58063df06b0f.png)

**Comment by jdneo** [comment]
@bsaby This is as expected.

Because the same named files contain the classes which have the same fully qualified names. They are introduced by different building tools. But the underlying Java Element is the same.
