### ISSUE TITLE
[Mac] Click 'Debug Test' codelens could pop up 'Failed to attach to remote debuggee VM. Reason...'

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-test#24]
Open `spring-boot-junit-project`, click `Debug Test` on some test case, it could pop up message box saying "Failed to attach to remote debugger VM. Reason: java.net.ConnectException: Connection refused (Connection refused)".
<img width="1025" alt="screen shot 2017-12-01 at 2 46 26 pm" src="https://user-images.githubusercontent.com/14052197/33471055-714e6074-d6a6-11e7-9cb7-872fc7d0b605.png">

This issue didn't happen very frequently, but i have saw it several times. So still need a look.

**Comment by sallyur** [comment]
It is also repro in windows.

**Comment by jdneo** [comment]
Root cause: the JVM has not been started in 500ms: https://github.com/Microsoft/vscode-java-test/blob/master/extension/src/runners/baseRunner/BaseRunner.ts#L108

Add a retry logic might help.

**Comment by jdneo** [comment]
We are now leveraging the Java Debugger to launch the tests instead of attaching to them. So this issue will no longer appear.
