### ISSUE TITLE
Endgame 0.7.1

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode-java-test#243]
# Build
- [x]  7/11 - Bump version to 0.7.1  - @ansyral 
- [x]  7/11 - Add change log for 0.7.1 - @ansyral
- [x]  7/11 - Signed RC Bits - @ansyral

# Test
- [x]  7/11 - Run test plan #49, verify #213 - @bsaby
- [x]  7/11 - verify bug #230 #222 #176  - @ansyral

# Release
- [x]  7/11 - Add 0.7.1 tag for vscode-java-test - @ansyral
- [x]  7/11 - Release to marketplace - @ansyral 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by bsaby** [comment]
### Ru test plan
1. Configurations

Test case | Windows | Mac
-- | -- | --
Configurations | Vscode   1.25   Jdk   1.8.1_171 | Vscode   1.25   JDK   1.8.1_171

2. Open bug:  #245
3. Test result

Test case | Windows | Mac
-- | -- | --
Configurations | Vscode   1.25   Jdk   1.8.1_171 | Vscode   1.25   JDK   1.8.1_171
Clean   install | Pass | Pass
Update | Pass | Pass
Uninstall | Pass | Pass
Test   explorer | Pass | Pass
Test   explorer of Multi-root | Pass | Pass
Test   report | Pass | Pass
Multi   module project | #212   #245[New] | #212   #245[New]
Test   status bar | Pass | Pass
Trigger   tests from test explorer | #235 | #235
Open   test log command | Pass | Pass
Configure   test report position | Pass | Pass
Junit5   test | #134 | #134
Test   configuration | Pass | Pass
Cancel   a test run | Pass | Pass
Run   with default configuration | Pass | Pass
Class   path is refreshed when build file(pom.xml, build gradle) is updated | Pass | Pass
Verify #213 | Pass | Pass
