### ISSUE TITLE
TestNG Support 

### ISSUE THREAD

**Issue by chrisaige** [Microsoft/vscode-java-test#248]
Because #53 seems abandoned I am creating a new Issue.
Are there any updates on the Progress for TestNG Support by this Plugin? 

Or is there a way I can help out implementing it?

**Comment by ansyral** [comment]
hi @chrisaige We haven't started implementing TestNG yet. It's great to hear that you'd like to contribute to this feature and you're welcome to open pull requests. I think to support TestNG, we might need the following steps:
1. discover tests of TestNG, the code is placed in `com.microsoft.java.test.plugin`
2. implement the TestNG runner Console to run the tests, might need to add another project similar to `com.microsoft.java.test.runner.junit5`
3. implement the TestNG runner to start the console, the code is placed in `extension/src/Runner`

**Comment by chrisaige** [comment]
Ok I made a fork (https://github.com/chrisaige/vscode-java-test) and pushed my changes.
I'm to incompetent to test the Plugin tho.
I'll try again tommorow maybe I can test my changes then.

**Comment by jdneo** [comment]
We have added the TestNG support in the newest code base (together with a bunch of refactoring work). It should be released recently. So I'm closing this issue for now.

@chrisaige Very appreciated for your contribution, which is very inspiring! 😄

**Comment by chrisaige** [comment]
@jdneo sorry that I couldnt do more.

**Comment by jdneo** [comment]
@chrisaige Please don't say that. You did great actually. I learned a lot from your code. Without your contribution, I cannot add the TestNG support in a short time.
