### ISSUE TITLE
Getting Error "undefined is not a function" after 0.7.1 update

### ISSUE THREAD

**Issue by medialwerk** [Microsoft/vscode-java-test#249]
Hello everybody,

after the latest update, I'm getting an `undefined is not a function` error if I want to run my java specs. So now, I can't work on my code anymore.

vscode-java-test version: 0.7.1

The TestOutput shows the following error message:
```
Found multiple projects: sub-project,projectFound multiple projects: sub-project,projectFailed to run tests.
```

I have a Gradle repository with 3 java projects in it.

I tried to let the plugin write a new launch.test.json, but it doesn't resolve my issue.

best regards

**Comment by ansyral** [comment]
@medialwerk what do the folder structures for project `sub-project` and `project` look like?

**Comment by ansyral** [comment]
Close it as no more info is provided.

**Comment by medialwerk** [comment]
Sorry for my late reply. I had not the time to create a sample repository. But I tested version 0.8.0 and the issue is fixed now. Big Thanks!
