### ISSUE TITLE
Adding watches/evaluating expressions fails during debug with multiple projects.

### ISSUE THREAD

**Issue by revz79** [Microsoft/vscode-java-test#261]
All was fine with one project only, but then i added a second project. Now, running a test in debug mode and evaluating and/or adding watches to expressions fails with the error:
Please specify projectName in launch.json.

Expected Behavior:

Add a breakpoint anywhere in the test method
Press "Debug Test" link
Evaluate or add a watch on an expression
View the result value of the expression

**Comment by ansyral** [comment]
hi @revz79  this is a [bug](https://github.com/Microsoft/vscode-java-debug/issues/307) in `Java Debugger` extension. 
Before it is resolved, could you try following walk around?

1. Execute the command `Java: Edit Test Configuration`, it would generate a test configuration. 
2. Debug the test from test explorer with `Debug with config`
