### ISSUE TITLE
Always use test configuration or make it configurable

### ISSUE THREAD

**Issue by lashchev** [Microsoft/vscode-java-test#264]
Java Test Runner 0.7.1

For out tests we need to provide env and vmargs, but they don't work with code lens (which actually took quite some time to realize). We use Code lens a lot since we practice TDD.

Ideally, once we define test run/debug configuration - it should be automatically picked up everywhere: in Test Explorer, Code Lens, Maven test, etc.

It would help to have the following configuration options for this extension:
- show/hide "Run/Debug with Config" in Code Lens
- configuration to use in "Run with Config" in Code Lens = none/ref to cfg
- configuration to use in "Debug with Config" in Code Lens = none/ref to cfg

**Comment by ansyral** [comment]
@lashchev unfortunately we removed `Run/Debug with Config` from the code lens as it would make the code lens rather long and not every one needs this feature. Adding an option to show/hide is a good way. However, we also provide a `default` property for people who use this feature often, you can edit your test config and specify the `default` field with the name of a config item, and then this config item would be picked even you choose `Run/Debug `. Does this make sense to you? Looking forward to your feedback.

**Comment by jdneo** [comment]
@lashchev I think your requirement should be achieved if we resolve  #524.

Please feel free to let us know your thoughts about it.

**Comment by jdneo** [comment]
Closing this issue since the experience of running/debugging with configuration has been changed.

More details can be found here: https://aka.ms/java-test-config

**Comment by llgcode** [comment]
Works great for me. Thank you.
