### ISSUE TITLE
Test explorer would disappear if java file isn't active

### ISSUE THREAD

**Issue by wolf99** [Microsoft/vscode-java-test#271]
The GIF on the extensions readme shows the Test Explorer as a section of the standard explorer pane (similar to the Maven projects section that gets added by the Maven for Java plugin).

In my installation it shows as a completely new pane on the activity bar. Given that the icon for it only shows on the activity bar when a java file is selected it is a very annoying experience to have the pane keep disappearing and then have to navigate back to it all the time (especially given vscode's behaviour of 'opening' files even only single-click in the Explorer file tree)

Is there a way to get the Test Explorer to show as a section in the default Explorer as shown by the GIF?
Additionally, is there a way to stop it disappearing every other darn second?

Expected behaviour of Test Explorer as shown in readme:
![1](https://user-images.githubusercontent.com/281700/44209577-d73d1300-a15b-11e8-92e7-5774bad4554b.png)

Actual behaviour:
![2](https://user-images.githubusercontent.com/281700/44209591-ddcb8a80-a15b-11e8-9bdb-9bc56aa53e56.png)

**Comment by ansyral** [comment]
@wolf99 sorry the demo hasn't been updated, actually we moved the Test Explorer to the sidebar as it is the recommended place by the VSCode team.
Test explorer would be up only if a java file is active, we'll see how to avoid the case of sudden disappearance.

**Comment by jdneo** [comment]
Changed the behavior of the explorer appearance condition in #291. Now the explorer will always show in the activity bar after the extension has been activated.

If the user wants to hide it, he can right-click the activity bar and deselect the item: `Test`:

![image](https://user-images.githubusercontent.com/6193897/45334555-d5753c80-b5ad-11e8-8faf-d17484ac539b.png)
