### ISSUE TITLE
Support @RunWith(Suite.class)

### ISSUE THREAD

**Issue by tylerteem** [Microsoft/vscode-java-test#272]
I have multiple test suites that I want to run and am using @RunWith(Suite.class)  @Suite.SuiteClasses but it is not showing in the test explorer to run this.

**Comment by natewaite** [comment]
Also not working with integration tests Such as naming your class + _IT

https://zeroturnaround.com/rebellabs/the-correct-way-to-use-integration-tests-in-your-build-process/

**Comment by jdneo** [comment]
Resolved in #633.

The current implementation has several problems, which are tracked in #640, #641

Closing this issue for now.
