### ISSUE TITLE
'Run Test' failed by show a 'undefined is not a function'

### ISSUE THREAD

**Issue by fbilo** [Microsoft/vscode-java-test#273]
Windows 10, 64bit.
Used the Red hat's JDK version.

There was another message shows "Running Test", but dispeard soon.

I tried to narrow down this issue by keep the method as simple as possible like just one line of system.out.println(""), the error is still happen.

**Comment by quantumelf** [comment]
I am also experiencing this issue on Ubuntu 18.04.1.

**Comment by quantumelf** [comment]
This is what displays immediately after clicking the first "Run Test" button above the ArrayListStudentTests class.

![screenshot from 2018-08-23 14-16-31](https://user-images.githubusercontent.com/36854671/44544468-3eb90c80-a6e0-11e8-8fdb-e6af1f966853.png)

This is what displays immediately after clicking the "Failed to run tests" button in the bottom left after running the test in the manner described above.

![screenshot from 2018-08-23 14-17-07](https://user-images.githubusercontent.com/36854671/44544485-4a0c3800-a6e0-11e8-8006-49b2ef887464.png)

When I run any specific test by clicking the Run Test button, I receive the same error message popping up as before, but I get this page when I click the "Failed to run tests" button.

![screenshot from 2018-08-23 14-17-27](https://user-images.githubusercontent.com/36854671/44544496-4d9fbf00-a6e0-11e8-85a7-6c2c1ee0cc08.png)

I found the following log file in the directory **~/.config/Code/logs/20180823T140445/output_1_20180823T140450**

[extension-output-#3.log](https://github.com/Microsoft/vscode-java-test/files/2315724/extension-output-.3.log)

The file was labelled "extension-output-#3.log", and it seemed to contain relevant information.

If you need a different log file or other details, point me to them, and I will happy yo pot them.

Thanks!

**Comment by ansyral** [comment]
@quantumelf thanks for the info and they are very useful. From the image, seems that you don't have a project? The extension doesn't support single file right now.

**Comment by quantumelf** [comment]
Thanks for the help @ansyral. I dont have the files setup in a project because I have little experience doing so, but I will try figure out how to set them up as a project and hopefully that should solve the problem. 

Thanks again.

**Comment by jdneo** [comment]
@fbilo is your project has a combination of Maven and Gradle?

**Comment by fbilo** [comment]
hi, jdneo, sorry for reply later. I just created some single file for testing, no project, Maven, and Gradle used. And, I have work around the issue by remove all setting files then reinstall VS code.

**Comment by praenubilus** [comment]
@fbilo I don't get it, you remove all setting files under .vscode folder then you can run unit test on single file? That's not working for me and drive me crazy

**Comment by praenubilus** [comment]
Is there any plan to support single file test?

**Comment by xdubx** [comment]
same problem here. Pls fix it fast

**Comment by jdneo** [comment]
We refactored the code recently. So the issue may be resolved or become other error messages.

So I'm closing this issue. But feel free to open new issues if you meet any problems.
