### ISSUE TITLE
Unable to open 'Aggregated test report': Reduce of empty array with no initial value.

### ISSUE THREAD

**Issue by EricaZhuKexin** [Microsoft/vscode-java-test#274]
All tests are being skipped and test suite shows error msg "Reduce of empty array with no initial value."

**Comment by ansyral** [comment]
@EricaZhuKexin could you help share a sample to repro the issue? Thanks

**Comment by EricaZhuKexin** [comment]
<img width="1429" alt="screen shot 2018-08-27 at 1 34 44 pm" src="https://user-images.githubusercontent.com/17301173/44675281-0f671000-a9fe-11e8-91bb-eaf7c8ccbc48.png">

**Comment by EricaZhuKexin** [comment]
Please see the screenshot up there. When I click the Run Test btn, the test will be skipped with the Test Output showing in the image. While the test runner used to work well with the last release of VSCode. Also please notice that this is multi-module maven+Spring Boot application. Not sure whether that's related.

**Comment by jdneo** [comment]
Hi @EricaZhuKexin, would you mind to provide a sample project which can repro this issue to us?

**Comment by jdneo** [comment]
Looks like it's dup with #208 

We refactored the code recently. So the issue may be resolved or become other error messages.

So I'm closing this issue. But feel free to open new issues if you meet any problems.
