### ISSUE TITLE
Icons are clipped in code lens

### ISSUE THREAD

**Issue by musiKk** [Microsoft/vscode-java-test#276]
Minor cosmetic problem: The icons in the code lens for the tests are clipped. I did not make any changes to font size but just to make sure I ran VSCode with a new user data dir (--user-data-dir option) to make sure that none of my settings would cause this problem.

As apparent from the screenshot this happens for both failing and succeeding tests. It is also independent of the "java.referencesCodeLens.enabled" setting.

If you need more information, I'd be glad to help.

![screen shot 2018-08-23 at 08 12 59](https://user-images.githubusercontent.com/976374/44507862-6d1cf480-a6ac-11e8-8035-a8bfabe9d6b6.png)

**Comment by musiKk** [comment]
@ansyral Yes, when I enable the Java references code lens, it looks like this:

![screen shot 2018-08-27 at 14 12 20](https://user-images.githubusercontent.com/976374/44659143-80f58d00-aa03-11e8-8a6b-14f783f24727.png)

I also disabled all extensions but the Java related ones.

I have not tried other extensions as I'm not aware of other extensions that write emoji characters in a lens. If you can point me to one, I'd be happy to give it a try.

**Comment by bsaby** [comment]
Vscode Version: 1.30.0-Insider
OS: Mac

Result: The code lens can be fully displayed.
![image](https://user-images.githubusercontent.com/22470312/48994157-ad44b500-f17c-11e8-960a-5cd01049965a.png)
![image](https://user-images.githubusercontent.com/22470312/48994186-d6fddc00-f17c-11e8-9976-79f9b29a4935.png)

**Comment by jdneo** [comment]
Fixed in 1.30-insider
