### ISSUE TITLE
Investigate how to debug java codes of the extension using VS Code

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#284]
... which can remove the requirements of Eclipse

**Comment by jbelford** [comment]
One way to debug at least the test.runner code in vscode is to do as follows:

1. hit f5 to launch the extension
2. in the *[Extension Development Host]* instance of vscode - set a breakpoint on java files in `java-extension` - easiest way to do this is add the `java-extension` as a folder to whatever workspace opens by default for you.
3. on any test hit `debug test` and it should stop at your breakpoint

**Comment by jdneo** [comment]
Thanks @jbelford. Will you see some compilation errors when you import the java code into your workspace? I think there might be several because the VS Code could not set the `target platform` as that in Eclipse.

**Comment by jbelford** [comment]
Yeah I don’t know if it is possible to debug the plugin project from vscode because there’s no way to set the target platform

**Comment by jdneo** [comment]
After some investigation, it looks like there is no smooth way to debug the Language Server plugin part in VS Code for now.

For anyone who wants to contribute, please refer to our [contributing document](https://github.com/Microsoft/vscode-java-test/blob/master/CONTRIBUTING.md)
