### ISSUE TITLE
Activating extension 'vscjava.vscode-java-test' failed 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#285]
Configuration:
```
VScode 1.26.1
Debugger for java 0.12.1
Language Support for Java 0.30.0
Java Test Runner: CI build 291
```
Repro steps:

1. Install the test bit 291
2. Open a java project to activate java test extension

Result:
![image](https://user-images.githubusercontent.com/22470312/45075552-0cfd6800-b11a-11e8-86ea-45f889d0f060.png)
![image](https://user-images.githubusercontent.com/22470312/45075555-0ec72b80-b11a-11e8-9958-636b3452c19c.png)

**Comment by jdneo** [comment]
Fixed in #286
