### ISSUE TITLE
Need to reatart vscode and reload window when updating extension

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#299]
### Configurations:
```
OS: Windows
VSCode: 1.27.1
VScode extensions:
   - Debugger for java: 0.12.2
   - Language Support for Java: 0.30.0
   - Java Test Runner: 0.8.0 
```
### Repro Steps:
1. Install a low version test runner extension, e.g. marketplace version
2. Update to a high version bit, e.g. CI build#299
![image](https://user-images.githubusercontent.com/22470312/45348004-040c0b00-b5e0-11e8-978f-ae2b709d2147.png)

### Result:
1. Prompt to restart code before reinstalling 
![image](https://user-images.githubusercontent.com/22470312/45347783-78927a00-b5df-11e8-9afb-07978691d1e6.png)
2. Need to reload window after restarting vscode
![image](https://user-images.githubusercontent.com/22470312/45347823-8fd16780-b5df-11e8-97a0-0bdae12875ed.png)
3. After reloading window, the reinstallation will succeed.

### Expect:
Update extension in current window.

I can update  Debugger for Java Extension in current window.

**Comment by jdneo** [comment]
Cannot repro...
