### ISSUE TITLE
Improve the test result page

### ISSUE THREAD

**Issue by jbelford** [Microsoft/vscode-java-test#306]
The font size for the test result window is way larger than the editor. This should probably be fixed to scale the result window more appropriately so we don't need to zoom out.

**Comment by jdneo** [comment]
Some possible actions:
- make the font size smaller.

**Comment by fbricon** [comment]
There should be a link to open the method/class under test from the report

**Comment by bheklilr** [comment]
I find that the report view is also way too wide.  Any messages just extend on the same line and require me to horizontally scroll.  Some text wrapping would be nice, maybe even reducing the margins/padding.  I think the report looks nice overall, but some simple improvements would really make an impact on how user friendly it is.

**Comment by bsaby** [comment]
I find that after updating the color theme of VSCode, for example, from light to dark, the color of the opened test report will not be automatically updated unless you switch to another editor and switch back.

**Comment by jdneo** [comment]
We did some refinement in #466 to the test report page. Those changes will be released in v0.12.0.

I'm closing this issue for now. If anyone still find there is anything needs to be improved. Please feel free to open a new issue.

Thanks.
