### ISSUE TITLE
Tree view for test explorer

### ISSUE THREAD

**Issue by jbelford** [Microsoft/vscode-java-test#307]
*Feature request*

The test explorer would be very much improved if:
 (a) packages were sorted alphabetically
 (b) subpackages were included as children instead of every package path being displayed

**Comment by jdneo** [comment]
@jbelford Thank you for the feedback.

Do you mind to separate this issue to two different ones?
- One is: packages were sorted alphabetically
- Another is: subpackages were included as children instead of every package path being displayed

**Comment by jbelford** [comment]
Yep! No problem

**Comment by jdneo** [comment]
Closing this issue and tacking with #310 #311
