### ISSUE TITLE
The status bar displays wrong status when running test fails

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#313]
Run test case: Class path is refreshed when build file(pom.xml, build.gradle) is updated

Steps:

1. Edit pom.xml, remove a dependency.
2. Run test, it is expected to fail because some dependency cannot be resolved.

Result:
![image](https://user-images.githubusercontent.com/22470312/45864656-420de980-bdad-11e8-8086-bf283bf82f85.png)
Expect:
![image](https://user-images.githubusercontent.com/22470312/45864741-9618ce00-bdad-11e8-8c93-854c0a0b6740.png)

**Comment by bsaby** [comment]
Build:  338
This issue can be reproduced.

**Comment by bsaby** [comment]
Project: https://github.com/Microsoft/todo-app-java-on-azure
### Environment:
```
1. VSCode: 1.34.0
2. JDK: 1.8.0_211
3. VSCode Extensions:
- Debugger for Java: 0.18.0
- Language Support for Java(TM) by Red Hat: 0.45.0
- Java Test Runner: 0.17.1
```
### Steps:
1. Open the project in VSCode
2. Edit pom.xml, remove a dependency, show as below:
![image](https://user-images.githubusercontent.com/22470312/58299903-33337700-7e13-11e9-9823-f8488395c249.png)
3. Run test from the workspace root

### Result:
1. There are two failed tests in the left bottom test result,
2. Click on the test result to open the test report, you will find tests shown in the Test Explorer does not contain the `initializationError `method.
3. Click the navigation button in the test report, prompt the info: `No test item could be found from Language Server..` in the test output channel

![image](https://user-images.githubusercontent.com/22470312/58300503-55c68f80-7e15-11e9-92a3-d58796dd58ad.png)

**Comment by jdneo** [comment]
Closing this issue since it has been fixed.
