### ISSUE TITLE
could not find Java home ... windows 7 professional

### ISSUE THREAD

**Issue by ronaldperezs** [Microsoft/vscode-java-test#333]
Hello, the problem that I am presenting is a message "could not find Java home ..." when opening the unit tests, which I can not execute through the extension. I have the Language Support for Java by Red Hat configured without problem, I can debugger. The message only appears when using its extension to run the unit tests in a visual way, I am currently doing it through maven.

Environment
Operating System: Windows 7 Professional SP1 x64
JDK version: Jdk 1.8.0_171
Visual Studio Code version: 1.27.2
Java extension version: Java extension pack 0.4

Steps To Reproduce
  1. Open unit test
![error1](https://user-images.githubusercontent.com/6565721/46442642-f144ac00-c72f-11e8-93ca-18b4a8a0c5d3.JPG)

could not find Java home ...

**Comment by jdneo** [comment]
@ronaldperezs would you mind to share your project to us?

**Comment by ronaldperezs** [comment]
the problem occurs in any project, it is as if the extension does not work, I do not know if it generates some log that can share them to find the error

**Comment by jdneo** [comment]
@ronaldperezs Hmm, the current version of the test runner extension has its own logic to resolve the java home. While in the next release we will update the logic - consume the java home path from the `Language Support for Java by Red Hat` extension. Would you mind to have a try when we release the new version? It might be comming in next week.

**Comment by ronaldperezs** [comment]
ready, I'm waiting for the release of the new version, to see if taking the java home configuration solves the problem. Thanks

**Comment by xzel23** [comment]
I have the same issue on MACOS. I thought it might be an issue with Java 11 (since some other tools also did not recognise the new version). It works now however in Redhat's Java support (as of version 32). From he comments above I understand that playing with the java.home setting is useless unless a new version is released because you still use your own logic. Is that true?

**Comment by jdneo** [comment]
@ronaldperezs @xzel23 We released the new version of the extension. Could you please try it again and let me know if the problem still occurs?

**Comment by xzel23** [comment]
The error message is gone. However as I understand it, the plugin does not yet support JUnit5, and I have upgraded, my project in the meantime because I had some issues using JUnit4 together with modules. So I did not test the functionality. I will see if I find a small JUnit4 based project to test this.

**Comment by ronaldperezs** [comment]
hello, after the plugin update the message changed, now it appears:
![2](https://user-images.githubusercontent.com/6565721/47045209-e6d6d900-d157-11e8-9c80-78d61b5d858e.JPG)
When trying to execute the unit test, it is observed in the report that it ignores it, whereas if I execute it the maven plugin test is executed by the console showing the successful result. I remain attentive to your support to improve this inconvenience. regards
![3](https://user-images.githubusercontent.com/6565721/47045518-a0ce4500-d158-11e8-9ca7-bf83371078d8.png)

**Comment by jdneo** [comment]
@ronaldperezs 

We refactored the code recently. Is the issue still occurs on your side now?

**Comment by ronaldperezs** [comment]
![ok](https://user-images.githubusercontent.com/6565721/51203806-fb9a4880-18cf-11e9-84d1-e3085b59fe80.png)
Excellent, the issue was solved. thanks
