### ISSUE TITLE
Sometimes, test results not be refreshed after rerun

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#341]
I have encountered this problem twice

1. Open a multi-root workspace and run all tests, then open the test report
1. Leave the window there, after a long time( > 30 minutes), the test report displays the file has been changed even though I haven't updated any files.
1. Then I update some test methods to make a different test result
1. Run all tests again

Result: 
The test report will not be refreshed even though reopen it
![image](https://user-images.githubusercontent.com/22470312/46719845-910ab880-cca1-11e8-85c1-b9f84c9ce20f.png)

**Comment by jdneo** [comment]
Closing since this message is removed.
