### ISSUE TITLE
There is no 'Test file has been changed, ...' prompt in the test report after updating test code

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#342]
Repro steps:

**Test report position: subview**

1. Open test report after run tests
2. Update test code
3. Reopen test report

**Test report position: currentView**

1. Open test report after run tests
2. Update test code

Result:
![image](https://user-images.githubusercontent.com/22470312/46723650-e5fefc80-ccaa-11e8-84ab-abae34a82707.png)

Expect:
![image](https://user-images.githubusercontent.com/22470312/46723639-df708500-ccaa-11e8-9a44-01f3bdecd668.png)

**Comment by jdneo** [comment]
Closing since this message is removed.
