### ISSUE TITLE
0.11.0 iteration plan

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#343]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

- [x] 💪 Code refactoring
  - [x] Explorer lazy load
  - [x] Centralize runners into one executable jar
  - [x] Decouple & simplify the local cache: TestResultCache + ExplorerNodeCache
  - [x] Search tests items before running/debugging tests
  - [x] Support TestNG
  - [x] Regression tests and bug fix
- [x] Update test plan

**Comment by Deathhush** [comment]
TestNG support will really come in handy.
