### ISSUE TITLE
Support JUnit with legacy JRE (Java 6)

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-test#345]
@PilouUnic reported Microsoft/vscode-java-pack#50

The Java Language Server supports Java 8+ and we won't change that. Is it possible that we run legacy cases in any way?

**Comment by PilouUnic** [comment]
Sadly my project need to be build in Java 6. Have you a tip for me or need i continue with Eclipse ?

**Comment by jdneo** [comment]
@PilouUnic 
Unfortunately, the test runner needs to depend on Java Language Server to resolve the project information(classpath, test suites, etc...), so, for now, it is impossible to run legacy Java project with test runner. 😞

**Comment by jdneo** [comment]
@PilouUnic 

I'm closing this issue since it is unsupported for now. But please feel free to discuss with us if you have more questions. 😄
