### ISSUE TITLE
Unresolved compilation problems

### ISSUE THREAD

**Issue by felwolff** [Microsoft/vscode-java-test#346]
From one day to the other, I cannot testcases of my gradle-based project from the testrunner anymore, independent of the way I start them. Since running `./gradlew test` works, I believe it is a problem of the testrunner. 
The tests fail with the Message:
`Unresolved compilation problems: [ClassNameHere] cannot be resolved to a type`
Any ideas on what happend and how to resolve the problem?

**Comment by felwolff** [comment]
Unfortunately, I currently do not have time for that due to urgent deadlines. I just tested other gradle projects and they still work. So it seems to be project-specific. Where does the testrunner look for the required classes? 

Here is my `launch.settings.json`, it looks like that also for the working projects:
```
{
    "run": {
        "default": "",
        "items": [
            {
                "name": "ProjektName",
                "projectName": "ProjektName",
                "workingDirectory": "c:\\Users\\...\\ProjektName",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    },
    "debug": {
        "default": "",
        "items": [
            {
                "name": "ProjektName",
                "projectName": "ProjektName",
                "workingDirectory": "c:\\Users\\...\\ProjektName",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    }
}
```

**Comment by felwolff** [comment]
As mysteriously as it appeared, it has just started to function correctly again. Maybe it was a bug related to some kind of caching or so in the language server? Retrospectively, I probably should have restarted my computer to see whether that would have solved the problem...
Nevertheless, thank's for responding to my issue!

**Comment by jdneo** [comment]
@felwolff I'm closing this issue since it looks like the problem has gone. But feel free to reopen it if you still meet this problem in the future.

**Comment by 4F2E4A2E** [comment]
That's how I've got it to work: https://stackoverflow.com/a/50632086/543426 :man_facepalming:
