### ISSUE TITLE
how to specify a system environment for junit test in vscode

### ISSUE THREAD

**Issue by yong9900** [Microsoft/vscode-java-test#354]
My junit test only runs successfully when a system environment is setup.

I looked into <project_dir>/.vscode/launch.test.json, there is env json property, I put something like this:

"env": { "MY_ENV": "env_value"},

but in my test, MY_ENV is not setup.

Is this a bug or this is not supported?

**Comment by jdneo** [comment]
@yong9900 If you right click the tests you want to trigger in the test explorer and select test `Run With Config`. Will this work for you?

**Comment by yong9900** [comment]
unfortunately, it does not work. 
I have following in my launch.test.json:
`
    "debug": {
        "default": "",
        "items": [
            {
                "name": "integration-tests",
                "projectName": "integration-tests",
                "workingDirectory": "<some dir>",
                "args": [],
                "vmargs": [],
                "env": {
                    "MYENV": "why abc"
                },
                "preLaunchTask": ""
            }
        ]
    }
`

With this, when I evaluate following in the code:
`
inal String configPath= System.getenv( "MYENV" );
`
I got nothing.

**Comment by chuckb** [comment]
Works for me so long as the configuration is run, by either explicitly picking it from the test explorer OR setting the default parameter to the name of the configuration you want to be the default.

**Comment by jdneo** [comment]
@yong9900 Would you mind sharing a sample project which can repro your issue?

**Comment by yong9900** [comment]
@jdneo Hi Sure. I will try to put a simple project on github shortly. At the same time, I just tried, didn't work for me. will send out the project once I setup.

**Comment by yong9900** [comment]
@jdneo Hi I tried again, this time, I can't reproduce the problem. I think my problem could related to my uncleaned workplace cache. will close this issue.
