### ISSUE TITLE
Code Lenses are not in the correct place 

### ISSUE THREAD

**Issue by gorkem** [Microsoft/vscode-java-test#36]
I am not sure how it got to this stage, I was simply adding the logic for the tests.
![image](https://user-images.githubusercontent.com/82738/33509522-6d771304-d6d0-11e7-85d1-e2913c0ff47e.png)

**Comment by ansyral** [comment]
@gorkem Could you help give me more details how you trigger this? I cannot repro it at my side.

**Comment by fbricon** [comment]
I'm seeing something similar:
<img width="685" alt="screen shot 2017-12-06 at 12 12 36 pm" src="https://user-images.githubusercontent.com/148698/33674905-f0834a40-da7e-11e7-8ec3-7f99f8da7b78.png">

I installed the Azure tooling, created a new Java project and organized imports in FunctionTest

**Comment by ansyral** [comment]
@fbricon Thanks for the detailed info and I can also repro it . Seems to be related to event trigger, i'll take a look at it.

**Comment by jdneo** [comment]
May related with this: https://github.com/Microsoft/java-debug/pull/230
