### ISSUE TITLE
How to change default encoding in output

### ISSUE THREAD

**Issue by eric2877** [Microsoft/vscode-java-test#37]
Error occured: ʮ���� 02, 2017 11:03:44 ���� org.springframework.context.support.ClassPathXmlApplicationContext prepareRefresh
��Ϣ: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@532760d8: startup date [Sat Dec 02 11:03:44 CST 2017]; root of context hierarchy
Error occured: ʮ���� 02, 2017 11:03:44 ���� org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
��Ϣ: Loading XML bean definitions from class path resource [beans.xml]
����û�
LinkedHashSet
����
����

**Comment by ansyral** [comment]
@eric2877 does changing the default encoding of your operating system's console to `UTF-8` works?

**Comment by eric2877** [comment]
I changed the log4j default encoding into utf-8,  it works,  but use " system.out.println " in java file,  it outputs  messy code in vscode' output-window. 

12:05:38.113 [main] INFO  log - around....环绕开始
12:05:38.113 [main] INFO  log - logger1....before
saving user......����
12:05:38.114 [main] INFO  log - around....环绕结束
12:05:38.114 [main] INFO  log - logger1....after

the same code works well in main method under vscode debugger-console. in addition , my operating system is win10,  default encoding of system console is GBK

**Comment by eric2877** [comment]
when i ust system environment variable “JAVA_TOOLS_OPTIONS="-Dfile.encoding=utf-8"，the system.out.printline  becomes right!!

**Comment by jdneo** [comment]
Closing since it seems to be resolved.
