### ISSUE TITLE
${workspaceFolder} working in launch.test.json?

### ISSUE THREAD

**Issue by chuckb** [Microsoft/vscode-java-test#372]
Is this supposed to work?  Does not seem like it for me...

**Comment by chuckb** [comment]
This would be nice as I have JNI dependencies that require to be referenced for the run/debug helpers to work.  Putting full directory spec in json file breaks for other devs.

**Comment by jdneo** [comment]
@chukb It should be work. Could you provide more information about this?

**Comment by jdneo** [comment]
@chuckb Oh, I realized that I misunderstanding your question at the beginning. Sorry for the confusion.

There is the same issue here: #438. Please tracking the status there. 

We will consider to add `${workspaceFolder}` in the `launch.test.json` in the later version. 😃
