### ISSUE TITLE
Add a way to customize the visibility of 'run' and 'debug' Code Lens

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-java-test#374]
I have a build where if you just attempt to run any test functions, it fails to start, because I have some native dependencies that need to be configured. I am providing this build to a large amount of users, and it is confusing our users, as those buttons do not work, and they throw very confusing errors. Could a property be added to disable these buttons from showing up?

PR is #373 

There was the same issue for the debug extension that was accepted.

https://github.com/Microsoft/vscode-java-debug/issues/464

**Comment by ThadHouse** [comment]
I just did in the PR. I have some weird setups where the arguments and inputs needed for the tests to run change every build, and its hard to reproduce those. But the sample I posted gets close.

**Comment by jdneo** [comment]
Hi @ThadHouse,

Sorry that we did some refactoring these days causing the conflicts in the PR. It will be great if you would like to resolve them.

**Comment by ThadHouse** [comment]
I will tomorrow.
