### ISSUE TITLE
Navigate from stacktrace line to proper file in test results

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-java-test#384]
Following up on #306, we need better navigation from the report to java files. Since this is gonna be more complicated I'm opening it in a separate ticket: I'd be nice if the generated stacktraces actually linked to matching lines from source code, to make it possible to navigate directly from the report to any file, in the workspace or the classpath, involved in the test failure, as with other Java IDEs.

**Comment by jkryanchou** [comment]
+1 Is there any other solution to navigate the stack trace file now? while we could not click file on it.

**Comment by jkryanchou** [comment]
@jdneo Could you redirect the stack trace to the DEBUG CONSOLE in order that we could click the stack trace file through the panel? Or we have no other way to navigate it quickly.

**Comment by getaceres** [comment]
This is a must have when refactoring tests. Not being able to go to places where the exception is being thrown in an easy way it's time consuming and puts VS Code in a serious disadvantage against IntelliJ or Eclipse when developing Java.

**Comment by Skynet0** [comment]
Bumping this issue again, this is a major blocker in moving from IntelliJ to VS Code.

**Comment by jdneo** [comment]
This is available in `0.26.0` (with Language Support for Java(TM) by Red Hat upgrade to 0.70.0).
