### ISSUE TITLE
Code coverage report ?

### ISSUE THREAD

**Issue by noomerzx** [microsoft/vscode-java-test#387]
Any way to see code coverage percentage for tested directory ?

**Comment by RuiffCardoso** [comment]
This with included integration when editing file would be great.

**Comment by sayonsur** [comment]
I would like to help although i am new to VScode extensions and typescript. 
Looking at jacoco, can we do this ?

- code coverage can be enabled from json config.
- prerequisite can be jacoco dependency.
- whenever a UT runs we trigger jacoco command to generate report.
- the output is xml , it can be shown in UI.

**Comment by jdneo** [comment]
Hi @sayonsur,

Thank you for your enthusiasm for this feature. Yes, all kind of contribution is welcome! Let me spend some time to do some investigation for this issue. I'll get back to you when I get some ideas.

Thanks.

**Comment by jdneo** [comment]
Hi @sayonsur, I have some questions:

> prerequisite can be jacoco dependency.

Do you mean that we will embedded a jacoco jar in the extension?

> the output is xml , it can be shown in UI.

Does that mean that we will parse the xml and show it in the VS Code webview?

**Comment by sayonsur** [comment]
Hi @jdneo,

I believe it can be achieved in both ways. You can embed the Jacobo jar and programmatically generate code coverage whenever a test is run.
Or we can rely on the jar being present in system and have a configurable path to use it.

It generates a xml . So it can be easily parsed for a web view report. In fact there are many vscode plugins which already parses xml and show report or color code the lines also directly.

**Comment by jdneo** [comment]
The embedded solution looks better since it could avoid breaking changes of the `jacoco`. But one thing we need to take care is about its license.

BTW, would you like to contribute for this feature?

**Comment by sayonsur** [comment]
Hi @jdneo,
I don't have expertise on TS. Although I would love to give it a shot. Is there a timeline ? I might need more time , to understand both the code base and embed jacoco to achieve this.

**Comment by jdneo** [comment]
Hi @sayonsur, there is no timeline. Just give it a shot whenever you want. If you meet any problem, just feel free to let me know.

**Comment by sayonsur** [comment]
Sure thing. I will give it a shot and reach out to you in case i need any guidance on the Test project.

**Comment by sayonsur** [comment]
@jdneo,

Is there any documentation for the Java test runner ? I don't see any associated test project. 
What parameters to pass to debug and check the flow. 
Could you please help me out.

Thanks,
Sayon

**Comment by jdneo** [comment]
Hi @sayonsur,

Please refer to this page: https://github.com/microsoft/vscode-java-test/blob/master/CONTRIBUTING.md

If you find anything missing, please let me know.

Thanks.

**Comment by Yashwin12** [comment]
Hi @jdneo, do we have any updates on the line-by-line code-coverage feature? Thanks in advance.

**Comment by jdneo** [comment]
Hey @Yashwin12,

Sorry not yet so far. But feel free to contribute if you want. 😃

**Comment by jdneo** [comment]
Just FYI, VS Code team is now working on a test API proposal, which might also include the test coverage support. Let's wait and see what we can do there: https://github.com/microsoft/vscode/issues/107467

**Comment by jdneo** [comment]
For everyone who wants to have this feature, could you please answer the following question to help us better understand the use case?

- What's the coverage tool you are using? (JaCoCo, Clover, Cobertura, JCov, Code Cover, PIT, etc...)
- How do you use the coverage tool? (Maven/Gradle/Eclipse/IntelliJ/CI integration, etc...)

**Comment by JonathanTrEs** [comment]
> For everyone who wants to have this feature, could you please answer the following question to help us better understand the use case?
> 
> * What's the coverage tool you are using? (JaCoCo, Clover, Cobertura, JCov, Code Cover, PIT, etc...)
> * How do you use the coverage tool? (Maven/Gradle/Eclipse/IntelliJ/CI integration, etc...)

- I use JaCoCo
- With the Eclipse/IntelliJ IDE

**Comment by RussellSanders1** [comment]
> For everyone who wants to have this feature, could you please answer the following question to help us better understand the use case?
> 
> * What's the coverage tool you are using? (JaCoCo, Clover, Cobertura, JCov, Code Cover, PIT, etc...)
> * How do you use the coverage tool? (Maven/Gradle/Eclipse/IntelliJ/CI integration, etc...)

* using Intellij IDEA code coverage runner
* from Intellij IDEA (naturally lol)

**Comment by baincd** [comment]
> For everyone who wants to have this feature, could you please answer the following question to help us better understand the use case?
> 
>     * What's the coverage tool you are using? (JaCoCo, Clover, Cobertura, JCov, Code Cover, PIT, etc...)
> 
>     * How do you use the coverage tool? (Maven/Gradle/Eclipse/IntelliJ/CI integration, etc...)

* Jacoco
* Eclipse and Maven

**Comment by Tazaf** [comment]
> For everyone who wants to have this feature, could you please answer the following question to help us better understand the use case?
> 
> * What's the coverage tool you are using? (JaCoCo, Clover, Cobertura, JCov, Code Cover, PIT, etc...)
> * How do you use the coverage tool? (Maven/Gradle/Eclipse/IntelliJ/CI integration, etc...)

* JaCoCo
* Maven (`mvn test`

**Comment by baincd** [comment]
It is possible to get code coverage reports from tests run in VS Code, however it does require some manual configuration, manual steps, and additional extensions:

1. Create a [Java Test Configuration](https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration) that configures the [Jacoco agent](https://www.eclemma.org/jacoco/trunk/doc/agent.html) to generate the execution data file (jacoco.exec) 
```json
"java.test.config": [
    {
        "name": "jacoco",
        "vmargs": ["-javaagent:/home/chris/.vscode/org.jacoco.agent-0.8.8-runtime.jar=destfile=target/jacoco.exec,append=false"]
    }
],
```

2. Use either the [Jacoco CLI report command](https://www.eclemma.org/jacoco/trunk/doc/cli.html) or the [Maven org.jacoco:jacoco-maven-plugin:report goal](https://www.eclemma.org/jacoco/trunk/doc/report-mojo.html) generate an XML report (jacoco.xml) from jacoco.exec

3. The overall code coverage can be viewed via the HTML report (by default, the Jacoco Maven plugin saves this to target/site/jacoco/index.html). This can be viewed in a web browser, or in VS Code using an extension to preview HTML files (example screenshot uses the [Live Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) extension)
![Jacoco Report Example](https://user-images.githubusercontent.com/5075659/168439108-58dadc20-ec8f-4f6b-887f-c79693234586.png)

4. The [VS Code Coverage Gutters Extension](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) can be installed to display code coverage on each Java file within the editor (example screenshot has "Coverage-gutters: Show Line Coverage" setting enabled
![Coverage Gutters Example](https://user-images.githubusercontent.com/5075659/168439103-943d4b22-413b-4d7e-a6a1-119b59364290.png)

The overall flow looks something like this:

```mermaid
flowchart
    s1["1. Run Tests in VS Code<br/>(vmargs configured for jacoco agent)"] --> jacoco.exec[/jacoco.exec/]
    jacoco.exec --> s2[2. Jacoco CLI report command OR <br/>mvn org.jacoco:jacoco-maven-plugin:report]
    s2 --> index.html[/jacoco/index.html/]
    s2 --> jacoco.xml[/jacoco.xml/]
    index.html --> s3[3. View code coverage in browser <br/>or with a VS Code extension to preview HTML]
    jacoco.xml --> s4[4. Code coverage displayed in Java editor<br/>with Coverage Gutters extension]
```

### Suggestions to improve the Code Coverage UX in VS Code
To improve the code coverage UX in VS code (and make it similar to Eclipse and IntelliJ), I offer the following suggestions

- Add a postLaunchTask option for Java Test Configurations so step 2 (generation of code coverage reports) could be configured to automatically happen after tests are run
  - It would be a big win to be able to have the code coverage reports generated automatically when tests are run 
- Natively display code coverage reports (with links that directly open Java files)
  - There are workarounds (browser, extensions to preview HTML).  But having this natively in VS Code would be nice
- Automatic setup of steps 1 and 2
  - Assuming this is the most complex, I think it'd be better to focus on the other options first.  And good documentation on how to setup VS Code to generate code coverage reports may be more feasible then automating the setup

**Comment by jdneo** [comment]
@baincd Thank you for the detailed suggestions.

The current state is that we are waiting the VS Code to publish the test coverage API: https://github.com/microsoft/vscode/issues/107467

About adding `postLaunchTask`, I would like to see more use cases, otherwise, once the API get released, this field would become useless.

But anyway, the steps you provided would be a great workaround for the current moment.

**Comment by baincd** [comment]
I'm excited to hear that there is a test coverage API (https://github.com/microsoft/vscode/issues/123713) in the works.  Knowing this is on deck, I think manually generating the Jacoco report is fine for now.

Regarding a `postLaunchTask` option, after experimenting a bit more I realized that there is not a way to pass the Java project being tested to the task.  This means it could not be used to generate the Jacoco report for Java projects not in the root folder, (including multi-module projects).  Since it would only work for some projects, I don't think it is justified add for now.

**Comment by baincd** [comment]
I put together [this script](https://gist.github.com/baincd/93c2f6814b30734db1ad476dcfe50d44) that runs continuously, creating the Jacoco reports (XML, HTML) when jacoco.exec changes.  This can be used to do step 2 [above](https://github.com/microsoft/vscode-java-test/issues/387#issuecomment-1126769444) automatically.

**Comment by viswatejan** [comment]
I usually use maven for my Java projects and so I have created a maven favorite entry in the Settings.JSON file for the jacoco code coverage report.

```json
"maven.terminal.favorites": [
    {
      "alias": "Java Code Coverage",
      "command": "clean -X org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report"
    }
  ],
```

In addition, I have installed [coverage-gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) extension. 

So, when ever I want code coverage, I will just run my Maven Favorite to run the Java Code Coverage like shown below:

![image](https://user-images.githubusercontent.com/3971316/174907799-e1135faa-c073-4856-bdde-582a82a5d721.png)

![image](https://user-images.githubusercontent.com/3971316/174907819-348bfcfd-c812-45e0-a7c9-8b2370074f9f.png)

And I use [Live Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) extension to preview the index.html file in the `target/site/jacoco` directory.

I switch multiple java workspaces and so I don't want to create the same task in all my projects. This way my maven favorite will be available for all my workspaces.

**Comment by gayanper** [comment]
I can look into this @jdneo. 

My plan so far
- Add a new profile to execute tests with coverage
- Generate coverage files in output dir

Then user can configure a coverage extension such as https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters to present it.

But if we really want smooth functionality, We could build the presentation support into vscode-java-test it self as the 2nd step.

WDYT ?

**Comment by jdneo** [comment]
@gayanper, thank you.

We've thought about this before but finally we decide to wait until the code coverage extension api is ready. (We planned to put more effort to the LS side)

It will be great if you are willing to contribute!

**Comment by nickzhums** [comment]
Hey @gayanper, we looked into the plan of VS Code. It looks like the extension API won't be ready for a while, so we think in the meantime we won't wait for them, sorry about the change. We've received a lot of customer feedback regarding the code coverage report, and we're wondering if you have any plan/timeline for this? Maybe we could work together on this.

**Comment by gayanper** [comment]
I started to look at it today, I was planning to first generate the lcov file so that we can suggest to use the coverage gutters plugin to start with. 

The idea is to add a new RunProfile in test controller for coverage and implement the coverage agent inject through there. Ofcourse coverage should be able to use for normal application launches as well, But that is something we can consider separately in java.debug. But as soon as I say that, I was thinking should we just add coverage support in java.debug and use it in java.test ?

@testforstephen @jdneo WDYT ?

**Comment by jdneo** [comment]
> should we just add coverage support in java.debug and use it in java.test ?

How many users ask about coverage at debug side? @testforstephen 

> to first generate the lcov file so that we can suggest to use the coverage gutters plugin to start with.

I think we can just generate jacoco exec file and jacoco report files like csv,html,xml.

If we suggest users to use coverage gutter, once the VS Code API is ready, it will be a big ux change, and I tend to avoid that happening.

**Comment by testforstephen** [comment]
> > should we just add coverage support in java.debug and use it in java.test ?
> 
> How many users ask about coverage at debug side? @testforstephen
> 

In debugger side, we didn't receive the request for coverage support. I prefer to put it in the test runner as it is more relevant to the test scenario.

**Comment by nwwells** [comment]
> 1. Create a [Java Test Configuration](https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration) that configures the [Jacoco agent](https://www.eclemma.org/jacoco/trunk/doc/agent.html) to generate the execution data file (jacoco.exec)

I seem to be running into problems with this and would appreciate a pointer for where to look. When I run the tests with the jacoco lib from my terminal I get a `jacoco.exec` file, but not when I do it from VS Code. I think there may be some problem with my settings.json? It doesn't seem like it's getting read in.

If you could take a look, it's here: [nwwells/JavaHello](https://github.com/nwwells/JavaHello)

**Comment by baincd** [comment]
@nwwells Testing your project (before it was converted to Gradle), I found that the jacoco.exec was being created but under the user data directory rather than in the workspace directory.  Relative to the [settings file location](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations), I found the jacoco.exec in a path like `workspaceStorage/deee7d3926e0d7be1c9d778fd1464714/redhat.java/jdt_ws/code_b60fb2d/target/jacoco.exec`

It's almost as if the working directory for the JVM executing the tests is this directory in user data rather than the workspace.  I don't experience this issue with Maven projects - the jacoco.exec is created in the path relative to the Maven project.

I'm not sure why this is different when not using Maven, but it seems like you can explicitly set the working directory for the JVM executing the tests:
```patch
     "java.test.config": [
         {
             "name": "jacoco",
             "vmargs": ["-javaagent:/Users/nathan.wells/.vscode/jacocoagent.jar=destfile=target/jacoco.exec,append=false"]
+             "workingDirectory": "${workspaceFolder}"
         }
     ]
```
Hope this helps!  All the best,
-Chris

**Comment by nwwells** [comment]
That's perfect, thanks @baincd!

**Comment by nwwells** [comment]
Just for style points I was thinking about a way to autogenerate the coverage report after the test run. My first inclination was using `fswatch` to do something like this:

```
fswatch app/build/jacoco/test.exec --one-event --event=Updated \
  | awk '{print $1}' \
  |  xargs -I % \
  java -jar ~/.vscode/jacococli.jar report % \
  --classfiles app/build/classes/java/main/ \
  --sourcefiles app/src/main/java/ \
  --html app/build/reports/jacoco-custom
```

and then put that into the `preLaunchTask` (I assume you'd probably have to background it in order for the test to proceed?).

I ran into an issue where the report was being generated off of classes compiled by gradle (in `app/build/classes`) and the report didn't like that they were out of sync with the source files. I assume either the test plugin is compiling the sources and putting the class files _somewhere_... but I'm not sure where.

**Comment by calle2010** [comment]
> * What's the coverage tool you are using? (JaCoCo, Clover, Cobertura, JCov, Code Cover, PIT, etc...)
> * How do you use the coverage tool? (Maven/Gradle/Eclipse/IntelliJ/CI integration, etc...)

- JaCoCo
- Maven, Eclipse, SonarQube from Jenkins

**Comment by jdneo** [comment]
Hi all,

Recently, VS Code made some update about the coverage API: https://github.com/microsoft/vscode/issues/123713. We adopted it immediately and released it in the pre-release channel. Now you can have the test coverage with following steps:

1. Install the latest **pre-release** version of java test runner in **VS Code Insiders**. (test coverage feature is not available in stable vs code)
2. You can find the entry in the context menu of test running shortcut
![image](https://github.com/microsoft/vscode-java-test/assets/6193897/53e78dd5-67b1-46ee-aea6-0d13078215cb)
![image](https://github.com/microsoft/vscode-java-test/assets/6193897/ba7825ae-f0d2-4661-b5ce-4a044eaf4fad)

Following is a video showing the overall experience:

https://github.com/microsoft/vscode-java-test/assets/6193897/a0e05045-ba67-496f-bd9e-841affab7aca

Please note that, since the API is still in preview stage, which means the functionality and experience might be changed before it becomes stable. If you have any questions, free to leave your comments.
