### ISSUE TITLE
Unable to load all tests for gradle project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#395]
Test project: https://github.com/junit-team/junit5-samples/tree/master/junit5-migration-gradle

![image](https://user-images.githubusercontent.com/22470312/48054262-d14d5000-e1e7-11e8-9dc5-2b6aaf097447.png)

Can load all gradle tests in marketplace version.

**Comment by jdneo** [comment]
@bsaby fixed

**Comment by bsaby** [comment]
Test passed.
Build used: 336

![image](https://user-images.githubusercontent.com/22470312/48252089-b58fb700-e43e-11e8-9c54-d4da307b9c52.png)
