### ISSUE TITLE
How to install Java Test Runner?

### ISSUE THREAD

**Issue by vincent1147** [Microsoft/vscode-java-test#40]
I want to use Junit. But I don't know how to install it...

I have Java Test Runner installed. But not Junit

Somebody help!

**Comment by ansyral** [comment]
@vincent1147 do you have a project that uses junit4 as test framework? To install JUnit, if you are using maven, you could update the `pom.xml` of your project to include junit as a dependency, you can refer [this wiki](https://github.com/junit-team/junit4/wiki/use-with-maven) for more info.
