### ISSUE TITLE
No codelens in the test file of testng project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#407]
Project: http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip
File: TestSpring.java under com.mkyong.testng.examples.spring package

1. No codelens in test file
2. Get error when runing this class in test explorer

![image](https://user-images.githubusercontent.com/22470312/48120175-5a2dbf80-e2ac-11e8-8505-e4f9c881f41e.png)

**Comment by jdneo** [comment]
@bsaby fixed.

**Comment by bsaby** [comment]
Test passed.
Build used: 336

![image](https://user-images.githubusercontent.com/22470312/48252176-07d0d800-e43f-11e8-97b8-cd8219f96a1e.png)
