### ISSUE TITLE
Status bar will not refresh after running test for empty classes

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#410]
For those classes which don't have valid test methods, trigger test from them

Result:
The status bar will always show Running Test...
![image](https://user-images.githubusercontent.com/22470312/48122049-8d268200-e2b1-11e8-9b8d-cc98ca14e070.png)

**Comment by jdneo** [comment]
@bsaby fixed

**Comment by bsaby** [comment]
Test passed.
Build: 322
