### ISSUE TITLE
There is no WorkingDirectory in the test configuration file generated by default

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#431]
Now:
![image](https://user-images.githubusercontent.com/22470312/48250052-f1734e00-e437-11e8-8a0f-cf7cfb5619c2.png)

Expect:
![image](https://user-images.githubusercontent.com/22470312/48249997-c2f57300-e437-11e8-8902-5c8a5dbaea87.png)

**Comment by jdneo** [comment]
@bsaby Fixed

**Comment by bsaby** [comment]
Test passed.
Build: 338
