### ISSUE TITLE
All tests are still loaded if user opens an invalid project directory

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#434]
Project: https://github.com/junit-team/junit5-samples
Build: 338

At the beginning of the regression test, if the user opens an invalid project directory, the extension will not load tests. But now it loads all the tests like below, expected?
![image](https://user-images.githubusercontent.com/22470312/48336331-000d6f80-e69b-11e8-8d11-12c631424e50.png)

**Comment by jdneo** [comment]
The extension consumes the results provided by LS.

On the other hand, I think it is good if the extension can find the test cases no matter what kind of folder is opened by the user. 😃
