### ISSUE TITLE
Chinese Language Support

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-test#437]
We have lots of Chinese developers. It would be great if we can provide a localized interface. This issue is to track the effort of building the localization story.
Supporting Chinese is a start. Once the solution is working, we can expand the support to other languages.

**Comment by jdneo** [comment]
Closing this for now since we have [package.nls.zh.json](https://github.com/microsoft/vscode-java-test/blob/master/package.nls.zh.json) now.

Will reopen this it turns out that we have other more works to do.
