### ISSUE TITLE
Support ${workspaceFolder} in launch.test.json

### ISSUE THREAD

**Issue by ronanmulvaney** [Microsoft/vscode-java-test#438]
Is there any variable substitution that can be used with `workingDirectory` so that the launch.test.json can be shared between a team allowing different workspace/project locations?

Ideally here I was hoping to use something like VSCodes ${workspaceFolder} variable as per https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables

**Comment by jdneo** [comment]
Closing this issue since the experience of running/debugging with configuration has been changed. Meanwhile, the `${workspaveFolder ` has been supported.

More details can be found here: https://aka.ms/java-test-config
