### ISSUE TITLE
Junit test not running

### ISSUE THREAD

**Issue by nithillsethupathi** [Microsoft/vscode-java-test#439]
I am new to Visual Studio Code, and I am not able to run JUnit tests on my project. I don't know how to fix it. Please help me. Attached screenshot for reference. Thanks.
![screenshot from 2018-11-16 15-51-07](https://user-images.githubusercontent.com/20954412/48653126-e714ff00-e9b7-11e8-93e3-e8c7937e39c2.png)
![screenshot from 2018-11-16 15-51-54](https://user-images.githubusercontent.com/20954412/48653131-ec724980-e9b7-11e8-8ea2-e973bba5c31c.png)

**Comment by jdneo** [comment]
Hi @nithillsethupathi,

Sorry that we do not support single test file for now. There is a same issue here: https://github.com/Microsoft/vscode-java-test/issues/348

Let's track this feature request in that issue.
