### ISSUE TITLE
0.11.0 Endgame

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-test#440]
# Build
- [x]  11/20 - Bump version to 0.11.0  - @jdneo
- [x]  11/20 - Add change log for 0.11.0 - @jdneo
- [x]  11/20 - Signed RC Bits - @yaohaizh 

# Test
- [x]  11/20 - Run test plan #49 - @bsaby
- [x]  11/20 - Verify common test scenarios - @yaohaizh

# Release
- [x] 11/20 - Add 0.11.0 tag for vscode-java-test - @yaohaizh
- [x]  11/20 - Release to marketplace - @yaohaizh 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by bsaby** [comment]
### Re-run test plan 
#### 1. Configuration
Windows | 
-- | 
Version: 1.29.1 (user setup) JDK 1.8.0_181 | 
#### 2. New issue
Add a comment here: https://github.com/Microsoft/vscode-java-test/issues/441#issuecomment-440573504
#### 2. Test result:

Test case | Windows
-- | --
Clean install | Pass
Update | Pass
Uninstall | Pass
Basic | Pass
Test Explorer - UI | Pass
Test Explorer - Run/Debug Test | #441 #411 #134
Code Lens | Pass
Test report | #424
Test Status Bar | Pass
Cancel the running job | Pass
Run With Configuration | Pass
