### ISSUE TITLE
Will run all tests under current class file if trigger test from method level in test explorer

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#441]
Project: https://github.com/Microsoft/todo-app-java-on-azure

Repro Steps:
1, Open todo project in vscode
2. Expand package com.microsoft.azure.sample to the method level
3. Trigger test from a method
![image](https://user-images.githubusercontent.com/22470312/48755205-8ba48300-eccf-11e8-9728-4dc211f8c887.png)

Result:
Test runner will run all methods in class TodoApplicationTest
![image](https://user-images.githubusercontent.com/22470312/48755409-1eddb880-ecd0-11e8-8bca-49a3c3a258bc.png)

Expect:
Only run one method if trigger test from a method.

**Comment by bsaby** [comment]
Form test output, we can see that if trigger tests from method level in the Test Explorer, it still shows the results of running all tests
 
**Result:**
Trigger test from a method in Test Explorer:
![image](https://user-images.githubusercontent.com/22470312/48827072-0f7d6e80-eda7-11e8-8caf-4945190dd86f.png)

**Expect:** 
Output should like below ( triggering test fromCodelens from the same method in test file)
![image](https://user-images.githubusercontent.com/22470312/48827117-36d43b80-eda7-11e8-913b-80fe00805aef.png)

**Comment by jdneo** [comment]
@bsaby please verify it in the newest bits
