### ISSUE TITLE
Add @DisplayName support for JUnit 5

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#446]
_From @smoyer64 in https://github.com/Microsoft/vscode-java-test/issues/93#issuecomment-377658852:_

After running a few more JUnit5 tests through VS Code's Java test extension I've also realized that the ``@DisplayName`` annotations are not being used when present.  I can submit a separate issue for this problem if you want (along with a small code sample and Eclipse output.

**Comment by smoyer64** [comment]
@jdneo ... I was on vacation but wanted to (after the fact) let you know that it looks good to me!

**Comment by jdneo** [comment]
@smoyer64 

Thank you. We've added it into the report.
