### ISSUE TITLE
Some projects do not run tests correctly

### ISSUE THREAD

**Issue by 591097213** [Microsoft/vscode-java-test#447]
我遇到了一个特别奇怪的问题.

这个项目(<https://github.com/591097213/Test>)在运行`com.chuckie.demo.demotest.DemoApplication`类中的测试时会弹出消息“Error”,同时状态栏会提示“Failed to run tests”。但是当把`Test/demo-test/pom.xml`文件中`<artifactId>`标签的值改为其他值(比如改为`<artifactId>abc-def</artifactId>`),然后退出VS Code,删除除源码和`pom.xml`以外的所有文件(例如`.vscode`文件夹,`.settings`文件夹,所有的`.project`文件和`.classpath`文件等),重新加载该项目,就能正常运行所有测试了.

我发现这不是一个个例,所有包含多模块,并且子模块的包名命名规则为`groupId.artifactId`(其中`artifactId`去掉“`-`”号)的项目好像都有这个问题,但我也还不确定是不是我自己弄错了.

VS Code version:1.29.1(user setup)
OS:win10,x64
Java Extension Pack:0.4.0
JDK version:1.8.0_171

I had a particularly strange problem.

This project (<https://github.com/591097213/Test>) will pop up the message "Error" when running the test in the `com.chuckie.demo.demotest.DemoApplication` class, and the status bar will prompt "Failed to run tests". But when you change the value of the `<artifactId>` tag in the `test/demo-test/pom.xml` file to other values (such as `<artifactId>abc-def</artifactId>`), then exit VS Code and delete all files except source code and `pom.xml` (such as `.vscode` folder, `.settings` folder, all `.project` files and `.path` files), reload this project. This project will be able to run all the tests properly.

I find that this is not an isolated example. All Maven projects that contain multiple modules and whose package name rule is `groupId.artifactId` (where `artifactId` removes the "`-`" character) seems to have this problem, but I'm not sure if I made a mistake myself.

Please don't mind if I have made any grammar mistake.

![image](https://user-images.githubusercontent.com/29732324/48963312-cb6ab380-efca-11e8-80d6-75f866dda2cd.png)

**Comment by jdneo** [comment]
Hi @591097213 

Thanks for reporting, the root cause of this issue is the same as this one: #443 

I'll release a hotfix for this issue next week.

**Comment by jdneo** [comment]
Java Test Runner 0.11.1 has been released.
