### ISSUE TITLE
Add preference to autosave when 'Run Test' is selected.

### ISSUE THREAD

**Issue by NikolasKomonen** [microsoft/vscode-java-test#468]
When I run a test would it be possible to have a preference to autosave the project?

Thanks

**Comment by jdneo** [comment]
@NikolasKomonen Do you mean to save all the changed files before running the tests?

**Comment by NikolasKomonen** [comment]
> Do you mean to save all the changed files before running the tests?

@jdneo yes

**Comment by baker-travis** [comment]
Or even just the test file you push the run button from. I often find myself writing a test and then running and not getting expected results because the test file didn't save.

**Comment by jdneo** [comment]
@NikolasKomonen @baker-travis 

From my understanding, the Java language server will auto-build the workspace when the file is changed(No matter the file is saved or not).

Do you guys stably meet this problem, or it just happens sometimes?

**Comment by NikolasKomonen** [comment]
@jdneo 

Sorry, what I wanted was basically what @baker-travis was asking for. 
If the tests are run in any way, to save the file before they execute.

And if 

> the Java language server will auto-build the workspace when the file is changed

is the case, I guess just saving the test files will do.

**Comment by jdneo** [comment]
@NikolasKomonen After trying, it's just the same as what you said. The Language Server will only update the class file after the saving action.

So here is the basic idea coming up in my mind to solve this issue:

The experience could be similar to that in Eclipse:
![wechat screenshot_20190212095502](https://user-images.githubusercontent.com/6193897/52607165-36cc6f00-2eb0-11e9-9ab1-02ea8b366084.png)

When the user click run/debug test cases, we do the following things:
1. Find out all the relative files that are going to be tested
2. If there is any dirty file, show a drop-down list in the VS Code, the user can select which file they want to save using the checkbox. Here `ESC` meaning to cancel the task.
3. After that, a dialog will be shown to ask the user if he wants to always save the files before launching.
4. The extension will wait for the Language Server to finish the auto-build, then, launch the tests.

@NikolasKomonen @baker-travis Please let me know if this looks good to you.

**Comment by baker-travis** [comment]
@jdneo I approve of this. 😀It will make life much better!

**Comment by NikolasKomonen** [comment]
@jdneo Sounds great, I'm looking forward to it!

**Comment by jdneo** [comment]
Update:

To implement this feature, we need VS Code to provide the API to get all the opened editors. So far it seems that there is no such API to achieve this. See: https://github.com/Microsoft/vscode/issues/15178

**Comment by jdneo** [comment]
Hi @all,

Sorry for the late reply. Instead of get all opened files in VS Code. I simplified the solution to solve this issue:
1. Provide a setting `java.test.saveAllBeforLaunchTest` to specify whether to save all the changed files before launch the test
2. save all the files if this setting is true.

More details can be found in #785.

> Note: together with the setting `java.test.forceBuildBeforeLaunchTest` set to `true` (See: #782). We can make sure the bits are latest for each test execution.

**Comment by NikolasKomonen** [comment]
Awesome, thanks!
