### ISSUE TITLE
Run/Debug code lenses don't appear

### ISSUE THREAD

**Issue by joshmanderson** [microsoft/vscode-java-test#470]
Starting about a week ago, code lenses for each test, as well as the lens for the test class as a whole, have stopped appearing. Also, no tests appear in the test explorer panel, though this may have been a pre-existing issue – I've never used the test explorer before so I can't say for sure.

Restarting or reloading vscode does not fix the problem, nor does restarting the computer, nor disabling and re-enabling the test runner code lens – or the root vscode code lens – setting (also tried disable+restart and re-enable+restart).

Project is using gradle and tests use junit. Gradle version was upgraded from `2.14.1` to `3.5.1` 17 days ago, but the issue has only started occurring in the last week, so I'm not sure that the gradle upgrade is relevant to the problem.

Has anyone else experienced similar issues recently and does anyone have any ideas as to what might be causing the issue?

**Comment by jdneo** [comment]
@joshmanderson Would you mind to share the project to us?

**Comment by joshmanderson** [comment]
@jdneo I can't do that, sorry – the project is private to my company.
I know that this certainly complicates the issue replication process, but I'm afraid it's just not possible for me to share it.

**Comment by jdneo** [comment]
@joshmanderson Ok I understand. I'll keep my eyes on this issue and update here if I find anything.

**Comment by jdneo** [comment]
@joshmanderson One more question.

Can you see the test explorer at the sidebar (though no test items in it), or there is no test explorer at all.

I‘m wondering if the extension gets activated successfully.

**Comment by chrissantamaria** [comment]
I'm having the same issue on two entirely separate machines; code lenses have stopped appearing and no tests are showing up in the Test Explorer either.

**Comment by jdneo** [comment]
@chrissantamaria Are you using Gradle as your building tools?

**Comment by jdneo** [comment]
@chrissantamaria Don't worry.

Would you mind to share the content of `.classpath` file? Which is located at the base path of your project.

**Comment by chrissantamaria** [comment]
@jdneo 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-10">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/4">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

**Comment by joshmanderson** [comment]
@jdneo Apologies for the late reply.
The test explorer appears in the sidebar, but there are no tests shown within it.

**Comment by jdneo** [comment]
I guess I got the root cause of this problem.

In our implementation, we will only search for the test items in the `test` folders. Here is the [implementation](https://github.com/Microsoft/vscode-java-test/blob/master/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectUtils.java#L88-L100) to determine the location of the test folder.

But the implementation could not solve all the problems.

A valid `.classpath` file may look like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry excluding="**" kind="src" output="target/classes" path="src/main/resources">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	...
</classpath>
```
For some unknown reason, some project may not have `test` attribute in its classpath entries. Just like @chrissantamaria provided. So I have to figure out a way to solve this scenario.

**Comment by joshmanderson** [comment]
@jdneo 
I can confirm that changing my `.classpath` from this:
```xml
...
<classpathentry kind="src" path="src/test/java" />
...
```
to this:
```xml
<classpathentry kind="src" path="src/test/java" output="build/classes/test">
    <attributes>
        <attribute name="test" value="true" />
    </attributes>
</classpathentry>
```
fixes the issue. Tests are now appearing in the test explorer, and code lenses are appearing again (and working).

**Comment by jdneo** [comment]
@joshmanderson Glad to know we have a workaround now. 😄

**Comment by thoni56** [comment]
This workaround definitely worked for me too.

**Comment by rdcoe** [comment]
I have run into this error on one laptop but not another.  Different code bases, so it may be project related, however I can successfully run the test goal using maven externally, so it's not a classpath problem.  I have also confirmed that my .classpath test setup has the "test" attribute set to "true"

	`<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>`

But when I run a test from the test explorer or from the test itself using the Run lens, an error dialog at pops up:
 
> x Error
> 
> Source: Java Test Runner (Extension)

**Comment by jdneo** [comment]
Hi @rdcoe,
 
Thanks for reporting. 

If you can see the Code Lens but cannot run the test, then the problem you met seems to be different from this issue. Let's open a new issue and track it there: https://github.com/Microsoft/vscode-java-test/issues/561

Thanks.

**Comment by badsyntax** [comment]
Hi. Thanks for the tip @jdneo. I'm using gradle and I have another scenario, in that we separate out our tests into "test" and "integration" and thus the `gradle_scope` for the integration tests is "integration". I'm not extremely experienced with gradle but I understand I shouldn't manually be editing the classpath file. Could the vscode extension be configured to look for something other than "test"? Can this be user defined? For example:

```json
{
    "tests_gradle_scope": "test,integration"
}
```

**Comment by jdneo** [comment]
@badsyntax Good point! Let me consider how to expose such a kind of setting to the users. Thanks

**Comment by badsyntax** [comment]
Awesome thanks @jdneo I'm curious as to why test paths need to be specified in the first place, and why tests can't be discovered just via the Junit annotations? (If I were to guess, it would be for performance reasons)

**Comment by jdneo** [comment]
@jenny-ci Is the `Language Support for Java` startup correctly?

**Comment by jdneo** [comment]
I'm thinking to add a command like `Mark as Test Folder` to update the `.classpath` file.

**Comment by badsyntax** [comment]
Would gradle not overwrite this change to the .classpath file when rebuilding?

**Comment by jdneo** [comment]
@badsyntax For some unknown reason, the `.classpath` does not have test entry for some Gradle project. That's why we plan to add this command

**Comment by marvingreenberg** [comment]
Regarding "Mark as test Folder..."  That might be fine.  But at a minimum, some kind of warning when the Test Explorer is displayed, or maybe when refresh is run, that No "Test Folder" was found on classpath, or something.

**Comment by coolboy0961** [comment]
My situation is that only the @Nested test does not show Run/Debug code lenses.Normal test,ParameterizedTest is OK.

- The version of VS Code
1.33.1
- Your operating system
macOS High Sierra 10.13.6
- Reproducible steps
just use @Nested annotation to write test case.
- What you expected to see, versus what you actually saw
  - expected
    Run/Debug code lenses appear on class definition and test method definition.
  - actually
    on both of those places, there is not  Run/Debug code lenses.
- Images, animations, or a link to a video showing the issue occurring
![Xnip2019-05-06_12-03-58](https://user-images.githubusercontent.com/12973893/57205107-0e5b9900-6ff7-11e9-880e-ee053a2eb2d3.jpg)
- Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)
![Xnip2019-05-06_12-14-09](https://user-images.githubusercontent.com/12973893/57205275-79599f80-6ff8-11e9-8811-b8c7a65bd9d2.jpg)

my .classpath is below:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
        <classpathentry kind="src" output="target/classes" path="src/main/java">
                <attributes>
                        <attribute name="optional" value="true"/>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry excluding="**" kind="src" output="target/classes" path="src/main/resources">
                <attributes>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="src" output="target/test-classes" path="src/test/java">
                <attributes>
                        <attribute name="test" value="true"/>
                        <attribute name="optional" value="true"/>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry excluding="**" kind="src" output="target/test-classes" path="src/test/resources">
                <attributes>
                        <attribute name="test" value="true"/>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8">
                <attributes>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
                <attributes>
                        <attribute name="maven.pomderived" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="src" path=".apt_generated">
                <attributes>
                        <attribute name="optional" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="src" output="target/test-classes" path=".apt_generated_tests">
                <attributes>
                        <attribute name="test" value="true"/>
                        <attribute name="optional" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="src" path="target/generated-sources/annotations">
                <attributes>
                        <attribute name="optional" value="true"/>
                        <attribute name="maven.pomderived" value="true"/>
                        <attribute name="ignore_optional_problems" value="true"/>
                        <attribute name="m2e-apt" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="src" output="target/test-classes" path="target/generated-test-sources/test-annotations">
                <attributes>
                        <attribute name="optional" value="true"/>
                        <attribute name="maven.pomderived" value="true"/>
                        <attribute name="ignore_optional_problems" value="true"/>
                        <attribute name="m2e-apt" value="true"/>
                        <attribute name="test" value="true"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="output" path="target/classes"/>
</classpath>
```

**Comment by jdneo** [comment]
Hi @coolboy0961,

We haven't supported that annotation yet. Tracked by #685

**Comment by jdneo** [comment]
Here is the final solution for this issue:
### For Maven projects
The user can use [`<testSourceDirectory/>`](https://maven.apache.org/pom.html#Build_Element) to configure the test source paths.

### For Gradle projects
The user can use [`sourceSets`](https://docs.gradle.org/current/userguide/java_plugin.html#source_sets) to configure the test source paths.

### For Eclipse & Invisible projects
All the source files are treated as testable files
> [What's an invisible project?](https://github.com/redhat-developer/vscode-java/issues/501#issuecomment-461234115)

### For **Default (single file)** project
It will be ignored.
> This is for those files that do not belong to the current workspace, for example, you drop(open) a file into the VS Code from another place.

**Comment by bcsrepo** [comment]
@jdneo - could you put this ^^ final solution info (or a link to your comment) into the README? It took me quite a bit of searching to find out that code lens was using my Gradle sourceSets, and more experimentation to find out that my additional test source sets needed to have
`test {}`
around them in order for them to get the code lens "Run Test | Debug Test" shortcuts added.
Thanks!

**Comment by jdneo** [comment]
@bcsrepo Sure, that's a good idea. I'll do it.

**Comment by dampcake** [comment]
@jdneo I have tried setting `<testSourceDirectory/>` in multiple different Maven projects and it doesn't seem to make a difference. It's always empty unless I manually edit the .classpath file.

Note that I am using the default `src/test/java` paths in all of these projects.

**Comment by jdneo** [comment]
@dampcake It would be helpful if you could share a sample project to repro the issue. This would be helpful for us to investigate what is going on?

**Comment by dampcake** [comment]
https://github.com/dampcake/bencode (small single module Maven sample).
https://github.com/dampcake/incubator-druid/tree/fix-eclipse (large multi-module Maven).

I have tried adding `<testSourceDirectory/>` in the parent pom.xml as well as in each individual child pom.xml for multi module projects. After adding I have even tried cleaning the Java workspace and restarting. Nothing I do outside of modifying the `.classpath` file directly seems to have any impact.

**Comment by jdneo** [comment]
@dampcake I tried the first one and it works on my side. Here are some places that you may take a look:
- Is the auto build turned on?
   ![image](https://user-images.githubusercontent.com/6193897/61262276-50ebdf80-a7b7-11e9-9b32-7390e82d6f6b.png)
- Try to trigger compilation task before running the test to see if it could help. It's `F1` > `Java: Force Java Compilation` > `Full`
- Is there any output in the output channel?
  ![image](https://user-images.githubusercontent.com/6193897/61262377-9e684c80-a7b7-11e9-8c15-58c7aba1a28a.png)

**Comment by dampcake** [comment]
Still not able to enable it:
- Auto build is turned on.
- Triggering a full build made no difference.
- There is no output in the Java Test Runner output channel.

More info:
Java Test Runner version: 0.18.1
VSCode version: 1.36.1
OS: macOS 10.14.5
Java version: 1.8.0_201
Maven version: 3.6.0

Other things tried:
- running `git clean -fdX` and opening to regenerate everything
- cleaning the java server workspace

Screen shots:
![Screen Shot 2019-07-15 at 11 25 15 PM](https://user-images.githubusercontent.com/6202532/61268188-f4a5a300-a757-11e9-83ab-0e5b9e6e6a3a.png)
![Screen Shot 2019-07-15 at 11 25 54 PM](https://user-images.githubusercontent.com/6202532/61268196-f96a5700-a757-11e9-89fd-fc4ed61c84c9.png)
![Screen Shot 2019-07-15 at 11 26 51 PM](https://user-images.githubusercontent.com/6202532/61268223-0be49080-a758-11e9-97e8-cb8d5ac20a79.png)

**Comment by jdneo** [comment]
Hmmm, tried on Mac as well.
<img width="847" alt="Screen Shot 2019-07-16 at 1 38 25 PM" src="https://user-images.githubusercontent.com/6193897/61268761-10985b80-a7cf-11e9-8867-416009d8e251.png">

So far I've no idea what is going on. Would you mind to share the `.classpath` file that generated by the Java Language Server? You can find it at the root of your project.

**Comment by dampcake** [comment]
Here is the generated `.classpath` file:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.6">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" path="target/generated-sources/annotations">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="m2e-apt" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="target/generated-test-sources/test-annotations">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="m2e-apt" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
```

**Comment by jdneo** [comment]
One thing I observed is that test scope is missing in the generated file. Here is mine:
```xml
<classpathentry kind="src" output="target/test-classes" path="src/test/java">
    <attributes>
        <attribute name="optional" value="true"/>
        <attribute name="maven.pomderived" value="true"/>
        <attribute name="test" value="true"/>
    </attributes>
    ...
```

**Comment by dampcake** [comment]
Yes and if added manually like in https://github.com/microsoft/vscode-java-test/issues/470#issuecomment-444681714 it works, but it will not generate it with it in there. Was yours automatically generated like that?

**Comment by jdneo** [comment]
Yes it's automatically generated. Wired....

**Comment by tthorntone** [comment]
@jdneo Thanks for working this through with everyone! I'm experiencing another weird issue, related to this--

My .classpath does not by default generate the <attribute name="test" value="true"/> for my test sources, and my configuration is a bit complicated, so instead of a re-work I implemented this into my build.gradle:
`eclipse.classpath.file.whenMerged {
	def testSources = entries.findAll {element -> element.path == "src/test/java" || element.path == "src/test/resources" || element.path == "src/integrationTest/java" || element.path == "src/integrationTest/resources" }
  testSources.forEach { entry -> 
    entry.entryAttributes['test'] = 'true'
  }
}`

This adds the test attribute, but at the bottom, see here:
`<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/test/java">
		<attributes>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/test/resources">
		<attributes>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/integrationTest/java">
		<attributes>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/integrationTest/resources">
		<attributes>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
`

This does not work. However, if I let Eclipse do it , it generates the same xml, but with the test attribute at top, and it DOES work: 
`<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/test/java">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/test/resources">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/integrationTest/java">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/integrationTest" path="src/integrationTest/resources">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="gradle_scope" value="integrationTest"/>
			<attribute name="gradle_used_by_scope" value="integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
`

**Comment by jdneo** [comment]
@dampcake is your problem get resolved?

If the test attribute is still not auto generated in your `.classpath`, I suggest to file an issue in the Language Server repo: https://github.com/eclipse/eclipse.jdt.ls

**Comment by jdneo** [comment]
Thank you @tthorntone for reporting this. I find a potential bug in the implementation. Let's discuss it in @759

**Comment by dampcake** [comment]
@jdneo it's still not working on my macbook. I just tried opening a couple projects today in Ubuntu and it's working fine there. I will try to dig in later this week and see if I can figure out what's going on.

**Comment by rmgalante** [comment]
I am unable to see the tests in the Test Explorer. However, I can run the Maven test command as follows and that works.

mvn test -f "c:\Users\xxx\Documents\xxx\Java\gozer\pom.xml"

All the tests run to completion. Here is my configuration.

VS Code Version: 1.39.0 (user setup)
VS Code Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515

Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Java JDK 1.8.0.221
Language Support for Java	v 0.50.0
Debugger for Java	v 0.22.0
Java Test Runner	v 0.20.0
Maven 	v 3.6.2

I tried the solution in Issue 470, and it did not solve the problem.

The Test Explorer is blank, and none of the CodeLens links appear in my unit tests.

**Comment by jdneo** [comment]
@rmgalante Any output in your output channel? Or any thing you can see in the problems panel?

**Comment by rmgalante** [comment]
I've cloned the open source repo, gozer, at https://github.com/walmartlabs/gozer. You should be able to duplicate this problem with that open source repo.

The Problem panel is empty. "No problems have been detected in the workspace so far."

The output panels shows the following exception when I launch the project. It does not look relevant to the problem as it is just the FileWatcher exception.

Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.21.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: c:\Users\xxx\Documents\xxx\Java\VSCode\gozer
> git status -z -u
> git check-ignore -v -z --stdin
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Failed to watch ref 'c:\Users\xxx\Documents\xxx\Java\VSCode\gozer\.git\refs\remotes\origin\master', is most likely packed.
Error: ENOENT: no such file or directory, watch 'c:\Users\xxx\Documents\xxx\Java\VSCode\gozer\.git\refs\remotes\origin\master'
	at FSWatcher.start (internal/fs/watchers.js:164:26)
	at Object.watch (fs.js:1232:11)
	at Object.t.watch (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:594401)
	at T.updateTransientWatchers (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:98291)
	at l.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:539)
	at k.updateModelState (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:115979)

I can't use VS Code if I don't have a Task Runner. I hope this can be fixed.

**Comment by adeick** [comment]
I'm trying to figure out Debugging and Unit Testing for the first time. My class is using Eclipse, but I'd rather not download Eclipse if don't need to.
I have the Run/Debug Code Lense for the main method, but I do not have the Run Test/Debug Test Code Lense appearing on my Unit Test.

I'm not entirely sure where to edit the classpath. I have a bunch of .java files in a folder, but there isn't any .classpath file. I have my Visual Studio extensions stored in a completely different place on my computer. I have a .java file I want to use for testing, but it's not specified as a test file as far as I know.

I search for .classpath files in the File Explorer, and I found like 5 (they all look identical, I think they are for different versions of Java) 
The one I have looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-12"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```
And I changed the 2nd line to what it said above, but it didn't work and I don't really know what I'm doing

**Comment by jdneo** [comment]
@adeick If your project for teaching purpose and is not complicated, you can use the standalone project in VS Code Java:

1. Just create a new empty folder.
2. In this folder, all the required libraries can be put into a folder named `lib`

See: https://code.visualstudio.com/docs/java/java-project/lib.mp4

**Comment by jdneo** [comment]
@ybelenko I think it's because this project mixed with both Maven and Gradle, and the Java Language Server will import Gradle project by default.

I tried to disable the setting `java.import.gradle.enabled` and open the folder `/modules/openapi-generator`. The Code Lenses appear:

![image](https://user-images.githubusercontent.com/6193897/84385569-644f3700-ac22-11ea-8f7f-997793917a30.png)

**Comment by ybelenko** [comment]
@jdneo Thanks a lot!

I've checked, it works under `/modules/openapi-generator` folder with disabled option. 
Can I make it work somehow when VSCode opened with root directory?
