### ISSUE TITLE
Junit tests start configuration vmArg issue

### ISSUE THREAD

**Issue by akaFalsh** [Microsoft/vscode-java-test#476]
Dear community,

Started using java on vs code, but seems launch.test.json does not work for me.
I added such options:
```
{
    "run": {
        "default": "",
        "items": [
            {
                "name": "MyLib",
                "projectName": "MyLib",
                "workingDirectory": "c:\\Users\\User\\MyLib",
                "args": ["-Xms2G","-Xmx2G"],
                "vmargs": ["-Xms2G","-Xmx2G"],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    },
    "debug": {
        "default": "",
        "items": [
            {
                "name": "MyLib",
                "projectName": "MyLib",
                "workingDirectory": "c:\\Users\\User\\MyLib",
                "args": ["-Xms2G","-Xmx2G"],
                "vmargs": ["-Xms2G","-Xmx2G"],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    }
}
```
But after running test java does not take either args or vmargs to consideration.

**Comment by akaFalsh** [comment]
for launch.json everything works fine, but for Tests does not.
I am using VS Code 1.29.1 latest java test runner

**Comment by jdneo** [comment]
If you are triggering the test from Code Lens. You need to set the default field to the configuration item name to make it work.

For example, here set the `default` to `MyLib`

**Comment by jdneo** [comment]
Closing this issue since the experience of running/debugging with configuration has been changed.

More details can be found here: https://aka.ms/java-test-config
