### ISSUE TITLE
Runs forever, even completing tests

### ISSUE THREAD

**Issue by tainer** [Microsoft/vscode-java-test#482]
Hi, 

I create a new project using maven and 'spring-boot-blank-archetype'.
After that, i just kept the following code:

    //HelloController.java
    package com.tainer.soft.apptotest.core;
    import org.springframework.web.bind.annotation.RequestMapping;
    import org.springframework.web.bind.annotation.RestController;

    @RestController
    public class HelloController {
        @RequestMapping("/")
        String hello() {
            return "Hello World!";
        }
    }

And

    //HelloControllerTest.java
    @Test
    public void testHello() throws Exception {
        when().get("/").then()
                .body(is("Hello World!"));
    }

And then, running the testHello unit test, this messagem shown on the Java Test Runner Output:

> [INFO] @@<TestRunner-{"name":"testFinished", "attributes":{"name":"com.tainer.soft.apptotest.core.HelloControllerTest#testHello", "duration":"3398"}}-TestRunner>
> [INFO] @@<TestRunner-{"name":"testSuiteFinished", "attributes":{"name":"com.tainer.soft.apptotest.core.HelloControllerTest"}}-TestRunner>
> [INFO] @@<TestRunner-{"name":"testSummary", "attributes":{"message":"Total tests run: 1, Failures: 0, Skips: 0"}}-TestRunner>

while a popup "Running Tests..." runs forever, without finish the process.

Any idea?

tanks for your time

**Comment by jdneo** [comment]
@tainer What's your OS?

**Comment by amitlevy21** [comment]
I'm having the same issue, using Ubuntu 16.04 and also happen in Windows 10

**Comment by jdneo** [comment]
I found out a potential bug which might be the root cause of this issue and fixed it in #490 

@amitlevy21 Tried with the project that you provided. Now it won't always keep running any more.

The fix will be released with v0.12.0. If the issue still occurs after 0.12.0 get released. Feel free to comment here and let me know.

Thanks.

**Comment by tainer** [comment]
Hi @jdneo, i'm using win10.
