### ISSUE TITLE
Sort the classes and methods alphabetically in the test report

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#487]
The classes and methods in test report should be sorted alphabetically 
Now: 
![image](https://user-images.githubusercontent.com/22470312/49362208-257d1e80-f719-11e8-8c47-bfef91eddc2d.png)

**Comment by jdneo** [comment]
The order here is actually the order in which the functions are defined.

We can add another sort button if we have users thumb up for this issue.

**Comment by jdneo** [comment]
In 0.31.0, we support the newest VS Code testing API in 1.59.0.

The test report is removed, instead, you can use the test explorer to see the status, which supports different sorting:

![image](https://user-images.githubusercontent.com/6193897/128446274-c99d7722-4ef4-4143-bae6-80ba87c50000.png)
