### ISSUE TITLE
Test Plan

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-test#49]

**Comment by ansyral** [comment]
## Test explorer
1. open a folder, check language server is up
2. check `test explorer` is up
3. check hierarchy is correct
4. click on class level, editor jumps to specified file of the class
5. click on method level, editor jumps to specified range of the method
6. update test code, check whether test explorer is auto-synced

**Comment by ansyral** [comment]
## Test explorer of Multi-root

1. open a workspace that contains multiple projects
2. check test explorer hierarchy

**Comment by ansyral** [comment]
## Test report

1. test class's report: check whether filter radio('All tests', 'Passed', 'Failed') works.
2. verify bug #1 #2 #7 #23 #25

**Comment by ansyral** [comment]
## Multi module project

1. clone code from `https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples`
2. use vscode to open folder `spring-cloud-function-samples`, verify tests can be run/debug successfully

**Comment by ansyral** [comment]
## Test status bar
1. after triggering running/debugging tests, check whether status bar is synced
2. click on status bar item, check whether output panel would open.

**Comment by ansyral** [comment]
## Trigger tests from test explorer

trigger tests from every level: all tests/folder level/package level/class level/method level

**Comment by ansyral** [comment]
## Open Test Log command

1. make some operations like running tests, open test report, and so on.
2. command panel, choose "Java: Open Log", validate logs file could be opened

**Comment by ansyral** [comment]
## Config test report position

1. go to File->Preferences-> Settings, add config `"java.test.report.position": "currentView"`
2. run test, open test report, verify that the report opens in current view column.

**Comment by ansyral** [comment]
## JUnit5 test

1. clone junit projects from https://github.com/junit-team/junit5-samples
2. open the junit5 project, e.g. junit5-maven-consumer, this projects contain both junit4 and junit5 tests.  After tests are loaded, check whether codelens are ok, trigger tests from codelens, check status and report
3. trigger tests from test explorer, check whether it handles all the tests well

**Comment by ansyral** [comment]
## Test configuration

1. ctrl+shift+p open command panel, trigger command `Java: Edit test configuration`, configure projectname, workingdirectory, prelaunchtask
2. trigger tests from codelens/test explorer `Run with config`
3. debug a test, check variable evaluation works

**Comment by ansyral** [comment]
## Cancel a test run

1. start a test run that lasts for a long period, for example, run the whole tests in a project, or add `Thread.sleep` in your test.
2. click `Cancel` button on the notification message or from test explorer, verify the test run is stopped.

**Comment by ansyral** [comment]
## Run with default configuration

1. Edit test configuration, fill in `default` section with the name of the config that you specify as default configuration
2. Click `Run Test` codelens, verify the default configuration is picked(e.g. set up working directory in the config)

**Comment by ansyral** [comment]
## Class path is refreshed when build file(pom.xml, build.gradle) is updated

1. Edit pom.xml, remove a dependency.
2. Run test, it is expected to fail because some dependency cannot be resolved.
3. Edit pom.xml to add the dependency back and rerun the test.
4. test runs successfully

**Comment by jdneo** [comment]
Move to: https://github.com/Microsoft/vscode-java-test/wiki/Test-Plan
