### ISSUE TITLE
Code coverage test

### ISSUE THREAD

**Issue by emannuelalmeida** [Microsoft/vscode-java-test#493]
Issue Type: <b>Feature Request</b>

I'd like to request for the Test Runner to have "code coverage" option. It's very useful when you need to track wheter your code is being tested or not. I'm suggesting it for the Java Test Runner, cause it's what I'm using right now, but it could be for any language, since it doesn't seem to exist.

Extension version: 0.11.1
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

**Comment by jdneo** [comment]
Thanks for reporting. This is dup with #387.

I'm closing this issue for easy tracking. Feel free to vote for #387 by adding a 👍 in that issue.
