### ISSUE TITLE
Automatically pick the right configuration file

### ISSUE THREAD

**Issue by IMEVER** [Microsoft/vscode-java-test#496]
I have several projects in one vscode workspace.
When running test by "Code lens", it always use default configuration in launch.test.json.
I hope it can pick the right config by project name automatically.

**Comment by jdneo** [comment]
Hi @IMEVER:

We are planning to redesign the launch with configuration experience. Please feel free to let us know your thought in this issue: https://github.com/Microsoft/vscode-java-test/issues/524

thanks.

**Comment by jdneo** [comment]
Closing this issue since the experience of running/debugging with configuration has been changed. More details can be found here: https://aka.ms/java-test-config
