### ISSUE TITLE
Can't trigger command Java: Open Test Runner Log to show the log file

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#501]
Build: 366

Repro steps:
1. Open a Project in vscode and activating extension 
1. Run tests
1. Pre F1 and choose the command: Java: Open Test Runner Log

Result:
It always shows that the log file does not exist.
![image](https://user-images.githubusercontent.com/22470312/49569064-daa81480-f96d-11e8-9f1b-a5ca820ec5c4.png)

**Comment by jdneo** [comment]
Fixed. Please help verify in the newest build

**Comment by bsaby** [comment]
Test passed.
Build used: 369
