### ISSUE TITLE
Cannot always show test report in side view

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#502]
Build: 366

Repro steps:
1. config the report position as sideView
1. After running tests, open the test report through status icon or status bar and keep it open
1. Click on a status icon again

Result:
The position of the test report has changed to currentView
![image](https://user-images.githubusercontent.com/22470312/49569769-d0871580-f96f-11e8-8777-d2ce86fb3a46.png)

Expext:
The position should be sideView.
![image](https://user-images.githubusercontent.com/22470312/49569717-b0efed00-f96f-11e8-9296-e798648f16d5.png)

**Comment by jdneo** [comment]
Fixed
