### ISSUE TITLE
The methods number in the "All" button doesn't match the number of methods actually displayed

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#503]
Build: 366

Repro steps:
1. Select one method to run test
1. After running test, open test report through status icon of class level

Result:
The number in the "All" button is the number of all test methods under current class. 
Only methods that have been run in the current class are displayed in the panel
![image](https://user-images.githubusercontent.com/22470312/49573267-95d5ab00-f978-11e8-916b-f78684c71295.png)

**Comment by jdneo** [comment]
This issue should be addressed in `0.15.0`
