### ISSUE TITLE
All cases will be skipped when running tests

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#507]
Build: 366
Project: https://github.com/checkstyle/checkstyle
Configurations:
```
OS: Mac
Vscode: 1.29.1
Java: 11.0.1 or 1.8.0_181
```

Result:
![image](https://user-images.githubusercontent.com/22470312/49576727-d20d0980-f980-11e8-8f5d-df8050067117.png)

**Comment by jdneo** [comment]
Cannot repro in the latest bits.
