### ISSUE TITLE
Can't run test cases

### ISSUE THREAD

**Issue by rileyma** [Microsoft/vscode-java-test#508]
Installed Java Test Runner.
Tagged test methods with *Test* tag.
imported org.junit.*;
imported org.mockito.Mockito.*;

Can't run any of the tests from the method level. There's no "Run" button on either of the methods.

**Comment by jdneo** [comment]
Looks duplicated with #470 

Will your problem be solved according to the workaround mentioned in #470?

**Comment by JasonHenriksen** [comment]
I used the classpath fix in #470 which caused the test to appear. 
However, when I attempt to run the test is always says "skipped".  
It looks like the compiled tests don't go where the runner is expecting them?  There was an error saying "Can't have test code compiled to the same directory as main code" so I'm trying to sort out if the .classpath file is pointing things to a directory that they're not being searched for.
( Just leaving this for posterity as I try to find a workaround for the tests skipping)
