### ISSUE TITLE
Tokennization is skipped for lines longer than 20k characters for performance resons

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#511]
Build:369
Project: https://github.com/angelozerr/lsp4xml

How to repro?
Scenario1. open the project in vscode and run all tests, then open log file 
Scenario2. keep the log file in the active editor, run all tests
Scenario3. keep the log file in the editor but not the active one, switch to log file after running all tests

Result:
Only the first scenario will prompt the notification message in the lower right corner of the vscode. Others just display the message in the toggle developer tools.

![image](https://user-images.githubusercontent.com/22470312/49630663-156f8280-fa2a-11e8-8707-dddaff5166d5.png)
![image](https://user-images.githubusercontent.com/22470312/49630665-17d1dc80-fa2a-11e8-8fd1-6949116fc327.png)

**Comment by jdneo** [comment]
This is VS Code behavior and we could do nothing for now about this issue.
