### ISSUE TITLE
Add show test report command in the explorer context menu

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#518]

**Comment by SupinePandora43** [comment]
show test report(passed, failed, skipped) in test explorer?

**Comment by jdneo** [comment]
Hi @SupinePandora43,

The feature that you mentioned is tracked by #126

**Comment by jdneo** [comment]
In 0.31.0, we support the newest VS Code testing API in 1.59.0.

The test report is removed. But there is a new entry at the context menu of the editor decoration.

![image](https://user-images.githubusercontent.com/6193897/128446522-594948ed-9848-4449-8019-768083332319.png)
