### ISSUE TITLE
Support for TestNG

### ISSUE THREAD

**Issue by oakad** [Microsoft/vscode-java-test#53]
TestNG may be a bit of a niche, but it's a good and cozy niche to be in. Are there any plans to support it as well?

**Comment by ansyral** [comment]
@oakad TestNG is in our plan :smile:

**Comment by RogueHat** [comment]
@ansyral  Got an ETA for that?

**Comment by chrisaige** [comment]
When will we get this?

**Comment by tylerteem** [comment]
Will this happen?

**Comment by yahudev** [comment]
When will this happen?

**Comment by jdneo** [comment]
Hi @all,

We have added the TestNG support in the newest code base. It should be released recently. So I'm closing this issue for now.

**Comment by ANK-13** [comment]
Testng is not able to throwing class not found Error. Can Anyone help? In eclipse, it works fine

**Comment by jdneo** [comment]
@ANK-13 Sorry for this issue. The root cause is that the error handling mechanism needs to be improved.  We have an issue tracking that: https://github.com/Microsoft/vscode-java-test/issues/355
