### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by franciscocpg** [microsoft/vscode-java-test#531]
I was able to configure a keyboard shortcut to run **all project tests** with the following configuration at `keybindings.json`.
```json
(...)
 {
        "key": "ctrl+t",
        "command": "java.test.explorer.run",
        "when": "resourceLangId == java"
 }
(...)
```
But I want to be able to configure 2 more shortcuts to:
1. Run all tests from the current file
2. Run test from the current focused method

Is there a way to do so?

**Comment by jdneo** [comment]
@franciscocpg Unfortunately, there is no way to do this for now.

We will consider adding this support in the future.

**Comment by tkleczek** [comment]
Would be also nice to be able to configure shortcut to re-run last "Run test" command

**Comment by JasonHenriksen** [comment]
> Would be also nice to be able to configure shortcut to re-run last "Run test" command

I'm considering writing a PR to do exactly this.  Would the Test Runner team be open to a PR like that?

**Comment by jdneo** [comment]
@JasonHenriksen All the contributions are welcome! Please go ahead!

**Comment by jdneo** [comment]
Hi @JasonHenriksen, is everything works fine? Is there anything I can help with?

**Comment by jdneo** [comment]
Some new commands are introduced in the next release version 0.24.0, which you can set shortcuts for them:

- Open the test report: `java.test.show.report`
- Relaunch the test execution: `java.test.relaunch`

**Comment by baldimir** [comment]
Hi, any idea when this could be implemented? I see it is in backlog, just asking if you are at least considering this in near future.

**Comment by jdneo** [comment]
@baldimir The next release will have a new command to run the test in the current editing file. See: #1066

**Comment by baldimir** [comment]
Thanks, so what is left is a command to run a specific test from a file.

**Comment by jdneo** [comment]
New commands added in the `0.25.0` to run/debug the tests in current file:

- java.test.editor.run
- java.test.editor.debug

**Comment by jdneo** [comment]
In 0.31.0, we support the newest VS Code testing API in 1.59.0.

There are some new commands added, which are useful and cover the request of this issue, please have a try!

![image](https://user-images.githubusercontent.com/6193897/128446850-cb8d293e-f5d3-4fbe-bda4-c7c78153dc07.png)

**Comment by jscherer** [comment]
Love this :-)
Maybe someone should update the (https://code.visualstudio.com/docs/java/java-testing) documentation with a keyboard shortcut section, because it took me quite a while to find this info!
