### ISSUE TITLE
TestNG test cases will be skipped

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#537]
According to https://github.com/Microsoft/vscode-java-test/issues/504#issuecomment-445131893 by @bsaby 

The TestNG test cases will be skipped if triggering from workspace root level and workspace folder level.

## Root cause
In `com.mkyong.testng.examples.group.TestGroup`, some of the codes are commented. Release them will make the runner running successfully.

## How to fix
I will investigating if there is a way to let the runner run other tests no matter the usage of `dependsOnGroups`

**Comment by bsaby** [comment]
Now:
![image](https://user-images.githubusercontent.com/22470312/58298753-3fb5d080-7e0f-11e9-81bf-5bdd529318cd.png)
