### ISSUE TITLE
Tests can't be run correctly in multi-root workspace 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#541]
Bits: 389

Steps to repro:
1. Open a multi-root workspace in Vscode
1. Trigger test from one workspace folder level

**Result:**
Run all tests under current multi-root workspace

**Expect:** 
Only run the tests under current workspace folder

**Comment by jdneo** [comment]
@bsaby Fixed in the newest bits

**Comment by ZhengJun003** [comment]
Verify this issue in Build 390, it's fixed.
