### ISSUE TITLE
Unexpected value in property "user.dir" under TestNG

### ISSUE THREAD

**Issue by JasonHenriksen** [Microsoft/vscode-java-test#543]
![image](https://user-images.githubusercontent.com/40472779/50455389-8eb01600-0902-11e9-9b8e-baf24bc76838.png)

I was expecting the user.dir to be the root of my workspace.  
Instead, the user.dir is equal to my home directory.  
This causes relative file lookups to fail.

**Comment by jdneo** [comment]
Hi @JasonHenriksen 

I think set the `launch.test.json` can help with your problem. You can look into this issue for a reference: https://github.com/Microsoft/vscode-java-test/issues/476

Well, I have to admit that this feature is not well designed, so we are planning to change it in the near future, you can track the progress here: https://github.com/Microsoft/vscode-java-test/issues/524

It would be great if you could let us know your thoughts about the user experience. 😄

**Comment by JasonHenriksen** [comment]
Thanks for getting back to me!

It's much better than not being able to run our TestNG suite at all.   

I have hundreds of tests, so it doesn't make sense for me to have a launch config for all of them. For example:
![image](https://user-images.githubusercontent.com/40472779/50497475-bf6c7a00-09ec-11e9-9efb-f0c0be0ab7a3.png)

It would be handy if the tree allowed me to collapse by package section instead of having to see all of the irrelevant packages listed so many times.

Beyond that my main work flow is either to run an individual test, run all tests in a class, or all tests in a package.  If I can do all those and easily debug then I'm good to go.  I feel like this is close to being ready to go, but I'm not quite there yet.

That said it doesn't seem to be connecting to the debugger for me, so each test ends up saying "skipped".  (But I'm still working on getting it to go.)

For reference, I'm using this to run TestNG tests that my team is writing in IntelliJ to launch Selenium code.

**Comment by jdneo** [comment]
Thanks for the feedback. 👍  I saw three problems there, correct me if I'm wrong.

### Launch config problem
Could you please let me know the reason why one launch config is not suitable for you?

### Collapse by package section
Currently, the explorer will show all the package roots which are in the project's `test` classpath, for example, `src/test/java`. But sometimes, it is possible that a package is in the test classpath, but it does not contain any class that is able to test. Could you please describe more about the `irrelevant` packages?

### tests are skipped
The TestNG support is just added a few weeks ago, so it may have some issues for it. We fixed several bugs that may cause the tests are skipped recently in 0.13.0, which will be released soon. Let's revisit this problem if it still occurs in 0.13.0.

**Comment by JasonHenriksen** [comment]
That sums it up.  Thanks!
And I'm fine with one launch config, My only concern is that it can be used to run at package, class & test levels without having to do any re-config.

I'm really excited for this project and I'm happy to contribute if I can.  Let me know if there's anything I could lend a hand with.

**Comment by jdneo** [comment]
Closing this issue since the experience of running/debugging with configuration has been changed. Briefly speaking, you can set workingDirectory to update the `user.dir`.

More details can be found here: https://aka.ms/java-test-config.
