### ISSUE TITLE
Wrong working direcrtory 

### ISSUE THREAD

**Issue by neilghosh** [Microsoft/vscode-java-test#549]
My launch.test.json file has the following entry 

"workingDirectory": "/Users/userid/dev/project_dir",

But when I run the tests the files are created to the root directory of the machine i.e. "/" instead of relative to the working directory. My code works fine (files are created relative to the working directory ) when I run the tests from the command line .

Does the workingDirectory config really works?

**Comment by jdneo** [comment]
@neilghosh Is the `default` field set in your `launch.test.json`?

**Comment by neilghosh** [comment]
Yes this file as it was created when I installed the plugin and run/debug
from the editor itself .

**Comment by jdneo** [comment]
@neilghosh 

Would you mind to share your `launch.test.json`?

**Comment by jdneo** [comment]
Please try to set the `default` to `mypubsub` and let me know if this could help.

**Comment by neilghosh** [comment]
@jdneo that worked!

Thanks, I think I misread your first comment.

**Comment by neilghosh** [comment]
I have one more issue - I could create a new discussion for that.
I don't see the console logs when I run the tests in line. I do see them in the `output` window and select `Java Test Runner` in the dropdown but the text is not well formatted.

**Comment by jdneo** [comment]
Yes, the output should be better formatted. We have an issue tracking that: #505 

Thank you for your feedback! 😃
