### ISSUE TITLE
Support navigate to the source from the test report

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#558]
If a user finds a test case failed in the report, and want to take a look at the source code. It is difficult because he can not navigate to the source code from the report.

**Comment by Eskibear** [comment]
In the PR, I see an additional column is added to place the navigation button.

How about adding the listener directly to method names? Clicking on the method name looks more **straightforward**  to me.  Just my 2 cents, current behavior in the PR is totally ok to me.

**Comment by jdneo** [comment]
I prefer putting the navigation button in an additional column to expose this feature. Add listeners to the method names will somehow mix with expanding to see details
