### ISSUE TITLE
Test explorer not show functions, Run|Debug code lens showed only on main(String[] args)

### ISSUE THREAD

**Issue by SupinePandora43** [Microsoft/vscode-java-test#559]
Code lens Run|Debug work, but only for main function, and not show report(green/red).
Test explorer show: package->.java file->nothing, but in there place must stand function main()!!!

my java file:

package main;
import org.junit.*;
public class Main{
@Test
public static void main(String[] args){
System.out.println("Hello Test");
}
}

**Comment by jdneo** [comment]
@SupinePandora43 

Could you please provide a screenshot of your problem?

I do not quite understand your problem.

But from the source code you provided, this is not a valid JUnit 4 testable method because the method you are testing is a static one.

**Comment by SupinePandora43** [comment]
can you show Junit 4 valid test?

**Comment by jdneo** [comment]
@SupinePandora43 You may take this for reference: https://junit.org/junit4/javadoc/4.12/org/junit/Test.html

Please Note:
> The Test annotation tells JUnit that the public void method to which it is attached can be run as a test case.

The method which is annotated by `@Test` should not be `static`

**Comment by SupinePandora43** [comment]
thanks! but failed test icon in code lens have missing symbol icon
