### ISSUE TITLE
Watch expressions don't evaluate when test launched from debug code lens

### ISSUE THREAD

**Issue by shawmanz32na** [Microsoft/vscode-java-test#573]
None of my debugging watch expressions are evaluating when running my test(s) using the "Debug Test" code lens, claiming `Cannot evaluate because of java.lang.IllegalStateException: Cannot evaulate, please specify projectName in launch.json`. This occurs when debugging from the test class' lens and when debugging from the test method's lens.

![image](https://user-images.githubusercontent.com/5596570/50986086-bc788b80-14ba-11e9-85e3-a608ecacea37.png)

I'm not sure if error represents the root cause of the issue, as I didn't think the "Debug Test" code lens used a launch configuration from **launch.json**. In my project, at least, there is only one entry in **launch.json**, and it's an "Attach" configuration. As this is a Maven project, I've never before configured **launch.json** to launch a debug session for JUnit tests, and am therefore unable to verify if this is isolated to the "Debug Test" code lens or if it's a wider-spread problem.

I'm hoping this doesn't require a sample project to be able to reproduce, but I found this when running in a multi-project workspace, in a multi-module Maven project that leverages JUnit 5.

**Comment by andxu** [comment]
@jdneo Please add projectName in generated launching/debugging configuration of test cases, eclipse jdt will require them to perform evaluation(in eclipse attach/launch, projectName is required)

**Comment by jdneo** [comment]
@shawmanz32na The problem may be related to the `launch.test.json`.

The extension will read the project name from it. please check this file, then update the debug related field. For example:

```js
"debug": {
        // Set the default field to the name of configuration item that you want to make it active
        "default": "todo-app-java-on-azure",
        "items": [
            {
                "name": "todo-app-java-on-azure",
                "projectName": "todo-app-java-on-azure",
                "workingDirectory": "C:\\Users\\sheche\\Desktop\\todo-app-java-on-azure-master",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    }
```

BTW, we are planning to redesign the experience about run/debug with configuration. Users should not take care of the project name. You can track the status in #524
