### ISSUE TITLE
A question status icon will be added as the third Code Lens automatically for inner class

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#586]
### Build
416
### Steps:

1. Open a java file.
2. Trigger tests from the outer class codelens

OR
1. Open a java file and  and make sure you have the class with a status icon
2. Add a new inner class
3. Save file

### Result:
A question status icon will be added automatically for inner class
Screenshot1:
![image](https://user-images.githubusercontent.com/22470312/51307617-1eb52b80-1a7b-11e9-90cb-92240dcbff38.png)

Screenshot2:
![image](https://user-images.githubusercontent.com/22470312/51307366-8028ca80-1a7a-11e9-8a99-bd6339947ee0.png)

**Comment by jdneo** [comment]
@bsaby Please help verify it in the newest bits, thanks

**Comment by bsaby** [comment]
Build: 418
Test passed.
