### ISSUE TITLE
Junit5 test skipped

### ISSUE THREAD

**Issue by SupinePandora43** [Microsoft/vscode-java-test#591]
i use #470 fix.

i can run Junit4 test cases, but not Junit5.
if i write:
@org.junit.Test // passed
public void Junit4Test(){
assertEquals(1,1);
}
@org.junit.jupiter.api.Test // skipped
public void Junit5Test(){
assertEquals(1,1);
}
but if i write junit5 test first, junit5 and junit4 test's skipped
(junit5/4 from jar in test runner extension (included using .classpath))

**Comment by jdneo** [comment]
@SupinePandora43 Could you please provide a sample project? This could help to investigate the problem.

**Comment by SupinePandora43** [comment]
how add -n option to runner? i trying to create config(java.test.config), but i see 'Unrecognized option: -n'. @jdneo

**Comment by jdneo** [comment]
@SupinePandora43 How about changing the class name from `Main` to `MainTest`

**Comment by jdneo** [comment]
@SupinePandora43 By the way, during investigating the problem, I found a bug which will cause the problem `Unrecognized option: -n`, the tracking issue is here: https://github.com/Microsoft/vscode-java-test/issues/592

Thank you for let us know this problem!

**Comment by SupinePandora43** [comment]
@jdneo thanks, i just create class MainTest, but first trying add -n option to runner!
