### ISSUE TITLE
Debug Console will open when first debug test a project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#6]
Result:
![image](https://user-images.githubusercontent.com/22470312/33428270-1d957f56-d603-11e7-8dfa-f12df8f19656.png)

Expect:
![image](https://user-images.githubusercontent.com/22470312/33428289-3102fee2-d603-11e7-9b47-a3a63f4e859b.png)

**Comment by ansyral** [comment]
duplicate of #41
