### ISSUE TITLE
Some tests will be skipped when running lsp4xml project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#605]
This issue repro on Windows but works on Mac and Linux.

Project:  https://github.com/angelozerr/lsp4xml
**Trigger tests from workspace root or workspace folder, most of the tests are skipped.**
![image](https://user-images.githubusercontent.com/22470312/51887169-beed4780-23cd-11e9-8a2c-916dac67b0ac.png)

**Trigger tests from the following packages level, tests are skipped.**
Org.eclipse.lsp4xml.extensions.contentmodel
![image](https://user-images.githubusercontent.com/22470312/51887216-db897f80-23cd-11e9-922a-53b0e7153418.png)
Org.eclipse.lsp4xml.uriresolver
![image](https://user-images.githubusercontent.com/22470312/51887218-ddebd980-23cd-11e9-8663-4a817b621af5.png)

**Comment by jdneo** [comment]
Root cause is that the source code has errors, if remove the classes, these tests work fine.

So no more action for this issue.

Tracking #355 instead.
