### ISSUE TITLE
Sometimes an error occurs after clicking the navigation button

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#607]
#### Repro steps:

1. Open a project in vscode
2. Run tests and open the test report
3. click the navigation button in test report

#### Result:
Sometimes, an error occurs in toggle developer tools
Mac:
![image](https://user-images.githubusercontent.com/22470312/51887803-f4933000-23cf-11e9-88dc-37dff38662f0.png)
Windows:
![image](https://user-images.githubusercontent.com/22470312/51887827-08d72d00-23d0-11e9-983b-8c86352bef37.png)

**Comment by jdneo** [comment]
@andxu Would you mind to take a look at this?

**Comment by jdneo** [comment]
Closing because it's not related with the Test Runner extension.
