### ISSUE TITLE
Prompt user that a test session is currently running but actually there is no session before

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#608]
This issue is only found on Mac now.

#### Steps:

1. Open a test project in vscode.
2. Trigger some tests.

#### Result:
Occasionally, the extension will show the following message box. 
But in fact there is no test session before tests are triggered.

![image](https://user-images.githubusercontent.com/22470312/51885967-c9f1a900-23c8-11e9-84ef-aab7a3a469e6.png)

**Comment by jdneo** [comment]
Could repro but not stable. Need more investigation.

**Comment by mwiest** [comment]
I have this, too.
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by calvin1864** [comment]
I have this.  I can get it to recreate with Java.

1)  Create a project with a test
2)  Modify a source file so it won't compile
3)  Click Debug Test or Run Test
4)  Prompt pops up and says "Build failed"  so click "Abort"
5)  Fix the error
6)  Rerun the test
7)  Prompt appears and won't go away until you reload the window


It's like the Abort button doesn't cancel the thing tracking the test

**Comment by diddi-** [comment]
I had this same issue right now. Solved by using `Java: Cancel Test Job` command.
Open command palette <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and search for `Java: Cancel Test Job`

**Comment by calvin1864** [comment]
Thanks.  I'll use that.

I also posted in the Open issue #835 and created a PR to solve (at least one of) the issue(s)
