### ISSUE TITLE
Packages cannot be resolved

### ISSUE THREAD

**Issue by sh-tech** [Microsoft/vscode-java-test#616]
## Enviroment

- macOS Mojave 10.14.3
- Visual Studio Code 1.31.1
- Java Test Runner 0.14.0

## issue

I want to use jUnit 5 on VSCode so I use Java Test Runner. However after installation console display errors saying `can not be resolved` for jUnit5. How can I solve it?  Please tell me solution. I have finished setting Java's PATH.

## Images

![image](https://user-images.githubusercontent.com/32533860/52829551-9a54d780-3110-11e9-9303-f52872e3f1b5.png)
![image](https://user-images.githubusercontent.com/32533860/52829573-ae003e00-3110-11e9-98ce-2182c18aeab8.png)

**Comment by jdneo** [comment]
Looks like an issue related with Java Language Server.

@yaohaizh @testforstephen Could you please take a look?

**Comment by testforstephen** [comment]
@sh-tech Could you try the command below?
![image](https://user-images.githubusercontent.com/14052197/52830496-ddf91280-310b-11e9-8461-adecdbff8376.png)

**Comment by sh-tech** [comment]
@testforstephen  I have just executed that command. But, The result did not change anything.

**Comment by sh-tech** [comment]
Hum.. I will try it several times.

**Comment by testforstephen** [comment]
@sh-tech what's your project type? Can you use `tree` cli command to list the workspace structure?

**Comment by sh-tech** [comment]
@testforstephen 
This is a Gradle project using Java8.
Yes, I can. 
I used `tree -L 2`.

```
.
├── bin
│   └── jp
├── build
│   ├── classes
│   ├── generated
│   ├── jacoco
│   ├── reports
│   ├── test-results
│   └── tmp
├── build.gradle
├── gradle
│   └── wrapper
├── gradlew
├── gradlew.bat
├── settings.gradle
├── src
│   ├── main
│   └── test
├── target
│   ├── classes
│   ├── generated-sources
│   ├── generated-test-sources
│   └── test-classes
└── version.txt

20 directories, 8 files
```

**Comment by sh-tech** [comment]
I think that it is a problem of the Java Language Server, so I will move to that issue.

**Comment by testforstephen** [comment]
I don't see `.project` and `.classpath` files in your workspace, looks like your gradle project is not loaded by java language server.

Could you share the java server log via vscode command `Java: Open Java Language Server log file`?

**Comment by yaohaizh** [comment]
This issue was moved to redhat-developer/vscode-java#800
