### ISSUE TITLE
An error occurred after activating the extension

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#622]
### Version:
```
- Vscode: 1.31.1
- Java Test Runner: 0.4.1
```

### Repro Steps:
1. Install Java Test Runner extension in VScode
2. Reload it
3. Click Test Explorer to activate the extension

### Result:
An error occured in toggle developer tools
![image](https://user-images.githubusercontent.com/22470312/52943968-54ff0700-33a9-11e9-8536-fc5f1a2747c2.png)

**Comment by jdneo** [comment]
@Eskibear I guess you may want to take a look. It seems that we need to update the version of `vscode-extension-telemetry` in the wrapper.

**Comment by Eskibear** [comment]
Verified, should not be the wrapper's issue, via following facts:
- By disabling test runner, but leaving other extension which depends on the wrapper, the issue is gone. 
- By updating the wrapper's dependency, the issue still exists.

Any other possibility?

**Comment by bsaby** [comment]
According to https://github.com/Microsoft/vscode-java-debug/issues/538,  related to webpack?
