### ISSUE TITLE
Error command 'java.test.explorer.run' not found

### ISSUE THREAD

**Issue by Gueka** [Microsoft/vscode-java-test#624]
Hi,
I'm trying to run some java test using spring boot and the project dependency manager is gradle. 
I'm not able to see any test. The extension should auto detect my tests in my test folder or I'm missing a configuration?
I'm able to run my application successfully with vscode but when I try to run the test, there is no test shown in the Test section and when I try to force to run any test (clicking on the play button) I can see the legend "command 'java.test.explorer.run' not found"

![screen shot 2019-02-20 at 5 01 41 pm](https://user-images.githubusercontent.com/4095440/53127765-4fccc400-3531-11e9-915a-371d086d9c9b.png)

**Comment by jdneo** [comment]
Hmm... Most;y, the error `command 'xxx' not found` means the extension failed to startup.

Have no idea about it for now. Would you mind to share a sample project which can repro this issue with us for investigation?

**Comment by yaohaizh** [comment]
@Gueka Could you take a look at this? And mark the related the folder as test? @jdneo  https://github.com/redhat-developer/vscode-java/issues/797 Please see this issue whether need handle on test explorer?

**Comment by Gueka** [comment]
Hi everyone, I was trying to generate a project to reproduce this error, it looks like I had a previous vs code version. I updated it and work as a charm, sorry to bother and thanks for the help.
