### ISSUE TITLE
Can't set PATH environment variable on OSX

### ISSUE THREAD

**Issue by chuckb** [microsoft/vscode-java-test#626]
OSX 10.12.5
VSCode 1.31.1
Java Test Runner 0.14.1
JVM 11.0.2

My java project relies on several JNI libraries being loaded. The following configuration works on Windows 10. It does NOT on my mac.

```
  "java.test.config": [
    {
      "name": "includeNativesConfiguration",
      "workingDirectory": "${workspaceFolder}",
      "args": [],
      "vmargs": [],
      "env": { "PATH":"build/tmp/jniExtractDir"}
    }
  ],
  "java.test.defaultConfig": "includeNativesConfiguration"
``` 
When I use an absolute reference it makes no difference. Further, when print System.getenv("PATH") from within my test, I do not get my expected path.

**Comment by jdneo** [comment]
@chuckb 

The root cause might be here: https://github.com/Microsoft/vscode-java-test/blob/master/src/runners/baseRunner/BaseRunner.ts#L61 the `PATH` env in the config is overridden by the system `PATH` env.

But I'm confused about why windows works. Does your windows not have the `PATH` env?

**Comment by chuckb** [comment]
My Windows machine has a long PATH, but not the location specified in the java.test.config. And in fact, if I do not specify that additional path, I will get an UnsatisfiedLinkException on Windows.

All I can say is that I have the following three files that are required for my tests to run: ntcore.dll, ntcorejni.dll, wpiutil.dll. On Windows 10, when I run the test, it works. When I run on OSX, the test fails with an UnsatisfiedLinkException. If on Mac, I specify -Djava.library.path=/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir as a parameter for vmargs, then ntcorejni will load, however the other two will not, because they are dependencies of ntcorejni, and the OS loader will look to the PATH.

My guess is that Windows is ok with the relative reference and Mac is not. Dunno.

But, what I would REALLY, REALLY like (and I requested this in another ticket), is that ${workspaceFolder}, or some such substitution variable, would work in the env, vmargs, and args parameters, across all platforms. In this way, I can specify whatever paths for whatever resources I need (be it data files, jni or native executables, etc) relative to my project and have it not matter where my other developers put their project.

**Comment by chuckb** [comment]
And by the way, I know you guys are putting in the effort on VSCode. And I love the tool. Automated testing with codelens and test report support is the bomb. However, I have fought with getting it to work reliably for the past 6 months. I have been trying to get a group of students to develop testing skills, but every time they try to use integrated testing features, something goes wrong. This has led to the WPI organization to ask for removal of VSCode codelens testing support as a feature, because they can't deal with their large user community asking them why testing does not work.

So, rather than remove the feature, it would be great to put the pieces in to make it work reliably.

**Comment by jdneo** [comment]
@chuckb Thank you for your patience and enthusiasm for out extensions. Just as you said, the extension do have a lot of room for improvement. We will keep making it become better.

For the issue we are discussing, it looks like we need to support a new substitution in our settings, which could be `${env:XXX}`. This substitution will look for the value of the environment variables. After this substitution is supported, then we can specify the configurations as:

```
"env": { "PATH":"${env:PATH};build/tmp/jniExtractDir" }
```

> The path seperator used in the setting might be different depends on the OS type, Windows is `;`, Unix based is `:`.

Then, make sure the customized settings will always override the system settings. I think by doing this, the issue could be addressed.

Do you have any thoughts about this?

**Comment by chuckb** [comment]
That would enable you to keep the existing PATH and then add on to it, which is good. But I don't think that covers my specific use case, which is, I need to know what the current reference is to my root workspace (at least), and the root of the current project (ideally), so that I can construct absolute path references to resources within variables that get substituted at execution time.

**Comment by chuckb** [comment]
You can see (and download/build if you wish) the project in question at https://github.com/Team997Coders/2019DeepSpace

**Comment by jdneo** [comment]
Hmm, I'm a little bit confused here. To construct the current workspace folder path, why not using the `${workspaceFolder}/build/tmp/jniExtractDir`?

**Comment by chuckb** [comment]
Right, it does not work, or at least it didn't last I tried. And further, an absolute reference on Mac didn't work either. And I am talking about the PATH environment variable in the env parameter.

**Comment by chuckb** [comment]
I will try again both ways, on both platforms, and report back.

**Comment by chuckb** [comment]
Here are my results:

Test set up: Using https://github.com/Team997Coders/2019DeepSpace, go in to src/test/java/frc/robot/commands/DriveToDistanceIntegrationTest.java. Set a breakpoint on line 20. Click "Debug Test" above test.

Test runner settings in settings.json like so:

  "java.test.config": [
    {
      "name": "includeNativesConfiguration",
      "workingDirectory": "${workspaceFolder}",
      "args": [],
      "vmargs": [],
      "env": { "PATH":"build/tmp/jniExtractDir"}
    }
  ],
  "java.test.defaultConfig": "includeNativesConfiguration"

Windows 10, Test runner 0.41.1, VSCode 1.31.1, JVM openjdk version "11.0.1-redhat" 2018-10-16 LTS
OpenJDK Runtime Environment (build 11.0.1-redhat+13-LTS)
OpenJDK 64-Bit Server VM (build 11.0.1-redhat+13-LTS, mixed mode)

As written above, the debugger will step into my code and stop. If I take out the PATH in the env variable, the test fails with an `java.lang.UnsatisfiedLinkError: no ntcorejni in java.library.path`, which I would expect. If I put in `"PATH":"${workspaceFolder}/build/tmp/jniExtractDir"`, the test does work (it used to not).

Now on to Mac. OSX 10.12.5, Java Test Runner 0.14.1, VSCode 1.31.1, java version "11.0.2" 2019-01-15 LTS

With `"PATH":"build/tmp/jniExtractDir"`, UnsatisfiedLinkError: no ntcorejni. With `"PATH":"${workspaceFolder}/build/tmp/jniExtractDir"`, same thing. With `"PATH":"/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir"`, same thing. I also have reports from a colleague that Linux does not work either.

Hope this helps...

**Comment by jdneo** [comment]
@chuckb

Thank you for trying out. 

Just as we have discussed before, according to the current implementation, the system env will override the customized env: 
https://github.com/Microsoft/vscode-java-test/blob/master/src/runners/baseRunner/BaseRunner.ts#L61,

If we switch the overriding order, I guess the issue should somehow be fixed. Would you mind to help test it and let me know if things work well with the fix? You can use the following steps:
- `git clone https://github.com/Microsoft/vscode-java-test.git`
- `cd vscode-java-test`
- `git checkout cs/test`
- `npm install`
- `npm run build-plugin`
- `npm run vscode:prepublish`
Then open the folder in VS Code, click `F5` to start the debug session, you will see a new VS Code window, and you can open your project and run tests in that window to see if the problem is fixed or not.

Hope this could help.

Thanks.

**Comment by chuckb** [comment]
Be glad to help. Will do it in the morning and report back. Thanks!

**Comment by chuckb** [comment]
When I run `npm run build-plugin`, I get:

```
charles-benedicts-macbook:vscode-java-test chuck_benedict$ npm run build-plugin

> vscode-java-test@0.14.1 build-plugin /Users/chuck_benedict/Projects/vscode-java-test
> gulp build-plugin

/Users/chuck_benedict/Projects/vscode-java-test/gulpfile.js:69
gulp.task('install-java-language-server', async (done) => {
                                                ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at execute (/Users/chuck_benedict/Projects/vscode-java-test/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/Users/chuck_benedict/Projects/vscode-java-test/node_modules/gulp/node_modules/gulp-cli/index.js:175:63)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-plugin"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! vscode-java-test@0.14.1 build-plugin: `gulp build-plugin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-java-test@0.14.1 build-plugin script 'gulp build-plugin'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vscode-java-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build-plugin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vscode-java-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vscode-java-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chuck_benedict/Projects/vscode-java-test/npm-debug.log
```

**Comment by jdneo** [comment]
Oh, that should be caused by low version of node.js

**Comment by chuckb** [comment]
On a hunch that either my node.js or npm was badly out of date, I installed latest LTS (Version: 10.15.1 (includes npm 6.4.1)), deleted project, refetch from git, and now I get (on OSX):

```
[INFO] --- tycho-compiler-plugin:1.2.0:compile (default-compile) @ com.microsoft.java.test.plugin ---
[WARNING] Parameter 'useProjectSettings' is set to true, but preferences file '/Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/.settings/org.eclipse.jdt.core.prefs' could not be found!
[INFO] Compiling 19 source files to /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Java Test Runner :: Parent ......................... SUCCESS [  0.054 s]
[INFO] Java Test Runner :: Build Tools .................... SUCCESS [  0.546 s]
[INFO] Java Test Runner :: Plugin ......................... FAILURE [  1.800 s]
[INFO] Java Test Runner :: Runner ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.061 s
[INFO] Finished at: 2019-02-28T04:36:33-08:00
[INFO] Final Memory: 63M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.2.0:compile (default-compile) on project com.microsoft.java.test.plugin: Compilation failure: Compilation failure: 
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[1] 
[ERROR] 	/*******************************************************************************
[ERROR] 	^
[ERROR] The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[1] 
[ERROR] 	/*******************************************************************************
[ERROR] 	^
[ERROR] The type java.util.List cannot be resolved. It is indirectly referenced from required .class files
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[1] 
[ERROR] 	/*******************************************************************************
[ERROR] 	^
[ERROR] The type java.lang.Exception cannot be resolved. It is indirectly referenced from required .class files
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[1] 
[ERROR] 	/*******************************************************************************
[ERROR] 	^
[ERROR] The type java.lang.RuntimeException cannot be resolved. It is indirectly referenced from required .class files
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[22] 
[ERROR] 	import java.util.List;
[ERROR] 	       ^^^^^^^^^^^^^^
[ERROR] The import java.util.List cannot be resolved
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[24] 
[ERROR] 	@SuppressWarnings("restriction")
[ERROR] 	 ^^^^^^^^^^^^^^^^
[ERROR] SuppressWarnings cannot be resolved to a type
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[25] 
[ERROR] 	public class TestDelegateCommandHandler implements IDelegateCommandHandler {
[ERROR] 	             ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The hierarchy of the type TestDelegateCommandHandler is inconsistent
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[25] 
[ERROR] 	public class TestDelegateCommandHandler implements IDelegateCommandHandler {
[ERROR] 	             ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The type TestDelegateCommandHandler must implement the inherited abstract method IDelegateCommandHandler.executeCommand(String, List<Object>, IProgressMonitor)
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[25] 
[ERROR] 	public class TestDelegateCommandHandler implements IDelegateCommandHandler {
[ERROR] 	             ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Implicit super constructor Object() is undefined for default constructor. Must define an explicit constructor
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java:[27] 
[ERROR] 	private static final String GET_TEST_SOURCE_PATH = "vscode.java.test.get.testpath";
...deleted for brevity
[ERROR] List cannot be resolved to a type
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestItem.java:[126] 
[ERROR] 	this.paramTypes = paramTypes;
[ERROR] 	^^^^^^^^^^^^^^^
[ERROR] String cannot be resolved to a type
[ERROR] /Users/chuck_benedict/Projects/vscode-java-test/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestLevel.java:[16] 
[ERROR] 	public enum TestLevel {
[ERROR] 	            ^^^^^^^^^
[ERROR] Implicit super constructor Enum(String, int) is undefined for default constructor. Must define an explicit constructor
[ERROR] 448 problems (448 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.microsoft.java.test.plugin
[04:36:33] 'build-plugin' errored after 12 s
[04:36:33] Error: Command failed: ./mvnw clean package
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at gulp.task (/Users/chuck_benedict/Projects/vscode-java-test/gulpfile.js:20:8)
    at taskWrapper (/Users/chuck_benedict/Projects/vscode-java-test/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/Users/chuck_benedict/Projects/vscode-java-test/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-java-test@0.14.1 build-plugin: `gulp build-plugin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-java-test@0.14.1 build-plugin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chuck_benedict/.npm/_logs/2019-02-28T12_36_33_984Z-debug.log
charles-benedicts-macbook:vscode-java-test chuck_benedict$ 
```

**Comment by chuckb** [comment]
So I tried it on Windows 10. The Windows build complained that I did not have JAVA_HOME defined, so I did that. Build seems to be running. Interestingly, I do not have JAVA_HOME defined on OSX, but I got no complaint. So I will define that env var and try again on OSX.

**Comment by chuckb** [comment]
When I do `npm run vscode:prepublish`, is VSCode supposed to start, or do I start it from desktop? If from desktop, how do I know that all the bits I just did made it into the version installed on machine?

**Comment by chuckb** [comment]
On Windows 10, I started VSCode from desktop. Java Test Runner badge says "preview", so I assume local install contains fixed bits. Ran through all conditions. Setting env to `
"PATH":"${workspaceFolder}/build/tmp/jniExtractDir"` still works as expected.

I set JAVA_HOME on OSX to $(/usr/libexec/java_home) per Apple recommendations, deleted project, recloned, ran through your instructions, and I get the same error as https://github.com/Microsoft/vscode-java-test/issues/626#issuecomment-468258283

**Comment by jdneo** [comment]
@chuckb Ok, don't worry, I can provide a private build to you later.

**Comment by jdneo** [comment]
@chuckb sorry for the late reply. Please try the private build here: [vscode-java-test-0.14.1.zip](https://github.com/Microsoft/vscode-java-test/files/2930227/vscode-java-test-0.14.1.zip)

Before installation, plaese make sure:
- Rename the file `.zip` -> `.vsix`
- Remove all the files under: `$HOME/.vscode/extensions/vscjava.vscode-java-test-*`

**Comment by chuckb** [comment]
I followed your instructions below. On OSX, I still get the same behavior.

itInitializesDriveTrainPIDFromRobotMap
Failed
6ms

Message:

no ntcorejni in java.library.path: [/Users/chuck_benedict/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]

Stack trace:

java.lang.UnsatisfiedLinkError: no ntcorejni in java.library.path: [/Users/chuck_benedict/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at
java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
at
java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
at
java.base/java.lang.System.loadLibrary(System.java:1867)
at frc.robot.helpers.DriveTrainMocks.<clinit>(DriveTrainMocks.java:14)
	at frc.robot.commands.DriveToDistanceIntegrationTest.itInitializesDriveTrainPIDFromRobotMap(DriveToDistanceIntegrationTest.java:19)
	at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0
(Native Method)
	at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at
java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.microsoft.java.test.runner.junit4.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at com.microsoft.java.test.runner.junit4.CustomizedJUnit4CoreRunner.run(CustomizedJUnit4CoreRunner.java:45)
	at com.microsoft.java.test.runner.junit4.JUnit4Launcher.execute(JUnit4Launcher.java:30)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:53)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chuckb** [comment]
By the way, all settings used to run this test are available here: https://github.com/Team997Coders/2019DeepSpace

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jdneo** [comment]
@chuckb 

What if you write your config like this:
"java.test.config": {
    "env": {"PATH" : "/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir"},
    "vmargs": ["/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir"]
}

**Comment by chuckb** [comment]
Passing the directory as indicated for vmargs causes a java.lang.ClassNotFoundException.

If you mean pass -Djava.library.path=/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir in vmargs (with the path in env as you requested), then I get:

itInitializesDriveTrainPIDFromRobotMap
Failed
8ms

Message:

/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir/libntcorejni.dylib: dlopen(/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir/libntcorejni.dylib, 1): Library not loaded: libntcore.dylib Referenced from: /Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir/libntcorejni.dylib Reason: image not found

Stack trace:

java.lang.UnsatisfiedLinkError: /Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir/libntcorejni.dylib: dlopen(/Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir/libntcorejni.dylib, 1): Library not loaded: libntcore.dylib
  Referenced from: /Users/chuck_benedict/Projects/2019DeepSpace/build/tmp/jniExtractDir/libntcorejni.dylib
  Reason: image not found
	at
java.base/java.lang.ClassLoader$NativeLibrary.load0
(Native Method)
	at
java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
at
java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
at
java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
at
java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2649)
at
java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
at
java.base/java.lang.System.loadLibrary(System.java:1867)
at frc.robot.helpers.DriveTrainMocks.<clinit>(DriveTrainMocks.java:14)
	at frc.robot.commands.DriveToDistanceIntegrationTest.itInitializesDriveTrainPIDFromRobotMap(DriveToDistanceIntegrationTest.java:19)
	at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0
(Native Method)
	at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at
java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.microsoft.java.test.runner.junit4.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at com.microsoft.java.test.runner.junit4.CustomizedJUnit4CoreRunner.run(CustomizedJUnit4CoreRunner.java:45)
	at com.microsoft.java.test.runner.junit4.JUnit4Launcher.execute(JUnit4Launcher.java:30)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:53)

This is telling me that the path is still not being set.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jdneo** [comment]
Is the problem still there? @chuckb
