### ISSUE TITLE
Class level displays incorrect status icon

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#646]
### How to repro:
1. Open a java project and open a test java file containing multiple test methods
2. Trigger test from one method 

### Result:
![image](https://user-images.githubusercontent.com/22470312/53948629-34ea7a00-4103-11e9-8626-bcbc4cb58c28.png)

### Expect:
![image](https://user-images.githubusercontent.com/22470312/53948691-5c414700-4103-11e9-9891-c7f075689d27.png)

**Comment by jdneo** [comment]
@bsaby 

Fixed, please help verify in the newest bits.

Thanks.

**Comment by bsaby** [comment]
Test passed.
Build used: 442
