### ISSUE TITLE
The import junit cannot be resolved

### ISSUE THREAD

**Issue by fromsilence520** [Microsoft/vscode-java-test#649]
![image](https://user-images.githubusercontent.com/12153595/54003972-ef738e80-418e-11e9-9586-bb383c806ded.png)

TestCase cannot be resolved to a type
![image](https://user-images.githubusercontent.com/12153595/54003985-fdc1aa80-418e-11e9-9140-d0f7c6ee5810.png)

**Comment by jdneo** [comment]
Looks like an issue related with Java Language Server.

@yaohaizh @testforstephen Would you mind helping take a look?

**Comment by yaohaizh** [comment]
@fromsilence520 Could you provide a sample project?

**Comment by fromsilence520** [comment]
@yaohaizh After I deleted the .classpath file in the project, It no longer reported an error.
