### ISSUE TITLE
messy code in java test runner

### ISSUE THREAD

**Issue by panjrui** [Microsoft/vscode-java-test#652]
Issue Type: <b>Bug</b>

When I use Java Test Runner to run Java demo test. If  string contanis chinese character ,the Output panel print messy code.But I use main function to run Java app ,the Debug Console print right code,why ? plese tell me,Thanks.

![1 (1)](https://user-images.githubusercontent.com/37069868/54074649-1dacb780-42d0-11e9-9aa3-e2f0f591debd.png)
![1 (2)](https://user-images.githubusercontent.com/37069868/54074650-1edde480-42d0-11e9-8f3f-9781433d5502.png)

Extension version: 0.14.1
VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jdneo** [comment]
Duplicated with #632, looks like we have something to improve due to encoding.
