### ISSUE TITLE
No test file recognised with import org.junit.*;

### ISSUE THREAD

**Issue by foxpluto** [Microsoft/vscode-java-test#653]
Dear team,

I think I found a strange behaviour. 

If i write a test class importing Junit with
```
import org.junit.*;
```
the tests are not recognised by Java Test Runner.

If I change the import with:
```
import org.junit.Test;
```
all the test appears. 
Is this a bug? 

Regards,
S.

**Comment by jdneo** [comment]
Hi @foxpluto, 

Would you mind to share your code samples to help us diagnostic?

**Comment by foxpluto** [comment]
No problem,

here is my code: 

```java
package net.mediaset.statistiche;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.sql.ResultSet;
import java.sql.DriverManager;

import org.junit.Before;
import org.junit.Test;

public class QueriesTest{

    private static final Logger logger = LogManager.getLogger(QueriesTest.class);

    Queries queries;
    Connection sqlConn;
    Statement stmt;
    ResultSet rs;
    String databaseUrl = "jdbc:mysql://10.102.43.52:3306/regemesso";

     /**
     * inizializzazione della connesione al DB di test
     */
    @Before
    public void initialize() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(databaseUrl,"guest","guest");
        } catch (Exception e) {
            logger.error("C'è stato un problema nella connessione al server: " + e);
        }
    }

    /**
     * Test di retrieve della quantità di dati recuperati per intervallo di tempo
     */
    @Test
    public void dataVsDataDelRetrieveTest (){
        LocalDate fromTimestamp = LocalDate.parse("2018-11-01");
        LocalDate toTimestamp = LocalDate.parse("2018-12-01");
        ChronoUnit interval = ChronoUnit.DAYS;
        queries.dataVsDataDelRetrieve(sqlConn, fromTimestamp, toTimestamp, interval);
    }
}
```

With this code I have the possibility to run the test:
![Screenshot 2019-03-15 at 09 56 33](https://user-images.githubusercontent.com/26223813/54419834-abd9d100-4708-11e9-94b6-c1219d3ca0ac.png)
![Screenshot 2019-03-15 at 09 55 55](https://user-images.githubusercontent.com/26223813/54419851-b3997580-4708-11e9-95fb-7bbc72fefe9c.png)

If I modify the code importing `junit` library with the star:
```java
package net.mediaset.statistiche;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.sql.ResultSet;
import java.sql.DriverManager;

import org.junit.*;

public class QueriesTest{

    private static final Logger logger = LogManager.getLogger(QueriesTest.class);

    Queries queries;
    Connection sqlConn;
    Statement stmt;
    ResultSet rs;
    String databaseUrl = "jdbc:mysql://10.102.43.52:3306/regemesso";

     /**
     * inizializzazione della connesione al DB di test
     */
    @Before
    public void initialize() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(databaseUrl,"guest","guest");
        } catch (Exception e) {
            logger.error("C'è stato un problema nella connessione al server: " + e);
        }
    }

    /**
     * Test di retrieve della quantità di dati recuperati per intervallo di tempo
     */
    @Test
    public void dataVsDataDelRetrieveTest (){
        LocalDate fromTimestamp = LocalDate.parse("2018-11-01");
        LocalDate toTimestamp = LocalDate.parse("2018-12-01");
        ChronoUnit interval = ChronoUnit.DAYS;
        queries.dataVsDataDelRetrieve(sqlConn, fromTimestamp, toTimestamp, interval);
    }
}
```

The test is not recognised anymore:
![Screenshot 2019-03-15 at 09 59 13](https://user-images.githubusercontent.com/26223813/54419942-02dfa600-4709-11e9-983f-9ca3dfc5cf3f.png)
![Screenshot 2019-03-15 at 09 59 02](https://user-images.githubusercontent.com/26223813/54419954-083cf080-4709-11e9-8790-13efc21ccb30.png)

Thanks,
S.

P.S. the code of the test is not really working but for the sake of the explanation should be enough.

**Comment by jbrackin01** [comment]
See the same issue.  The tests are recognised when I add specific import for:
import org.junit.Test; 

VS Code version 1.31.1

**Comment by visahannula** [comment]
For me this issue started with 0.15.0. When I use "Install another version" and roll back to 0.14.1, tests work again.

![image](https://user-images.githubusercontent.com/46907790/54462824-b1bbca80-4779-11e9-8458-c34880b8769b.png)

VSCode:
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by jdneo** [comment]
Thank you all for reporting this, I'll take a look!
