### ISSUE TITLE
How to use JUnit in VSCode

### ISSUE THREAD

**Issue by Yi-yi** [Microsoft/vscode-java-test#658]
It's a question from beginners. I use JUnit in eclipse and IntelliJ. Both of them are designed for JAVA so it's not difficult to find tutorials about setting JUnit environment. But I cann't find any detailed solution on github or stackoverflow. When I insert the `import static org.junit.Assert.*;` at the front of the file, there's an error `The import org.junit cannot be resolved`.

I've downloaded `JUnit.jar`, how to import it into VSCode and configure the classpath of it? Thank you.

**Comment by jdneo** [comment]
Hi @Yi-yi,

Thank you for trying out our extension. May I ask what kind of project is it?
- Is it a Maven project?
- Or is it a Gradle project?
- Or is it an Eclipse/IntelliJ project?

In other words, how do you manage your dependencies within your project, like JUnit? 

// cc @yaohaizh

**Comment by Yi-yi** [comment]
> 
> 
> Hi @Yi-yi,
> 
> Thank you for trying out our extension. May I ask what kind of project is it?
> 
>     * Is it a Maven project?
> 
>     * Or is it a Gradle project?
> 
>     * Or is it an Eclipse/IntelliJ project?
> 
> 
> In other words, how do you manage your dependencies within your project, like JUnit?
> 
> // cc @yaohaizh

Sorry I'm not sure what kind of project it is. It's the java file I create originally/directly from VSCode.

**Comment by jdneo** [comment]
Hmm, if you don't mind, is it possible for you to share your project with us?

**Comment by Yi-yi** [comment]
[JunitVSCode.zip](https://github.com/Microsoft/vscode-java-test/files/2983163/JunitVSCode.zip)
It's a 'HelloWorld' project I create to test/practise `Junit` in VSCode. In the `AppTest.java`, errors: `The import org.junit cannot be resolved` 

Should I modify/configure the files of '.classpath' and '.project'? Or, import the 'junit.jar' into the project?

Thank you.

**Comment by SupinePandora43** [comment]
i'm recommend you use gradle project. its a easy way to run test's, just include junit in build.gradle

**Comment by jdneo** [comment]
Thank you @SupinePandora43. 

@Yi-yi Yes, As @SupinePandora43 has said, for now, using the build tool: Maven/Gradle could be a workaround to solve your problem.

**Comment by jdneo** [comment]
Closing since this issue is duplicated with #348 

@Yi-yi Sorry that the extension does not support the project without the build tools(Maven/Gradle). For now, you can try to add Maven/Gradle into the project, or wait for us resolving #348

**Comment by niccolomineo** [comment]
Hi, I have the same issue. How to sort this out? I put the junit.jar file in a /lib directory at the same level as my proejct's /bin and /src, but to no avail. If that's correct, I understand I have to set up the classpath. But how to do that?

**Comment by SupinePandora43** [comment]
@niccolomineo 
> ![demo](https://user-images.githubusercontent.com/6193897/55700331-740d3300-5a01-11e9-8f67-cf3f6dcfcfde.gif)

you need:
workspaceFolder -> 
/lib -> junit.jar
/yourClass.java

(yourJavaFile and lib folder in one folder)

**Comment by niccolomineo** [comment]
Hi, thanks, done that, but I am still getting "The import org.junit cannot be resolve".

**Comment by jdneo** [comment]
Thank you for the help @SupinePandora43.

@niccolomineo If you still have the classpath problem, that might be related with the Java Language Server. Could you please try to trigger the command `Java: Clean the Java Language Server workspace` > `Restart and delete`.

**Comment by niccolomineo** [comment]
> Thank you for the help @SupinePandora43.
> 
> @niccolomineo If you still have the classpath problem, that might be related with the Java Language Server. Could you please try to trigger the command `Java: Clean the Java Language Server workspace` > `Restart and delete`.

Thank you jdneo, unfortunately doing so doesn't have any effect. 

- Do I need to add anything to my Bash Profile?
- Is the junit.jar filename expected to be in a certain way?
- Do I need to change anything in VSCode's configuration?
- Do I need any other plugin besides Java Test Runner?

Thank you.

**Comment by SupinePandora43** [comment]
@niccomineo try to open `battleship` folder as workspace

**Comment by niccolomineo** [comment]
Ok, now that seems to work, thank you, but I get:

<img width="466" alt="Schermata 2019-06-22 alle 10 35 22" src="https://user-images.githubusercontent.com/5409469/59961553-8dd6f600-94d9-11e9-9ecc-83afbf0fd172.png">

**Comment by niccolomineo** [comment]
Ok, that seems to get rid of the JUnit-related errors, thank you! Now I get this message, though:

<img width="466" alt="Schermata 2019-06-22 alle 10 35 22" src="https://user-images.githubusercontent.com/5409469/59961553-8dd6f600-94d9-11e9-9ecc-83afbf0fd172.png">

Should also the `.classpath` file be in the workspace?

Also, when I click on the play arrow in Test Explorer nothing happens.

**Comment by SupinePandora43** [comment]
try to move all your files/folders in workspace to previous workspace folder
> <img alt="Schermata 2019-06-22 alle 10 17 57" width="190" src="https://user-images.githubusercontent.com/5409469/59961374-1902bc80-94d7-11e9-92a2-0398644745bd.png">

structure like:
workspace
| .vscode
| lib
.. | junit.jar
| BattleCruiser.java
| OceanTest.java
(".." for indent)

**Comment by niccolomineo** [comment]
Ok, I put the `.vscode` folder in the `src/battleship` folder. The latter is now my workspace folder. 

- What should be in `launch.json`?
- Also, I have a `.classpath` and `.project` file where `/bin` and `/src `are. Where should it go and what should be in them?
- what shou
- what module should I import in each `.java` file?

**Comment by SupinePandora43** [comment]
@niccolomineo NO, i tryed say to don't use `src/battleship` folder!

**Comment by niccolomineo** [comment]
Can you please attach a dummy project so that I can see what it should be like? It should be able not only to run tests but also to compile java classes. Thanks.

**Comment by SupinePandora43** [comment]
@niccolomineo wait ~5 minutes

**Comment by SupinePandora43** [comment]
@niccolomineo 
[dummy.zip](https://github.com/microsoft/vscode-java-test/files/3316879/dummy.zip)

**Comment by niccolomineo** [comment]
Thanks, it works now and I'd suggest to somehow add this dummy project to the docs.
In addition, all those having issues may install Eclipse and create a workspace/project to check how to include all paths properly, specifically in `.classpath`.

**Comment by niccolomineo** [comment]
Thanks, it works now and I'd suggest to somehow add this dummy project to the docs.
In addition, all those having issues may install Eclipse and create a workspace/project to check how to include all paths properly (particularly in `.classpath`).

**Comment by niccolomineo** [comment]
Thanks, it works now and I'd suggest to somehow add this dummy project to the docs.
In addition, all those having issues may install Eclipse and create a workspace/project to check how to include all paths properly (particularly those in and related with `.classpath`).

**Comment by jdneo** [comment]
Thank you @SupinePandora43 again for your great work and contribution! Well done!! 👍 

@niccolomineo Thank you for your advice, we will consider it!

**Comment by edelauna** [comment]
> [JunitVSCode.zip](https://github.com/Microsoft/vscode-java-test/files/2983163/JunitVSCode.zip)
> It's a 'HelloWorld' project I create to test/practise `Junit` in VSCode. In the `AppTest.java`, errors: `The import org.junit cannot be resolved`
> 
> Should I modify/configure the files of '.classpath' and '.project'? Or, import the 'junit.jar' into the project?
> 
> Thank you.

Adding this line to the `.classpath` folder worked for me:

    <classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/4"/>

**Comment by jdneo** [comment]
@edelauna It's not recommended to modify the `.classpath` file. Instead, you can put the jars into the `lib` folder.

https://code.visualstudio.com/docs/java/java-project#_adding-external-jar

**Comment by MrYakobo** [comment]
Just for clarity, here is the file structure from the dummy zip by @niccolomineo, if someone don't want to download a zip file

![dummy](https://user-images.githubusercontent.com/11942597/92918910-2257ac00-f430-11ea-90b4-9a9839ceec42.png)
