### ISSUE TITLE
Automatically add --enable-preview to vmargs, when necessary

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-java-test#669]
Following on https://github.com/redhat-developer/vscode-java/issues/671, when trying to test Java 12 code using preview features, you need to add the `--enable-preview` flag in the test configuration's `vmargs`, in settings.json:
```json
    "java.test.config": [
        {
            "name": "java12",
            "workingDirectory": "${workspaceFolder}",
            "vmargs": [ "--enable-preview" ],
        },
    ],
    "java.test.defaultConfig": "java12"
```

This could be done automatically by the vscode-java-test extension. Also see https://github.com/Microsoft/vscode-java-debug/issues/553

**Comment by yllekz** [comment]
+1 to this. This has been driving me crazy. Programs previously functioning under JDK 8 suddenly give me all this hassle under JDK 12.

**Comment by ccescobar** [comment]
+1

**Comment by stubifox** [comment]
+1 :)
