### ISSUE TITLE
The status code lens of the class is displayed incorrectly

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#671]
Bits: 454
First, make sure there are only two methods in your test class.
### Repro Steps:
1. Trigger test from one test method
![image](https://user-images.githubusercontent.com/22470312/55314334-81c03700-549c-11e9-8515-ebd90e18a80d.png)
2. Delete or comment the test method.

### Result:
![image](https://user-images.githubusercontent.com/22470312/55314381-9ac8e800-549c-11e9-9c74-ffeaceba97bc.png)

**Comment by jdneo** [comment]
This has been fixed in recent refactoring.
