### ISSUE TITLE
Test working directory not set correctly for multi-module Maven projects

### ISSUE THREAD

**Issue by jaydee864** [microsoft/vscode-java-test#675]
VS Code Version 1.33.0
Java Test Runner version 0.15.1
Maven for Java version 0.16.0
OS: Windows 10 Enterprise 1803

Steps to repro:

1. Clone https://github.com/jaydee864/multi-module-test-repro
2. Run `mvn test` -- this should succeed.
  a. output from print statements (where I print `System.getProperty("user.dir")`):
     1. FirstExampleTest -- (parent directory)`\multi-module-test-repro\first`
     2. SecondExampleTest -- (parent directory)`\multi-module-test-repro\second`
3. Open project in VS Code, let the workspace build, then run the unit tests from the Test Explorer or from Code Lens. -- the tests fail on my machine.
  a. output from print statements in the Java Test Runner console:
     1. FirstExampleTest -- (parent directory)`\multi-module-test-repro`
     2. SecondExampleTest -- (parent directory)`\multi-module-test-repro`

I've tried creating a `.vscode\settings.json` inside each module root (so `first\.vscode\settings.json` and `second\.vscode\settings.json`), setting up "java.test.config" for each module individually, with workingDirectory set to `"${workspaceFolder}\\first"` and `"${workspaceFolder}\\second"`, respectively, but that doesn't seem to fix the issue.

Is there something I'm missing that would set the workingDirectory correctly for each module, like a variable I could use?

**Comment by rdcoe** [comment]
I have exactly this same problem.  I was trying to fix it by using the java.test.config settings but have not had success.

**Comment by jdneo** [comment]
Hi all,

Sorry for my late reply and thank you @jaydee864 for providing the source code to help me repro.

To solve this problem, you can import your projects in the `multi-root` way, which means:
1. First Open the folder `\multi-module-test-repro\first` in your VS Code.
2. In the File Explorer, right click on a blank area, and you can find an option named `Add Folder to Workspace...`:
![image](https://user-images.githubusercontent.com/6193897/57842141-83507f00-77fe-11e9-9416-f8dbb074c1f0.png)
3. Select the folder `\multi-module-test-repro\second`
4. Now you have imported the two folders as `multi-root` mode in VS Code, just as the following screenshot:
![image](https://user-images.githubusercontent.com/6193897/57842314-cf9bbf00-77fe-11e9-90cb-f54f045db238.png)

By doing this, your workspace will have two workspace folders, and thus, the `${workspaceFolder}` will point to `\multi-module-test-repro\first` and `\multi-module-test-repro\second` separately. And you will find all the test cases work fine.

![image](https://user-images.githubusercontent.com/6193897/57842415-083b9880-77ff-11e9-8129-52fbd25b3045.png)

**Comment by jaydee864** [comment]
Hi @jdneo,

Thank you for your suggestion. I have tried it and confirmed that it fixes the working directory issue, but unfortunately, I ran into another error in the code base from which I first discovered this. In my original code base, I have a dependency on environment variables in my application, which for the most part we can ignore, except the one environment variable which we need to parse to an integer. That line fails due to the fact that int values cannot be null. I tried adding settings.json files for each of my modules, but I started seeing an ENOENT error when running the Java Test Runner. I commented out the workspaceDirectory lines in those configs, and that fixed the environment variable, but broke the workspaceDirectory again.

I've updated multi-module-test-repro with a test case for per-module environment variables. Please let me know if you would prefer I raise a new issue for this case.

Thanks,
jaydee864

**Comment by jdneo** [comment]
Hi @jaydee864, 

I guess there might be some misunderstanding here. The `${workspaceFolder}` is a variable which will always point to the path of the workspace folder. Here the difference between `single-root` and `multi-root` is:
- single-root: when you directly open `multi-module-test-repro` in VS Code, your workspace only contains one folder, in that case, the `${workspaceFolder}` will point to `multi-module-test-repro`
- multi-root: when you add both `multi-module-test-repro/first` and `multi-module-test-repro/second` into VS Code. now your workspace has two workspace folders. And now, the `${workspaceFolder}` in the different folders has different meanings. So you can just change your settings as follow:

```jsonc
"java.test.defaultConfig": "first",
  "java.test.config": {
    "name": "first",
    "projectName": "multi-module-test-repro",
    "workingDirectory": "${workspaceFolder}",
    "args": [],
    "vmargs": [],
    "env": {
      "SOME_INTEGER": "10"
    },
  }
```

You were getting the ENOENT error is because `${workspaceFolder}\\first` is equal to `<some path>\\multi-module-test-repro\\first\\first`. And there is no such folder actually.

**Comment by jaydee864** [comment]
Hi @jdneo,

Ah, you're right, it does work as expected once I remove the sub-folders! Thank you for clearing up my misunderstanding.

Thanks,
jaydee864

**Comment by efredriksson-modelon** [comment]
I also ran into this problem. It would be nice if the Java Test Runner could use Maven to check what working directory should be used if no `workingDirectory` is given.
