### ISSUE TITLE
Can't update classpath unless reloading vscode window

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#677]
### Environment:
```
OS: Windows/Linux
JDK: 8
Java Test Runner Extension: 0.16.0
```
### Repro steps:
1. Create an empty folder
2. Create a java test file and write some test case.
2. Add the dependency jar file into the lib folder.
3. Force build
### Result:
Build failed but works after reloading VSCode window.
![image](https://user-images.githubusercontent.com/22470312/55793053-9af86180-5af4-11e9-9f82-2606cad70ae2.png)

**Comment by jdneo** [comment]
@yaohaizh @testforstephen

**Comment by jdneo** [comment]
Tracking in https://github.com/redhat-developer/vscode-java/issues/882
