### ISSUE TITLE
Support Groovy

### ISSUE THREAD

**Issue by gabloe** [microsoft/vscode-java-test#678]
My maven config is working fine for running JUnit tests against a groovy codebase, but the Java test runner does not show any test content.  Does it depend on the file extension being .java?

**Comment by jdneo** [comment]
Hi @gabloe, 
Yes, so far the Java Test Runner only supports Java language.

**Comment by asharron** [comment]
Hey! I would also like groovy support for unit tests, as I use groovy for my tests at work. 

How much work would this take? 

I would be willing to help out if we could break this up into smaller tickets, or at least have a general outline for what would need to be completed.

TL;DR I want to help, but need a few pointers on where to get started.

**Comment by jdneo** [comment]
Hey @asharron

Thank you for your enthusiasm! Briefly speaking, the Java Test Runner depends on [Java Language Server](https://github.com/redhat-developer/vscode-java) to resolve project information. To support Groovy, I guess we need first find out how to resolve the Groovy project information first. So far I have no idea how to achieve that. 😞

**Comment by jdneo** [comment]
@asharron.

Exactly, and that's at least of what we need. Actually, things might become more complex, since the Groovy Language Server needs to have some APIs exposed that the Test Runner can leverage. For example, calculate the classpaths of the project.

**Comment by natewaite** [comment]
https://github.com/prominic/groovy-language-server

**Comment by jdneo** [comment]
So far the Java Test Runner depends on Java Language Support (aka Java Language Server), which only support Java Language.

To support Groovy, there must have a language server which can understand Groovy, which is beyond our scope for now.

I'm closing this issue for now, but it does **NOT** mean that we won't support that. Once the requirements are ready, we can still revisit this item.

Thank you for understanding.
