### ISSUE TITLE
Test Explorer not displaying any java tests, but tests run successfully

### ISSUE THREAD

**Issue by marvingreenberg** [Microsoft/vscode-java-test#680]
I have tried this with several different projects.  I am currently using java test runner 0.16.0 (but also tried 0.15.0 and 0.15.1), along with Java Debugger 0.17.0 and Language Support for Java  0.43.0

The (24) tests run from the test explorer if I select "run tests".  But no tests are displayed in Test Explorer.  I have observed the same behavior in classes using junit4 and junit5 style tests.  Selecting "Refresh" on Test Explorer does not have any effect, and no output is evident when "Refresh" is selected.

![explorer_no_test](https://user-images.githubusercontent.com/216707/56516130-af325a80-6507-11e9-8329-d2aa7f1367f1.png)

Similarly, CodeLens does not display any option to run/debug the individual tests.

![codelens_no_test](https://user-images.githubusercontent.com/216707/56516434-68913000-6508-11e9-96c1-f00e3277ef7c.png)

With the developer tools window open, no messages are displayed that seem relevant.

**Comment by jdneo** [comment]
Hi @marvingreenberg,

Will this workaround help solve your problem?

**Comment by marvingreenberg** [comment]
```this?```  Did your comment drop a link reference?

**Comment by jdneo** [comment]
@marvingreenberg Sorry, my bad. https://github.com/Microsoft/vscode-java-test/issues/470#issuecomment-444327456

**Comment by marvingreenberg** [comment]
Yes, work around is fine. Thanks! This is a duplicate of #470, essentially.
