### ISSUE TITLE
Latest releases do not contain `vsix` files

### ISSUE THREAD

**Issue by ibuziuk** [Microsoft/vscode-java-test#684]
Latest 0.15 / 0.16 releases do not contain the `vsix` files.. Will it be possible to add the `vsix` files also for the latest releases to make it consistent with previous ones e.g. 0.14.1 ? 

[1] https://github.com/Microsoft/vscode-java-test/releases
[2] https://github.com/Microsoft/vscode-java-test/releases/tag/0.14.1

**Comment by jdneo** [comment]
Thank you for the suggestion. The vsix files have been added.
