### ISSUE TITLE
Add support for showing the Test Report below the current editor window

### ISSUE THREAD

**Issue by sjetha-pason** [microsoft/vscode-java-test#687]
My development monitor is in portrait orientation. Having the Report open to the right side of the current editor just squishes a lot of content into a small space. Changing it to appear inside the editor is a nice alternative but a better alternative would be to allow the report runner to appear below the current editor window, possibly in the same window as the Output and Terminal appear in, but even if it's between this and the editor itself, that would be a good alternative.

**Comment by jdneo** [comment]
Hi @sjetha-pason 

Thank you for reporting this to us. Unfortunately. As far as I know, so far the VS Code does not have the API to put the column in the bottom position.

But there still can have some workaround for your issue:
1. update the setting `java.test.report.position` to `currentView`, then the report will always show in the active column.
2. Move the report to the bottom and do not close it. See:
![demo](https://user-images.githubusercontent.com/6193897/57499374-10cd3400-7312-11e9-9673-a84e04c3c002.gif)
