### ISSUE TITLE
JUnit4 parameterized test fails

### ISSUE THREAD

**Issue by GeraldNDA** [microsoft/vscode-java-test#693]
Simplified definition:
```
package tests
import org.junit.Test;
import org.junit.runners.Parameterized;
import org.junit.runner.RunWith;
...

@RunWith(Parameterized.class)
public class TestClass {
       ...
       public TestClass(..) {
		...
	}

	@Parameterized.Parameters
	public static Collection<Object[]> files() {
		...
	}

	@Test
	public void test() {
		...
	}


        public static boolean run() {
		...
	}

	public static void main(final String[] args) {
		run();
	}
}
```

Results in (simplified error) when doing trying to find all errors:
```
org.junit.runner.manipulation.Filter
initializationError
Failed
2ms
Message:
No tests found matching Method test(tests.TestClass) from org.junit.internal.requests.ClassRequest@5eb5c224
Stack trace:
java.lang.Exception: No tests found matching Method test(tests.TestClass) from org.junit.internal.requests.ClassRequest@5eb5c224
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at com.microsoft.java.test.runner.junit4.JUnit4RunnerUtil.getRequestForOneMethod(JUnit4RunnerUtil.java:59)
	at com.microsoft.java.test.runner.junit4.JUnit4RunnerUtil.createTestReferences(JUnit4RunnerUtil.java:44)
	at com.microsoft.java.test.runner.junit4.CustomizedJUnit4CoreRunner.run(CustomizedJUnit4CoreRunner.java:25)
	at com.microsoft.java.test.runner.junit4.JUnit4Launcher.execute(JUnit4Launcher.java:30)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:53)
```

**Comment by jdneo** [comment]
Hi @GeraldNDA,

Is it possible for you to share the project to us?

**Comment by GeraldNDA** [comment]
Example Project: 
[JtestBug.tar.gz](https://github.com/microsoft/vscode-java-test/files/3193635/JtestBug.tar.gz)

I'm running AdoptOpenJDK 8 on Windows 10

Expected Result:
![image](https://user-images.githubusercontent.com/11413630/57964247-ff7ebb80-78ff-11e9-84aa-54dd137f0eae.png)

**Comment by jdneo** [comment]
Hi @GeraldNDA,

Thank you for your sample project. I tested locally with the newest bits. And the tests could be run successfully:

![demo](https://user-images.githubusercontent.com/6193897/58074193-34786000-7bd7-11e9-853e-1fa9377a2838.gif)

The newest bits is version `0.17.0` which should be published in this week. Please just wait and feel free to have a try when it gets released.

Thank you for your patience.

**Comment by jdneo** [comment]
Closing this since the `0.17.0` has been released.

@GeraldNDA, feel free to let us know if you have any other problems during using the extension. You can reach us through filing an issue or in the Gitter channel.

Thanks.

**Comment by GeraldNDA** [comment]
So I was able to reproduce the issue in `0.17.0`. It seems like the tests are being run differently via the explorer than from the test file. Here's a gif showing the issue (sorry for the poor quality). Basically, the test explorer and running the specific method does not work. However, running the class works. 
![Failing Test Run](https://user-images.githubusercontent.com/11413630/58260080-d2893900-7d43-11e9-96ce-f0edc6fa28be.gif)

**Comment by jdneo** [comment]
Filed a new issue here: https://github.com/microsoft/vscode-java-test/issues/714.
