### ISSUE TITLE
Junit xml reports for gradle project

### ISSUE THREAD

**Issue by rohinwork** [microsoft/vscode-java-test#694]
I am trying to fetch the generated junit test reports for my gradle project. 

This is the test part of my gradle file: 
```    
       test {
        reports {
            junitXml.enabled = true
            junitXml.destination = file("$buildDir/xml")
            html.enabled = true
        }
```
I am not able to 
1. Figure out where this build directory for test cases reside
2. Even if I change the destination directory; there is no junit xml file there. 

I have done lots of exploration and still unable to figure this out. 

Any help is greatly appreciated! :)

**Comment by jdneo** [comment]
Hi @rohinwork

Are you using JUnit 5?

**Comment by rohinwork** [comment]
Hi @jdneo 
Yes, I am using JUnit 5. 
Can you tell me where the test reports get generated? 

Thanks for you response :)

**Comment by jdneo** [comment]
Hi @rohinwork,

I'm afraid the current implementation will not be able to generate the test report. To achieve that, you have to run the test cases through Gradle command as a workaround for now.

**Comment by rohinwork** [comment]
Thank you for the update @jdneo :+1:
