### ISSUE TITLE
Failed to get workspace folder for the test items when running the test cases

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#698]
### Repro step:

1. Open a test project
2. Open another test file with is not belong to the project (This operation will cause the JLS to create a new project in the workspace storage)
3. Run tests at root level in the test explorer

### Root cause:
The test searcher will find the single file as a testable file, but it does not belong to the current workspace actually.

**Comment by chandangreddy** [comment]
Hello, 
I am "Failed to get workspace folder for the test items" error on Java TestRunner 0.19. 
I only get this error when I try to run tests through remote-ssh. 
Could you please let me know if there is any workaround?

Thanks.
Chandan

**Comment by jdneo** [comment]
Hi @chandangreddy,

Thank you for your feedback. I'll take a look with it.
