### ISSUE TITLE
Cannot show display name of the test class

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#722]
### Environment:
OS: Mac
JDK: 8
Java Test Runner Extension: 0.17.0

### Result
Cannot show the display name of the test class
![image](https://user-images.githubusercontent.com/22470312/59167433-d4d0fd00-8b63-11e9-9df0-c8c4534870a6.png)

**Comment by jdneo** [comment]
Fixed in 0.31.0. See: https://github.com/microsoft/vscode-java-test/issues/667
