### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by valentin-dm** [microsoft/vscode-java-test#726]
- Issue Type: `Performance`
- Extension Name: `vscode-java-test`
- Extension Version: `0.18.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/vdittmar/vscjava.vscode-java-test-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jdneo** [comment]
@valentin-dm Could you share the profile txt?
