### ISSUE TITLE
Can't easily cancel test if notification is dismissed

### ISSUE THREAD

**Issue by rothfels** [microsoft/vscode-java-test#739]
## Problem

Launching a test with this extension produces a notification with a "Cancel" button: 

![image](https://user-images.githubusercontent.com/1095573/60137776-deaa5100-975c-11e9-83b6-ee714493ba24.png)

If the notification is accidentally dismissed (the "x" in the right corner) the test will continue but after that point I've found no way to cancel the test other than to find the test launcher pid and kill it. I want to manually cancel a test if e.g. it is taking too long to complete. I accidentally dismiss the notification often because 'Esc' hides notifications in VSCode by default.

## Possible solution

The click action for the status bar item offers option to stop test in addition to linking to test output:

![image](https://user-images.githubusercontent.com/1095573/60138046-cab31f00-975d-11e9-87cb-4719faf9a67d.png)

## Current workaround

Unbind `notifications.hide*` keyboard shortcuts.

`kill $PID`.

## Context

Extension version: 0.18.0
VSCode version: 1.35.1
MacOS: 10.14.5

**Comment by jdneo** [comment]
Hi @rothfels

Another solution is to use the command to cancel the test job:
![image](https://user-images.githubusercontent.com/6193897/60144722-1a452980-97f6-11e9-9a8f-81ed6853fa8c.png)

**Comment by rothfels** [comment]
@jdneo oooh sorry I didn't notice that and thanks for the pointer! Yeah that's awesome, much better than my workaround. Will start using. 👍

**Comment by jdneo** [comment]
You are welcome @rothfels.

We should mention it in the documents. Thanks for trying!

Closing the issue since the problem should be solved.
