### ISSUE TITLE
Running an outer class test will cause the previous inner class state CodeLens to disappear

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#740]
### Environment:
OS: Windows
JDK: 8
### Steps to reproduce
1. Run the inner class test 
2. Run the outer class test 
### Result
Status CodeLens disappears in 2
![image](https://user-images.githubusercontent.com/22470312/60165418-d4a65200-9831-11e9-997d-ffb23b2dcac6.png)

**Comment by jdneo** [comment]
This has been fixed in the recent update.
