### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LeonardoJaques** [microsoft/vscode-java-test#742]
- Issue Type: `Performance`
- Extension Name: `vscode-java-test`
- Extension Version: `0.18.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/leonardojaques/vscjava.vscode-java-test-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jdneo** [comment]
@LeonardoJaques Could you attach the cpuprofile.txt in the comment
