### ISSUE TITLE
Test output not showing in console

### ISSUE THREAD

**Issue by nobody-famous** [microsoft/vscode-java-test#743]
I'm using VSCode 1.35.1 with Java Test Runner 0.18.1.

I created a project using Maven and the quickstart archetype. When I open the generated AppTest.java unit test, the Run Test|Debug Test links show up and the test runs fine when I click one of those. I added a println() to test the output and it's not showing up in any of the consoles. If I run the test with Maven from the command line, I see the message printed.

This looks like a duplicate of [#344](https://github.com/microsoft/vscode-java-test/issues/344), but disabling the maven plugin doesn't work.

**Comment by jdneo** [comment]
Hi @nobody-famous, could you please try the following action to see if it could help:
- Make sure you are focus on the output channel.  
<img width="878" alt="Screen Shot 2019-06-29 at 1 19 49 PM" src="https://user-images.githubusercontent.com/6193897/60380027-b24e4780-9a70-11e9-98c2-e9b4e05e7eaa.png">

- Make sure the setting `java.test.log.level` is **not** `error`
<img width="659" alt="Screen Shot 2019-06-29 at 1 21 52 PM" src="https://user-images.githubusercontent.com/6193897/60380037-ee81a800-9a70-11e9-82f5-06c800599c55.png">

**Comment by nobody-famous** [comment]
Ah, ok. I didn't notice the drop down on the Output panel, it was set to Tasks.

**Comment by qrqhuang** [comment]
@jdneo Could auto switch to debug console when junit test runs?

**Comment by jdneo** [comment]
@qrqhuang Create an issue here: https://github.com/microsoft/vscode-java-test/issues/978
