### ISSUE TITLE
Cannot expand folder in test explorer with property cannot be null error

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#749]
### Environment:
1. OS: Windows
2. JDK: 8
3. Extension:
   ```
    - Language Support for Java(TM) by Red Hat： 0.47.0
    - Debugger for Java: 0.20.0
    - Java Test Runner: 0.18.1
   ```

### Steps to reproduce
1. Open a project in VSCode
2. Open Test Explorer
3. Expand workspace folder 

### Result
An error occurs and cannot expand the project.
![image](https://user-images.githubusercontent.com/22470312/61515213-9a952e00-aa34-11e9-9c43-b668da11fe08.png)

**Comment by romainjacquet** [comment]
Same problem on my computer with a slightly different environment:

1. OS: CentOS 7.4
2. JDK 1.8.0_171
Extension (same as @bsaby ):
 - Language Support for Java(TM) by Red Hat： 0.47.0
 - Debugger for Java: 0.20.0
 - Java Test Runner: 0.18.1

**Comment by luisbaldissera** [comment]
Same here:

OS: Ubuntu 19.04
OpenJDK 11.0.3

Extension (same as @bsaby )

**Comment by jdneo** [comment]
Hi @all,

I'm fixing this issue right now. Hopefully we can release the fix very soon. Sorry for the inconvenience.

Thanks,
