### ISSUE TITLE
The extension doesn't work when switching versions

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#755]
### Environment:
1. OS: Windows
2. JDK: 8/12
3. Java Extensions:
```
 - Language Support for Java(TM) by Red Hat： 0.47.0
 - Debugger for Java: 0.20.0
 - Java Test Runner: 0.18.2
```

### Steps to reproduce
1. Install extension 0.18.1
2. Open a java project in Vscode and activate test runner extension
3. Install extension 0.18.2
4. Reload then expand folder in the test explorer

### Result
An error occurs and the code lens also doesn't work.
![image](https://user-images.githubusercontent.com/22470312/61613921-1988a180-ac95-11e9-819b-5a4d84c6c25d.png)

**Comment by jdneo** [comment]
Closed since this bug should be automatically fix after new VS Code Java 0.49.0 get released.
