### ISSUE TITLE
Ignored tests cannot be run individually

### ISSUE THREAD

**Issue by katzelad** [microsoft/vscode-java-test#757]
When manually executing (using CodeLens) a `@Test` method with `@Ignore` in IntelliJ the test is still executed, which is useful in order to run tests which should not be executed by the CI service.
With this extension, the test is ignored and nothing happens.
I think the test should still run, as this is the most intuitive behavior for the per-method CodeLens.
Thanks

**Comment by jdneo** [comment]
Hi @katzelad,

This might be related with https://github.com/microsoft/vscode-java-test/issues/672. I'll move your comment there as a different opinion for open discussion.

Thank you!
