### ISSUE TITLE
Not working well in spring boot junit test

### ISSUE THREAD

**Issue by danielludan** [Microsoft/vscode-java-test#76]
It seems the spring boot context can't read configuration properly when running case, the test case src structure is followed maven default standard. The case can be executed on Eclipse IDE so it can't be case issue. Not sure if there is someway to config resource in test running to solve the issue. Thanks for your attention.

**Comment by ansyral** [comment]
@danielludan could you help share a sample about it? Thanks.

**Comment by callain** [comment]
Here is an example of application.properties under src/test/resources which I believe is either not being load or not filtered when I click on Run Test.

There is maven properties filtering in it. And those properties are in a profile active by default.
```
# DATASOURCE
# Note that those properties should be define in your maven settings and are profile dependent
spring.datasource.type = com.zaxxer.hikari.HikariDataSource
spring.datasource.url = ${test.database.url}
spring.datasource.username = ${test.database.username}
spring.datasource.password = ${test.database.password}
```

```
java.lang.IllegalStateException: Failed to load ApplicationContext
...
Caused by: java.lang.NullPointerException
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:120)
```

Test runs fine if I launch it with maven command line.

Here is launch.test.json

```
{
    "run": {
        "default": "",
        "items": [
            {
                "name": "my-project",
                "projectName": "my-project",
                "workingDirectory": "/path/to/my-project",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    }
}
```
I don't know if I need to configure something or how to do it

**Comment by jdneo** [comment]
There is a workaround here: https://github.com/Microsoft/vscode-java-test/issues/534#issuecomment-450779581

Closing this issue and let's track it in #534
