### ISSUE TITLE
Why was launch.test.json removed?

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-java-test#765]
I have an extension that provides jni based java builds to users. Because of this, in order to run tests, I must set JNI paths correctly. I didn't implement it for our 2019 product, but I wanted to for our 2020 product. However, I'm seeing now that using `launch.test.json` was removed, and replaced with definitions in `settings.json`. However this is a huge pain, since our projects commit settings.json to git in order to save workspace settings. The separate file was nice, because it could be ignored but still have local paths placed in it. By putting local paths in settings.json, it becomes a huge problem sharing between computers. Please bring `launch.test.json` back as it really is a much better solution when configuration requires full paths.

**Comment by jdneo** [comment]
@ThadHouse Could you explain more about why full paths are needed?

**Comment by ThadHouse** [comment]
Because of the way our gradle build is set up and how gradle tranforms work, the native libraries are actually not in the workspace, but are in the gradle cache folder in the users home directory. So without the java.library.path being set to that extraction directory, our tests cannot run. And we can't generate a relative path from the workspace to that, it doesn't seem to work.

**Comment by jdneo** [comment]
I see. The reason that we stop using `launch.test.json` is that it makes users confused. Many of users think that the `launch.test.json` is the VS Code official file, which is not correct. As an extension, generate files inside `.vscode` is out of the extension's scope and should be stopped.

Actually there is an upstream issue related with this: https://github.com/microsoft/vscode/issues/15909. And I noticed that you have already leave your comments there.

Regarding the extension side. One workaround is to save the config in the user settings.

BTW, will it workable if the extension supports more variable expansion like `${env:name}`. For example, you can use `${env: home}/...` to reference the libraries?
