### ISSUE TITLE
Wrong directory when running JavaCompiler/Executor.  Can't find project packages.

### ISSUE THREAD

**Issue by AdsonEsteves** [microsoft/vscode-java-test#767]
Our project is an IDE in our main language (portuguese).
It was setup as a NetBeans project, but I' trying to run it as a vscode project also.
Everything worked fine until running some specific tests that uses **JavaCompiler** or **Executor** to compile some java files.
They apparently can't find the packages that are necessary to run the file, even though they are located in the workspace.
![image](https://user-images.githubusercontent.com/8836540/62572072-475f1000-b869-11e9-9f26-8657dc4422cc.png)
![image](https://user-images.githubusercontent.com/8836540/62572170-7ecdbc80-b869-11e9-8fba-ca7d8a4d98bd.png)
The workspace directories work fine when it's file management, but when trying to compile a java file it seems it runs outside of the directory somehow.
The Compiler and Executor work fine on the main IDE, also all the tests work fine on NetBeans and Travis. So I think it's a problem with java test runner,

**Comment by jdneo** [comment]
Hi @AdsonEsteves,

I think I need more information to understand the problem. May I ask if it is possible for you to share a sample project to repro this issue? I can use it to investigate where is the gap.

**Comment by AdsonEsteves** [comment]
Sorry for the late reply.
It's a complex project, so I've been trying to reduce to you, but since it's an IDE, I couldn't do much.
Here I have a zip with the project: https://drive.google.com/open?id=1VE4W3OTF-q-ogb7Klgbyxa88sG7jsbIX

It has a lot of Portuguese words used on it, so it might be difficult to understand, so I will try to explain.
It uses 3 modules, Core, IDE and Console.
The problem is on the Core tests, so open the _**core**_ folder in the workspace.
Once it's loaded you can try the tests.
**IntegracaoGeradorCodigoJavacTest** and **TradutorRuntimeExceptionTest** are the ones with the errors and the ones that compile javacode.

I'd suggest using **IntegracaoGeradorCodigoJavacTest** to test the problem since it is less complex then the other. It uses JavaCompiler and gives the errors from the prints.
I will try to explain the test.

- It uses example codes from our language (portugol) to test if they are compiling. We compile by translating from portugol to java, then compiling it.
- The test starts by taking all the example files (called exemplos) and sending each one to the **geraCodigo** (generateCode) function.
- On that funtion it looks if the file is correct then it analyses the code (with AnalisadorAlgoritmo) to see if there are sintax errors.
- Then it uses the **GeradorCodigoJava** (Java Code Generator), to create the equivalent java code from the example.
- It writes the java code in the _arquivoJava_ File through the PrintWriter. Once it's done, it does the **check** function.
- On this check function it uses **JavaCompiler**, to compile the Java code put the errors on the _diagnostics_ and if there are errors the test fails.

I hope it helps, if there's any doubt just ask.

**Comment by jdneo** [comment]
Yes I can repro that. Need more time to understand the root cause.

**Comment by jdneo** [comment]
Root cause:

This project is a multi-root project, but the default working directory we are using is `${workspaceFolder}`, which cannot apply to the sub-modules. the extension should guess the working directory according to which project the current test cases is belong to.
