### ISSUE TITLE
The changelog has the wrong version

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-java-test#769]
**Environment:**
OS: Win10
JDK: 8
Java Test Runner Extension: 0.19.0

**Result:**
![image](https://user-images.githubusercontent.com/41051257/62672590-eb61cc00-b9cd-11e9-947c-d9d4068ade2d.png)

**Comment by jdneo** [comment]
Thanks. Have updated here: https://github.com/microsoft/vscode-java-test/pull/766
