### ISSUE TITLE
Does not run tests

### ISSUE THREAD

**Issue by sanketjpatel** [microsoft/vscode-java-test#777]
Issue Type: <b>Bug</b>

I do not get test output when clicking on "Run Tests"

Extension version: 0.19.0
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment]
Hi @sanketjpatel,

Could you provide a sample project to repro this issue? I can use that to investigate further.
