### ISSUE TITLE
Need to rebuild before tests

### ISSUE THREAD

**Issue by StefanoDeVuono** [microsoft/vscode-java-test#781]
When I add imports or change associated files, my tests will often fail until I run `mvn test-compile` in a terminal.

Is there a way to make this a prelaunch task to running my tests?

**Comment by jdneo** [comment]
As a workaround, you can turn on `java.autobuild.enabled`.

<img width="304" alt="Screen Shot 2019-08-20 at 3 51 38 PM" src="https://user-images.githubusercontent.com/6193897/63328264-704fcc80-c362-11e9-823d-9b9bfcd8a256.png">

This will make sure your project will be incrementally built after each save event.


I'll send out a PR later to provide a setting whether to force build the workspace before each test execution.
