### ISSUE TITLE
add run button to test report

### ISSUE THREAD

**Issue by andxu** [microsoft/vscode-java-test#789]
![image](https://user-images.githubusercontent.com/17075863/64233682-4d5b1600-cf27-11e9-9bac-05c662943b70.png)
Could it be possible to add several entries for running interested test cases in test report, see red circles in the picture

**Comment by JasonHenriksen** [comment]
I have a PR that adds Alt-T to re-run last test.  
I have to finish tweaking it this week, but that might help you too.

**Comment by spottedmahn** [comment]
Semi-related, re-run failed tests!

**Comment by jdneo** [comment]
Test report is removed in 0.31.0.

But you can now rerun the tests in the test message view now

![image](https://user-images.githubusercontent.com/6193897/128448424-767579ca-9ba0-41c7-8df1-51bf32436324.png)
