### ISSUE TITLE
How to quickly enter code where the error happened

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-java-test#794]
Issue Type: <b>Bug</b>

Java Test Runner output all the message in vscode output panel.How to quickly enter code where the error happened by click.

![image](https://user-images.githubusercontent.com/27731323/64307485-ceb6b500-cfc8-11e9-8fc2-cd040b6bbfa6.png)

Extension version: 0.19.0
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment]
Thank you for reporting this. I'm sorry it's not supported so far. But we have an issue to tracking the same request. https://github.com/microsoft/vscode-java-test/issues/384

Closing it for now and let's track with #384
