### ISSUE TITLE
Failed to get workspace folder for the test items when running the test cases

### ISSUE THREAD

**Issue by chandangreddy** [microsoft/vscode-java-test#797]
Repro step:

- Open a test project in remote ssh 
- Run tests at root level in the test explorer

Java Test Runner version 0.19

**Comment by chandangreddy** [comment]
Note that my tests are successfully recognized and code lens is displayed.

**Comment by christianfosli** [comment]
I'm seeing the same issue when using [VsCode through WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl).

**Comment by chandangreddy** [comment]
@christianfosli  Please let me know if you found any workarounds for this issue.

**Comment by jdneo** [comment]
Hey guys,

Sorry for the late reply and thank you for reporting this. I'll check about this issue these days and see what's the gap there.

**Comment by jdneo** [comment]
I got a chance to try with Remote WSL today. (not Remote SSH)

It seems to work from my side:
![demo](https://user-images.githubusercontent.com/6193897/65103086-b6e72400-d9ff-11e9-8a92-c9741e85dc32.gif)

@christianfosli Could you provide more information to help us diagnostic this issue?

**Comment by christianfosli** [comment]
Thanks for looking into this, @jdneo. Good to know it's working for you 😄

* I've got a simple gradle project, which I can test in the commandline using `./gradlew test`.

* I'm running windows 10 pro version 1809, build 17763.678

* I'm running FedoraRemix distro on WSL

My tests are recognized with Code Lense, and that's how I try to run them.
They are not recognized in the Test Explorer.

![wsl-java-tests](https://user-images.githubusercontent.com/36294671/65112542-50064280-d9e0-11e9-965a-32dc62be9903.gif)

**Comment by chandangreddy** [comment]
Hi @jdneo, I still having this issue, did you get a chance to try with remote ssh?

**Comment by brainafesoh** [comment]
Hi @jdneo could we see the content of your `settings.json` [here](https://github.com/microsoft/vscode-java-test/issues/797#issuecomment-532492282)? I'm guessing the `java.test.config` attribute might be our solution here.

**Comment by jdneo** [comment]
Hi @brainafesoh, I'm just using the default `java.test.config`, which is:

```
{
    "name": "default",
    "workingDirectory": "${workspaceFolder}"
}
```

But so far I just tried it within WSL, not in the SSH, so I'm not sure if the extension still work in SSH. I will take a look when I have a chance.

**Comment by brainafesoh** [comment]
Hey @jdneo, thanks for checking. Another supposition though; I think it has to do with vs code's behaviour with symlinked folders as you say on issues #630 & [here](https://github.com/microsoft/vscode/issues/74104#)

In my case, I generally do work on linux but equally like to access my project folders  while on Windows too. So what I do is that I save all my projects in a folder on the windows partition then while on linux, I access to it via a symlink. For a temporary workaround, I'll just copy my project folder out of the symlinked folder, directly into my HOME dir.

It'll make me a little more disorganized though. just hope it's resolved soon.

**Comment by shane-axiom** [comment]
Just confirmed this issue still exists in code 1.40.1, running on Debian 10. 

> Failed to get workspace folder for the test items

when trying to run a detected JUnit test in a symlinked folder. Opening the target folder directory works fine. Thanks for the tip @brainafesoh!

**Comment by jdneo** [comment]
For people who encountered this problem, are you having the symlinked folder and try to open that when using the `Remote - SSH`?

**Comment by jimnz111** [comment]
Same issue for me using an attached docker container. 
I had a symlink into home directory from a source directory. Switched to the absolute path and it all works perfectly. Problem definitely is only where the workspace folder points to a symlink.

**Comment by jdneo** [comment]
According to the feedback. I guess this issue is related (or duplicated) with #630. 

So far, the VS Code has some problem handing this scenario, see: https://github.com/microsoft/vscode/issues/74104

For anyone who has the same problem, please also go to https://github.com/microsoft/vscode/issues/74104 to echo/vote for that.

I'm closing this issue for now and track in #630.

**Comment by andrewpajda** [comment]
Hey, 

Not sure if the issue persists in your case but this is what I found, and when you think about it, it's kinda tricky.

If u open a project folder in VSCode, IT IS NOT considered workspace. So even when the test classes are identified succesfully (CodeLens is properly displaying run and debug options), your folder is not a part of the workspace. 

Fix: 
Open VSCode --> File --> Add Folder to Workspace... --> [here you add a project folder to workspace, and save the workspace with configuration file in project's root].

After this I have also reinstalled all deps with maven (but im not sure its necessary for this fix to work).

From now on, you should be able to see all tests in tests explorer and also run them successfully.

Let me know if this helped.

**Comment by robaho** [comment]
This is not working properly.

Using a gradle project with subprojects, the subprojects correctly appear in Code Lens to allow test running, but when the tests are run the working directory is the top of the root project rather than the top of the subproject - which is the case when you run them with gradle, or the gradle extension
