### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Eliezer-creator** [microsoft/vscode-java-test#805]
- Issue Type: `Performance`
- Extension Name: `vscode-java-test`
- Extension Version: `0.19.0`
- OS Version: `Linux x64 4.15.0-62-generic`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/eliezer/vscjava.vscode-java-test-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jdneo** [comment]
Hi @Eliezer-creator, would you mind to share the profile txt?
