### ISSUE TITLE
No All tests/Passed/Failed filter radio in  test report of one method class

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#81]
After running test, click on class codelens or test statistics from status bar to open class report
![image](https://user-images.githubusercontent.com/22470312/34598383-657b3b22-f227-11e7-9ffb-ae6ad148b0b5.png)

**Comment by ansyral** [comment]
#80

**Comment by bsaby** [comment]
Test passed on both windows and mac and filter radios are work fine.
Using build sign9.

![image](https://user-images.githubusercontent.com/22470312/34599489-9479ae80-f22d-11e7-97a6-db93167a3cdc.png)
