### ISSUE TITLE
linkedResource is not taken into consideration when resolve test class path

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode-java-test#812]
Hi
I cannot run my test. It's a folder with multiple projects defined with simple .classpath

I obfuscated the name of Test Class name in the log below.

@@<TestRunner-{"name":"error","attributes":{"message":"No test found to run for suite *****************#testUnitParsing. Details: *******************.","trace":"java.lang.ClassNotFoundException: com.******************
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.microsoft.java.test.runner.junit4.JUnit4RunnerUtil.getRequestForOneMethod(JUnit4RunnerUtil.java:55)
	at com.microsoft.java.test.runner.junit4.JUnit4RunnerUtil.createTestReferences(JUnit4RunnerUtil.java:44)
	at com.microsoft.java.test.runner.junit4.CustomizedJUnit4CoreRunner.run(CustomizedJUnit4CoreRunner.java:25)
	at com.microsoft.java.test.runner.junit4.JUnit4Launcher.execute(JUnit4Launcher.java:30)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:56)
"}}-TestRunner>
.

**Comment by jdneo** [comment]
Hi @llgcode,

I guess you have set the log level to verbose. Could you check the command line the test runner launched (it will be printed at the beginning of the execution) and see if the classpath is correct?

**Comment by llgcode** [comment]
Ok, I activated log in user settings (not working in workspace settings)
"java.test.log.level": "verbose"

I don't see any classpath referring to my project configuration:
Executing: 'C:\Program Files\Java\jdk1.8.0_112\bin\java -cp c:\Users\***\.vscode\extensions\vscjava.vscode-java-test-0.19.0\server\com.microsoft.java.test.runner.jar;c:\Users\***\.vscode\extensions\vscjava.vscode-java-test-0.19.0\server\lib -Dfile.encoding=iso88591 com.microsoft.java.test.runner.Launcher junit com.****#****'

**Comment by llgcode** [comment]
I think, I've found something that could be the cause of my issue.
 First when tracing java language server log (in verbose), I found that there's no computed classpath for this command:
```
[Trace - 3:54:28 PM] Sending request 'workspace/executeCommand - (18)'.
Params: {
    "command": "vscode.java.test.runtime.classpath",
    "arguments": [
        [
            "e:\\******\\src\\com\\*****.java"
        ]
    ]
}


[Trace - 3:54:28 PM] Received response 'workspace/executeCommand - (18)' in 11ms.
Result: []
```
then when looking at the java language server implementation, I see that when computing classpath, the algo check if the file belong to the project:
see
https://github.com/microsoft/vscode-java-test/blob/e5e7fd6b10e6c045e6092c9edd3a23c681ac682e/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java#L68

and

https://github.com/microsoft/vscode-java-test/blob/1a88f87ae5d123e46963df295d7d2f4ad2892e44/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java#L156

Then I remembered my project classpath uses linkResources to reference sources that are not at the same place as project files see below:

```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
    <name>********</name>
    <comment></comment>
    <projects>
    </projects>
    <buildSpec>
        <buildCommand>
            <name>org.eclipse.jdt.core.javabuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
    </buildSpec>
    <natures>
        <nature>org.eclipse.jdt.core.javanature</nature>
    </natures>
    <linkedResources>
        <link>
            <name>src</name>
            <type>2</type>
            <location>e:/********/src</location>
        </link>
    </linkedResources>
</projectDescription>
```


Finally I think *isPathBelongToProject* always return false in my case, because isPathBelongToProject doesn't care about linkedResource

```java
...
if (ProjectTestUtils.isPathBelongToProject(testPath, project)) {
                    projectsToTest.add(javaProject);
                    iterator.remove();
                }
...
```

**Comment by llgcode** [comment]
Hi @jdneo, any news on this issue

**Comment by jdneo** [comment]
Hi @llgcode,

We recently changed the classpath resolving logic. I'm not sure if the change can resolve your problem. But if it is possible for you to share a sample project to us. I'm willing to test it.

If it's not convenient to share, you can try it again when the new version released. And let me know if the problem still occur.

**Comment by llgcode** [comment]
Hi @jdneo,
Sorry I can't share my project. But I've tested and launched **successfully** my junit tests.

Thank you.

**Comment by llgcode** [comment]
Not sure if it's related, but in the test treepanel, all classes of my project are present, even if it's not a junit test class.

**Comment by jdneo** [comment]
I guess what you are talking about is this one: https://github.com/microsoft/vscode-java-test/issues/768
