### ISSUE TITLE
Support for method detection with @Testable (and meta)

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-java-test#818]
In #683 it was mentioned that `@Testable` is designed for support in IDEs (so exactly the use case that `vscode-java-test` was created for), but there is no support yet. It would be really useful, especially if supported (as intended according to the javadocs) as a meta annotation.

**Comment by jdneo** [comment]
Thank you for the feedback @dsyer. Yes we will try to support it ASAP
