### ISSUE TITLE
Cancel Junit4 running test will show debug bar

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-test#820]
#### environment:
     1. OS: Win
     2. JDK: 8/12
     3. Java Test Runner version:0.20.0
#### Repro steps:
1. Open a Junit4 project.
2. Click run test code lens.
3. Click Cancel button on the notificaton message.

#### Result:
It will show debug bar.
![image](https://user-images.githubusercontent.com/44559777/65668540-7b3e0100-e074-11e9-8898-a005da398770.png)

**Comment by ZhengJun003** [comment]
Fixed
Debug bar will display when click cancel after ⚡ appear
