### ISSUE TITLE
Get error when cancel JUnit5 running test

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-java-test#821]
**Environment:**
1. OS: Windows
2. JDK: 8
3. Java Extensions:
    - Language Support for Java(TM) by Red Hat： 0.48.1
    - Debugger for Java: 0.22.0
    - Java Test Runner: 0.20.0

**Steps to reproduce:**
1. Open the JUnit5 project in VSCode: [https://github.com/ZhengJun003/junit5-samples/tree/testrunner ](https://github.com/ZhengJun003/junit5-samples/tree/testrunner )
2. Click cancel after run test from workspace /package level in the test explorer

**Result:**
![图片](https://user-images.githubusercontent.com/41051257/65669171-a7a64d00-e075-11e9-9917-f5e03450d949.png)

**Comment by jdneo** [comment]
Fixed with #828. We are now leverage the debugger to launch the debug session. The previous implementation is using attach.
