### ISSUE TITLE
 Illegal reflective access operation warning causing runner to fail

### ISSUE THREAD

**Issue by Phonesis** [microsoft/vscode-java-test#825]
I am using the JUnit runner in VSCode to run Junit tests that have a dependency for Groovy 2.5.6. This is installed and in the Maven repo. 

Whenever I run a test (via the runner not terminal) I get a build failed error with:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/.m2/repository/org/codehaus/groovy/groovy/2.5.6/groovy-2.5.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

Even though I get this, I am able to click proceed and the tests run ok.

I have tried using the env var for ignoring warnings in my bash profile but this has not helped. I have also cleared the VS Code Java cache and re installed the Groovy dependency.

**Comment by jdneo** [comment]
@Phonesis is it possible to provide a sample project to us for diagnostic?

**Comment by Phonesis** [comment]
> @Phonesis is it possible to provide a sample project to us for diagnostic?

Afraid not. I think you can re-create it by simply having a Java pom based project with the latest version of Rest Assured installed - https://mvnrepository.com/artifact/io.rest-assured/rest-assured-all/4.1.2

**Comment by jdneo** [comment]
@Phonesis any environment setup information? Like OS, JDK version, etc...

**Comment by Phonesis** [comment]
> @Phonesis any environment setup information? Like OS, JDK version, etc...

I am using macOS Mojave with latest VS Code and JDK 1.8

**Comment by jdneo** [comment]
I used this project https://github.com/adriangonciarz/rest-assured-example to try to reproduce the issue. But everything works fine, unless I switch my JDK from 8 to 11.

Please make sure your Java Language Server do use JDK 8 to launch its JVM, you can see this in the Process Explorer:
<img width="437" alt="Screen Shot 2019-12-06 at 3 04 24 PM" src="https://user-images.githubusercontent.com/6193897/70303129-c70de300-1839-11ea-97bb-13f0e2ecaaf0.png">

<img width="1141" alt="Screen Shot 2019-12-06 at 3 05 20 PM" src="https://user-images.githubusercontent.com/6193897/70303181-ee64b000-1839-11ea-872a-0cee3a7b6262.png">
