### ISSUE TITLE
Test context reading 'wrong' application properties file

### ISSUE THREAD

**Issue by gitorko** [microsoft/vscode-java-test#826]
I think the issue is occurring again in latest version 0.20.0

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic

Test are not referring the application.yaml in the test/resources folder. If i run the tests it fails, but when i update the application.yaml in the main/resources folder the tests pass. They never refer to the application.yaml in the test/resources folder. The same tests work on intellij.

https://github.com/microsoft/vscode-java-test/pull/629

**Comment by jdneo** [comment]
@gitorko what's the test framework you are using? JUnit 4, 5 or TestNG?

**Comment by tnatanael** [comment]
Please, re-open this because the issue is ocurring for me too!

**Comment by tnatanael** [comment]
For those who are facing the same problem, on the configuration in .classpath file, put the test resource pathentry before main resources pathentry.
```
	<classpathentry kind="src" output="bin/test" path="src/test/resources">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
```
Now the extension find the application.resources on test first, and then works!
