### ISSUE TITLE
Often get "A test session is currently running. Please wait until it finishes."

### ISSUE THREAD

**Issue by ZhengguanLi** [microsoft/vscode-java-test#835]
All I have to do is start my VSCode often...

**Comment by jdneo** [comment]
Hey @ZhengguanLi,

I'll take a look to this issue. For now, you can use the command: `Java: Cancel Test Job` as a workaround.

**Comment by calvin1864** [comment]
This happens reliably for me when I run tests when the project has a compiler error.

Clicking 'Abort' on the 'Build Failed' seems to leave the test job running without hope for completion.

This may be a different use case than OP's since it doesn't happen on startup, only when I trigger tests

**Comment by jdneo** [comment]
Hi @all.

Thank you for the feedback. I've noticed this issue and try to fix it in: #839. The fix should be released in next week.

**Comment by jdneo** [comment]
Thank you @calvin1864 for the information.

I'll close this issue for now. If the problem still occurs, please let me know.

Thanks.

**Comment by shiroukamui** [comment]
> Hey @ZhengguanLi,
> 
> I'll take a look to this issue. For now, you can use the command: `Java: Cancel Test Job` as a workaround.as a workaround.as a workaround.

Hi @jdneo, 
Excuse me but what exactly do you mean with the command `Java: Cancel Test Job`? this isn't clear enough since it is not a valid command.
Thanks.

**Comment by jdneo** [comment]
@shiroukamui  What do you mean by: 

> it is not a valid command.
