### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by wurst44** [Microsoft/vscode-java-test#84]
using the latest version it does not seem to show me the cancle/setting icon?

![image](https://user-images.githubusercontent.com/2656697/34668496-fda22d50-f46d-11e7-8585-1426d721d883.png)

**Comment by ansyral** [comment]
@wurst44 do you mean canceling a running test? We haven't supported this feature.

**Comment by wurst44** [comment]
No, my first screen shows the green check icon, pickaxe icon and red X icon missing.
I mean this kind of stop (red X?) button were you can apparently stop the test run.

How it should be:
![image](https://user-images.githubusercontent.com/2656697/34708475-341391c6-f513-11e7-8fa1-3931011f6b56.png)

Also the info "0 references" is missing, and the separator pipes characters.
I need to always restart the IDE to stop the test? Red X?

**Comment by wurst44** [comment]
![image](https://user-images.githubusercontent.com/2656697/34709385-522dead6-f517-11e7-996c-405dc35bfc73.png)

**Comment by ansyral** [comment]
> I mean this kind of stop (red X?) button were you can apparently stop the test run.

The red cross or green check mark show the status of the test, cross mark means that the test failed and check mark means that the test succeeded. They only show when you have run or debugged the test. And seems that the screen is from our demo? sorry it is a bit outdated, we've made some changes about the look. I'll record a new one later.

> Also the info "0 references" is missing, and the separator pipes characters.

You can show the references by editing your settings file(File->Preferences->Settings), add below configuration: `"java.referencesCodeLens.enabled": true`

**Comment by wurst44** [comment]
Ok, well I think it was another problem with the Spring Boot Context not beeing started so the Test will not end somehow at all when started separately. On other testcases the icons appear and tests end properly.
Thanks for your time.
