### ISSUE TITLE
PLEASE, Better instructions in documentation

### ISSUE THREAD

**Issue by intin1beep** [microsoft/vscode-java-test#841]
I struggled a lot on how to start my testing.

It would be so helpful if there was a description on steps needed to create a test for any simple java project, so that anyone could recreate it, for example, what is required to add to the .classpath, the filestructure and so on.

There are no information on how to start a test project with java on VSCode, In ParTiCuLaR, anywhere! (ref: [#658](https://github.com/Microsoft/vscode-java-test/issues/658)

Thanks for a useful extension!

**Comment by jdneo** [comment]
@intin1beep what kind of project are you using? Is it a Maven/Gradle project?

**Comment by jdneo** [comment]
Hi @intin1beep, it would be great if you can share a sample project to us. I can take a look to see where is the gap.

**Comment by jdneo** [comment]
The following sections are added to tell what jars are needed for different Test Framework:

JUnit4: https://github.com/microsoft/vscode-java-test#getting-started-for-junit-4
JUnit5: https://github.com/microsoft/vscode-java-test#getting-started-for-junit-5

> Note: For TestNG, so far I cannot find any official document mentioning the plain-old jar. If anyone finds it, please let me know.

I'll close this issue for now. If you still have any problem setting up the project, feel free to let me know.

Thanks.
