### ISSUE TITLE
Use octicon to replace emojis

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-test#845]
This is to request replacing the emojis in the editor view:
![image](https://user-images.githubusercontent.com/16755094/67256592-8db42a80-f4ba-11e9-8eb5-4f29d799a236.png)

VS Code now supports oct icons, and by adopting them, the test status looks more consistent and appealing in the editor window.
https://code.visualstudio.com/api/references/icons-in-labels
https://octicons.github.com/

**Comment by jdneo** [comment]
So far the octicon icons are only supported in StatusBarItem and QuickPickItem. Code Lens is not supported yet. But I can first replace the icons in the test explorer.
