### ISSUE TITLE
vscode doesn't find junit after i configure it in .classpath

### ISSUE THREAD

**Issue by elichyb** [microsoft/vscode-java-test#851]
Ok so I have an hello_world project to java in vscode and i can't defined there the Junit 4.12.
Step for recreate the problem:
1. Create new java project in vsc.
2. Create dir lib.
3. Put insidw the lib the Junit.jar
4. Configure the .classpath this way:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="src" path="src/test" output="bin/test">
		<attributes>
			<attribute name="test" value="true" />
		</attributes>
	</classpathentry>
	<classpathentry kind="lib" path="lib/junit.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>

```
5. Add test file under directory test and import org.junit.Test;

Still got an import error....

My directory tree looks like this:
C:.
├───.settings
├───bin
│   ├───app
│   └───test
├───lib
└───src
    ├───app
    └───test

**Comment by jdneo** [comment]
> Create new java project in vsc.

Is the project created with the help of Java Dependency Viewer?

Actually there is a very simple way to create a new project. You can:
- Create an empty folder, let's say its name is `A`
- Create a lib folder at the root of the empty folder `A`, the lib folder is used to put dependency jars, like JUnit 4.12
- Create your source file in `A`, that's it.

_There is no need to update the `.classpath` manually_

Please have a try and let me know if this works.

**Comment by elichyb** [comment]
I think that this ticket related to this bug: https://github.com/redhat-developer/vscode-java/issues/1122

**Comment by jdneo** [comment]
Closed since the upstream issue seems having been resolved.
