### ISSUE TITLE
A test session is currently running. Please wait until it finishes.

### ISSUE THREAD

**Issue by juandiego9221** [microsoft/vscode-java-test#857]
Issue Type: <b>Bug</b>

this message "A test session is currently running. Please wait until it finishes." keeps appearing , even i already close the test

Extension version: 0.20.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jdneo** [comment]
Thanks for the feedback. The issue is dup with #835

Please refer to https://github.com/microsoft/vscode-java-test/issues/835#issuecomment-542481346 as a workaround. The ETA of the fix release will be before the end of this week.
