### ISSUE TITLE
Class name is not set correctly

### ISSUE THREAD

**Issue by Dekadee** [Microsoft/vscode-java-test#86]
I'm trying to make this extension work, but the first letter of the class name is always cut off. The problem is depicted in these Pictures:

![vscodejunitexplorer](https://user-images.githubusercontent.com/24483904/34744361-3f6e6f6c-f58d-11e7-9a34-d6b55da60b39.png)

![vscodejunittest](https://user-images.githubusercontent.com/24483904/34744344-357c6f68-f58d-11e7-8e3c-b091355db07d.png)

The name of the Test is always missing the first letter of the class name, thats whats causing the error.
The class' name is "TestThis", but the name of the test that is being run is "estThis". This happens with every other letter too and i have no idea whats causing this.

JUnit itself works fine with this test, if i run it manually.

I have no idea what could cause this on my end and have not found any mention of this in other issues.

**Comment by ansyral** [comment]
@Dekadee Thanks for reporting this, I can repro it and it only happens for default package. Will make a fix.
