### ISSUE TITLE
Error when trying to run a test

### ISSUE THREAD

**Issue by AveryBuehler** [microsoft/vscode-java-test#870]
I'm getting the following error whenever I try to run a test:

`Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;`

Any idea why?

**Comment by jdneo** [comment]
Hi @AveryBuehler, what kind of project are you using? Is it a Maven or Gradle project? It would be helpful if you can share a sample project.

**Comment by AveryBuehler** [comment]
Hi @jdneo, this is a Maven project. Unfortunately, I'm unable to share a sample from this project. For now, I'm running my tests in IntelliJ but want to move over to VSCode once this is resolved.

**Comment by jdneo** [comment]
I need a project to repro it, then I can take a look and find the gaps.

**Comment by AveryBuehler** [comment]
Are you looking for an entire repository, or just a unit test I'm trying to execute? I won't be able to share the former since this is a private service, but can share the latter if it would be of any use (probably not).

**Comment by jdneo** [comment]
Not the whole repository. Just whatever a project which can repro this issue would be helpful.

**Comment by jdneo** [comment]
Hi @AveryBuehler,

Is this problem still occur?

**Comment by gollapudi2009** [comment]
Hi @jdneo 

This problem is occurring for me and I am using a maven project with spring boot framework
