### ISSUE TITLE
ClassNotFoundException In A JPMS Module Project With JUnit5

### ISSUE THREAD

**Issue by lingocoder** [microsoft/vscode-java-test#872]
I was genuinely excited when I stumbled across #807 „[*Support modular test project*](https://github.com/microsoft/vscode-java-test/issues/807)“ a few days ago. I like Eclipse, but it's often too heavyweight for a lot of my projects. I prefer vscode. 

So as excited as I was anticipating vscode-java-test to support JUnit 5 tests in my JPMS projects, I was equally disappointed when it didn't work at all in any of my projects.

### Expected Behavior

Given @jdneo's [*recent comment*](https://github.com/microsoft/vscode-java-test/issues/859#issuecomment-550100215)...

> „...*The changes we made from 0.20.0 to 0.21.0 is to use the Eclipse's JUnit runner instead of our own runners*...“

...I expect any JUnit test that works successfully in Eclipse to also work successfully in vscode.

### Actual Behavior

Given a JUnit test that works successfully in Eclipse, that exact same test, in the exact same project opened in vscode, cannot run successfully.

### Context

I'm working with a Gradle-built project that contains a *`module-info.java`* descriptor, and a Gradle plugin that enables JPMS module development in Eclipse. The project includes a JUnit 5 tests.

Importing that project into Eclipse, and launching the JUnit test with Eclipse's test runner, works as expected.  Disappointingly, opening that same project in vscode, results in the following error:

```
Class not found com.example.project.CalculatorTests
java.lang.ClassNotFoundException: com.example.project.CalculatorTests
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

```

![vscode java test bug 872 a](https://user-images.githubusercontent.com/49788472/68403166-6c1e9880-0174-11ea-9f3f-c6f7745bbbc0.gif)

You can see in the screen recording that vscode does not have any problems compiling the modularized project. The *`Problems`* view shows zero problems. That means that the JPMS development-enabling plugin ([***mrJar***](http://bit.ly/mrJar)) is successfully enabling JPMS development in vscode, just as it does in Eclipse. The fact that there aren't any compilation errors, suggests that the module path is correctly configured.

### Steps To Reproduce

1. Import [*the attached project*](http://bit.ly/2ClfKHp) into Eclipse using the *`Existing Gradle Project`* wizard.
2. In Eclipse's *`Package Explorer`*, right-click on the project and select *`Run as — JUnit Test`* from the context menu
3. Observe that the test launches and succeeds as expected
4. Exit Eclipse
5. Open the same project in vscode
6. Click the gray, *`Run Test`*  label that appears above the name of the *`CalculatorTests`* class
7. Observe that the test fails to launch and instead dumps the *`ClassNotFoundException`* stack trace listed above

### Your Environment

```
Eclipse 2019.09

Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:10.237Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT ia32 6.1.7601

vscode-java-test  0.21.0
vscode-java-debug 0.23.0
vscode-java 0.52.0

Gradle 6.0-rc-2
mrJar plugin v0.0.16
```

**Comment by jdneo** [comment]
I‘m trying to repro this issue but get the following exception:
![image](https://user-images.githubusercontent.com/6193897/68932975-aa4c3580-07ce-11ea-913e-657f2c9d3f7a.png)

Same in Eclipse

**Comment by lingocoder** [comment]
Hi jdneo. Thanks for investigating this.

I had to take that particular version (*0.0.16*) of the mrJar plugin *offline*; for maintenance. I expect to republish it in the next day or so. 

I will get back to you when it is available again. Very soon. 

Thanks so much for taking the time to look into it :+1:

**Comment by jdneo** [comment]
Thank you @lingocoder .

**Comment by lingocoder** [comment]
AHH! I didn't look at your screenshot closely before, @jdneo. Apologies. But I'm seeing now the third line from the bottom of your screenshot: „*`maven(file:/z:/staging/consuming/maven-repo)`*“. That is a location on my local file system. It is where I locally publish plugins during development.

Evidently, I forgot to remove the *`pluginManagement{}`* block from the *`settings.gradle`* file when I uploaded that sample project. So sorry about that.

Going by [*this issue I just reported*](https://github.com/gradle/plugin-portal-requests/issues/15), even though I deleted the plugin from the portal, if you remove or comment out that *`pluginManagement{}`* block from the project's *`settings.gradle`*, the ***mrJar*** plugin will probably still be downloaded for you, actually.

Looking forward to learning whatever you find out. TIA :+1:

**Comment by jdneo** [comment]
Hey @lingocoder 

I tried to comment out the `pluginManagement{}` block but got a new error:

```
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.0-rc-2-all.zip'.
Build file 'C:\Users\sheche\Desktop\TestRunnerBugs\872\build.gradle' line: 4
Plugin [id: 'com.lingocoder.mrjar', version: '0.0.16'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.lingocoder.mrjar:com.lingocoder.mrjar.gradle.plugin:0.0.16')
  Searched in the following repositories:
    Gradle Central Plugin Repository
Plugin [id: 'com.lingocoder.mrjar', version: '0.0.16'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.lingocoder.mrjar:com.lingocoder.mrjar.gradle.plugin:0.0.16')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

Do you have any ideas?

**Comment by jdneo** [comment]
Downgrade the plugin version to `0.0.15` and using JDK 11 works. Let me see what's happening inside the Test Runner.

**Comment by lingocoder** [comment]
Please forgive me for the late reply @jdneo,

> *Do you have any ideas?...*

Yeah this part in your console output...

```
...
Plugin [id: 'com.lingocoder.mrjar', version: '0.0.16'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.lingocoder.mrjar:com.lingocoder.mrjar.gradle.plugin:0.0.16')
  Searched in the following repositories:
    Gradle Central Plugin Repository
...
```

...is what I *thought* I saw in your output from four days ago. Your most recent one is what I was expecting to see the other day because I knew that I had deleted version 0.0.16 from Gradle's Plugin Portal. 

That is also why I raised [*this ticket*](https://github.com/gradle/plugin-portal-requests/issues/15) against Gradle's portal. From my machine, I can still access that deleted version (*see the screen recording in that issue*). 

Thanks again for letting me know.

**Comment by lingocoder** [comment]
> „...*Downgrade the plugin version to `0.0.15` and using JDK 11 works. Let me see what's happening inside the Test Runner*...“

You were smart to try `0.0.15`. It didn't even occur to *me* to try it myself. I guess that's why Microsoft pays you the big bucks :)  

> „...*Update:
> *Still cannot import the project into Eclipse. Is there any special settings I need to pay attention?*...“

I've never come across that problem with `0.0.15` myself jdneo. What exactly is the error Eclipse is reporting for that version?

**Comment by jdneo** [comment]
It says:
```
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.0-rc-2-all.zip'.
Build file 'C:\Users\sheche\Downloads\lingocoder.issue.872.a\872\build.gradle' line: 4
An exception occurred applying plugin request [id: 'com.lingocoder.mrjar', version: '0.0.15']
Failed to apply plugin [class 'com.lingocoder.plugin.mrjar.JdksPlugin']
You must use -PcrossCompile to enable cross compilation, or run Gradle with JDK 9
```

I'm using JDK 11
