### ISSUE TITLE
Running multiple tests simultaneously

### ISSUE THREAD

**Issue by aghasemi** [microsoft/vscode-java-test#873]
Hi,
Is there any way to run a test when another is still being executed, somehow as two separate processes, without mixing the output?

Thanks

**Comment by jdneo** [comment]
Hi @aghasemi, 

So far it's not possible now. But I think your request is somehow the same as [this one](https://github.com/microsoft/vscode-java-test/issues/780). Let me merge your issue into that one.

Thank you!
