### ISSUE TITLE
Be able to select multiple nodes from the explorer and run/debug

### ISSUE THREAD

**Issue by template99** [microsoft/vscode-java-test#874]
Just like in Test Explorer for Visual Studio, have the ability to click on 2 or more tests to be ran individually. Currently you can only run one test, or all the tests in the class.

**Comment by jdneo** [comment]
Hi @template99,

So this is to support multi-selection in the explorer, am I right?

**Comment by template99** [comment]
That would be correct. Click-select individual, shift-click for groups of tests.

**Comment by jdneo** [comment]
Multi-selection is supported in 0.31.0
