### ISSUE TITLE
Can't successfully Run Test nor Debug Test

### ISSUE THREAD

**Issue by cajetaneducode** [microsoft/vscode-java-test#876]
Hi,

I'm running VSCode 1.40.0 with the extension vscode-java-test extension 0.21.0 on Ubuntu 18.04.3. 

When I go in my test file and click on **Run Test** or **Debug Test**, I see that VSCode tries to launch the test extension but silently fails. 

I looked around and found this palette command `Java: Show test output`

It displayed the following error
```
{"name":"error","attributes":{"message":"Exception happens in the Test Runner.","trace":"java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
	at com.microsoft.java.test.runner.testng.TestNGRunner.run(TestNGRunner.java:33)
	at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:32)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:57)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more
"}}.
```

The following code is the test I've written to obtain that error
```java
@Test
public void sum_one_to_nine_double_expects_forty_five() {

    final double expectedResult = 45.0;
        
    final double[] values = new double[]{1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0};
    double sum = Evaluate.sum(values); // Function to test

    Assert.assertEquals(sum, expectedResult);
}
```

Let me know if you need more information.

_Disclaimer: I'm currently learning Java and TestNG. I may have done something wrong_

**Comment by jdneo** [comment]
Generally, the error: `java.lang.NoClassDefFoundError: xxx` means the classpath is incomplete so the required class could not be found.

I guess you are not using Maven/Gradle, but put the lib jars into the `lib` folder. If that is the case, what you need to do is to put the [jcommander](https://mvnrepository.com/artifact/com.beust/jcommander/1.72) into your lib folder.

**Comment by cajetaneducode** [comment]
You did guess right, I'm learning the hard way right now (no Maven/Gradle). Adding jcommander did solve the issue.

Thank you so much for taking the time to explain how to understand that kind of error.

**Comment by jdneo** [comment]
You are welcome. 😄 

Happy coding~

**Comment by Hec12579** [comment]
I am seeing a similar error working on a project that seems to have no issues when running in eclipse. I have copied the project to vscode and when attempting to run one of my TestRunner files I am getting the following error below. Has anyone encountered such an issue?  I am also new to TestNG & Java.

`Exception occured while running tests.
java.lang.RuntimeException: No test found to run.
	at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:29)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:57)`
