### ISSUE TITLE
Failed to get workspace folder for the test items

### ISSUE THREAD

**Issue by JdKock** [microsoft/vscode-java-test#878]
I have created a default spring-boot project to see how it works in VSCode for Java development.
I started VSCode and via File - Open Folder, opened my new Java spring-boot project.
The project runs without any problems and when I opened a test in the editor I see the "Run Test/Debug Test" shortcuts above the test class.
When I now click on "Run Test" I get the error message: "**Failed to get workspace folder for the test items**"

I also don't see any tests in the Test explorer. Even after adding the following to my pom file.
<testSourceDirectory>${project.basedir}/src/test/java/</testSourceDirectory>

I really like to try to use VSCode for my Java development but it looks like it not yet ready for this. There are a lot of issues I see here about testing.

Can anyone help me to get my tests working ?

**Comment by jdneo** [comment]
Hi @JdKock，

Is there any repro steps that I can try in my side?

**Comment by jdneo** [comment]
Hi @JdKock 

Is the problem still occur?

**Comment by JdKock** [comment]
No it's working now. Thnx.

**Comment by AndrzejPajda** [comment]
@JdKock 
Can you share how did you solve this issue? My CodeLens is properly recognizing test classes but not showing them in the test outliner. I am also getting 'Failed to get workspace folder for test items.' error when trying to run any tests.

**Comment by adchang** [comment]
@AndrzejPajda 
Any progress on resolving this? I have the same exact issue. I opened my Maven project in VS Code (working in Eclipse). CodeLens shows Run/Debug Test, but Test Explorer is empty. When I click Run or Debug Test, I am getting the "Failed to get workspace folder for test items"

Folder is added to workspace; .classpath is correct (with the attribute test); tried testSourceDirectory in pom; java.autobuild.enabled = auto; ran Update project configuration; cleaned java server workspace; running mvn test works

In Java Test Runner, I'm getting the error "Test job is canceled.Failed to clean up. TypeError: this.testIds is not iterable"...not much info googling this error

**Comment by jdneo** [comment]
@AndrzejPajda @adchang

Are you just running your project in your local environment? Or in a `Remote` environment?

Would you mind the share the project to us for diagnostic?

**Comment by adchang** [comment]
This is happening to me in a local environment and a new mvn project

Thanks for looking into it!

********************************************************************************
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Chrome OS: Linux x64 4.19.98-08076-g24ab33fb8e14

Java:
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Maven:
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T01:41:47+07:00)
Maven home: /opt/adchang/bin/apache-maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /opt/adchang/sdk/jdk-1.8.0_201/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.19.98-08076-g24ab33fb8e14", arch: "amd64", family: "unix"

Extensions:
Dart 3.9.1
Debugger for Java 0.25.1
Flutter 3.9.1
GitLens 10.2.1
Java Dep Viewer 0.9.0
Java Ext Pack 0.9.0
Java Test Runner 0.22.3
Language Support for Java 0.60.0
Maven for Java 0.21.2
Python 2020.4.74986
REST Client 0.23.2
VS intelliCode 1.2.6
XML 0.11.0

Repro steps:
1. New window
2. Save workspace as...
3. Create Maven Project > archetype-quickstart-jdk8 > 1.2.0
    groupID: com.example.hello
    artifactID: example-hello
    version: 1.0-SNAPSHOT
    package: com.example.hello
4. Add Folder
5. Run Test for testApp()
    Get "Failed to get workspace for the test items"
6. mvn clean, mvn test
    build success
7. Run Test for testApp() -> Same error

[878.zip](https://github.com/microsoft/vscode-java-test/files/4537834/878.zip)

**Comment by jdneo** [comment]
@adchang I tried the steps on my Windows machine but not able to repro.

Are you able to run the tests if you directly open the folder in vscode? (Not add folder to workspace)

What the result if you click the CodeLen (Run/Debug Test)

**Comment by adchang** [comment]
@jdneo Unclear what you mean by "directly open the folder in vscode"

I did:
1. New Window
2. File > Open Folder and selected example-hello
3. Click on CodeLens Run Test, same "Failed to get workspace for the test items"

FWIW, visually, this looks about the same as "Add folder to workspace"

I also went into the workspace file and changed it from relative to fully qualified and still got the same error

I am using ChromeOS. Will try on my ubuntu after I upgrade to 20.04

**Comment by jdneo** [comment]
Yes please try on Ubuntu and let me know the result.

**Comment by adchang** [comment]
@jdneo Same error :(

1. Created a new VM with ubuntu 20.04
2. Installed java 11.0.7, mvn 3.6.3
3. Installed VS Code via Ubuntu Software
4. Installed Java Ext Pack

**Comment by jdneo** [comment]
Have no idea what's happening. I tried the attached project both on Windows and Mac, they just works fine. :(

**Comment by adchang** [comment]
@jdneo Any devs troubleshooting linux?

Seems to be failing on the first check, ie there's a workspace. Any clues as to where I should look to help out & contribute?

**Comment by jdneo** [comment]
@adchang

It will be great if you would like to debug locally on your side. See this [doc](https://github.com/microsoft/vscode-java-test/blob/master/CONTRIBUTING.md) for the guidance.

**Comment by numbernumberone** [comment]
@adchang

**Comment by numbernumberone** [comment]
Can you share how did you solve this issue? I am also getting 'Failed to get workspace folder for test items.' error when trying to run any tests.I am running my project in a remote environment(centos 7)

**Comment by numbernumberone** [comment]
@adchang 
Can you share how did you solve this issue? I am also getting 'Failed to get workspace folder for test items.' error when trying to run any tests.I am running my project in a remote environment(centos 7)
![image](https://user-images.githubusercontent.com/17960477/133063710-2ef19a48-5849-4f57-b553-83deffddc687.png)

**Comment by adchang** [comment]
Sorry, I gave up and was just using eclipse. Haven't been using java for a
while. Were you able to get it to work?

**Comment by adchang** [comment]
Just gave it a try. Seems to be working on my ubuntu now, but still not
working on my ChromeOS
