### ISSUE TITLE
Test can't work

### ISSUE THREAD

**Issue by zhongxigong** [microsoft/vscode-java-test#882]
when I trying to test my java code, it occurs like the msg Error: 

org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.Error: org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(Ljava/lang/String;)Lorg/eclipse/jdt/core/IJavaProject;.

**Comment by jdneo** [comment]
What if:

1. Trigger the command: `Java: Clean the Java Language Server workspace`
2. Delete and restart

**Comment by embersdev** [comment]
I get the same error and the clean didnt help.

**Comment by jdneo** [comment]
@zhongxigong @embersdev

Could you provide a sample project to us for investigation?

**Comment by embersdev** [comment]
Im trying to narrow this down first.  This error is on a Mac using java 11.  Same code works on windows with java 8.  Will test out java versions on both then let you know what I discover.

Tried on the make with Junit 4 and 5.  same error.

**Comment by embersdev** [comment]
let me correct that.  Windows
Windows: java version "1.8.0_221" 
Mac: java version openjdk version "11.0.3"

**Comment by zhongxigong** [comment]
java test can work in windows, but not mac 。

**Comment by jdneo** [comment]
Hi @zhongxigong @embersdev,

Could you provide more information about this issue? like:

- What's your project build tool? Maven? Gradle?
- The test framework your are using. JUnit 4? JUnit5? TestNG?
- How you triggered your tests? Code Lens? Test Explorer?

Also, it would be very helpful if a sample project could be provided. If not, a code snippet would be fine.

Thanks.

**Comment by WJayesh** [comment]
@jdneo I am facing a similar issue on Ubuntu when running [code-server](https://github.com/cdr/code-server). Are there any updates on this? A sample [repository ](https://github.com/LableOrg/java-maven-junit-helloworld)to use.
The issue exists when running through Code Lens and Test Explorer both.
It's a maven project.

**Comment by WJayesh** [comment]
If it helps, I tried version 0.20.0 and it works perfectly :+1:

**Comment by jdneo** [comment]
@WJayesh If using 0.21.0 and not running on code-server but just latest VS Code. Will it work?

**Comment by WJayesh** [comment]
I'll try it out and let you know 

> @WJayesh If using 0.21.0 and not running on code-server but just latest VS Code. Will it work? I tried on my side with Windows 10 + JDK 11, it works well. So I'm not sure if it is a problem with Code Server

I'll try it out and let you know
