### ISSUE TITLE
JUnit 5 Tests w/ @Mocks in Method Cannot be Launched Individually

### ISSUE THREAD

**Issue by dansiviter** [microsoft/vscode-java-test#883]
If you have Mockito mocks injected into the test method and try to launch the single test at method level (not at class level) using 'Run Test' it fails with:

```
Error: Failed to load JUnit launch configuration.Error: Failed to load JUnit launch configuration.
```

Example:

```
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class MyTest {

  @Test
  public void doTest(@Mock MyMock myMock) {  // this method cannot be launched individually
    ... do something!
  }
}
```

**Workaround:** 
Launch at class level.

**Comment by jdneo** [comment]
Hi @dansiviter,

I'm trying to repro this issue but it could not on my side. Is there anything I missed?

![demo](https://user-images.githubusercontent.com/6193897/69841472-3e6fcf80-129a-11ea-8351-44a57bc65091.gif)
