### ISSUE TITLE
Cannot have underscore in folder name

### ISSUE THREAD

**Issue by pyramid-johng** [microsoft/vscode-java-test#884]
This one took a long time to discover.

I am using a workspace (via code-workspace JSON) and maven, and all of my projects (in the workspace) work properly with the Test Runner, except for one.  In this project, the "mvn test" goal runs perfectly, but any attempt to use the Code Lens to execute tests resulted in a "workspace item not found" error and tests would not execute.

I cross-checked all of the "eclipse" project files (e.g. .classpath etc.) and they were all made to be identical (to the working ones), yet this project would refuse to run tests via Code Lens.  I even deleted all of those files, and let the IDE regenerate them (they were identical to the ones I deleted btw) to no avail.

I finally looked at my file system layout, and only thing different about this project was it had an underscore in the folder name "XXX_Operations".  After i removed the underscore "XXXOperations" lo and behold, everything started working!  I have no explanation for this behavior, but I wanted to report it, because it caused me 3 (lost) hours of troubleshooting.

**Comment by jdneo** [comment]
Hi @pyramid-johng,

I'm try to repro this issue according to your description. Attached with an gif to show what I was doing. Please correct me if I miss anything.
![demo](https://user-images.githubusercontent.com/6193897/69840880-12534f00-1298-11ea-893e-62bfde7b9792.gif)

Basically, I cannot repro this issue when the folder contains underscore.

Are you in the Linux dev environment and using symlink for the folder `XXX_Operations`?

**Comment by pyramid-johng** [comment]
it is windows and there are no symlinks anywhere in the workspace.  i am using an explicit workspace file and not a "default" workspace and all the "names" have spaces in them.

{
	"folders": [
		{
			"path": "build",
			"name": "Build Deployable Assets"
		},
		{
			"path": "deploy",
			"name": "Deployable Assets"
		},
		{
			"path": "iDirectDocPlugin",
			"name": "Plugin (Global Settings)"
		},
		{
			"path": "iDirectDocPropertyEditor",
			"name": "Custom Editors"
		},
		{
			"path": "iDirectDocServices",
			"name": "Services WAR"
		},
		{
			"path": "PyrasolWidgets",
			"name": "Widget Package"
		},
		{
			"path": "ContentEngineActions",
			"name": "Elasticsearch Index CE Update Action"
		},
		{
			"path": "IDDOperations",
			"name": "Process Engine Custom Operations"
		}
	],
	"settings": {
		"java.home": "C:\\Program Files\\Java\\jdk1.8.0_192",
		"maven.terminal.useJavaHome": true,
		"maven.executable.path": "C:\\java\\apache-maven-3.6.0\\bin\\mvn",
		"terminal.integrated.cwd": "c:/projects/ECM/iDirectDoc/repos",
		"terminal.integrated.env.windows":{
			"MAVEN_HOME": "C:/java/apache-maven-3.6.0"
		},
		"eslint.enable": false,
		"java.configuration.updateBuildConfiguration": "automatic"
	}
}

**Comment by jdneo** [comment]
Hmm, still could not repro if I use an explicit workspace file.

So, The folder `IDD_Operations` could not work if it's contained in the workspace file. What if directly open it in VS Code? (I mean not using the multi-root feature, but just open the folder `IDD_Operations`)
