### ISSUE TITLE
Test Runner should be visible even when not viewing a test file.

### ISSUE THREAD

**Issue by bdway** [Microsoft/vscode-java-test#89]
As soon as I navigate away from a test file the Test Runner disappears. When I navigate back to a test file the Test Runner re-appears but the tree is collapsed.

**Comment by ansyral** [comment]
@bdway, right now only java file(no matter a test file or not) would trigger test explorer. This is not to bother users when they open a node project or something else.

**Comment by jeffgbutler** [comment]
Could you add a command to open, and keep open, the test explorer?

**Comment by ansyral** [comment]
@jeffgbutler yes, that could be an enhancement

**Comment by wolf99** [comment]
Does #271 cover this?

**Comment by jdneo** [comment]
@wolf99 Thank you for reminding! Yes, it is.

The current behavior is that once the extension is activated (for example the user opens a java file), then the explorer will be pinned in the activity bar. 

While before the extension is activated, the explorer will not show.

We will release the new version recently.

**Comment by jdneo** [comment]
Fixed in #291
