### ISSUE TITLE
test didn't launch when setting files.encoding to iso88591 

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode-java-test#896]
When set another encoding for java file
"[java]": {
        "files.encoding": "iso88591"
    }, 

launching test fails 

![image](https://user-images.githubusercontent.com/524083/70057991-68006200-15de-11ea-88bf-387d6e4e7c5a.png)

Workaround: 
remove the setting

**Comment by jdneo** [comment]
Hi @llgcode,

Thank you for reporting. We recently merged a PR related with the encoding issue: https://github.com/microsoft/vscode-java-test/pull/885, I think that may resolve your issue. I'll inform you in the issue thread once the fix is released.

**Comment by jdneo** [comment]
Hi @llgcode, 

The new version of Test Runner was released. Please feel free to have a try with the latest(0.22.0) version and please let me know if this problem has been solved.

Thanks.

**Comment by llgcode** [comment]
It works now. Thank you @jdneo
:-)
