### ISSUE TITLE
Tests no longer being detected/extension not working.

### ISSUE THREAD

**Issue by patrickwhittell** [microsoft/vscode-java-test#899]
I had previously been working with the extension with no problems, using test explorer and CodeLens, however recently both have ceased to work entirely. No option to run or debug tests on CodeLens, Test explorer appears empty, clicking refresh or run buttons on test explorer gives me "command 'java.test.explorer.refresh' not found". VSCode and extensions are all up to date.

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601

TestRunner 0.21.0

Maven project dependencies for Tests

<dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>1.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>5.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>

Classpath is as one would expect a working one to be, going from the workaround being lauded, I have tried everything I can think of and am at the point where I can no longer develop and meet project deadlines unless we shift entirely to a different IDE.

**Comment by jdneo** [comment]
If you get `command 'XXX' not found` error, mostly it's caused by the extension failed to activate.

Please first check if the Java Language Server is start-up in a good way. Check the output channel and please let us know if there is any error logs there.

**Comment by patrickwhittell** [comment]
I believe the language server is operating normally. I'm seeing nothing in the output pane, and I get the following from querying the extension logs:

message: 'Starting Java server with: C:\\Program Files ' +
    '(x86)\\Java\\jdk1.8.0_161\\bin\\java ' +
    '-Declipse.application=org.eclipse.jdt.ls.core.id1 ' +
    '-Dosgi.bundles.defaultStartLevel=4 ' +
    '-Declipse.product=org.eclipse.jdt.ls.core.product ' +
    '-Dfile.encoding=utf8 -DwatchParentProcess=false -noverify -Xmx1G ' +
    '-XX:+UseG1GC -XX:+UseStringDeduplication -jar ' +
    'c:\\Users\\patrick.whittell\\.vscode\\extensions\\redhat.java-0.54.1\\server\\plugins\\org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar ' +
    '-configuration ' +
    'c:\\Users\\patrick.whittell\\.vscode\\extensions\\redhat.java-0.54.1\\server\\config_win ' +
    '-data ' +
    'c:\\Users\\patrick.whittell\\AppData\\Roaming\\Code\\User\\workspaceStorage\\084bfbae61d6b2cce4cf292f4a0bc084\\redhat.java\\jdt_ws',
  level: 'info',
  timestamp: '2019-12-05 09:42:43.277'

**Comment by patrickwhittell** [comment]
!SESSION 2019-12-05 09:42:44.206 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_161
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_GB
Command-line arguments:  -data c:\Users\patrick.whittell\AppData\Roaming\Code\User\workspaceStorage\084bfbae61d6b2cce4cf292f4a0bc084\redhat.java\jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:05.678
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:08.913
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.058
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.060
!MESSAGE Initializing Java Language Server 0.48.0.201912041640

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.123
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.0/dist/com.microsoft.jdtls.intellicode.core-0.3.14.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.132
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-debug-0.23.0/server/com.microsoft.java.debug.plugin-0.23.0.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.139
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-dependency-0.6.0/server/com.microsoft.jdtls.ext.core-0.6.0.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.254
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/com.microsoft.java.test.plugin-0.21.0.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.299
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.eclipse.jdt.junit4.runtime_1.1.1000.v20190510-0840.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.358
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.eclipse.jdt.junit5.runtime_1.0.500.v20190510-0840.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.505
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.api_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.578
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.engine_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.701
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.migrationsupport_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.803
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.params_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.854
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.vintage.engine_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.861
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.opentest4j_1.1.1.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:09.931
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.commons_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:10.011
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.engine_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:10.079
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.launcher_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:10.161
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.runner_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:10.206
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.suite.api_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:10.228
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.apiguardian_1.0.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:10.375
!MESSAGE Installed reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-maven-0.20.0/jdtls.ext/com.microsoft.java.maven.plugin/target/com.microsoft.java.maven.plugin-0.20.0.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.125
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.eclipse.jdt.junit4.runtime_1.1.1000.v20190510-0840.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.126
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.eclipse.jdt.junit5.runtime_1.0.500.v20190510-0840.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.126
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.vintage.engine_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.127
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.migrationsupport_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.128
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.commons_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.128
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.api_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.129
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.engine_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.130
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.apiguardian_1.0.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.131
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.suite.api_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.131
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.jupiter.params_5.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.132
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.engine_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.133
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.runner_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.133
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.opentest4j_1.1.1.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.134
!MESSAGE Started reference:file:/C:/Users/patrick.whittell/.vscode/extensions/vscjava.vscode-java-test-0.21.0/server/org.junit.platform.launcher_1.4.0.v20190212-2109.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.166
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.167
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.updateSourceAttachment, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveSourceAttachment, java.project.addToSourcePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.167
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.168
!MESSAGE Non-Static Commands: [java.maven.initializeSearcher, java.maven.searchArtifact, java.maven.addDependency, java.maven.controlContext]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.168
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.169
!MESSAGE Non-Static Commands: [vscode.java.test.search.codelens, vscode.java.test.search.items.all, vscode.java.test.search.location, vscode.java.test.search.items, vscode.java.test.get.testpath, vscode.java.test.junit.argument]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.169
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.170
!MESSAGE Non-Static Commands: [java.project.list, java.getPackageData, java.resolvePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.170
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.170
!MESSAGE Non-Static Commands: [vscode.java.checkProjectSettings, vscode.java.isOnClasspath, vscode.java.fetchUsageData, vscode.java.validateLaunchConfig, vscode.java.resolveMainMethod, vscode.java.resolveClasspath, vscode.java.resolveBuildFiles, vscode.java.resolveMainClass, vscode.java.updateDebugSettings, vscode.java.buildWorkspace, vscode.java.startDebugSession, vscode.java.inferLaunchCommandLength, vscode.java.resolveElementAtSelection]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.171
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.171
!MESSAGE Non-Static Commands: [java.intellicode.completion, java.intellicode.completion.resolve, java.intellicode.enable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:14.394
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:21.749
!MESSAGE Importing Maven project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:22.981
!MESSAGE Workspace initialized in 8807ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:23.001
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:23.173
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:23.273
!MESSAGE >>New configuration: {java={home=C:\Program Files (x86)\Java\jdk1.8.0_161, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}}, configuration={checkProjectSettingsExclusions=false, updateBuildConfiguration=disabled, maven={userSettings=null}}, trace={server=off}, import={maven={enabled=true}, gradle={enabled=true, wrapper={enabled=true}, version=null, arguments=null, jvmArguments=null, home=null}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, maven={downloadSources=false, updateSnapshots=false}, referencesCodeLens={enabled=false}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=null}, comments={enabled=true}, onType={enabled=true}}, saveActions={organizeImports=false}, contentProvider={preferred=null}, autobuild={enabled=true}, maxConcurrentBuilds=1.0, completion={enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], filteredTypes=[java.awt.*, com.sun.*], importOrder=[java, javax, com, org]}, foldingRange={enabled=true}, progressReports={enabled=true}, codeGeneration={hashCodeEquals={useJava7Objects=false, useInstanceof=false}, useBlocks=false, generateComments=false, toString={template=${object.className} [${member.name()}=${member.value}, ${otherMembers}], codeStyle=STRING_CONCATENATION, skipNullValues=false, listArrayContents=true, limitElements=0.0}}, selectionRange={enabled=true}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=false, showQualifiedNames=false, showLogicalStructure=true, showToString=true, maxStringLength=0.0, hotCodeReplace=manual, enableRunDebugCodeLens=true, forceBuildBeforeLaunch=true, console=integratedTerminal}}, dependency={showOutline=true, syncWithFolderExplorer=true, autoRefresh=true, refreshDelay=2000.0, packagePresentation=flat}, help={firstView=auto}, test={report={showAfterExecution=onFailure, position=sideView}, editor={enableShortcuts=true}, log={level=info}, message={hintForDeprecatedConfig=true, hintForSetingDefaultConfig=true}, defaultConfig=, config={}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:23.274
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:29.808
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:29.912
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:30.196
!MESSAGE >> workspace/executeCommand java.maven.initializeSearcher

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:30.198
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:43:55.519
!MESSAGE Reconciled 0. Took 25250 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:17.416
!MESSAGE begin problem for /UserCredentialsCognitoHelperTest.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:17.416
!MESSAGE 1 problems reported for /UserCredentialsCognitoHelperTest.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:17.417
!MESSAGE Validated 1. Took 85 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:17.679
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:24.879
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:25.880
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:25.882
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:44:25.883
!MESSAGE >> watchers registered

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:06.363
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:06.847
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:07.093
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:07.760
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:07.839
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:08.981
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:09.452
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:09.860
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:46:13.074
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:47:11.058
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 09:47:15.928
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:09:28.621
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:09:34.713
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.792
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.793
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.793
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.800
!MESSAGE >> workspace/executeCommand java.project.list

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.807
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.813
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.813
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.814
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.814
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.815
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.815
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.819
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.824
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:11.868
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:13.392
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:13.488
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:13.907
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:14:28.890
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:26:59.766
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:26:59.767
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:26:59.927
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:26:59.985
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:27:04.582
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:27:08.988
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:27:08.989
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:27:09.147
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:27:09.203
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-05 10:28:13.680
!MESSAGE >> workspace/executeCommand java.resolvePath

**Comment by jdneo** [comment]
It would be helpful if a sample project could be provided.

**Comment by patrickwhittell** [comment]
I'm not sure how helpful a sample project would be to you. I strongly suspect everything would work as expected; a colleague of mine has been able to use the test explorer + CodeLens tests as expected, plus debugging (I also have an issue where attempting to launch debugging on Tomcat is not working, throwing an error). I think there is an issue with my environment, I'm happy to provide you with any additional information you think would help you diagnose the issue with this in mind.

**Comment by jdneo** [comment]
So you mean the same project works fine on your colleague's machine?

**Comment by patrickwhittell** [comment]
Yes, it does. He has the same vscode/plugins version

On 7 Dec 2019 02:57, Sheng Chen <notifications@github.com> wrote:

So you mean the same project works fine on your colleague's machine?

**Comment by jdneo** [comment]
Hmm, Is there any error in the console if you open `Help` > `Toggle Developer Tools`?

**Comment by patrickwhittell** [comment]
Developer Tools console proved to be the help I needed, thank you. Java Debug extension was failing to activate due to the dist folder being mysteriously vanished, and the test runner depends on this extension (I have also been unable to attach a debugger to my code), uninstalling the extension, deleting the folder and then reinstalling has fixed both issues, many thanks for your guidance.

**Comment by jdneo** [comment]
Good to know the issue is solved! 👍
