### ISSUE TITLE
incorrect code lens 

### ISSUE THREAD

**Issue by gorkem** [Microsoft/vscode-java-test#90]
The code lenses for  testing are not removed when the `@Test` annotation is removed from a test method.

![image](https://user-images.githubusercontent.com/82738/34798185-0abcc4ca-f629-11e7-9797-8e821880966f.png)

**Comment by ansyral** [comment]
After some investigation, it seems to be a bug of JDT. When removing the annotation`@Test`, `IAnnotatable.getAnnotation("Test")` would still exist while `IAnnotatable.getAnnotations()` is empty. will make a  workaround for it first.

**Comment by gorkem** [comment]
@ansyral Is this already reported on JDT?
