### ISSUE TITLE
Incomplete sourceSet when running from extension with Gradle project

### ISSUE THREAD

**Issue by Barbiero** [microsoft/vscode-java-test#901]
I've been trying to run tests through this extension on our project, which uses an annotation processor to generate sources. Then, I add the generated sources directory to my `sourceSets` on my build.gradle, and thats enough for `./gradlew test` to run. On Eclipse, I have an option to configure annotation processors output directory and it's junit runner will recognize the directory normally.

However, when running with this extension, it seems that it can't recognize the `srcDirs` I set on my build.gradle and the tests fail with `ClassNotFoundException` for classes inside the 'generated' folders.

# Minimum reproductible steps:

Create a basic gradle project with the following structure for the `src` dir:

```
src
|
- main/java/rootpackage
- test/java/rootpackage
- generated/java/rootpackage
```

Add the following `sourceSets` on build.gradle:
```gradle
sourceSets {
    generated {
        java {
            srcDirs = ['src/generated/java']
        }
    }
    main {
        java {
            srcDirs += generated.java.srcDirs
        }
    }
    test {
        java {
            srcDirs += generated.java.srcDirs
        }
    }
}
```
(don't forget to refresh the project to update the classpath)

Add a basic class in `generated/java/rootpackage` just for this test:
```java
public class GeneratedClass {
    public boolean thisShouldWork() {
        return true;
    }
}
```

Write a test that references said class:
```java
class AppTest {

    @Test
    public void itWorks() {
        assertTrue(new GeneratedClass().thisShouldWork());
    }
}
```

Run `gradle test` on the command line. The test should pass no problem.

Try to run it on the vscode-java-test extension. The test will fail.

**Comment by jdneo** [comment]
Hi @Barbiero,

I tried it on my side but not able to repro. Attached with a gif, please let me know if there is anything missing.

meanwhile, you can also try the following action to see if it could help:

- Trigger the command `Java: clean the java language server workspace` > `delete and restart`
