### ISSUE TITLE
Test report Stack trace could navigate or click to the file.

### ISSUE THREAD

**Issue by jkryanchou** [microsoft/vscode-java-test#902]
I have met an error when running a test. while I couldn't click to the file like in debug console. Is there any other solution to work it out?  I want to navigate the file. 
![image](https://user-images.githubusercontent.com/1206342/70453073-1a568e80-1ae3-11ea-85d7-09f5c51c91f4.png)

**Comment by jkryanchou** [comment]
I found it not convenient to dig into the error position of file. I wonder how to navigate the stack trace file like IDEA. Is there any solution to help me navigate it.?

**Comment by jkryanchou** [comment]
I wish this feature should be added as soon as possible. While I have no other way to navigate the stack trace file. I had to switch to IDEA to figure it out.

**Comment by jdneo** [comment]
Thanks for providing the feedback. Since it's dup with #384, I'll close this one and let's track it in #384

**Comment by jkryanchou** [comment]
@jdneo what time the feature would be released?  Wish it release soon.

**Comment by jkryanchou** [comment]
@jdneo Could vscode-java-test output stack trace into debug console? I could navigate the file path through the console panel. Because I have no other way to dig insight into it correctly.
