### ISSUE TITLE
Consider redirect the test stack trace into the debug console

### ISSUE THREAD

**Issue by jkryanchou** [microsoft/vscode-java-test#903]
I run a test case raise a exception on stack trace in the test report while I could not see the whole filename on it. While in the IDEA, I could see the whole stack trace. in de debug console.
Could author redirect the stack trace into the debug console? it also could navigate the stack trace file through the debug console panel.

![image](https://user-images.githubusercontent.com/1206342/70500606-e917a600-1b56-11ea-9580-a8d7ea95016b.png)

**Comment by jdneo** [comment]
There is a scroll bar at the bottom of the view.

**Comment by jkryanchou** [comment]
@jdneo I knew this is a up-down scroll bar, while I couldn't see the right part which show the exact line of file. the stack trace show the whole information of exceptions or omit some part.

**Comment by jkryanchou** [comment]
@jdneo Is there any settings I could configure redirect the exception into DEBUG CONSOLE. or Output. I could view the whole stack trace info.

**Comment by jdneo** [comment]
Sorry there is no such setting for now. Will consider to add the ability to redirect it into debug console.

**Comment by jkryanchou** [comment]
@jdneo Would the feature release in next version? Be eager to see the feature in next release. Because there is no other way to help me out within the VSCode.

**Comment by jkryanchou** [comment]
1. Redirect to the Debug Console
2. The stack trace file could be clickable to the file location such as DEBUG CONSOLE panel.

**Comment by jkryanchou** [comment]
@jdneo Could it be released in 0.22.0?

**Comment by jdneo** [comment]
I cannot say a definite time or version of when this feature get released for now. But it's on our radar.

Meanwhile, if you want to contribute for this feature, you can just send out the PR.

Thanks.

**Comment by jkryanchou** [comment]
@jdneo I got it. If time available. I will.

**Comment by jdneo** [comment]
Thanks @jkryanchou,

IMO, I prefer to support navigate from the stacktrace instead of redirect the output into the debug console, since it will ruin the program's own output.

If you want to implement navigating from the stacktrace, here is a reference of the debugger's Java implementation: https://github.com/microsoft/java-debug/blob/ac7d26bcfd5736f2cabd93f2bc065aa8ff302088/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java#L256-L280

Meanwhile, I'll ask the team if it is possible to let either Debugger or Language Server to expose the related API for navigating from the stacktrace. If we have this API, things would be much easier.

**Comment by jdneo** [comment]
Related issue in language server https://github.com/eclipse/eclipse.jdt.ls/issues/1202

If we have this API in language server, both Debugger and Test Runner can leverage it.

**Comment by jkryanchou** [comment]
@jdneo Got it. Thanks. If I could navigate the traceback in DEBUG Console. it could be link to the proper file location easily.

**Comment by jdneo** [comment]
@jkryanchou I still not prefer redirecting the stacktrace to debug console. This will ruin the program's output. We should enable the feature in the test report.

**Comment by jkryanchou** [comment]
@jdneo OK.

**Comment by jdneo** [comment]
Now it's supported to navigate from stracktrace to source location in `0.26.0` (with `Language Support for Java(TM) by Red Hat` upgrade to `0.70.0`).

Is this solved your problem @jkryanchou?

**Comment by jkryanchou** [comment]
@jdne OK I will try it later.

**Comment by jdneo** [comment]
Close since being inactive for a long time. Please let me know if you have any concerns.
