### ISSUE TITLE
Possibility to execute all tests under a package and sub-packages of it

### ISSUE THREAD

**Issue by blassmegod** [microsoft/vscode-java-test#907]
Would be really great to be able to execute all tests under a package and sub-packages of it, would be easier to test a full functionality grouped by package and sub-packages without the need to create a test suite.

**Comment by jdneo** [comment]
Have you tried to run all the tests under a package in the Test Explorer?

![image](https://user-images.githubusercontent.com/6193897/71231729-18ce6700-232a-11ea-88be-0c5609a31150.png)

**Comment by blassmegod** [comment]
yes, this part works, I mean to execute all tests under "com.example.project" package including the tests under sub-packages, like "com.example.project.functionality1", "com.example.project.functionality2", "com.example.project.functionality3.base", "com.example.project.functionality3.extended". Just with one run. For now I have to go on each sub-package to execute them.

**Comment by jdneo** [comment]
I see. Can I understand that as to support multi-selection in the `Test Explorer`? In that case you can select those sub-packages together and run them in one execution.

**Comment by blassmegod** [comment]
Multiselect would be nice too. Thanks

**Comment by jdneo** [comment]
In 0.31.0 we support multi selection in test explorer, which should mitigate this problem.
