### ISSUE TITLE
environment variable(config) when running test by code lens

### ISSUE THREAD

**Issue by iKoru** [microsoft/vscode-java-test#910]
[provide a description of the issue]

Is there any way to set environment variables when running a test (or debug) by code lens?
I couldn't find in the documents.

##### Environment
- Operating System: Windows 10 64bit
- JDK version:1.8.0 (think it's irrelevant)
- Visual Studio Code version: 1.40.0
- Java extension version: 0.54.2(latest)
- Java Debugger extension version: 0.23.0(latest)

##### Steps To Reproduce
1. [step 1] enable code lens
2. [step 2] run test or debug by clicking code lens

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
any project you want(not a bug)

##### Current Result
environment variables weren't set
##### Expected Result
there sould be any way to set environment variables.

**Comment by testforstephen** [comment]
@jdneo could you take a look?

**Comment by jdneo** [comment]
Hi @iKoru,

You can simply add a test config into your workspace setting. See: https://github.com/microsoft/vscode-java-test/wiki/Run-with-Configuration

**Comment by iKoru** [comment]
Hi @jdneo ,
Even I have made a setting java.test.config on settings.json, it doesn't work. it just shows the results not applied the config (environment variables).

The document says that there would be a message to select the configuration that I want to apply, but no dialog shows.

> The extension will let you select the configuration if it detects there are customized configuration available.

I wrote the properties: name, env, vmargs. Is there anything I omitted?

**Comment by jdneo** [comment]
@iKoru,

if it is possible, could you please share your whole settings.json file? Please also make sure the config is set in `workspace setting`, not the `user setting`

**Comment by iKoru** [comment]
@jdneo 
Here is my workspace settings.json file. Sorry for poor formatting and there might be some typos because my workspace is in offline environment and I wrote them manually, but in my workspace, there is no warning sign due to format error.
`{
	"folders":[{"path":"."}],
	"settings":{
		"java.configuration.updateBuildConfiguration": "automatic",
		"java.dependency.packagePresentation":"hierarchical",
		"maven.view":"hierarchical",
		"java.import.gradel.wrapper.enabled":false,
		"java.codeGeneration.generateComments":true,
		"java.format.onType.enabled":false,
		"java.progressReports.enabled":false,
		"java.import.gradle.enabled":false,
		"java.test.config":[{
			"name":"configName",
			"env":{
				"someKey":"someValue",
				"anotherKey":"anotherValue"
			},
			"vmargs":["-Dthe.other.key=true"]
		}],
		"java.debug.settings.console": "integratedTerminal"
	}
}`

**Comment by jdneo** [comment]
Thank you @iKoru, the config looks fine.

Then could you please also take a look at your user settings to see if there is any test config related settings there?

**Comment by iKoru** [comment]
Thanks for your kind response, @jdneo ,
In my user settings, there are settings about java and maven like these : 

java.home : (path to java)
java.configuration.maven.userSettings : (path to settings.xml)
java.implementationsCodeLens.enabled : true
maven.terminal.customEnv : (same as the previous env)
java.jdt.ls.vmargs : (memory settings and including lombok.jar)
java.referencesCodeLens.enabled : true
java.codeGeneration.generateComments: true
maven.terminal.useJavaHome : true

but there is no settings about java.test.**. 
Please note that I removed java.test.config setting on my user settings since you mentioned earlier (https://github.com/microsoft/vscode-java-test/issues/910#issuecomment-568951745)
and it seems no differences. Maybe the offline environment is the problem?

**Comment by iKoru** [comment]
Also, I want to mention that there is a warning sign when I try to execute test or debug by code lens button, 
it says that "C#" extension always tries to update its dependencies through the internet which always fails due to offline(it's a little bit weird because I don't have any C# code files in the workspace and I tried to execute "Java". 
And there is another dialog, this time from "Debugger for Java" extension, "Build failed, do you want to continue?."
That's because I created issue on Debugger for Java repository at the beginning. 
There are some build errors, of course. but it's irrelevant to test function that I want to execute, it just disappears when I try to rebuild the project that has such error, and when I just select "Proceed", the test starts well (without environment variables). 
But I've experienced that there was no such a dialog when I used "java test runner" extension version 0.19.0 at first. (I've just tested using this version and it figured out that it **also** doesn't have the variables)

What a confusing situation..

**Comment by jdneo** [comment]
> it says that "C#" extension always tries to update its dependencies through the internet which always fails due to offline

I guess this should be something related with the C# extension.

> But I've experienced that there was no such a dialog when I used "java test runner" extension version 0.19.0 at first

This is because we changed the implementation recently. Previously we will resolve the classpaths and then launch a new process to run the java command. And now, what we did is just construct the launch configuration and pass it to Java Debugger, let the Java Debugger to handle the execution.

To be honest, I have no idea about this issue now. How about one last try: create a new setting `java.test.defaultConfig`, and point it to the name of the configuration you have mentioned before.

If this still not work, could it be possible that sharing a sample project which can repro this issue to us for diagnostic? Sorry for not giving enough help about this...

**Comment by iKoru** [comment]
Thanks for your kindness. Sadly, I'm facing the same situation even though I set the default config. :(
I'd try something I can do more and let me ask you further. I'm really appreciated for your help.

**Comment by joshvanderberg** [comment]
I have basically the same issue, and have tried all the same steps as iKoru has.

I've tried the following:

**Comment by joshvanderberg** [comment]
I basically have the same issue iKoru has.  I've tried the following:	

```
"java.test.config": {
        "name" : "middletier",
        "vmargs": ["-Dspring.profiles.default=TEST", "-Dcatalina.home=/opt/local/tomcat/","-Xms512M","-Xmx1024M"]
    },
"java.test.defaultConfig": "middletier"
```
In the Workspace, User, and the Remote Dev Container settings.

And verified that in each case wherever I put it, it was only in that location.

No matter what, the vmargs are not applied.  If I remove the defaultConfig, I am not prompted for a config when I run test.  It feels like the java.test.config just isn't being detected at all.

Could this be related to running this in a container?  It's just a pretty stock JDK8 container.

**Comment by rdcoe** [comment]
I've just hit this issue.  My settings are:
`{
    "java.test.config": [
        {
            "name": "chatsrv",
            "workingDirectory": "${workspaceFolder}/chatsrv/",
            "java.test.log.level": "debug",
            "vmArgs": [ "-Dvertx.disableDnsResolver=true" ]
        }
    ],
    "java.test.defaultConfig": "default",
    "search.usePCRE2": true,
    "zenMode.restore": true
}`

but when I run my test, the output I get tells me the vmArg is ignored.  I use the same vmArg in the launch config of my code-workspace file:
    `"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"name": "CodeLens (Launch) - MainVerticle",
				"type": "java",
				"request": "launch",
				"mainClass": "ca.xxxx.chat.MainVerticle",
				"projectName": "chatsrv",
				"args": "-conf /d/cygwin64/home/rcoe/linked/conf/config.json",
				"vmArgs": "-Dvertx.disableDnsResolver=true -DVERTXWEB_ENVIRONMENT=dev",
				"stopOnEntry": false
			}
		]
	}`

As an experiment that made no difference, I removed the [ ] from the vmArg in the test config, because they aren;t needed in the launch config.

**Comment by rdcoe** [comment]
@jdneo Can you please re-open

**Comment by jdneo** [comment]
@rdcoe Seems you set the wrong default config:

`"java.test.defaultConfig": "default"`

Please change to `"java.test.defaultConfig": "chatsrv"` and try again.

**Comment by rdcoe** [comment]
When I try to run with the code lens after changing the config, I now get:

TypeError: t.vmArgs.filter is not a function.TypeError: t.vmArgs.filter
 is not a function.

Going back to "default" allows the test to run.

Thanks

**Comment by jdneo** [comment]
What's your extension version?

**Comment by rdcoe** [comment]
Java Extension Pack v 0.12.1, which includes test runner v0.28.0
