### ISSUE TITLE
 ClassNotFoundException

### ISSUE THREAD

**Issue by lovekill** [microsoft/vscode-java-test#918]
steps:
 1. delete bin dir
2. click run test 
then an ClassNotFoundException will  appear in debug console

**Comment by lovekill** [comment]
The exception stack:
Class not found cn.anjiu.bee.OrderWorkDaoTest
java.lang.ClassNotFoundException: cn.anjiu.bee.OrderWorkDaoTest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
URLClassLoader.java:381
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
ClassLoader.java:424
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
ClassLoader.java:357
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:780)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:503)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)

**Comment by jdneo** [comment]
@lovekill 

what kind of project are you using? Maven/Gradle/Eclipse?

Please share a sample project if it's possible, which would be helpful to diagnostic.

**Comment by lovekill** [comment]
gradle project .
when i clean the java language server workspace  this problem  disappear ！

**Comment by jdneo** [comment]
Good to know problem solved!

**Comment by ETLJ** [comment]
> gradle project .
> when i clean the java language server workspace this problem disappear ！

I had the same issue and this worked for me. Thanks!

**Comment by pkondekar29** [comment]
I tried to clean the JAVA language server and it did not work for me. Can anyone please tell what is the workaround for this issue?

My team is still at JAVA 8 hence I am not sure if I will be able to upgrade to the latest version!

Could you please let me know the extension version in which this is fixed?

**Comment by jdneo** [comment]
@pkondekar29 JDK 11 is only required to launch the Java language server, you can still use JDK 1.8 to build your project.

What if trying the following setting?

```
    "java.home": "C:\\AdoptOpenJDK\\jdk-11.0.8.10-hotspot",
    "java.configuration.runtimes": [
        {
          "default": true,
          "name": "JavaSE-1.8",
          "path": "C:\\Java\\openjdk8u181-b13",
        }
    ],
```

**Comment by TeaTotalin** [comment]
One thing that worked to clear this problem up for me was to build the project on the command line (without running tests).  After that the tests run just fine via the VS Code GUI.  I'm using Maven, so in the project folder I run:

mvn clean install -DskipTests

After that the tests work.

**Comment by jdneo** [comment]
@TeaTotalin Sounds like the project could not be built successfully from the extension, is it possible to provide a sample project?

**Comment by jdneo** [comment]
That's because the build job is done by command line, which could not be done correctly by the extension.

It would be helpful for us to understand the problem if a sampe project can be provided.

**Comment by AlexanderTirik** [comment]
_Update to my problem_. 
The problem was not in the test runner extension. The new maven extension broke the build process. Downgrading to the previous version helped fix it.

> The extension worked fine for a while. But now the tests have stopped building all classes.
> 
> `mvn clean install -DskipTests` only works for unit tests. Integration tests throw the error: `java.lang.IllegalStateException: Unable to read meta-data for class ...` Unfortunately, I can't provide an example project.
> 
> > One thing that worked to clear this problem up for me was to build the project on the command line (without running tests). After that the tests run just fine via the VS Code GUI. I'm using Maven, so in the project folder I run:
> > mvn clean install -DskipTests
> > After that the tests work.

**Comment by jdneo** [comment]
@AlexanderTirik, do you mean the execution results of the maven goal via the maven extension are different?
