### ISSUE TITLE
Can't run all test cases of TestNG project when there are test file in the editor

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-java-test#921]
### Environment:

- OS: Win10
- JDK: 8
- Java Test Runner Extension: 0.22.0

### Repro steps:

1. OpenTestNG project [TestNG-Spring-Example](http://www.mkyong.com/wp-content/uploads/2014/01/TestNG-Spring-Example.zip) and comment `com.mkyong.testng.examples.group.TestGroup.runFinal()` method.
2. Run or Debug test project
    - Running the test in Workspace Root by click `Run All Tests` button 
    - Running the test in Workspace Folder level

### Result:
It's only run the test case `com.mkyong.testng.examples.group.TestGroup`
![image](https://user-images.githubusercontent.com/41051257/72119996-679f7780-3391-11ea-8c5e-81afeecfb552.png)

**Comment by jdneo** [comment]
This is a regression bug

**Comment by ZhengJun003** [comment]
Fixed, Tested in the build: 11842545.
