### ISSUE TITLE
Allow to kill a hanging session

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode-java-test#922]
I have a session that hangs:

![image](https://user-images.githubusercontent.com/15714253/72202301-fe396a80-345d-11ea-8568-80aa12c2095a.png)

However, I have no way to cancel/abort it (and the Output for `Java Test Runner` is empty, so I have no idea what the issue might be either).
There's a closed issue, #101, which asks for a way to abort a hanging test session, but that issue was resolved by fixing the root cause of the hang (and another one, #164, but that was closed as a duplicate of #101).

Of course, it would be best if sessions never hang, but as long as the extension can't guarantee that'll never happen (which, I believe, is impossible to guarantee), there should be a way to easily kill them.

PS: if a user aborts a hanging session, the extension could offer the user a window with the relevant logs etc. and ask to create a GitHub issue, such that the root cause of the hang can be solved as well

**Comment by jdneo** [comment]
@anthonyvdotbe you can use `Java: Cancel Test Job` in the command palette

**Comment by anthonyvdotbe** [comment]
My bad for not having thought of checking the command palette. Thanks @jdneo
