### ISSUE TITLE
No output logs

### ISSUE THREAD

**Issue by Sammers21** [microsoft/vscode-java-test#926]
### Steps to reproduce:
1. git clone https://github.com/artipie/rpm-adapter
2. code rpm-adapter
3. Run unit tests
![image](https://user-images.githubusercontent.com/16746106/72431513-0ff47800-37a6-11ea-9f70-c5102e0ee5a5.png)

### Excepted result:
I see test output logs and progress

### Actual result:
I see only that tests are passed. No logs in the output

### Env
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**Comment by jdneo** [comment]
@Sammers21  

To see the program's own output, please find them in the debug console
![image](https://user-images.githubusercontent.com/6193897/72578369-e015b380-3910-11ea-89b7-1f3498fe0873.png)

To see the test runner's log when running the test, you can set the `java.test.log.level` to `verbose`, and you will find them in the output channel.

**Comment by Sammers21** [comment]
@jdneo , debug console windows is empty

**Comment by Sammers21** [comment]
> To see the test runner's log when running the test, you can set the java.test.log.level to verbose, and you will find them in the output channel.

How can I do it?

**Comment by Sammers21** [comment]
That is what I'm getting with `Java: Open Test Runner Log`:
![image](https://user-images.githubusercontent.com/16746106/72683879-a26d8200-3aec-11ea-81ca-467f6334d50f.png)

**Comment by Sammers21** [comment]
> To see the test runner's log when running the test, you can set the java.test.log.level to verbose, and you will find them in the output channel.

After setting  java.test.log.level to verbose, I'm getting this:
![image](https://user-images.githubusercontent.com/16746106/72683920-1a3bac80-3aed-11ea-9198-559f5d88dbce.png)
It is a complete mess now. Not event similar to what I've expected.

**Comment by Sammers21** [comment]
@jdneo, I'm NOT interested in the test runner(vs-code related thing) logs, but in actual test code produced logs.

**Comment by jdneo** [comment]
@Sammers21 This is related to your project config. If you directly run this project in other platform, like IntelliJ IDEA, there is also no output in the console.

To see them, I guess what you need to do is to update the `log4j.properties`, for example:
```
log4j.rootLogger=DEBUG, CONSOLE
```

**Comment by Sammers21** [comment]
@jdneo, in case I run the tests from the command line or IntelliJ Idea, I'm getting output logs in both cases. Without any additional properties

**Comment by jdneo** [comment]
@Sammers21 If the logs you mean are those error stack trace. It can be found in the Test Report

![image](https://user-images.githubusercontent.com/6193897/72768350-14031880-3c32-11ea-9793-1e6698cbde0d.png)

**Comment by Sammers21** [comment]
@jdneo, no, but logs I mean text messages, produced by code during tests run. Stacktraces could be a part of that.  
Look what I have in my case:
![image](https://user-images.githubusercontent.com/16746106/72788482-0efa9500-3c43-11ea-8ca5-5ebccc0d900d.png)

As you can see, there are no logs at all. The Debug console is empty, the test report is empty as well

**Comment by jdneo** [comment]
This is the test output I directly run `mvn test`

![image](https://user-images.githubusercontent.com/6193897/72789411-b4772e00-3c6e-11ea-8610-d53d3c661905.png)

Do you mean those lines with the SLF4J at the begining?
