### ISSUE TITLE
xml reports for gradle project

### ISSUE THREAD

**Issue by karnwork** [microsoft/vscode-java-test#934]
#694 
Hey, I'm also trying to fetch the generated junit test reports for my gradle project.

       test {
        reports {
            junitXml.enabled = true
            junitXml.destination = file("$buildDir/xml")
            html.enabled = true
        }

Is there any update for the above mentioned issue for junit5?
If not, is it possible to generate xmls for any other test suites? (other than junit5)

Any help is greatly appreciated! :)

**Comment by jdneo** [comment]
I'm sorry the Test Runner extension does not support generate XML report now.

But maybe you can take a look at [this](https://maven.apache.org/surefire/maven-surefire-plugin/)?

**Comment by karnwork** [comment]
Hey, this looks promising. Thanks. 

By the way, if I were to convert my project to a maven project, then can we get XML support?

**Comment by jdneo** [comment]
> if I were to convert my project to a maven project, then can we get XML support?

The XML support is provided by the Maven plugin, so you can get it by running the command line. But for the extension, it will not generate test report file so far.

**Comment by jdneo** [comment]
Close for inactive for a long time. If you have any questions, please still fell free to leave the comments
