### ISSUE TITLE
Horizontal scrollbar too low

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#938]
Please see the screenshot below.  To scroll right/left I first have to scroll down -> then right -> then up and repeat 🔁.  It's very tedious.

![image](https://user-images.githubusercontent.com/14079228/74654485-6152a700-5158-11ea-9f4c-03d87769c518.png)

**Comment by jdneo** [comment]
If enable wrap-all in css:

<img width="757" alt="Screen Shot 2020-02-18 at 7 54 37 PM" src="https://user-images.githubusercontent.com/6193897/74734012-93fbbd00-5288-11ea-9582-251abb38c980.png">

Still not good to me. Any ideas?

**Comment by jdneo** [comment]
Summary:

I'll add the `wrap-all` style to the stracktrace area. (We should avoid horizontal scroll in the page).

Another workaround to this problem is to set the setting `java.test.report.position` to `sideView`, which will show the report in a new editor window -- which has more width.

**Comment by spottedmahn** [comment]
works great, thanks for fixing and releasing so quickly!!
