### ISSUE TITLE
Test report UI Feedback: Overlapping Text, Unformatted Values

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#939]
1. The timings are **on top** of the passing label when the values are large enough
1. Can we **format** the **ms** results? i.e. 3,038ms vs 3038ms or maybe even 3.04s instead of 3083ms
1. Can't read full test name and hovering of it doesn't display it.  Can we **wordwarp** the test name? Perhaps that will be a problem as there are no spaces but there's probably an answer for that somewhere on google/stackoverflow.

![image](https://user-images.githubusercontent.com/14079228/74679934-2f0f6c80-518d-11ea-885a-51987535a18b.png)

**Comment by jdneo** [comment]
A workaround for this is to set the setting `java.test.report.position` to `sideView`.

> Can we format the ms results? i.e. 3,038ms vs 3038ms or maybe even 3.04s instead of 3083ms

Agree!

> Can we wordwarp the test name?

Any example about the `wordwarp` operation?

**Comment by spottedmahn** [comment]
Looks great!  Love the modern tools and release cadence.  This might have taken years not days in the old days.

![image](https://user-images.githubusercontent.com/14079228/75598737-2744a780-5a6c-11ea-9f1f-8a53e939cae0.png)
