### ISSUE TITLE
Cannot parse the JUnit4's parameterized tests correctly

### ISSUE THREAD

**Issue by go1done** [microsoft/vscode-java-test#940]
whenever update the class file,  'Run test' turns out to run test against old file despite any changes.
switch back to 0.22.0 it works fine.

Junit 4.12
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by jdneo** [comment]
Have you set `java.debug.settings.forceBuildBeforeLaunch` to `true`?

**Comment by go1done** [comment]
thanks for checking. 
yes. actually it defaults to be true, doesn't it? same settings work for older version

**Comment by jdneo** [comment]
Hmm.. wired...

I cannot repro this on my side. And actually there should be no changes about this between `0.22.0` & `0.22.1`.

Could you describe more details about your case?

**Comment by go1done** [comment]
not sure it matters, installed the extension on WSL, project files include source files and tests all reside on WSL. 
use case is rather simple. maven compiler plugin 3.8.0 + jdk 11, other dependent vscode extensions are all latest.
I modified the source class but it appeared the stale compiled class file was being used by test runner as resulting test report seemed the same.
let me know if you need more info or somewhere I can look at on my own.

**Comment by go1done** [comment]
I did some more tests and it agrees with your observation that the issue doesn't appear every time. 
But once it appeared it's always there.
A contrived example:
when return value 1 changed to whatever other number, returning results were failed (expected), but when reverted to 1, test reports still show failed and stuck there until restarted vscode . 
 class HelloDemo{
    int sayHello(){
        return 1;
    }
}
public class HelloTest {
    HelloDemo h = new HelloDemo();

    @Parameter(0)
    public int num;
    @Parameter(1)
    public int expected;


    @Parameters
    public static Collection<Object[]> data(){
        return Arrays.asList(new Object[][]{
            {1, 1}, {2, 1}

        });
    }

    @Test
    public void testHello() {
        assertEquals(expected, h.sayHello());
    }


}

**Comment by jdneo** [comment]
Yes I can repro it. Will take a look.

**Comment by jdneo** [comment]
The root cause is here: https://github.com/microsoft/vscode-java-test/blob/master/src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts#L100

We use the regex expression: `/\d+,(@AssumptionFailure: |@Ignore: )?(.*?)\((.*?)\)/` to capture the test id from the test runner's output.

For the JUnit4's parameterized tests, the test runner will return something like `testHello[0](HelloTest)`, `testHello[1](HelloTest)`... (for different parameter inputs). While the index `[0]` should be ignored to make it able to match the test method name.

One quick fix could be change the regex to `/\d+,(@AssumptionFailure: |@Ignore: )?(.*?)(?:\[\d+\])\((.*?)\)/`.

I'll think about if there is any better solution for it.

**Comment by go1done** [comment]
I just installed 0.2.2.  The issue persists.
As the old title indicated ,  junit  can't test against modified source class file.

**Comment by jdneo** [comment]
Cannot repro on my side:
![Kapture 2020-03-01 at 19 52 22](https://user-images.githubusercontent.com/6193897/75625149-52f39900-5bf6-11ea-9c0f-f4041643899e.gif)

**Comment by go1done** [comment]
hello,  thanks for following up. 
I'd like to underscore that you put the class  to be tested and testing class in the same file. Not a doubt they will be re-compiled for testing. 
However my case they were in separate files.  When the source file was changed,   it seemed that test runner didn't trigger  compilation and stale class file was used.
I'm still using 0.22.0 without any issues.

**Comment by jdneo** [comment]
Hmm, still not able to repro:

![Kapture 2020-03-05 at 9 58 02](https://user-images.githubusercontent.com/6193897/75940415-f0d1b700-5ec7-11ea-9027-e612efbc9b58.gif)

It would be helpful if you can directly share a sample project to us. Maybe the different folder structure can cause the problem?

**Comment by go1done** [comment]
just use maven to scaffold a tiny project.  strange only version works fine. 

my-app
|-- pom.xml
`-- src
    |-- main
    |   `-- java
    |       `-- com
    |           `-- mycompany
    |               `-- app
    |                   `-- App.java
    `-- test
        `-- java
            `-- com
                `-- mycompany
                    `-- app
                        `-- AppTest.java

**Comment by jdneo** [comment]
Hmm, still works on my side:
![Kapture 2020-03-05 at 15 31 09](https://user-images.githubusercontent.com/6193897/75958136-956aed80-5ef6-11ea-9d1f-b006e920b65a.gif)

**Comment by go1done** [comment]
well , I can repro yours.... have you noticed above two test cases only one report returned?
can you add one line and see if anything is different? Thanks. 
@RunWith(Parameterized.class)
public class AppTest {

**Comment by jdneo** [comment]
I think I get your point. Did you mean that the test report should look like this:

```
AppTest
`--TestHello
     |--#1 test
     `--#2 test
  
```

**Comment by go1done** [comment]
if not indexed, actually one test result masked the other and the issue as well.

**Comment by jdneo** [comment]
If a test case contains multiple executions, like parameterized test, repeated tests, the test report should show each execution results. Am I right?

**Comment by go1done** [comment]
yeh at least old versions behave this way.  I felt the fix might not work for all flows.

**Comment by jdneo** [comment]
I see. Created a new issue #954 to track this.

> Here to share some background:
_Our current implementation will only show one execution results for those test cases which run multiple times. The previous version can show multiple times is just an unexpected behavior. Though the test result can somehow show correctly, but the result won't be stored into the result cache._
