### ISSUE TITLE
Run current test keyboard shortcut

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#943]
Is there a way to wire up a keyboard shortcut to run the "current" test?  Current being where my cursor is.

And is there a way to wire up a keyboard shortcut to run all the tests in the current file?

![image](https://user-images.githubusercontent.com/14079228/75061016-dd792180-54ad-11ea-8f07-65c3ddd142ed.png)

Tried this but it all kicked off ALL my tests which doesn't seem right as there is a "run all tests" option 🤷‍♂️:

![image](https://user-images.githubusercontent.com/14079228/75060880-9f7bfd80-54ad-11ea-80e5-742f07ff7f10.png)

**Comment by jdneo** [comment]
Thanks, but it's dup with #531, so I'm closing this one.
