### ISSUE TITLE
Collapse/Expand Test Levels

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#949]
Is this extension the creator of this UI?

![image](https://user-images.githubusercontent.com/14079228/75695499-24b69d80-5c78-11ea-81bb-6c0b1b0ed33f.png)

---

If so, what about improving the collapse button?

Something like Azure DevOps, expand/collapse one level at a time? 🤔

![image](https://user-images.githubusercontent.com/14079228/75695926-c807b280-5c78-11ea-9c7d-fddf5fa3bb2c.png)

[Source](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/organize-backlog?view=azure-devops#:~:text=Use%20the%20expand)

**Comment by jdneo** [comment]
The `Collapse All` button is the VS Code's API. As far as I know, there is no such API to expand a node. Did you see any example in other VS Code extensions?

**Comment by spottedmahn** [comment]
>button is the VS Code's API

Oh, bummer

>As far as I know, there is no such API to expand a node.

😲.  Wonder if there's a feature request already for that 🤔?

>Did you see any example in other VS Code extensions?

No but I'll keep my eyes open.  Thanks @jdneo !

**Comment by spottedmahn** [comment]
What about in explorer?

![image](https://user-images.githubusercontent.com/14079228/75779982-a36b1380-5d28-11ea-8c55-1f02648f10ff.png)

**Comment by jdneo** [comment]
Thanks, if there is any update/new findings, please feel free to comment here.

**Comment by spottedmahn** [comment]
Found one!  Search has one 😊

![image](https://user-images.githubusercontent.com/14079228/77965026-2cd11f80-72ae-11ea-9115-1bf996803fca.png)

**Comment by jdneo** [comment]
Thank you! Let me check the implementation

**Comment by guiAlberto** [comment]
Looking forward for this enhancement :eyes:

**Comment by jdneo** [comment]
This is still limited by API, see: https://github.com/microsoft/vscode/issues/88682

**Comment by spottedmahn** [comment]
>This is still limited by API, see: microsoft/vscode#88682

Bummer.  Thanks for looking into it again.  Should we close the issue again?

**Comment by jdneo** [comment]
@spottedmahn just make it open is fine. Then I can always take a look at the upstream issue when I see it.

**Comment by ghry5** [comment]
In my opinion the reason for an 'expand all' button comes from the wish to see the status of running/completed tests quickly. A collapsed node does not have any indication if tests inside it are still running/succeeded/failed. Adding this information to classes/packages/projects would be more appropriate.

**Comment by jdneo** [comment]
In 0.31.0, we support the newest VS Code testing API in 1.59.0. It changes to that the test runner extension contributes the test items to the VS Code (a pushing API model). And the view is not controlled by us. So I'll close this issue.
