### ISSUE TITLE
Junit Kotlin Support

### ISSUE THREAD

**Issue by gjlaubenstein** [microsoft/vscode-java-test#95]

**Comment by jdneo** [comment]
So far the Java Test Runner depends on Java Language Support (aka Java Language Server), which only support Java Language.

To support Kotlin, there must have a language server which can understand Kotlin, which is beyond our scope for now.

I'm closing this issue for now, but it does not mean that we won't support that. Once the requirements are ready, we can still revisit this item.

Thank you for understanding.

**Comment by BeeeWall** [comment]
> 
> 
> So far the Java Test Runner depends on Java Language Support (aka Java Language Server), which only support Java Language.
> 
> To support Kotlin, there must have a language server which can understand Kotlin(able to search/find test cases), which is beyond our scope for now.
> 
> I'm closing this issue for now, but it does **NOT** mean that we won't support that. Once the requirements are ready, we can still revisit this item.
> 
> Thank you for understanding.

Assuming you don't mean you need one made by Microsoft, there is one [here](https://github.com/fwcd/kotlin-language-server) (used by the [Kotlin extension](https://github.com/fwcd/vscode-kotlin-ide)).

**Comment by jdneo** [comment]
Thanks for the information, @BeeeWall

Sure there's no need for a Microsoft one. What the Test Runner needs to support Kotlin is a Kotlin language server exposing some APIs to let its dependents to search the test methods/class, resolve the classpaths, etc... 

And whether the Java Debugger has the ability to launch it is also an unknown area which needs to take a look at.

**Comment by rajatkb-sc** [comment]
Assuming this is still not resolved yet. Any issue to follow for this ?

**Comment by Tamara-Sennin** [comment]
We need support for this in our company so we can switch to VSCode. We really need it!
