### ISSUE TITLE
Build fails when running tests in Maven project

### ISSUE THREAD

**Issue by ASL07** [microsoft/vscode-java-test#953]
Hi

I have a maven project (https://github.com/infiniteautomation/BACnet4J) , I can build it and run the tests successfully from the termilan using `mvn test`

However, when I run a test from the Java test runner on the left panel, then I get build errors (cannot be resolved)
It seems that the test runner is not compiling the project using Maven, how can I set the compilation commands for this extension?

Thanks

**Comment by jdneo** [comment]
This is a bug related with the Java Language Server I guess. Generally speaking, the project has both `build.gradle` and `pom.xml`. According to the current implementation, the Language Server will import the project as a `Gradle` project (Gradle project has a higher priority).

A workaround is:

- Close VS Code
- Remove
  - .gradle/
  - .settings/
  - bin/
  - .project
  - .classpath
- Rename the `build.gradle` to another name, i.e. `build.gradle.bak`
- Reopen the folder in VS Code

**Comment by jdneo** [comment]
@ASL07 If you have more questions, please feel free to let me know.
