### ISSUE TITLE
Show each execution result if a test method runs several times

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#954]
There are several kinds of tests which will run several times during the execution, for example:

- Parameterized tests
- Repeated tests

### Current Behavior
The test report will only show one failure case.

### Expected Behavior
The test report should show every execution result

**Comment by 95th** [comment]
Also, for success case, it should show each test (i.e. its parameters etc) separately that was run as part of the Parameterized tests. Right now even if there are 1000 tests in a parameterized test, it shows that it ran only one. Eclipse already does this.

**Comment by 95th** [comment]
If we started showing each iteration of parameterized test as a separate test in the report, then the failure case will also be better handled i.e. we'd show error for each case separately.

**Comment by tongyuwang** [comment]
Any progress on this bug?

**Comment by beckerjohannes** [comment]
I am having the same Issue for @TestTemplate tests.

Suppose you have this test:
```java
@ExtendWith(MyExtension.class)
class IntegrityTest {

	@TestTemplate
	void correctFileNaming(final TestCaseFile testCase) {
              //some assertions
	}

}
```
with an Extension providing a 100+ `TestCaseFile` instances. Then I get this result view in Eclipse JUnit Runner:
![image](https://user-images.githubusercontent.com/56342691/91975067-1af11e00-ed1f-11ea-9426-cf52943e4115.png)
Where [1] .. [x] is the `DisplayName` provided by the `TestTemplateInvocationContext`. 

In VSCode I just get a single failed result:

![image](https://user-images.githubusercontent.com/56342691/91975275-702d2f80-ed1f-11ea-85e8-db853e62a392.png)

**Comment by jdneo** [comment]
Supported in the 0.31.0, which the VS Code testing API. You can see each invocation in the test explorer

![image](https://user-images.githubusercontent.com/6193897/128447949-bc966762-1b03-42af-9e91-8da09c14039d.png)
