### ISSUE TITLE
Using @DisplayName makes Run/Debug test disappear, then re-appear

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#955]
![run debug disappears](https://user-images.githubusercontent.com/14079228/76101180-01536180-5f9c-11ea-9223-b7b162d9d36a.gif)

**Comment by jdneo** [comment]
Thanks, but this is by design. Changing the file content will cause the Language Server to re-calculate the test entries. So sometimes you may observe a ‘flash’.

**Comment by spottedmahn** [comment]
>Thanks, but this is by design

Really, by design?  You want it to work the way it does?  Or it's way too much work to fix this use case?

**Comment by jdneo** [comment]
The event to recalculate the location of Code Lens is controlled by VS Code. And besides, it has some debounce logic there. So you can see sometimes it won't recalculate until you end up editing.

**Comment by spottedmahn** [comment]
I see, thanks @jdneo! 🤝
