### ISSUE TITLE
Show display name in the test report

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#956]
I've overridden the [display name with a generator](https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator) but it's not being honored the runner.

```java
@DisplayNameGeneration(ReplaceCamelCase.class)
class LibraryTest {
  //...
}
```

## VS Code Test Runner Output

![image](https://user-images.githubusercontent.com/14079228/76114780-dcb7b380-5fb4-11ea-8a49-da57f2f4f07d.png)

## Code is being called 🤔🤷‍♂️
![image](https://user-images.githubusercontent.com/14079228/76114818-f0fbb080-5fb4-11ea-90bf-50b5b94b3e9d.png)

```java
private String replaceCapitals(String name) {
  name = name.replaceAll("([A-Z])", " $1");
  name = name.replaceAll("([0-9]+)", " $1");
  System.out.println(String.format("new test name: '%s'", name));
  return name;
}
```

[Full sample](https://github.com/spottedmahn/experiments-2020/tree/master/display-name-generator)

Reference: [Building a Camel Case @DisplayNameGenerator For JUnit 5](https://leeturner.me/posts/building-a-camel-case-junit5-displaynamegenerator/)

**Comment by spottedmahn** [comment]
Apparently it's not specific to generators...  the simple case doesn't work either:

![image](https://user-images.githubusercontent.com/14079228/76133790-e9093400-5fe7-11ea-8ed6-169e16ff82e5.png)

**Comment by jdneo** [comment]
display name generator is duplicated with #667

But I will change this issue's title to: Show display name in the test report.

**Comment by spottedmahn** [comment]
>Show display name in the test report

Fair enough but that's kinda misleading as `@DisplayName("This Works ✅")` works but generators don't work and using `@DisplayName()` on a class name doesn't work either.

**Comment by jdneo** [comment]
Supported in 0.31.0 in test explorer
