### ISSUE TITLE
Test report still visible when maximize panel tray

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#958]
![image](https://user-images.githubusercontent.com/14079228/76334333-498ac080-62c9-11ea-96fa-cab2b441d270.png)

repro, make report active, maximize panel tray:
![image](https://user-images.githubusercontent.com/14079228/76334146-04ff2500-62c9-11ea-9560-de626fc7625b.png)

when a java file is active and I maximize the panel tray: 
![image](https://user-images.githubusercontent.com/14079228/76334060-e9941a00-62c8-11ea-9cdc-71a1bb1c23b5.png)

**Comment by jdneo** [comment]
Cannot repro it on MacOS.

Could you please try to open other webview to see if this could repro. If yes, this is nothing we can control at the extension side, which should be a bug of VS Code

**Comment by spottedmahn** [comment]
>Could you please try to open another webview

hmm... such as?

**Comment by jdneo** [comment]
Let me see... Maybe the release notes? Open the command palette and enter `release note`, there should be some related commands in it.

**Comment by spottedmahn** [comment]
Yep, VS Code problem apparently:

![image](https://user-images.githubusercontent.com/14079228/76520918-351a0580-643a-11ea-87b3-1e866f79bca2.png)

I'm thinking the semi-circle is this:

![image](https://user-images.githubusercontent.com/14079228/76520992-57138800-643a-11ea-977d-4ab5944eeaab.png)
