### ISSUE TITLE
code is not running

### ISSUE THREAD

**Issue by programer1012** [microsoft/vscode-java-test#960]
<img width="359" alt="Screen Shot 2020-03-11 at 6 01 47 PM" src="https://user-images.githubusercontent.com/47304729/76468505-7a025580-63c2-11ea-9263-f9736db00672.png">
 

My output is[Done] exited with code=127 in 0.006 seconds 
what should I do?

**Comment by jdneo** [comment]
Are you writing a Java test code? From the screenshot, I cannot get your point. Please provide more information to help us to repro your issue.

Thanks.

**Comment by programer1012** [comment]
I am writing in javascript

**Comment by programer1012** [comment]
<img width="992" alt="Screen Shot 2020-03-12 at 3 50 18 PM" src="https://user-images.githubusercontent.com/47304729/76561209-33236700-6479-11ea-8c42-bde6b7df5a1d.png">

**Comment by jdneo** [comment]
Hi @programer1012, this repo is for Java Test Runner extension, which is not responsible for launching JS program.

If you have problem using JS in VS Code, please consider open issue in [VS Code repo](https://github.com/microsoft/vscode)

Thanks.

**Comment by programer1012** [comment]
thanks for your time jdneo

**Comment by programer1012** [comment]
so how do i fix it
