### ISSUE TITLE
Class not found exception during debugging junit tests

### ISSUE THREAD

**Issue by tonylsw** [microsoft/vscode-java-test#962]
Have problem when debugging junit tests with the latest version of vscode (on osx), after clicking on "debug test" above test case, get error 

```
Exception has occurred: java.lang.ClassNotFoundException: "java.lang.ClassNotFoundException: org.eclipse.jdt.internal.junit.runner.RemoteTestRunner"
```

No problem running the same test.

Un-installed and reinstalled vscode, same error.

Worked for a short while with vscode insider before getting the same error.

Performed "clean java language server workspace" and restart, didn't help.

Maven project.

**Comment by jdneo** [comment]
Could you provide more information to us?

JDK version
JUnit 4 or 5?
A sample code snippet to repro this issue.

Thanks.

**Comment by jdneo** [comment]
@tonylsw Please provide more information to help us diagnostic the issue. Thanks.
