### ISSUE TITLE
Display Test Report in a split to the bottom of the editor

### ISSUE THREAD

**Issue by JChaneyGuardian** [microsoft/vscode-java-test#964]
It would be nice to be able to have the option of splitting the Test Report to the bottom of the editor automatically rather than just to the right side and then having to move it every time.

I find the wide layout easier to read errors and messages rather than the squished narrow view on the side.

Better yet would be to move the test report into the same split as the Problems, Output, Debug and Terminal at the bottom.

**Comment by jdneo** [comment]
@JChaneyGuardian Thank you, I'll check if there is any API available to do this.

While so far you can set the setting `java.test.report.position` to `currentView` as a workaround.

**Comment by spottedmahn** [comment]
>splitting the Test Report to the bottom of the editor automatically rather

when I'm debugging failed tests I usually do the same thing as code goes wide not all 😉

>move the test report into the same split as the Problems, Output, Debug and Terminal at the bottom.

I think I would like that too!

>`java.test.report.position` to `currentView` as a workaround

Gotta try that out, thanks Sheng!

**Comment by JChaneyGuardian** [comment]
@jdneo Thanks for the response and for looking into this.

Using `currentView` doesn't do the split window.  It simply puts it into the current pane.  I still need to reposition it to the bottom split position.

Thanks again for looking into this.  Over all I am pretty happy with the extension. :)

**Comment by jdneo** [comment]
Checked the API for the latest stable version of VS Code:

Here is the API to create `Webview`:

```ts
export function createWebviewPanel(viewType: string, title: string, showOptions: ViewColumn | { viewColumn: ViewColumn, preserveFocus?: boolean }, options?: WebviewPanelOptions & WebviewOptions): WebviewPanel;
```

And the definition of the `ViewColumn`:

```ts
export enum ViewColumn {
		/**
		 * A *symbolic* editor column representing the currently active column. This value
		 * can be used when opening editors, but the *resolved* [viewColumn](#TextEditor.viewColumn)-value
		 * of editors will always be `One`, `Two`, `Three`,... or `undefined` but never `Active`.
		 */
		Active = -1,
		/**
		 * A *symbolic* editor column representing the column to the side of the active one. This value
		 * can be used when opening editors, but the *resolved* [viewColumn](#TextEditor.viewColumn)-value
		 * of editors will always be `One`, `Two`, `Three`,... or `undefined` but never `Beside`.
		 */
		Beside = -2,
		/**
		 * The first editor column.
		 */
		One = 1,
		/**
		 * The second editor column.
		 */
		Two = 2,
		/**
		 * The third editor column.
		 */
		Three = 3,
		/**
		 * The fourth editor column.
		 */
		Four = 4,
		/**
		 * The fifth editor column.
		 */
		Five = 5,
		/**
		 * The sixth editor column.
		 */
		Six = 6,
		/**
		 * The seventh editor column.
		 */
		Seven = 7,
		/**
		 * The eighth editor column.
		 */
		Eight = 8,
		/**
		 * The ninth editor column.
		 */
		Nine = 9
	}
```

So far, this only possible to put the web view into the editor area. I'll keep tracking in case VS Code support more places in the future.

**Comment by JChaneyGuardian** [comment]
Thank you for checking that.

I figured it was a long shot being able to open it in the terminal pane.

It's odd to me that there is no option for splitting the current editor horizontally and opening the new pane below the current pane.

Thanks again for checking on this.

**Comment by spottedmahn** [comment]
>I'll keep tracking in case VS Code support more places in the future

>It's odd to me that there is no option for splitting the current editor horizontally and opening the new pane below the current pane.

Wouldn't it be a good idea to open an issue in the VS Code repo requesting the feature? 🤔

**Comment by spottedmahn** [comment]
>Checked the API for the latest stable version of VS Code

I assume there's a web url for that?  Can you share it by chance? thanks! 🙏

**Comment by jdneo** [comment]
> I assume there's a web url for that? Can you share it by chance? thanks! 🙏

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts

**Comment by jdneo** [comment]
In 0.31.0, we support the newest VS Code testing API in 1.59.0. The test report is removed, so I'll close this issue.
