### ISSUE TITLE
Display Name not Honored on First Run

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#966]
### Repro steps
1. Open folder
1. I believe it is critical that the test file is not open.  if any java files are open after opening the folder, chose all the files, close vs code and start over.
1. Run all tests

![image](https://user-images.githubusercontent.com/14079228/77070899-7f166480-69c1-11ea-8b02-0a58d6f0b1f3.png)

![image](https://user-images.githubusercontent.com/14079228/77071090-d1f01c00-69c1-11ea-9008-7745435e4715.png)

![image](https://user-images.githubusercontent.com/14079228/77071031-b7b63e00-69c1-11ea-929d-6f6e34232e7e.png)

### After opening the test file and re-running all tests again

![image](https://user-images.githubusercontent.com/14079228/77071060-c3a20000-69c1-11ea-9d5e-1545a745ba78.png)

**Comment by jdneo** [comment]
In 0.31.0, we support the newest VS Code testing API in 1.59.0. The test report is removed.

Also some refactors are made for display name support. This problem should disappear.
