### ISSUE TITLE
Vscode Java Test Runner Test Explorer not displaying any java tests, but codeLens display option let me run

### ISSUE THREAD

**Issue by MingHsuan0313** [microsoft/vscode-java-test#967]
This is a Maven Project build using Vscode "Maven for Java" plugin

I can run tests from codeLen and it works correctly , but I don't know why the test explorer doesn't show anything....
![image](https://user-images.githubusercontent.com/38287914/77191170-8058a600-6b15-11ea-9782-6389269aeab0.png)

Here is my .classpath , I am sure that I have included test attribute in classpathentry
![image](https://user-images.githubusercontent.com/38287914/77190994-3374cf80-6b15-11ea-8ad5-63a8a4530946.png)

Environment
OS : ubuntu 18.04
java : 1.8.0
java Test Runner : 0.22.2

**Comment by jdneo** [comment]
Are you using `symlink` for your project folder?

**Comment by MingHsuan0313** [comment]
No , but I fix this problem by remove ~/.config/Code 
Before I remove ~/.config/Code , I try reinstall VScode ,It didn't work
I also try to remove ~/.vscode (directory store VScode extension) , and can't work
So I think maybe there is something wrong in my local cache of VScode
Thanks~~

**Comment by jdneo** [comment]
I see.

I'm closing this issue for now but if you meet any problem later, just feel free to comment here or create a new one.

Thanks.
