### ISSUE TITLE
Spring Boot integration test hanging test runner

### ISSUE THREAD

**Issue by charlvictor** [Microsoft/vscode-java-test#97]
I have a vanilla Spring Boot app, and when running the default integration test supplied the test runner just hangs in the "Running tests..." state. I can see that the tests actually execute by looking at the test output window, but it seems it never returns the state. Normal unit tests without spring context works 100%.

Sample Class:
```java 
@RunWith(SpringRunner.class)
@SpringBootTest
public class MyApplicationTests {

    @Test
    public void contextLoads() {
    }  

}

**Comment by ansyral** [comment]
@charlvictor I could not repro using the sample above. Do you have any special logic in your test setup?

**Comment by charlvictor** [comment]
@ansyral I just did another test with a fresh sample and it seems to work now. Maybe there has been an update since or I just had a funky setup.  Appreciate you looking into it.
