### ISSUE TITLE
Java Test Runner extension does not working properly...

### ISSUE THREAD

**Issue by EminemRap** [microsoft/vscode-java-test#976]
The Java Test Runner extension does not working properly after updating VS Code to the latest version (1.44.0), often stuck in the Compiling workspace, or pops up with an error alert: "The extension 'Java Test Runner' took a very long time to complete its last operation and it has prevented other extensions from running."

**Comment by jdneo** [comment]
Compiling workspace is not a task executed by Test Runner.

What kind of project are you using? Would you mind to share it to us for diagnostic?

**Comment by EminemRap** [comment]
> Compiling workspace is not a task executed by Test Runner.
> 
> What kind of project are you using? Would you mind to share it to us for diagnostic?

My project is based on Spring Boot, a company project that is not convenient to share project details.

**Comment by jdneo** [comment]
Seems dup with #832.

🤔
