### ISSUE TITLE
Debug console does not show tests' log

### ISSUE THREAD

**Issue by 1mdc** [microsoft/vscode-java-test#979]
I can only see these lines from "debug console" view

```
23:21:17.613 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
23:21:17.617 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
23:21:17.618 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
23:21:17.628 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
23:21:17.629 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
23:21:17.635 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
23:21:17.686 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
23:21:17.686 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
23:21:17.700 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: MacOS
23:21:17.760 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
23:21:17.761 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 11
23:21:17.764 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
23:21:17.766 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
23:21:17.771 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
23:21:17.779 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
```

Also I have logback.xml file in test/resoures but vs code does not read it. I still can see log and see logback.xml used when using console e.g. ./gradlew test

**Comment by jdneo** [comment]
@1mdc Is it possible to share a sample project to us?

**Comment by 1mdc** [comment]
Hi, I got it fixed now. I disabled Maven Plugin and clean and reset java build server. I can see the logs now. Thank you.

**Comment by jdneo** [comment]
@1mdc Do you mean the [Maven VS Code extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven)?

**Comment by 1mdc** [comment]
@jdneo yes, I disabled that plugin as I use gradle for my project. I see it generates some maven config in .project file.

**Comment by jdneo** [comment]
@1mdc I guess it might not be related with the maven extension. Would you mind to re-enable the Maven extension and try again?

**Comment by 1mdc** [comment]
@jdneo I enabled the plugin again, I do not see the log any more. 
<img width="783" alt="Screenshot 2020-04-23 at 00 39 33" src="https://user-images.githubusercontent.com/5703525/80043955-0728e600-84fb-11ea-8a61-f43e17814b04.png">

**Comment by 1mdc** [comment]
@jdneo please ignore my above message. I was running a test without any output. I ran a test with some output now and I can see the logging in "debug console". I don't know what was changed though. but I will keep maven plugin enabled and will raise this again if I see the issue again.

**Comment by jdneo** [comment]
@1mdc Thanks.
