### ISSUE TITLE
Add a new field in the java.test.config to specify source paths

### ISSUE THREAD

**Issue by michael-emmi** [microsoft/vscode-java-test#982]
The [`sourcePaths` key](https://code.visualstudio.com/docs/java/java-debugging) is not being set for the launch configuration created by this extension. Without adding extra source paths to the launch configuration, my VSCode debugger shows `Unknown Source` for all the stack frames that aren’t either found in `src/test/java` or the JDK. The Java Test Runner seems to ignore the debug configurations I have created, [constructing its own instead](https://github.com/microsoft/vscode-java-test/blob/f3fc82f4484ead1dfc2aa5488d2d589090916cdb/src/utils/launchUtils.ts#L56-L69) — shown below.

Is there some other way to inject extra source paths into the launch configurations created by the Java Test Runner, or some other workaround?

With the setting `"java.test.log.level": "verbose"` I see the following Java Test Runner output:
```console
Launching with the following launch configuration: '{
  "name": "Launch Java Tests - 01f5fe",
  "type": "java",
  "request": "launch",
  "mainClass": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner",
  "projectName": "<redacted>",
  "cwd": "${workspaceFolder}/<redacted>",
  "classPaths": [ <redacted> ],
  "args": [
    "-version",
    "3",
    "-port",
    "51543",
    "-testLoaderClass",
    "org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader",
    "-loaderpluginname",
    "org.eclipse.jdt.junit5.runtime",
    "-test",
    "<redacted>"
  ],
  "vmArgs": [
    "-ea"
  ],
  "noDebug": false,
  "console": "internalConsole"
}'
```

**Comment by michael-emmi** [comment]
I should add that I am launching from code lens.

(Launching from test explorer seems to have been solved by #801).

**Comment by jdneo** [comment]
So far the Test Runner won't persist the launch configuration. It will resolve it dynamically and pass it to the Debugger.

For this case, I think we can add a new field in the [java.test.config](https://github.com/microsoft/vscode-java-test/wiki/Run-with-Configuration) to let users specify source paths.

Meanwhile, I'm actually want to know why launching from test explorer can have the source paths. From my understanding, they should have no differences. Which part of the sources are missing in your case?

**Comment by michael-emmi** [comment]
> Meanwhile, I'm actually want to know why launching from test explorer can have the source paths.

@jdneo I was basing that on the fact that your PR (#801) passes a `DebugConfiguration` object from the registered entry points for the test explorer (`{RUN,DEBUG}_TEST_FROM_EXPLORER`) but not for code lenses (`{RUN,DEBUG}_TEST_FROM_CODELENS`). I assumed that `DebugConfiguration` object somehow originated from an existing launch configuration, but having just tried it myself, it does not seem to — I get the same Test-Runner-created configuration referenced above.

> For this case, I think we can add a new field in the java.test.config to let users specify source paths.

That would solve the problem.

But it would also be a shame not to use existing launch configuration(s) if possible. I don’t know my way around VS Code extensions, but I wonder whether it’s possible to grab an existing launch configuration from the test runner code? For example, whether one can query some [DebugLaunchConfigurationProvider](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode/index.d.ts#L10065) to obtain them?

**Comment by jdneo** [comment]
The main purpose of #801 is actually allow other extensions register their commands to the Test Explorer. (i.e. [PDE Support](https://github.com/testforstephen/vscode-pde/blob/master/package.json#L155-L164))

Since the test runner won't have the context that other extensions have, so it allows other extension to pass a debug configuration. So that the test runner will just simply pass it to the Java Debugger and parse the output to show the test result.
