### ISSUE TITLE
Do not display test report if test execution is aborted and no tests are executed.

### ISSUE THREAD

**Issue by AnthonyWeston** [microsoft/vscode-java-test#983]
If I need to abort or restart a test run while debugging, i.e. if I made a code change and VSCode can't hot swap the updated code in, the test report still appears when I click the Stop button. It gets to be a little cumbersome if I have to leave the Test Report tab after every run, so it would be great to have a configuration option to not display an empty test report for an aborted test.

Java Test Runner already has a setting` java.test.report.showAfterExecution`, but none of the existing values accomplish this.

**Comment by jdneo** [comment]
I see...

Ii'm thinking that to add a new option in `java.test.report.showAfterExecution`, or just always not show the report if the user cancels the execution...
