### ISSUE TITLE
Cannot run JUnit5' test if the method has comment (//) above it

### ISSUE THREAD

**Issue by malkav30** [microsoft/vscode-java-test#987]
I open this issue as I'm unable to launch a JUnit5 @ParameterizedTest individually : If launched by clicking the "run test" on the test class, everything works fine, but when I launch the test by clicking on the "run test" on the test method, nothing happens. 

*Expected behavior* : the test should run as many times as there are parameters
*Expected behavior for the debug mode* : the test should run in debug mode as many times as there are parameters

*Using:*
- Java 11,
- java test runner 0.22.3
- VSCode : 
 Version: 1.44.2 (system setup)
 Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd0
 Date: 2020-04-16T16:36:23.138Z
 Electron: 7.1.11
 Chrome: 78.0.3904.130
 Node.js: 12.8.1
 V8: 7.8.279.23-electron.0
 OS: Windows_NT x64 10.0.18362

**Comment by jdneo** [comment]
Hi @malkav30,

I cannot repro this on my side.

![Kapture 2020-05-03 at 17 12 32](https://user-images.githubusercontent.com/6193897/80910343-6be90980-8d61-11ea-99f7-af642b135c47.gif)

Would you mind to share a sample project to us?

**Comment by malkav30** [comment]
Shure, here is a sample program, as simple as it gets. 

[testfail.zip](https://github.com/microsoft/vscode-java-test/files/4569987/testfail.zip)
![testfail](https://user-images.githubusercontent.com/9546533/80911579-6b3b7d80-8d37-11ea-9061-331f46f07733.gif)

**Comment by malkav30** [comment]
Hello, for what it's worth, I have the same issue if I comment @ParameterizedTest just above a otherwise working @Test method, e.g.
```java
// @ParameterizedTest
@Test
public void some_working_test_case() {
}
```

**Comment by jdneo** [comment]
Find out that this issue occurs when the method has comments (// ...) above it. I'll check if there is any way to fix it!
