### ISSUE TITLE
Code lens links are not shown if Test class extends Abstract Test Class

### ISSUE THREAD

**Issue by rdehuyss** [microsoft/vscode-java-test#989]
I'm unable to run tests when the Test class extends another Test Class...

![image](https://user-images.githubusercontent.com/567842/80872258-240aa980-8cb1-11ea-9df3-29f61aee0e97.png)

All test methods are are in a super class 3 levels higher.

P.s.: you guys have made enormous progress on Java support. Great work!

**Comment by jdneo** [comment]
Hey @rdehuyss,

Thank you for your feedback. We have not fully supported the inherited class so far. Sorry for troubling you on this issue. We have already an existing one(#718) on this. Let's track it there.

Thanks.
