### ISSUE TITLE
Status bar displays "Failed to run tests" even though tests were run successfully

### ISSUE THREAD

**Issue by bobderrico** [Microsoft/vscode-java-test#99]
When I click "Run Test," the status bar displays "Running tests..." and the changes to "Failed to run tests" after the testing has finished running.

However, the tests to did run successfully. I see the correct reporting on test cases in the code and can click the icon to see test results.

When I look at the test output, I see several lines start with `Error occurred`. This all prefix expected logging output during the test. This output is generated by calls to an SLF4J Logger method. For example:
```
Error occured: [main] INFO com.some.packages.ClassName - Some Message
```

(also worth noting that "occurred" is spelled incorrectly in the message).

I suspect the plugin is seeing these log messages and assuming there was a failure with running the test, causing "Failed to run tests" to be incorrectly reported.

**Comment by sswane** [comment]
👍 The same thing is happening to me. The tests run successfully and the status bar text is green, but it says "Failed to run tests". I also see in the output `Error occured:` followed by complaints about multiple SLF4J bindings. What is interesting though is when I run `mvn clean install` on my project, I do not see those errors in the console.

**Comment by davidaorr** [comment]
I am experiencing the same issue.

**Comment by roguechad** [comment]
I am having the same issue.

**Comment by ansyral** [comment]
Seems the test itself would output something to system.err. I would add some label to tell errors outputted by junit runner and those from the tests themselves.

**Comment by ansyral** [comment]
5cf1acc
