### ISSUE TITLE
Can't detect the test cases in the main folder?

### ISSUE THREAD

**Issue by shenpan** [microsoft/vscode-java-test#990]
Newbie here, seems this plugin only detects test cases in test folder, is this my configuration issue or a limitation?
Thanks.

**Comment by jdneo** [comment]
Only the files which are in the test scope will show the CodeLens in the editor. See: https://github.com/microsoft/vscode-java-test/wiki/FAQ#i-cannot-see-the-codelens-in-my-test-code-why

**Comment by shenpan** [comment]
Works like a charm.
Thanks!
