### ISSUE TITLE
Can't open error details

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-java-test#993]
Issue Type: <b>Bug</b>

the test is obviously failed but i can't watch error message when click greater than sign.
![image](https://user-images.githubusercontent.com/27731323/81461363-c4932900-91dd-11ea-8af0-83b41a650799.png)

Extension version: 0.22.3
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdneo** [comment]
Hi @bonaluo,

Thank you for reporting the issue. It's duplicated with #984. See [this] comment for a workaround.
