### ISSUE TITLE
Can't run junit5, NoClassDefFoundError occured

### ISSUE THREAD

**Issue by Dae-Hwa** [microsoft/vscode-java-test#994]
![image](https://user-images.githubusercontent.com/24666330/81575371-ea891b00-93e1-11ea-8b2b-28bdb91692ea.png)

When I run it at eclipse, it's ok. But in vscode it thorws errors.

**Comment by jdneo** [comment]
@Dae-Hwa Could you please update your junit dependency to `junit.jupiter:5.6.0` and try again?
